typelevel/cats

- AUTHORS.md
- CHANGES.md
- README.md
We're really close to 1.0, so I decided to draft some release notes. I think it'd be great if we could also get a blog post on typelevel.org in time as well. :)
Only have a couple of tickets still open:
And then we have a couple of others that break bincompat so we should think about including them in 1.0.0
> Get ready for RC2

- build.sbt
- project/Boilerplate.scala
This makes it so when you look at the `Applicative` scaladoc you don't
have a bunch of `ap3`, `ap4`, etc noise mixed in with the more
meaningful methods. Instead, the generated higher-arity methods show up
in separate scaladoc groups below.
To see the changes you can pull this branch, run `sbt unidoc` (you may
need to clean first), and open
`cats/docs/target/scala-2.12/unidoc/cats/Applicative.html` in your
browser.
> Add grouping to scaladoc for arity methods

- kernel/src/main/scala/cats/kernel/Semigroup.scala
Fixed a typo in the ScalaDoc for the `combine` method of `Semigroup`.
> Fixed a typo in the ScalaDoc for the combine method (Semigroup)

- core/src/main/scala/cats/syntax/either.scala
- tests/src/test/scala/cats/tests/EitherSuite.scala
`Either` should have `leftFlatMap` for cases when you want to `leftMap` a function that returns an `Either` and flatten the total result.
> Add leftFlatMap to Either

- core/src/main/scala/cats/syntax/either.scala
since `EitherNel` is a lot more useful with the `Parallel` TC
> added `leftNel` and `rightNel` syntax

- build.sbt
This change is due to to the documentation URL not being properly formed depending on the base href. By setting it as root-relative, we can be totally sure where we are pointing the link to.
Info related to this can be found on https://github.com/47deg/sbt-microsites/issues/251
> Set micrositeDocumentationUrl as root-relative

- .travis.yml
> update travis cache settings

- core/src/main/scala/cats/data/Ior.scala
- tests/src/test/scala/cats/tests/IorSuite.scala
Added `Bitraverse[Ior]`, as discussed in #2144 
For the testing part, I followed the pattern found in for testing `Bitraverse[Either]`, within `cats.tests.EitherSuite`
This is my first PR, let me know if I need do something around this.
...and thanks for all the good work!
> Added Bitraverse for Ior (#2144)

- core/src/main/scala/cats/implicits.scala
- core/src/main/scala/cats/syntax/all.scala
- core/src/main/scala/cats/syntax/package.scala
- core/src/main/scala/cats/syntax/unorderedTraverse.scala
- testkit/src/main/scala/cats/tests/CatsSuite.scala
- tests/src/test/scala/cats/tests/UnorderedTraverseSuite.scala
Addresses #2147:
>The import cats.syntax.traverse._ doesn't provide the .unorderedTraverse. This is inconsistent, as the import cats.syntax.foldable._ does provide the unorderedFold syntax.
> Add missing UnorderedTraverse syntax

- .travis.yml
- sbt 1.x does not work with Java 7
- travis-ci no longer support oraclejdk7 https://github.com/travis-ci/travis-ci/issues/7884#issuecomment-308451879
> remove java 7 build

- docs/src/main/tut/datatypes/kleisli.md
This makes it easier for the reader to follow the flow of the types.
> Add types in the Kleisli code sample for composition

- docs/src/main/tut/typeclasses/contravariant.md
that says that B is subtype of A.
See also gitter discussion with @tpolecat on Jan 14 2017.
> contravariant.md [reversing roles of A and B in commentary to match the code]

- free/src/main/scala/cats/free/ContravariantCoyoneda.scala
- free/src/test/scala/cats/free/ContravariantCoyonedaSuite.scala
This is mostly a copy/paste job from `Coyoneda` with the arrows flipped.
> contravariant coyoneda

- core/src/main/scala/cats/ApplicativeError.scala
- core/src/main/scala/cats/syntax/TrySyntax.scala
- core/src/main/scala/cats/syntax/all.scala
- core/src/main/scala/cats/syntax/applicativeError.scala
- core/src/main/scala/cats/syntax/either.scala
- core/src/main/scala/cats/syntax/option.scala
> added `liftTo` to `Try`, `Either` and `Option`

- core/src/main/scala/cats/Parallel.scala
- project/Boilerplate.scala
- tests/src/test/scala/cats/tests/ParallelSuite.scala
As from the discussion in here https://github.com/typelevel/cats/pull/2128 this and attempt to add parTuple syntax in a way that preserves backwards binary compatibility.
> Add parTuple

- core/src/main/scala/cats/data/Const.scala
- core/src/main/scala/cats/data/WriterT.scala
- tests/src/test/scala/cats/tests/WriterTSuite.scala
This adds `Foldable`, `Traverse` and `Comonad` instances for WriterT. The relevant issue is https://github.com/typelevel/cats/issues/620
> Add `Foldable`, `Traverse` and `Comonad` instances to `WriterT`

- laws/src/main/scala/cats/laws/ApplicativeErrorLaws.scala
- laws/src/main/scala/cats/laws/MonadErrorLaws.scala
`PartialFunction.apply` is deprecated in 2.12.5, removed in 2.13.0. So this PR is advance work for the 2.13 build. Error message in 2.13.0-M3 build:
> method apply in object PartialFunction is deprecated (since 2.12.5): For converting an ordinary function f to a partial function pf, use `val pf: PartialFunction[A, B] = { case x => f(x) }`. For creating a new PartialFunction, use an explicit type annotation instead, like in `val pf: PartialFunction[Int, String] = { case 1 => "one" }`.
Required for https://github.com/typelevel/cats/pull/2173
> Remove calls to PartialFunction.apply, deprecated in 2.12.5

- .travis.yml
- build.sbt
- kernel-laws/src/test/scala/cats/kernel/laws/LawTests.scala
Also tweaked the cache in travis, including `- $HOME/.cache` for javascript build artifacts
> split build jvm,add workers to kernel

- core/src/main/scala/cats/data/Newtype.scala
- core/src/main/scala/cats/data/NonEmptySet.scala
- core/src/main/scala/cats/data/package.scala
- laws/src/main/scala/cats/laws/discipline/Arbitrary.scala
- tests/src/test/scala/cats/tests/NonEmptySetSuite.scala
Pretty much the same situation as #2141
> Add NonEmptySet

- core/src/main/scala/cats/data/Kleisli.scala
- tests/src/test/scala/cats/tests/KleisliSuite.scala
Close #1733.
This is badly needed in `cats-effect` in order to define a `Sync[Kleisli[F, R, ?]]` implementation.
I'm already pushing one right now, but with a patched `flatMap` implementation that would no longer preserve _coherence_ with the official `flatMap` of Kleisli. So it would be nice if both these PRs happen, see: https://github.com/typelevel/cats-effect/pull/144
The way to fix it is to define a `flatMap` implementation that triggers the `F[_]` context _earlier_. Like this:
```scala
def flatMap[C](f: B => Kleisli[F, A, C])(implicit F: Monad[F]): Kleisli[F, A, C] =
Kleisli(a => F.pure(a).flatMap(a => F.flatMap[B, C](run(a))((b: B) => f(b).run(a))))
//                     ^^^^^^^                      ^^^^^^
//              Suspended execution in F[_], no longer increases the stack …
```
> Fix #1733: make Kleisli.flatMap stack safe

- core/src/main/scala/cats/data/EitherT.scala
- tests/src/test/scala/cats/tests/EitherTSuite.scala
In certain circumstances the default value might be wrapped in the `F[_]` context already. I think `valueOrF` belongs in `EitherT`.
> Add valueOrF to EitherT

- bench/src/main/scala/cats/bench/StateTBench.scala
- core/src/main/scala/cats/data/AndThen.scala
- core/src/main/scala/cats/data/IndexedStateT.scala
- tests/src/test/scala/cats/tests/AndThenSuite.scala
- tests/src/test/scala/cats/tests/IndexedStateTSuite.scala
Close #2186.
This is very similar in spirit with the PR #2185 that fixes `Kleisli`, but this one is for `IndexedStateT` and with a different solution.
For `IndexedStateT` instead of piggybacking on an `F: Monad` for the stack safety of repeated left binds, this time we are introducing an `AndThen` implementation.
`AndThen` was first introduced in `cats-effect` for describing functions that are stack safe in `andThen` and `compose`, the original `cats.effect.IO` implementation being based on it.
Introduced as an internal helper (thus not exposed to the public), this is now used to provide stack safety for `IndexedStateT`.
Note that an implementation similar to that of PR #2185 is also possible, deferring this responsibility to `F[_]`, except that this version proposed here works for any …
> Fix #2186: make IndexedStateT stack safe

- docs/src/main/resources/microsite/data/menu.yml
Laws are important and the link to the Law Testing page is quite hidden (in a hyperlink all the way down the bottom of the Typeclasses page). I suspect making it more visible might encourage more people to learn how to test typeclass laws.
Here's a screenshot on how it would look:
> Add "Law Testing" to side menu to increase visiblity.

- core/src/main/scala/cats/Foldable.scala
- core/src/main/scala/cats/syntax/foldable.scala
- tests/src/test/scala/cats/tests/FoldableSuite.scala
#2113, Am I right, test should be added to the `FoldableSuite` ?
> Add `contains_`, `foldSmash` and `mkString_` to `FoldableOps`

- free/src/test/scala/cats/free/CofreeSuite.scala
- free/src/test/scala/cats/free/FreeApplicativeSuite.scala
This is the last explicit `new FunctionK` that I saw in the code base
when I looked to close out #1374.
> Use poly lambda syntax in FreeApplicative test

- alleycats-core/README.md
Closes https://github.com/typelevel/cats/issues/2202.
This PR ports the useful [README.md from the defunct alleycats repo](https://github.com/non/alleycats/blob/master/README.md) with some very minor changes in wording and also without the buttons and some sections (`Getting Alleycats`, `Copyright and License`) since this is now a module within the cats project.
I'm not entirely sure about the licensing thing though, but I did remove the section at the end (see https://github.com/non/alleycats/blob/master/README.md#copyright-and-license) since my reasoning is that the root README.md probably covers things, let me know what works.
> Port alleycats README.md from the defunct repo

- core/src/main/scala/cats/syntax/list.scala
Mostly stolen from the `groupBy` example on `NonEmptyList`.
> Add doctest example for groupByNel

- core/src/main/scala/cats/data/EitherK.scala
- core/src/main/scala/cats/data/EitherT.scala
- core/src/main/scala/cats/data/IndexedReaderWriterStateT.scala
- core/src/main/scala/cats/data/IorT.scala
- core/src/main/scala/cats/data/Kleisli.scala
- core/src/main/scala/cats/data/Nested.scala
- core/src/main/scala/cats/data/OptionT.scala
- core/src/main/scala/cats/data/Tuple2K.scala
- core/src/main/scala/cats/data/WriterT.scala
- tests/src/test/scala/cats/tests/NestedSuite.scala
- tests/src/test/scala/cats/tests/Tuple2KSuite.scala
- tests/src/test/scala/cats/tests/WriterTSuite.scala
This is about using the Functor instance in Traverse for the monad transformers `EitherT` and `OptionT` and in `Tuple2K` so to use its `map` implementation. This follows @peterneyens 's comment https://github.com/typelevel/cats/pull/2182#discussion_r173720529 related to `WriterT`.
> Extend Functor implementation in the Traverse instance of EitherT, OptionT and Tuple2K

- core/src/main/scala/cats/Alternative.scala
- core/src/main/scala/cats/Applicative.scala
We have a unit on Applicative, but we weren't using it in a few places where we could.
> Use unit from Applicative

- build.sbt
- core/src/main/scala/cats/syntax/applicativeError.scala
- tests/src/test/scala/cats/tests/ApplicativeErrorSuite.scala
This is to address https://github.com/typelevel/cats/issues/2242
> Add `orElse` to ApplicativeError

- README.md
These instances could be useful for someone working with fastparse. Hoping to reach a wider audience.
> Add fastparse-cats to the list of projects

- core/src/main/scala/cats/data/OptionT.scala
- core/src/main/scala/cats/implicits.scala
- core/src/main/scala/cats/syntax/all.scala
- core/src/main/scala/cats/syntax/flatMap.scala
- testkit/src/main/scala/cats/tests/CatsSuite.scala
- tests/src/test/scala/cats/tests/IndexedStateTSuite.scala
Three cases I have wanted:
1. taking a scalacheck `Gen[Option[A]] => Gen[A]`
2. writing a server that has a single step as `IO[Unit]` then repeating that forever.
3. a server that has some state: `S => IO[S]` that each call updates the state and repeat forever.
This has to be done with syntax backwards compatibility hacks, but we can repair that at cats 2.0
> Add some FlatMap loops useful for State and Effects

- docs/src/main/tut/typeclasses/foldable.md
With the previous wording, a reader might interpret the `Foldable` docs
as suggesting that `foldLeft` traverses the structure from the left
while `foldRight` traverses the structure from the right. In my
experience, this is a common misconception. In fact, `foldRight` can
terminate on infinite structures while `foldLeft` can't, which doesn't
make sense if you are thinking about the two as traversal order. I've
tried to be more precise about `Left` and `Right` referring to the
associativity of the operations. I'm not sure whether my `List(1, 2, 3)`
example is very good or not -- open to feedback
> Be more precise about left vs right in Foldable doc

- core/src/main/scala/cats/Composed.scala
changed internal variable names in trait ComposedFoldable[F[_], G[_]] for better readability
> updated trait ComposedFoldable in Composed.scala

- core/src/main/scala/cats/syntax/option.scala
- tests/src/test/scala/cats/tests/OptionSuite.scala
just a postfix version of `OptionT.fromOption`
> Add .toOptionT to option syntax 

- build.sbt
somehow I missed that last release
> update bin compat versions to 1.0.0 and 1.1.0

- core/src/main/scala/cats/syntax/all.scala
- core/src/main/scala/cats/syntax/nested.scala
- core/src/main/scala/cats/syntax/package.scala
- tests/src/test/scala/cats/tests/SyntaxSuite.scala
I attended @iravid's talk at the typelevel summit and was surprised that I hadn't known about `Nested` yet. 
Also, I found the syntax a bit clunky. I would propose to add a `.nested` extension method so that
```scala
listOfOption.nested
```
is equivalent to 
```scala
Nested(listOfOption)
```
Since many people `import cats.implicits._` this change would also make it easier to discover `.nested` through an IDE's syntax completion.
> Add `.nested` syntax.

- docs/src/main/tut/resources_for_learners.md
_Advanced Scala with Cats_ was renamed to _Scala with Cats_.
> Update 'Scala with Cats' reference in docs

- build.sbt
Removes Need for Manually Setting Binary Compatible Versions
> Add Function To Check All Relevant MiMa Versions

- core/src/main/scala/cats/Bitraverse.scala
- update bisequence doc (not sure if it got any better)
- add bitraverse doctest example
> Update Bitraverse docs 

- core/src/main/scala/cats/ApplicativeError.scala
- core/src/main/scala/cats/syntax/all.scala
- core/src/main/scala/cats/syntax/applicativeError.scala
- core/src/main/scala/cats/syntax/package.scala
- core/src/main/scala/cats/syntax/validated.scala
- tests/src/test/scala/cats/tests/ValidatedSuite.scala
so that you can lift a `Validated[E, A]` to any `F[A]` that has an `Applicative[F, E]`. 
Note that I placed the syntax in a `ValidatedOps` value class mainly work around the variance requirement.  (If the method is inside `Validated` you wouldn't be able to use `E` and `A` in invariant/contravariant position, so you would have to introduce an EE >: E and AA >: A but that requires extra type parameters to be passed in, which beat the purpose of this thing which is mostly ergonomic.
> added `liftTo` syntax to `Validated`

- core/src/main/scala/cats/data/NonEmptySet.scala
- core/src/main/scala/cats/syntax/all.scala
- core/src/main/scala/cats/syntax/package.scala
- core/src/main/scala/cats/syntax/set.scala
- tests/src/test/scala/cats/tests/NonEmptySetSuite.scala
- tests/src/test/scala/cats/tests/SyntaxSuite.scala
Should fixe #2282.
@LukaJCB PTAL.
> Add groupBy for NonEmptySet

- core/src/main/scala/cats/data/OptionT.scala
- tests/src/test/scala/cats/tests/OptionTSuite.scala
> 2228-add MonadError instance for optionT where F is a Monad

- CONTRIBUTING.md
Small nits, which are even smaller than regular nits
> markdown improvements

- CONTRIBUTING.md
I am new to contributing to Cats, and ran into quite a few difficulties setting up IntelliJ with the project. I have documented the issues I hit and how to resolve them in the contributors guide.
> add editor setup tips to contrib guide

- .jvmopts
> Replace to new jvm flag

- core/src/main/scala/cats/data/AndThen.scala
- laws/src/main/scala/cats/laws/discipline/Arbitrary.scala
- laws/src/main/scala/cats/laws/discipline/Eq.scala
- tests/src/test/scala/cats/tests/AndThenSuite.scala
I'm increasingly finding use-cases for `AndThen` and it is frustrating that I have to copy it around.
Now I need it in Monix, to work with `Iterant`'s new encoding. And I remember another use-case for it in cats-effect. As explained in the ScalaDoc, it's an incredibly useful data type for whenever you have to work with `A => F[B]`.
In such cases you can piggyback on `F[_]` if it implements a stack-safe `flatMap`, however `F[_]` can be more expensive than usage of `AndThen`.
I'd like `AndThen` to be in `cats-core`, because we need it for `IndexedStateT` anyway and because it is reusable.
N.B. this doesn't break binary compatibility and so it could be released in the 1.x series.
> Make cats.data.AndThen public

- README.md
Interoperability provided in Rainier since the recent addition of a Cats module
Addresses https://github.com/stripe/rainier/issues/167 in Rainier. cc @kailuowang
> Add Rainier to the cats library list

- core/src/main/scala/cats/arrow/Choice.scala
- core/src/main/scala/cats/syntax/all.scala
- core/src/main/scala/cats/syntax/choice.scala
- core/src/main/scala/cats/syntax/package.scala
- laws/src/main/scala/cats/laws/ChoiceLaws.scala
[Choice ](https://github.com/typelevel/cats/blob/master/core/src/main/scala/cats/arrow/Choice.scala) doesn't have a separate syntax object in `cats.syntax` package and its syntax (`choice`, `|||`) is not accessible via `import cats.implicits._`
> Add choice syntax

- alleycats-core/src/main/scala/alleycats/std/map.scala
Adds the ability to import just the lawless instances for Map.
Some context:
Right now the most sane way to import lawless map instances is via `import alleycats.std.all._`. However, this is problematic due to conflicting ambiguous instances between lawless Try and regular Try:
```
[error] SomeFile.scala:38: ambiguous implicit values:                                                                
[error]  both method catsStdInstancesForTry in trait TryInstances of type => cats.MonadError[scala.util.Try,Throwable] with cats.CoflatMap[scala.util.Try] with cats.Traverse[scala.util.Try] with cats.Monad[scala.util.Try]                                                                                             
[error]  and method legacyTryBimonad in trait LegacyTryInstances of type (implicit …
```
> Add one off object for importing lawless Map instances

- core/src/main/scala/cats/Defer.scala
We might as well use sbt-doctest to ensure that this example continues
to compile.
> Use sbt-doctest for Defer example

- build.sbt
- scripts/travis-publish.sh
simulacrum companion expansion doesn't work when scaladoc compile on 2.13. 
It is probably a bug on the scala macro side, reported at https://github.com/scala/bug/issues/11045
>  temporarily disable scaladoc on 2.13

- README.md
I had a discussion with @milessabin see (https://github.com/typelevel/kittens/issues/96). We think that making kittens an official cats module (still in its own separate repo) would be a good idea. @milessabin moved it to under github typelevel.  I'm proposing this to the Cats community through this PR.
Update: I updated the title to further clarify the intention.
> Make kittens officially a Cats module (still separate repo)

- docs/src/main/tut/datatypes/nested.md
If anyone has more motivating examples, I'm happy to add them.
> Add a documentation page for Nested

- tests/src/test/scala/cats/tests/RepresentableSuite.scala
> tweak a test to compile on latest Scala 2.13 nightlies

- README.md
Very much WIP - I only added a few companies that (I guess) use Cats in prod. Please suggest others!
> Add initial adopters list

- README.md
In the _Adopters_ section given that https://47deg.com is not working.
> Updates 47 Degrees homepage URL

- CHANGES.md
- PROCESS.md
- core/src/main/scala/cats/Reducible.scala
- core/src/main/scala/cats/UnorderedFoldable.scala
- core/src/main/scala/cats/data/AndThen.scala
- core/src/main/scala/cats/evidence/package.scala
- docs/src/main/tut/datatypes/eithert.md
- kernel-laws/src/main/scala/cats/kernel/laws/SerializableLaws.scala
- tests/src/test/scala/cats/tests/EvalSuite.scala
Fixing typos is sometimes very hard. It's not so easy to visually review them. Recently, I discovered a very useful tool for it, [misspell](https://github.com/client9/misspell). 
This pull request fixes minor typos detected by [misspell](https://github.com/client9/misspell) except for the false positives. If you would like me to work on other files as well, let me know. 
```
$ misspell . | grep -v '/target/'
PROCESS.md:90:40: "occured" is a misspelling of "occurred"
CHANGES.md:806:20: "preceeded" is a misspelling of "preceded"
core/src/main/scala/cats/Reducible.scala:95:5: "Overriden" is a misspelling of "Overridden"
core/src/main/scala/cats/Reducible.scala:107:5: "Overriden" is a misspelling of "Overridden"
core/src/main/scala/cats/UnorderedFoldable.scala:47:14: "overriden" is a …
```
> Fix typos detected by github.com/client9/misspell

- free/src/main/scala/cats/free/Free.scala
- free/src/test/scala/cats/free/FreeSuite.scala
Issue https://github.com/typelevel/cats/issues/2281
> Monad[Free[Id, ?]] cannot be found

- README.md
kittens is an external cats module now. 
mainecoon became cats-tagless which is yet to be announced, but likely to become an external cats module as well.
> removed kittens and mainecoon from list

- README.md
Thi PR
- Adds HomeAway (Expedia Brand) to the adopters list
> Add HomeAway to the adopters list

- core/src/main/scala/cats/implicits.scala
- core/src/main/scala/cats/instances/all.scala
- core/src/main/scala/cats/instances/map.scala
- core/src/main/scala/cats/instances/package.scala
- testkit/src/main/scala/cats/tests/CatsSuite.scala
- tests/src/test/scala/cats/tests/MapSuite.scala
> Add Compose instance for Map

- core/src/main/scala/cats/data/OptionT.scala
- tests/src/test/scala/cats/tests/OptionTSuite.scala
> Adding on flatTransform to OptionT as suggested. (Issue #2309)

- core/src/main/scala/cats/data/Chain.scala
- laws/src/main/scala/cats/laws/discipline/Arbitrary.scala
This should fix the concerns @johnynek had in https://github.com/typelevel/cats/pull/2371
Also optimizes the `Chain.apply` builder :)
> Better Chain Arbitrary

- core/src/main/scala/cats/data/Chain.scala
This should be a slight optimization.
> Override size in Chain instance

- core/src/main/scala/cats/data/Chain.scala
- laws/src/main/scala/cats/laws/discipline/Arbitrary.scala
- tests/src/test/scala/cats/tests/ChainSuite.scala
forgive me @LukaJCB I wanted a direct Arbitrary that constructs in all the ways we can (empty, single, concat or fromList).
I think this current generator should create any possible chain with some probability.
> Make Chain Arbitraries recursively build concatenations

- core/src/main/scala/cats/Foldable.scala
- core/src/main/scala/cats/syntax/foldable.scala
- tests/src/test/scala/cats/tests/FoldableSuite.scala
#2365 seems abandoned, so this is a rework of `findM` implemented as a syntax extension for binary compatibility. Another but equivalent implementation chosen, because `Foldable.Source` is private.
> Add/fix Foldable extensions: findM and collectFirstSomeM

- core/src/main/scala/cats/data/EitherT.scala
- core/src/main/scala/cats/data/Validated.scala
- core/src/main/scala/cats/data/package.scala
- core/src/main/scala/cats/syntax/all.scala
- core/src/main/scala/cats/syntax/either.scala
- core/src/main/scala/cats/syntax/list.scala
- core/src/main/scala/cats/syntax/package.scala
- core/src/main/scala/cats/syntax/validated.scala
- tests/src/test/scala/cats/tests/EitherSuite.scala
- tests/src/test/scala/cats/tests/EitherTSuite.scala
- tests/src/test/scala/cats/tests/SyntaxSuite.scala
- tests/src/test/scala/cats/tests/ValidatedSuite.scala
This adds the `ValidatedNec` type alias as well as several api enhancements that were previously only available to `NonEmptyList`
> Give NonEmptyChain more presence

- core/src/main/scala/cats/data/Chain.scala
- core/src/main/scala/cats/instances/sortedMap.scala
- kernel/src/main/scala/cats/kernel/instances/map.scala
Remove unnecessary semicolons for small  improvements.
> Remove unnecessary semicolons

- docs/src/main/tut/datatypes/ior.md
- docs/src/main/tut/datatypes/iort.md
* replace `NonEmptyList` with `NonEmptyChain` in `Ior` and `IorT` docs
* fixes #2429
> #2429 Replace all usage of the list Monoid in the docs with the chain Monoid

- README.md
Not a module inside Cats repo, it's still in its own repo with its own release cycle just like the other 4 "outside" modules cats-mtl, cats-effect, mouse and kittens. 
Nothing really special about being an official cats external module other than some sort of commitment that Cats maintainers are going to help its maintenance. As of now, the majority of the code of cats-tagless came from two projects from two Cats maintainer @LukaJCB and myself. I plan to remain a maintainer of the project. (how about you @LukaJCB ?)
> Proposal - add cats-tagless as an external module

- core/src/main/scala/cats/ApplicativeError.scala
- core/src/main/scala/cats/syntax/either.scala
- core/src/main/scala/cats/syntax/option.scala
Currently OptionOps#liftTo interacts badly with subtyping. Something like this won't compile:
```scala
42.some.liftTo[IO](new Exception("foo"))
```
One needs to write this instead: 
```scala
42.some.liftTo[IO](new Exception("foo"): Throwable)
```
This patch fixes this.
> improve interaction with subtyping in OptionOps#liftTo

- core/src/main/scala/cats/Functor.scala
This PR implements https://github.com/typelevel/cats/issues/2479 for the `Functor` typeclass.
Would love feedback on the examples, if anything more complex is needed.
> Add examples to Functor and verify with docstyle

- build.sbt
Are we sure we even need this? I just ran `buildJVM` on my laptop for 2.13.0-M4 and it worked just fine.
> Kill scala-collection-compat

- core/src/main/scala/cats/syntax/nested.scala
Made 'value'  private in `NestedIdOps`
This prevents 'value' from leaking into types with shape `F[G[A]]`.  
I encountered this issue while using Scalatests `OptionValues` on things with a `G[A]` shape, so I had a `Option[G[A]]` and tried to use `.value`.  It caused an ambiguous implicit match with `NestedIdOps`.
I didn't add a test, because I didn't know where it should go.  Would `SyntaxSuite.testNested` be an appropriate place?
> Fix NestedIdOps.value leaking to types of shapes `F[G[A]]`

- kernel-laws/src/test/scala/cats/kernel/laws/LawTests.scala
- kernel/src/main/scala/cats/kernel/Order.scala
I sometimes find myself writing `Order` instances using a 'less than' function. There is no such helper function for `Order`, but there is one for `Ordering`, which means that you currently have to rely on the `fromOrdering` function as follows.
```scala
import cats.Order
import java.time.Instant
implicit val orderInstant: Order[Instant] =
Order.fromOrdering(Ordering.fromLessThan(_ isBefore _))
```
This pull request adds a `fromLessThan` function to `Order`, so we don't have to use `Ordering`.
```scala
implicit val orderInstant: Order[Instant] =
Order.fromLessThan(_ isBefore _)
```
> Add Order#fromLessThan

- core/src/main/scala/cats/syntax/applicativeError.scala
- tests/src/test/scala/cats/tests/SyntaxSuite.scala
Inspired by #2480, applying the same trick to `.raiseError` so that I can write `MyException(...).raiseError[IO, Unit]`, instead of `(MyException(...): Throwable).raiseError[IO, Unit]`.
> .raiseError syntax allows an error subtype

- alleycats-core/src/main/scala/alleycats/std/all.scala
- alleycats-core/src/main/scala/alleycats/std/future.scala
The big advantage of doing this is that doing `pure` does not require an ExecutionContext, as catsStdInstancesForFuture does
> Add Pure instance for Future

- core/src/main/scala/cats/syntax/eq.scala
- tests/src/test/scala/cats/tests/SyntaxSuite.scala
> fixed eqv alias issue #2513:

- core/src/main/scala/cats/data/Validated.scala
- tests/src/test/scala/cats/tests/ValidatedSuite.scala
fix the problems in https://github.com/typelevel/cats/pull/2472
> Add toValidatedNec to Validated

- core/src/main/scala/cats/implicits.scala
- core/src/main/scala/cats/syntax/all.scala
- core/src/main/scala/cats/syntax/package.scala
- core/src/main/scala/cats/syntax/unorderedFoldable.scala
- testkit/src/main/scala/cats/tests/CatsSuite.scala
- tests/src/test/scala/cats/tests/UnorderedFoldableSuite.scala
> Add count as syntax to UnorderedFoldable

- build.sbt
- kernel/src/main/scala/cats/kernel/Group.scala
- kernel/src/main/scala/cats/kernel/Monoid.scala
- kernel/src/main/scala/cats/kernel/Semigroup.scala
PR for part of #2479.
Adds doctests for the `Semigroup`, `Group`, and `Monoid` typeclasses.
> Add doctests for Semigroup, Group, and Monoid

- core/src/main/scala/cats/data/NonEmptyMapImpl.scala
- tests/src/test/scala/cats/tests/NonEmptyMapSuite.scala
Hello, this is my first pull request there so please go easy with me :)
As for #2346 started with small steps - implementing just first method. Frankly i have no idea if I placed this in proper place, no idea if my test is sufficient and no idea if the thing I implemented is performant and if my git message is sufficient. Would love any feedback from you. Then after initial feedback I will do my best to implement rest of the methods from that issue
> Add NonEmptyMap#toNonEmptyList (issue #2346)

- core/src/main/scala/cats/data/Ior.scala
- core/src/main/scala/cats/syntax/either.scala
- tests/src/test/scala/cats/tests/EitherSuite.scala
- tests/src/test/scala/cats/tests/IorSuite.scala
Also brings `Ior#toIorNel`.
I'm also pondering submitting an `EitherTNel` type alias in the `cats.data` package object, together with conversions from `EitherT`, but then we'd need to do the same for `IorT` I guess.
> Add Either#toEitherNel extension and friends

- CONTRIBUTING.md
Resolves #153 (okay someone else resolved this issue a while ago, but we
should be able to close out the issue when this is merged).
> Fix link for contributing documentation

- core/src/main/scala/cats/data/IndexedStateT.scala
- core/src/main/scala/cats/data/package.scala
- tests/src/test/scala/cats/tests/IndexedStateTSuite.scala
Work by @sderosiaux in #2294. Rebased to current master. For some reason, the bincompat error also went away (at least locally).
> Add empty to State and StateT objects

- README.md
@stew generously [donated dogs to become typelevel/cats-collections](https://github.com/typelevel/cats-collections/issues/104). @larsrh completed the migration and started actively maintaining it. @LukaJCB, @ChristopherDavenport and I also signed up for help maintaining it. 
We'd like to propose to the Cats community to make cats-collections an external Cats module (separate repo and release cycle). 
The main implication for being a Cats external module is that at least some Cats maintainers will help maintaining it, which is the case now.
> Proposal: add `cats-collections` as an external cats module

- bench/src/main/scala/cats/bench/FoldBench.scala
- core/src/main/scala/cats/instances/vector.scala
I've also added a benchmark to compare the new implementation with the
old. Here are the results that I got on my computer when running
`bench/jmh:run -i 10 -wi 10 -f1 -t1 .*FoldBench\.vector.*`:
```
Benchmark                     Mode  Cnt        Score       Error  Units
FoldBench.vectorIndexFoldM   thrpt   10  1185138.829 ± 45633.259  ops/s
FoldBench.vectorToListFoldM  thrpt   10   817330.438 ± 21998.851  ops/s
```
> Optimize the foldM implementation for Vector

- core/src/main/scala/cats/data/NonEmptyList.scala
- tests/src/test/scala/cats/tests/NonEmptyListSuite.scala
Here comes the implementation of nel to nem, hope you like it :)
> Add NonEmptyList#toNem (issue #2346)

- core/src/main/scala/cats/data/Ior.scala
- core/src/main/scala/cats/data/package.scala
- core/src/main/scala/cats/syntax/either.scala
- tests/src/test/scala/cats/tests/EitherSuite.scala
- tests/src/test/scala/cats/tests/IorSuite.scala
addresses  https://github.com/typelevel/cats/issues/2539
We might need to merge https://github.com/typelevel/cats/pull/2475 first because our changes are going to overlap each other, happy to merge the previous PR then fix conflicts in my branch.
> Adding Nes and Nec equivalents of Nel functions

- README.md
addresses https://github.com/typelevel/cats/issues/2529
I added a link to the new "cats friendly" badge and a quick snippet on how to put it in another README, from @rossabaker's comment on http4s https://github.com/typelevel/cats/issues/2529#issuecomment-427704930
> Adding the cats friendly badge link to README

- core/src/main/scala/cats/data/Const.scala
- core/src/main/scala/cats/data/OptionT.scala
- core/src/main/scala/cats/data/WriterT.scala
- laws/src/main/scala/cats/laws/discipline/Arbitrary.scala
- tests/src/test/scala/cats/tests/ConstSuite.scala
- tests/src/test/scala/cats/tests/OptionTSuite.scala
- tests/src/test/scala/cats/tests/WriterTSuite.scala
It should close https://github.com/typelevel/cats/issues/2545
While checking the Invariant I noticed that there is an issue with the priority of ContravariantMonoidal and Traverse in Const so I fixed it and added tests. Can be reproduced with
```scala
scala> import cats._, cats.implicits._, cats.data._
import cats._
import cats.data._
scala> Invariant[Const[String, ?]]
<console>:21: error: ambiguous implicit values:
both method catsDataContravariantMonoidalForConst in class ConstInstances of type [D](implicit evidence$3: cats.Monoid[D])cats.ContravariantMonoidal[[β$0$]cats.data.Const[D,β$0$]]
and method catsDataTraverseForConst in class ConstInstances of type [C]=> cats.Traverse[[β$2$]cats.data.Const[C,β$2$]]
match expected type …
```
> Missing Contravariant instance for OptionT

- README.md
- core/src/main/scala/cats/syntax/option.scala
We do have `toInvalidNel` and `toValidNel` already - just the the methods to lift an `Option` to a `ValidatedNec` are missing - though they come in very handy sometimes.
Complements the work already done #2475 and #2539.
> Add OptionOps.toInvalidNec and OptionOps.toValidNec

- build.sbt
Scalacheck hasn't published artifact for Scala Native yet and that cause problem with indexing project in IntelliJ. The plan is to temporarily disable Scala Native cross-project until artifact will be available
at https://github.com/rickynils/scalacheck/issues/396
fixes #2559
> Disable Scala Native build for kernel

- build.sbt
I noticed that the test is running in fork and was using the default java options. 
This setting change shall boost it's max memory to 6GB, according to travis, we have 7.5 G on the machine.
> give test more memory

- docs/src/main/resources/microsite/data/menu.yml
- docs/src/main/tut/typeclasses/alternative.md
Adds some docs on the `Alternative` type class covering:
- Examples from basic collections
- Examples from parsing (just sketched)
- Examples using partition
> Add Alternative docs

- core/src/main/scala/cats/data/EitherT.scala
- tests/src/test/scala/cats/tests/EitherTSuite.scala
> Add biFlatMap to EitherT

- build.sbt
To be honest I have no idea what I'm doing, but we were getting an
`[warn] javaOptions will be ignored, fork is set to false` warning, and
the [SBT docs](https://www.scala-sbt.org/1.0/docs/Forking.html) suggest
that this is the right approach.
> Fix test fork settings I think

- core/src/main/scala/cats/UnorderedFoldable.scala
- tests/src/test/scala/cats/tests/UnorderedFoldableSuite.scala
Fixes issue https://github.com/typelevel/cats/issues/2584 and adds some tests.
> UnorderedFoldable#isEmpty default implementation is incorrect

- CONTRIBUTING.md
Made the link to the code guidelines in `CONTRIBUTING.md` absolute so that it works in both the github markdown viewer and form the website as discussed here https://gitter.im/typelevel/cats?at=5bccdbb8bbdc0b25057a0716.
Consistent with the references to [laws](https://github.com/typelevel/cats/blob/master/CONTRIBUTING.md#L165) [lawtesting](https://github.com/typelevel/cats/blob/master/CONTRIBUTING.md#L165).
> Contributing guidelines link

- core/src/main/scala/cats/data/NonEmptyMapImpl.scala
- tests/src/test/scala/cats/tests/NonEmptyMapSuite.scala
- Named `updateWith` since `updated` would imply a simple setting of k -> v
- Added a couple small tests
Closes https://github.com/typelevel/cats/issues/2288
> Add `updateWith` method to NonEmptyMap

- core/src/main/scala/cats/data/Chain.scala
- core/src/main/scala/cats/data/NonEmptyChain.scala
- tests/src/test/scala/cats/tests/ChainSuite.scala
- tests/src/test/scala/cats/tests/NonEmptyChainSuite.scala
Implemented and tested `Chain#distinct` and `NonEmptyChain#distinct`.
Still needs examples.
> Added `Chain#distinct` and `NonEmptyChain#distinct` to match `List#distinct` and `NonEmptyList#distinct`

- docs/src/main/tut/nomenclature.md
Adds a page with the types and names of the many functions and methods of `cats`. 
The types are written in a Haskell-lke form, as separate currified type signatures, without the names of the parameters.
> Add Nomenclature / Cheatsheet page

- core/src/main/scala/cats/FlatMap.scala
I noticed that these implementations can be slightly improved. Given their common usages I think it would worth it. 
related issue https://github.com/typelevel/cats-effect/issues/401
> Optimize `Apply` methods in `FlatMap`

- core/src/main/scala/cats/data/Chain.scala
- tests/src/test/scala/cats/tests/ChainSuite.scala
This is a kind reminder to run `sbt prePR` and commit the changed files before submitting.
> Expose headOption for Chain

- core/src/main/scala/cats/data/ContT.scala
- tests/src/test/scala/cats/tests/ContTSuite.scala
ContT is a challenging Monad to implement if you need to implement tailRecM.
The addition of the Defer typeclass solves this problem. This PR replaces the unmerged #1400.
cc @non
> Add ContT monad

- core/src/main/scala/cats/Apply.scala
- core/src/main/scala/cats/syntax/all.scala
- core/src/main/scala/cats/syntax/function1.scala
Add the `flap` function to `Apply` to facilitate combining a function in an
`Apply` context with a value which is not.
This is similar to `ap`:
```
def ap[A, B](ff: F[A => B])(fa: F[A]): F[B]
```
with the minor change of the value not being in a context:
```
def flap[A, B](ff: F[A => B])(a: A): F[B]
^^^^
```
This is a kind reminder to run `sbt prePR` and commit the changed files before submitting.
> Add flap function to Apply

- binCompatTest/src/main/scala/catsBC/MimaExceptions.scala
- build.sbt
- core/src/main/scala/cats/syntax/either.scala
- core/src/main/scala/cats/syntax/nested.scala
This makes the `.value` of two of the `Ops` classes private, since they shouldn't ever be referenced and they collide with Scalatest.
Fixes #2514 and #2613
> Make the value of the class private

- .jvmopts
- build.sbt
Another attempt at fixing OOM's in build 
So the .jvmopts sets max memory to 6G AND the (one) forked jvm for tests also sets memory to 6G (which by default would receive the same settings anyway, btw). So if my maths is correct, that‘s 12G in total on a machine that IIRC is only 7.5G. 
So set .jvmopts to 3G and the forked JVM javaopts to also 3G
Supporting issue :
https://github.com/scalatest/scalatest/issues/770, 
NB:
„...to cap the memory for the main process + the forked process to be < 3G at any point of time. That would mean:
main process + SBT forked process + debugger process in test (if you created)
should not be > 3G“
„...providing the memory caps on the main process, forked, process, and children worked.“
Note that, if you follow the links, the same issue is reported for specs2 …
> Reduce Xmx in .jvmopts and build.sbt

- core/src/main/scala/cats/data/IndexedStateT.scala
- core/src/main/scala/cats/data/Kleisli.scala
- tests/src/test/scala/cats/tests/IndexedStateTSuite.scala
- tests/src/test/scala/cats/tests/KleisliSuite.scala
This adds `FunctorFilter` to `Kleisli` and `IndexedStateT` as from the issue https://github.com/typelevel/cats/issues/2556 . As a side note I tried to reduce the requirements for the `IndexedStateT` instance but I couldn't come up with anything that need less than `Applicative` and `FlatMap`, so I kept the implementation in the issue that requires `Monad` (see below as an example)
```scala
def mapFilter[A, B](fa: IndexedStateT[F, SA, SB, A])(f: A => Option[B]): IndexedStateT[F, SA, SB, B] =
IndexedStateT[F, SA, SB, B] { sa =>
FF.mapFilter(fa.run(sa)){ case (sb, a) => f(a) map (sb -> _) }
}
```
I'm happy to change it though if there's something less restrictive.
There is still some work to do about the comments at the bottom of the ticket that I'm still investigating. I need more details …
> Get FunctorFilter on par with the other MTL typeclasses

- scripts/parse-test-durations.awk
This is something that I have recreated a couple of times when I've been
looking into builds timing out, so I wanted to save it somewhere in case
I want to use it again. I figured I might as well submit a PR in case
other people might find this to be useful. But I can understand if we
don't want to litter the Cats code base with one-off scripts.
> Add awk script to parse test durations

- docs/src/main/tut/nomenclature.md
> Fix documented constraint on B param in foldMapM

- docs/src/main/tut/nomenclature.md
> Update table headers and clarify method signature for `flatTap`

- docs/src/main/tut/nomenclature.md
This is a kind reminder to run `sbt prePR` and commit the changed files before submitting.
> Fix type signature of `productL` in cats glossary

- docs/src/main/tut/datatypes/chain.md
> Fix a typo in Chain's doc

- build.sbt
Just realized that currently prePR is testing BC  on 2.12 which probably won't catch the majority of the BC breaking changes.
> change prePR to run BC test on Scala 2.11

- docs/src/main/tut/datatypes/either.md
- docs/src/main/tut/datatypes/ior.md
- docs/src/main/tut/datatypes/nested.md
- docs/src/main/tut/datatypes/validated.md
- docs/src/main/tut/typeclasses/applicative.md
- docs/src/main/tut/typeclasses/functor.md
- docs/src/main/tut/typeclasses/monoid.md
- docs/src/main/tut/typeclasses/semigroup.md
- docs/src/main/tut/typeclasses/traverse.md
https://github.com/typelevel/cats/issues/2651
@LukaJCB @tpolecat 
How does this look to you guys? Hopefully I got them all, happy to take another sweep through if you know of any I missed.
> Cleaning up docs to no longer use fine grained imports

- core/src/main/scala/cats/data/Kleisli.scala
- tests/src/test/scala/cats/tests/KleisliSuite.scala
Related: https://github.com/typelevel/cats-effect/pull/334
I don't like the name either, so feel free to suggest a better one 😅
> Add Kleisli#mapK equivalent returning FunctionK

- CONTRIBUTING.md
- shell.nix
I have mixed feelings about this. On the one hand, it feels like which
tools a developer uses in their environment shouldn't bleed into the
source repository. On the other hand, getting a proper Cats development
environment includes wrangling some finicky bits that can be tricky for
a Scala developer (such as managing Jekyll and Node.js versions). I'm
generally in favor of lowering this barrier and using a deterministic
build environment.
I've been using something like this for a while when working on Cats and
thought that I'd put together this PR in case others are interested in
doing the same. If people aren't crazy about this, it's no big deal;
it's easy enough to have it ignored by git.
> Add a shell.nix and instructions for using it

- docs/src/main/tut/faq.md
As stated by https://github.com/typelevel/cats/pull/1435#issuecomment-256284304 the `{{ site.sources }}` configuration item was lost. 
Already 6 occurrences exist in the docs that link directly to `https://github.com/typelevel/cats/blob/master`. 
In all documentation, this was the only place where `sources` was still used, so instead of adding a [custom yaml](https://47deg.github.io/sbt-microsites/docs/settings.html) and keep the tightly coupling with Jekyll, I've replaced this one instance with another hard-coded link to master.
> Fix broken link to Arrow.scala

- core/src/main/scala/cats/syntax/all.scala
- core/src/main/scala/cats/syntax/package.scala
- core/src/main/scala/cats/syntax/parallel.scala
- tests/src/test/scala/cats/tests/SyntaxSuite.scala
in #2038 introduced `&>` and `<&` syntax for parallel which are very helpful
why not have a `<&>` too, so  I can
```scala
mab <&> ma
```
instead of
```scala
Parallel.parAp(mab)(ma)
```
> add syntax <&> for parallel

- docs/src/main/tut/faq.md
- docs/src/main/tut/guidelines.md
Closes #2272.
Just a few lines to start with, hope you have some feedback on what else I can mention/what can be reworded :)
> Add an explanation for the missing Applicative instances for monad transformers

- core/src/main/scala/cats/syntax/all.scala
- core/src/main/scala/cats/syntax/foldable.scala
- core/src/main/scala/cats/syntax/package.scala
- core/src/main/scala/cats/syntax/reducible.scala
Closes #2275.
Not sure if we need to forward the target effect parameter of these functions in all the test classes, or whether we can just use `Id` or some other hardcoded type having a `MonoidK`, but for now I added appropriate implicits etc. everywhere.
> Add foldMapK, reduceMapK

- build.sbt
> minor fix to build

- core/src/main/scala/cats/data/EitherT.scala
- core/src/main/scala/cats/syntax/monadError.scala
- tests/src/test/scala/cats/tests/EitherTSuite.scala
- tests/src/test/scala/cats/tests/MonadErrorSuite.scala
- Add `rethrowT` method to EitherT: inverse of `ApplicativeError#attemptT`, analogous to `MonadError#rethrow`
- Add/fix some tests
- Document `MonadErrorOps.reject` and refactor to one line
> Add `rethrowT` method to EitherT

- core/src/main/scala/cats/data/Chain.scala
- testkit/src/main/scala/cats/tests/ListWrapper.scala
- tests/src/test/scala/cats/tests/ChainSuite.scala
> Override equals and hashCode on Chain

- core/src/main/scala/cats/implicits.scala
- core/src/main/scala/cats/instances/all.scala
- core/src/main/scala/cats/instances/duration.scala
- core/src/main/scala/cats/instances/finiteDuration.scala
- core/src/main/scala/cats/instances/package.scala
- testkit/src/main/scala/cats/tests/CatsSuite.scala
- tests/src/test/scala/cats/tests/ShowSuite.scala
This is to address https://github.com/typelevel/cats/issues/2657
> Issue 2657 - Ambiguous duration instances

- core/src/main/scala/cats/data/IndexedStateT.scala
- core/src/main/scala/cats/data/package.scala
> Add IndexedState alias (#2686)

- README.md
BabylonHealth is a London based healthcare and AI company with several teams using Scala and cats. I've added it to the list of adopters.
> Add BabylonHealth to list of adopters

- docs/src/main/resources/microsite/data/menu.yml
I've noticed that in the documentation, there seems to be duplicate sub-menu items for Functors and Applicatives, under both `Traversable Functors` and `Monads`.
When you click on either sub-menu items, they show the exact same page and highlight both items on the side menu. It seems to make more sense to remove `Functors` and `Applicatives` from the Monads menu, since Monads appear right after `Traversable Functors` anyways. 
Let me know if this is something that has already been raised before, or it is this way for a reason. I was just initially confused because I noticed that 2 menu items would be lit up when I visited these pages.
> Remove duplicate menu item in docs

- core/src/main/scala/cats/data/Kleisli.scala
We add an `applyK` function to the `Kleisli` companion object. This takes a parameter of type `A`, and generates a natural transformation (`FunctionK`) from `Kleisli[F,A,?]` to `F`, i.e., it maps over the Kleisli object by applying it to the given parameter.
An alternative name for this function could be `dipK`, or something that conveys the idea of it being contrary to the `liftK` function.
> Add an `applyK` function to `Kleisli`.

- docs/src/main/tut/resources_for_learners.md
> added Scala Pets store as an example project

- binCompatTest/src/main/scala/catsBC/MimaExceptions.scala
- build.sbt
- core/src/main/scala/cats/syntax/either.scala
- core/src/main/scala/cats/syntax/foldable.scala
- core/src/main/scala/cats/syntax/reducible.scala
- core/src/main/scala/cats/syntax/traverseFilter.scala
- kernel-laws/src/main/scala/cats/kernel/laws/package.scala
- laws/src/main/scala/cats/laws/package.scala
- project/Boilerplate.scala
- project/KernelBoiler.scala
In relation to https://github.com/typelevel/cats/issues/2673 , this adds few more `private`s to constructor's parameters when extending `AnyVal`.
In the case of `Either`'s `CatchOnlyPartiallyApplied` I added an exception to MiMa as there are good chances no one is really using `dummy`.
> Private val in value classes (Resolve TODO since 2.10 is dropped)

- docs/src/main/tut/datatypes/contt.md
Had a crack at writing some documentation for ContT.
Corrections/suggestions welcome.
> Write documentation for ContT

- core/src/main/scala/cats/data/ContT.scala
- tests/src/test/scala/cats/tests/ContTSuite.scala
As suggested in #2677.
Similar to the existing `pure` function, but evaluation of the argument is deferred.
This is useful for building a computation which calls its continuation as the final step. Instead of writing:
```scala
ContT.apply { next =>
val x = foo()
val y = bar(x)
val z = baz(y)
next(z)
}
```
you can write:
```scala
ContT.defer {
val x = foo()
val y = bar(x)
baz(y)
}
```
> Add a `defer` factory method to `ContT`

- core/src/main/scala/cats/syntax/foldable.scala
- testkit/src/main/scala/cats/tests/CatsSuite.scala
- tests/src/test/scala/cats/tests/FoldableSuite.scala
> Adds version of mkString_ with no prefix/suffix, matching the std lib.

- core/src/main/scala/cats/data/Kleisli.scala
Re: Issue #2479 -- Appreciate any feedback to improve or further clarify examples.
Adds  comments and some doctests for *Kleisli*:
* dimap
* map
* andThen
* local
* liftF
* pure
* ask
> Add more doctests to Kleisli

- laws/src/main/scala/cats/laws/InvariantMonoidalLaws.scala
- laws/src/main/scala/cats/laws/InvariantSemigroupalLaws.scala
- laws/src/main/scala/cats/laws/discipline/InvariantMonoidalTests.scala
- laws/src/main/scala/cats/laws/discipline/InvariantSemigroupalTests.scala
Changed the parents of InvariantMonoidalTests to invariantSemigroupal and moved the invariant associativity test from InvariantMonoidalTests to InvariantSemigroupalTests
> Fixes #2631 Fix InvariantMonoidal Laws

- core/src/main/scala/cats/data/Kleisli.scala
- core/src/main/scala/cats/syntax/foldable.scala
Though they don't seem to actually fail the build before #2734 and I'm
not sure why...
> Fix failing doctests

- build.sbt
- project/build.properties
The old release steps are from the sbt 0.13 era. Now that modular crossScalaVersions issue is improved in sbt 1.x, we need to switch to this new release steps - i.e. the root module should have a `Nil` `crossScalaVersions` setting, then each module can have their own `crossScalaVersions` settings and release accordingly.
This change also reduced significantly the number of unnecessary settings on the root module - which fixes #2730  
To test this build code, I released a `0.0.1-DONOTUSE`, and tested with cats-tagless
> new better release settings

- free/src/main/scala/cats/free/Free.scala
- free/src/test/scala/cats/free/FreeSuite.scala
so any `Free[S, A]` can be converted to `FreeT[S, G, A]` if there is an Applicative instance of G
> adding helper method `toFreeT` to `Free`

- .travis.yml
Resolves #2570
This sets up the Cats Travis build to use Travis's stages feature and
modularizes the Travis jobs. This probably introduces a little bit of
extra overhead since each new job needs to spin up a virtual machine and
pull the cache. However, I think that this extra overhead is offset by a
number of factors (see further below). And in experimenting with builds on
my fork, the build time looks to have gone from ~43 min to ~33 min with this
change. See [here](https://travis-ci.org/ceedubs/cats/builds/494690714) for an example.
We are now only publishing code coverage reports for the default Scala
version (currently 2.12.x). I don't think that publishing multiple
coverage reports for the same commit even has well-defined results, and
I suspect that we didn't really mean to do that. …
> Experiment with modularizing Travis jobs

- core/src/main/scala/cats/Apply.scala
Further improvement similar to #2597 . Resolves problems like this: https://github.com/typelevel/cats-effect/issues/401 .
Reference to `a` was kept unnecessarily by prev implementation with map2:
```
//Expanding productR: map2 => product => ap => flatMap
fa *> fb == 
fa
.map(a => (b: B) => (a,b))
.flatMap(f => fb.map(f)).map((_, b) => b)
```
> Optimize productR in Apply

- core/src/main/scala/cats/implicits.scala
- core/src/main/scala/cats/instances/all.scala
- core/src/main/scala/cats/instances/map.scala
- core/src/main/scala/cats/instances/package.scala
- core/src/main/scala/cats/instances/sortedMap.scala
- testkit/src/main/scala/cats/tests/CatsSuite.scala
- tests/src/test/scala/cats/tests/MapSuite.scala
- tests/src/test/scala/cats/tests/SortedMapSuite.scala
> MonoidK instances for Map and SortedMap

- core/src/main/scala/cats/CommutativeApplicative.scala
- core/src/main/scala/cats/CommutativeApply.scala
- tests/src/test/scala/cats/tests/AlgebraInvariantSuite.scala
> add method on `object CommutativeApplicative` to get `CommutativeMonoid`

- core/src/main/scala/cats/instances/function.scala
- tests/src/test/scala/cats/tests/FunctionSuite.scala
> Make MonoidK[Endo] stack safe on combineK

- build.sbt
> upgrade to scalacheck 1.14

- .travis.yml
before committing to run the full build.
> added a styling stage to check the styles first

- core/src/main/scala/cats/data/OptionT.scala
> Define OptionT.mapFilter in terms of OptionT.subflatMap

- core/src/main/scala/cats/evidence/Is.scala
- tests/src/test/scala/cats/tests/IsSuite.scala
> Category[Is] and related tests

- core/src/main/scala/cats/Parallel.scala
- core/src/main/scala/cats/syntax/all.scala
- core/src/main/scala/cats/syntax/package.scala
- core/src/main/scala/cats/syntax/parallel.scala
- testkit/src/main/scala/cats/tests/CatsSuite.scala
- tests/src/test/scala/cats/tests/ParallelSuite.scala
- tests/src/test/scala/cats/tests/SyntaxSuite.scala
Added `parBitraverse`, `parBisequence`, `parLeftTraverse`, `parLeftSequence`
> Par functions for Bitraverse

- core/src/main/scala/cats/Representable.scala
- tests/src/test/scala/cats/tests/RepresentableSuite.scala
> Distributive instance for Representable Functor

- core/src/main/scala/cats/data/EitherT.scala
- tests/src/test/scala/cats/tests/EitherTSuite.scala
very simple short cuts, kind of a counterpart for `getOrElseF`
> added `foldF` to `EitherT`

- kernel/src/main/scala-2.12-/cats/kernel/compat/WrappedMutableMapBase.scala
- kernel/src/main/scala-2.13+/cats/kernel/compat/WrappedMutableMapBase.scala
- tests/src/test/scala/cats/tests/MapSuite.scala
We are running into Spark `Task not serializable` issues when a closure
that executes on a Spark executor node involves a `Map` that is created
via running `foldMap` on a `List`. This commit makes the
`WrappedMutableMap` hierarchy extend `Serializable` and chex that the
cerealization works (this test failed before extending `Serializable`).
> Make WrappedMutableMapBase extend Serializable

- alleycats-core/src/main/scala/alleycats/ConsK.scala
- alleycats-core/src/main/scala/alleycats/Empty.scala
- alleycats-core/src/main/scala/alleycats/EmptyK.scala
- alleycats-core/src/main/scala/alleycats/Extract.scala
- alleycats-core/src/main/scala/alleycats/One.scala
- alleycats-core/src/main/scala/alleycats/Pure.scala
- alleycats-core/src/main/scala/alleycats/Zero.scala
- alleycats-core/src/main/scala/alleycats/std/all.scala
- alleycats-core/src/main/scala/alleycats/std/future.scala
- alleycats-core/src/main/scala/alleycats/std/iterable.scala
- alleycats-core/src/main/scala/alleycats/std/list.scala
- alleycats-core/src/main/scala/alleycats/std/map.scala
- alleycats-core/src/main/scala/alleycats/std/option.scala
- alleycats-core/src/main/scala/alleycats/std/set.scala
- alleycats-core/src/main/scala/alleycats/std/try.scala
- alleycats-tests/src/test/scala/alleycats/tests/MapSuite.scala
- build.sbt
export hook seems to be blocking updating to 2.13.0-RC1 #2792
> removed export hook

- .jvmopts
Changes the JVM options used by SBT somewhat.
Here is the reasoning for each change:
* `-Xmx4G` - the Travis infrastructure that we're using [has 7.5GB of memory](https://docs.travis-ci.com/user/reference/overview/), this could probably be increased further if forking tests was also disabled
* removal of `XX:-UseGCOverheadLimit` - I think that this is just creating zombie builds that are stuck thrashing the GC and will timeout anyway due to lack of progress, better to fail early IMO
* removal of `-XX:+CMSClassUnloadingEnabled` - this is relevant only for the CMS collector
* switch from `-XX:+UseConcMarkSweepGC` to `-XX:+UseParallelGC` - from what I understand the concurrent CMS collector is a response time collector, whereas the parallel GC is a throughput collector (more on this in the …
> Tuning JVM options for throughput

- core/src/main/scala/cats/data/NonEmptyChain.scala
This will update the scaladocs for NonEmptyChain. 
The same example was used for  `reduceRightTo` and `reduceLeftTo` method. 
Fix #2803
> Fix repetition in NonEmptyChain scala docs

- alleycats-tests/shared/src/test/scala/alleycats/tests/AlleycatsSuite.scala
- binCompatTest/src/test/scala/catsBC/MimaExceptionsTest.scala
- build.sbt
- kernel-laws/shared/src/test/scala/cats/kernel/laws/LawTests.scala
- laws/src/test/scala/cats/laws/discipline/MonadTestsTests.scala
- testkit/src/main/scala/cats/tests/CatsSuite.scala
- tests/src/test/scala/cats/tests/FoldableSuite.scala
- tests/src/test/scala/cats/tests/ParallelSuite.scala
- tests/src/test/scala/cats/tests/SemigroupSuite.scala
- tests/src/test/scala/cats/tests/ShowSuite.scala
- tests/src/test/scala/cats/tests/TraverseSuite.scala
- tests/src/test/scala/cats/tests/UnorderedFoldableSuite.scala
This shall enable a 2.0-M1 release
> update scalatest and discipline.

- core/src/main/scala/cats/syntax/monadError.scala
- tests/src/test/scala/cats/tests/RegressionSuite.scala
> Change MonadErrorOps#reject so it no longer runs effects twice

- README.md
> added navigation links to readme

- core/src/main/scala/cats/data/Chain.scala
- core/src/main/scala/cats/data/NonEmptyChain.scala
> Added collectFirst to Chain and NonEmptyChain

- core/src/main/scala/cats/Apply.scala
- tests/src/test/scala/cats/tests/ApplicativeSuite.scala
This is to address the root cause of #2648 and #2319, the target method of this test is the combine method provided by `Apply.semigroup`
https://github.com/typelevel/cats/blob/master/core/src/main/scala/cats/Apply.scala#L223-L225
```
def combine(a: F[A], b: F[A]): F[A] =
f.map2(a, b)(sg.combine)
```
In the case of `F` being a list,  since this is a product operation between the two lists, the result is a list of the size `a.size * b.size`
When this `combine` is used in the `combineAllOption` test, which combine all items in a `Vector[ListWrapper[Int]]`, it exponentially increase the size of the accumulative result list. That leads to a list of millions of items and over limit GC pressure that breaks the build.
I switch it to using `Option` instead.
> In  Apply.semigroup test replace ` ListWrapper` with `Option`

- core/src/main/scala/cats/UnorderedFoldable.scala
- core/src/main/scala/cats/data/NonEmptyChain.scala
- core/src/main/scala/cats/instances/map.scala
- core/src/main/scala/cats/instances/set.scala
- laws/src/main/scala/cats/laws/FoldableLaws.scala
- laws/src/main/scala/cats/laws/UnorderedFoldableLaws.scala
- laws/src/main/scala/cats/laws/discipline/FoldableTests.scala
- laws/src/main/scala/cats/laws/discipline/UnorderedFoldableTests.scala
- tests/src/test/scala/cats/tests/UnorderedFoldableSuite.scala
I noticed that `foldRight`'s laziness was tested through `forallLazy` and `existLazy` laws. Since `foldRight` is a type class method I think we should have the laziness law on it. In kittens we were caught by the lack of such a law. 
Also I noticed that although `forallLazy` and `existLazy` are defined in `UnorderedFoldableLaws`, they are actually only used in `FoldableTests`. Moreover, implementations in `UnorderedFoldable` breaks these two laws. So I think they should probably be `FoldableLaws`. 
Update: This actually caught a bug in NonEmptyChain whose `Foldable.foldRight` implementation is simply delegating to the native (scala std lib) `foldRight`.
> added a new foldRight lazy law, move forallLazy and existLazy laws

- tests/src/test/scala/cats/tests/ApplicativeSuite.scala
> fixed applicative monoid test

- core/src/main/scala/cats/data/EitherT.scala
This PR delete an unnecessary type restriction on the `EitherT#biFlatMap` implementation
> Delete unnecessary restriction on biFlatMap

- docs/src/main/tut/datatypes/freemonad.md
> added FreeT basic example

- docs/src/main/tut/typeclasses/parallel.md
The previous example didn't actually illustrate the parallel behavior of parSequence.
> Edit example in Parallel docs

- .travis.yml
The sbt-hydra checks if a hydra.license file exists to decide whether it should enable
itself. Therefore, if the $HydraLicense is empty, it's important not to
create the hydra.license file.
The reason why the $HydraLicense can be empty is because its content is a
secret, hence it is available only to PRs created from within the repository.
Otherwise, the secret would be easily leaked.
This commit is a followup fix for 8069e09
---
I'm afraid the PR #2857 needs to include this fix to be validated. Sorry!
Please, don't hesitate to pull me and @dragos in if you hit any hurdle with Hydra.
> Don't create the hydra.license if $HydraLicense is empty

- .travis.yml
- alleycats-tests/shared/src/test/scala/alleycats/tests/AlleycatsSuite.scala
- build.sbt
- testkit/src/main/scala/cats/tests/CatsSuite.scala
Depends on a new Discipline release with [this change](https://github.com/typelevel/discipline/pull/98) and Machinist but otherwise I think this is ready to go.
> Updates for 2.13.0-RC2

- laws/src/main/scala/cats/laws/discipline/Eq.scala
Since `cats-laws` already breaks bin compat, we no longer need these bin compat and deprecated methods in `laws.discipline.eq` any more. They were causing deprecation warning in the downstream.
> remove deprecated eq instances from scope

- kernel/src/main/scala/cats/kernel/Order.scala
Changed description to better fit their implementation:
* `max` is using `gt` which is: `>` and not `>=`
*  `min` is using `lt` which is: `<` and not `<=`
> Fix Order.max and Oder.min description comments

- core/src/main/scala/cats/data/Kleisli.scala
- tests/src/test/scala/cats/tests/KleisliSuite.scala
Rationale: #2749
also as described in the test, it's more composable
```scala
val program = for {
k1 <- Kleisli((a: A1) => List(1))
k2 <- Kleisli((a: A2) => List("2"))
k3 <- Kleisli((a: A3) => List(true))
} yield (k1, k2, k3)
```
scala can infer type to be `Kleisli[List, A1 with A2 with A3, (Int, String, Boolean)]`
if not using scala subtyping it would looks like
```scala
val program = for {
k1 <- Kleisli((a: A1) => List(1)).local(identity[A1 with A2 with A3])
k2 <- Kleisli((a: A2) => List("2")).local(identity[A1 with A2 with A3])
k3 <- Kleisli((a: A3) => List(true)).local(identity[A1 with A2 with A3])
} yield (k1, k2, k3)
```
> Kleisli contravariant on input type A

- project/plugins.sbt
See #2870 and my comment on #2848:
> I wish this change had been put forward for more public discussion before being merged. I personally didn't hear anything about this before seeing all the tweets about it after it was done.
> I think there are many good reasons to avoid requiring a closed-source sbt plugin to run the Cats build, and that's even if it had been tested thoroughly and we had established that it wasn't likely to cause problems. As it is right now running `sbt prePR` from a clean checkout crashes with [this error](https://github.com/typelevel/cats/issues/2870) on both my Mac laptop and Linux desktop, and it's completely impossible to investigate because sbt-hydra is just a binary from a commercial repo.
> I appreciate Triplequote's generosity, but the Cats build already has …
> Remove sbt-hydra for now

- core/src/main/scala/cats/Apply.scala
- core/src/main/scala/cats/syntax/monadError.scala
- kernel/src/main/scala-2.12-/cats/kernel/compat/WrappedMutableMapBase.scala
- kernel/src/main/scala-2.13+/cats/kernel/compat/WrappedMutableMapBase.scala
- kernel/src/main/scala/cats/kernel/Order.scala
- tests/src/test/scala/cats/tests/MapSuite.scala
- tests/src/test/scala/cats/tests/RegressionSuite.scala
Some of the features in v2.0.0-M1 and v2.0.0-M2 are suitable for backporting:
For v1.6.x:
* #2810
* #2842
* #2784
* #2728
* #2837 (arguably?)
Alternatively or additionally, we could do a 1.7.x, and get several more while we await 2.0.0:
* #2780 
* #2775 
* #2760 
* #2759 
* #2750 
* #2747 
* #2744 
* #2726 
* #2724 
* #2709 
* #2698 
* #2696 
* #2796 
* #2840 
* #2837, if it's not already on a 1.6.1
> Backports for a cats-1.6.x patch

- PROCESS.md
`docs/src/site/index.md` has been subsumed by the readme, so remove it from the post-release instructions.
> Remove index.md from post-release process

- AUTHORS.md
- CHANGES.md
- README.md
The usual. That's a bunch of new contributors.
r? @rossabaker
> Update docs for 2.0.0-M2 and 2.0.0-M3

- core/src/main/scala/cats/MonadError.scala
- core/src/main/scala/cats/syntax/monadError.scala
- tests/src/test/scala/cats/tests/MonadErrorSuite.scala
This allows calling `MonadError`'s `rethrow` directly on an `F[Either[E, A]]`, where `E <: Throwable`. Currently I don't think this is possible: one has to explicitly `leftWiden` to `Throwable`.
> Improve MonadError rethrow syntax to be more flexible

- PROCESS.md
- README.md
- scripts/releaseNotes.scala
- scripts/releaseNotesTestFile
fixes #2879
There are some minor review process clarifications here as well. 
namely from
```
When fixing typos or improving documentation only one sign-off is
required (although for major edits waiting for two may be preferable).
```
to
```
When fixing typos, improving documentation or minor build fix only 
one sign-off is required (although for major edits waiting for two
may be preferable).
```
> improve process document and release notes script

- core/src/main/scala/cats/arrow/FunctionK.scala
- core/src/main/scala/cats/data/NonEmptyChain.scala
- core/src/main/scala/cats/data/NonEmptyMapImpl.scala
- core/src/main/scala/cats/data/NonEmptySet.scala
- core/src/main/scala/cats/syntax/foldable.scala
- tests/src/test/scala/cats/tests/FoldableSuite.scala
- tests/src/test/scala/cats/tests/FunctionKSuite.scala
- tests/src/test/scala/cats/tests/ValidatedSuite.scala
Related to #2893. I thought I'd done this for Cats but it must have been other projects.
> Replace ⇒ with => to avoid Scala 2.13 warnings

- build.sbt
- core/src/main/scala/cats/instances/SymbolInstances.scala
- core/src/main/scala/cats/instances/symbol/package.scala
- laws/src/main/scala/cats/laws/discipline/ExhaustiveCheck.scala
- laws/src/main/scala/cats/laws/discipline/MiniInt.scala
- tests/src/test/scala/cats/tests/BinCodecInvariantMonoidalSuite.scala
- tests/src/test/scala/cats/tests/NonEmptySetSuite.scala
Also added Scala version specific folders for tests
fixed a minor symbol package object file not in the package warning.
> replace `Stream` in ExhaustiveCheck with `List`

- README.md
Since `dsl-domains-cats` is now separated from `Dsl.scala` repository.
> Change link to dsl-domains-cats instead of Dsl.scala

- .scalafmt.conf
- build.sbt
- core/src/main/scala/cats/Eval.scala
- core/src/main/scala/cats/Foldable.scala
- core/src/main/scala/cats/Monad.scala
- core/src/main/scala/cats/Reducible.scala
- core/src/main/scala/cats/data/Chain.scala
- core/src/main/scala/cats/data/EitherT.scala
- core/src/main/scala/cats/data/IndexedStateT.scala
- core/src/main/scala/cats/data/Kleisli.scala
- core/src/main/scala/cats/data/NonEmptyList.scala
- core/src/main/scala/cats/data/NonEmptyVector.scala
- core/src/main/scala/cats/data/OptionT.scala
- core/src/main/scala/cats/data/WriterT.scala
- core/src/main/scala/cats/evidence/As.scala
- core/src/main/scala/cats/instances/function.scala
- core/src/main/scala/cats/instances/list.scala
- core/src/main/scala/cats/syntax/foldable.scala
- free/src/test/scala/cats/free/CofreeSuite.scala
- kernel/src/main/scala/cats/kernel/instances/DoubleInstances.scala
- kernel/src/main/scala/cats/kernel/instances/FloatInstances.scala
- laws/src/main/scala/cats/laws/discipline/Arbitrary.scala
- laws/src/main/scala/cats/laws/discipline/Eq.scala
- project/Boilerplate.scala
- project/KernelBoiler.scala
- project/plugins.sbt
- tests/src/test/scala/cats/tests/AndThenSuite.scala
- tests/src/test/scala/cats/tests/ParallelSuite.scala
I tried keeping the diff small by setting
```
align.openParenCallSite = true
align.openParenDefnSite = true
```
There might be other options to keep it even smaller, but if they exist, they weren't obvious to me. Suggestions welcome!
This should unblock #2900.
> Update sbt-scalafmt to 2.0.1

- docs/src/main/resources/microsite/data/menu.yml
- docs/src/main/tut/typeclasses/comonad.md
Added a document page for Comonads
> Comonad documentation

- scalafix/build.sbt
- scalafix/project/build.properties
- scalafix/project/plugins.sbt
- scalafix/rules/src/main/scala/fix/Cats_v1_0_0.scala
- scalafix/tests/src/test/scala/fix/Cats_Tests.scala
This updates Scalafix to 0.6.0-M9 by applying [this diff](https://github.com/scalacenter/scalafix.g8/blob/c22ae75cabb629aa4a83a95d5fdd8f99691cd92b/scalafix/readme.md). I've checked locally that the Scalafix tests still pass.
My ultimate goal is to update Scalafix to 0.9.x so that this rule (and potential future rules) can be used by Scala Steward (https://github.com/fthomas/scala-steward/pull/611) but it is currently unclear to me if updating to 0.9.x means that this rule needs to rewritten with Scalafix' `v1` API. @olafurpg do `v0` rules also work with 0.9.x?
> Update sbt-scalafix to 0.9.5

- core/src/main/scala/cats/data/package.scala
- tests/src/test/scala/cats/tests/KleisliSuite.scala
https://github.com/typelevel/cats/issues/2304
Same as this PR https://github.com/typelevel/cats/pull/2916, I implemented `local` for `Reader`.
> Implement local for Reader

- core/src/main/scala/cats/data/WriterT.scala
- core/src/main/scala/cats/data/package.scala
- tests/src/test/scala/cats/tests/WriterTSuite.scala
https://github.com/typelevel/cats/issues/2304
I'm sorry if someone is already working on this issue, but since there's no action for a month, I just wrote `listen` for `Writer` and `WriterT`.
> Add listen for Writer and WriterT

- tests/src/test/scala/cats/tests/SortedSetSuite.scala
I found we have PartialOrderTests for SortedSet, but not OrderTests.
> Add OrderTests for SortedSet

- docs/src/main/tut/typeclasses/show.md
Small doc change to add a missing space, which may misleads users into thinking there is a library called kittensa instead of kittens:
From
>Thankfully with the help of a small library called kittensa lot of type class instances including Show can be derived automatically!
To
>Thankfully with the help of a small library called kittens a lot of type class instances including Show can be derived automatically!
> Fix typo in show.md

- core/src/main/scala/cats/data/Kleisli.scala
- core/src/main/scala/cats/data/package.scala
Kleisli is contravariant on A from #2843 , so Reader and ReaderT should also be contravariant in A.
> Reader contravariant on input type A

- kernel/src/main/scala/cats/kernel/Band.scala
- kernel/src/main/scala/cats/kernel/BoundedSemilattice.scala
- kernel/src/main/scala/cats/kernel/CommutativeMonoid.scala
- kernel/src/main/scala/cats/kernel/CommutativeSemigroup.scala
- kernel/src/main/scala/cats/kernel/Monoid.scala
- kernel/src/main/scala/cats/kernel/Semilattice.scala
> Add missing factories similar to existing factories

- README.md
Ebiznext website is prefixed with "www"
> Set the link to the ebiznext sponsor to correctly reference the website

- core/src/main/scala/cats/data/IndexedReaderWriterStateT.scala
- core/src/main/scala/cats/data/IndexedStateT.scala
- tests/src/test/scala/cats/tests/IndexedReaderWriterStateTSuite.scala
- tests/src/test/scala/cats/tests/IndexedStateTSuite.scala
I'm currently adding `Sync` instances for `IndexedReaderWriterStateT` to cats-effect (see https://github.com/typelevel/cats-effect/pull/577). Some of the tests there fail as `IndexedReaderWriterStateT.flatMap` is not stack-safe even when used with a stack-safe monad. 
Based on previous work for `Kleisli` (see #2185), I made `flatMap` and `flatMapF` stack-safe by introducing `IndexedReaderWriterStateT.shift` which implements special behavior if `F[_]`'s `FlatMap` instance is also an `Applicative`. 
Furthermore, I applied the usage of `AndThen` which made `IndexedStateT.flatMap` stack-safe in #2187 to `map` as well, allowing for repeated `map` calls without blowing the stack. The same method unfortunately cannot easily be applied to `IndexedReaderWriterStateT` as we don't have a `Function1` …
> More stack safety for IndexedReaderWriterStateT & IndexedStateT

- core/src/main/scala/cats/data/Chain.scala
- core/src/main/scala/cats/data/NonEmptyChain.scala
- tests/src/test/scala/cats/tests/ChainSuite.scala
- tests/src/test/scala/cats/tests/NonEmptyChainSuite.scala
> Add  method init and last to NonEmptyChain like NonEmptyList.

- core/src/main/scala/cats/data/Chain.scala
- tests/src/test/scala/cats/tests/ChainSuite.scala
> added Chain#takeWhile and Chain#dropWhile

- core/src/main/scala/cats/data/NonEmptyChain.scala
> add back mistakenly removed overrides

- core/src/main/scala/cats/syntax/option.scala
- Add `toRightNel`
- Add `toRightNec`
- Add `toLeftNel`
- Add `toLeftNec`
These are useful when used with `Parallel`.
> Add syntax to option.

- core/src/main/scala/cats/FunctorFilter.scala
> Fix FunctorFilter mapFilter doc example

- core/src/main/scala-2.13+/cats/instances/lazyList.scala
Implements `LazyList`'s `tailRecM` using `Iterator.unfold`.
> Implement LazyList tailRecM using Iterator.unfold

- core/src/main/scala/cats/Parallel.scala
- core/src/main/scala/cats/syntax/all.scala
- core/src/main/scala/cats/syntax/package.scala
- core/src/main/scala/cats/syntax/parallel.scala
- tests/src/test/scala/cats/tests/SyntaxSuite.scala
Hi,
There currently doesn't seem to be a convenient way to traverse a `Set` with `IO`. `traverse` doesn't work because there's no `Traverse` instance for `Set`, and `unorderedTraverse` doesn't work because there is no `CommutativeApplicative` instance for `IO`. So I've added `parUnorderedTraverse` and `parUnorderedSequence` for that purpose.
I also added `parUnorderedFlatTraverse` and `parUnorderedFlatSequence` for symmetry, but given that the non-par versions of these don't exist I'm not really sure we need these.
Another logical set of operations would be `parUnorderedTraverse_`  and `parUnorderedSequence_`. But again, there is no `unorderedTraverse_` or `unorderedSequence_` in `UnorderedFoldable`, so it's not going to be any more efficient than the non-_ variants, and given that it's …
> add unordered parallel variants of (flat)traverse and (flat)sequence

- build.sbt
- core/src/main/scala/cats/data/OptionT.scala
stumbled across this minor typo when I was looking for specific `traverseFilter` instance for `OptionT`
> fix typo for `Data` in traverseFilter for OptionT

- core/src/main/scala/cats/data/NonEmptyList.scala
- core/src/main/scala/cats/data/NonEmptyVector.scala
NonEmptyTraverse already inherits Reduceable.
> Remove redundant type annotation.

- docs/src/main/tut/typeclasses/comonad.md
> fix a typo in `comonad.md`

- core/src/main/scala/cats/data/Chain.scala
- tests/src/test/scala/cats/tests/ChainSuite.scala
Added unapplySeq to Chain and ==: object to allow pattern match Chain in list like manner:
```scala
Chain(1, 2, 3) match {
case Chain(a, b, c) => 
}
Chain(1, 2, 3) match {
case h ==: t => 
}
```
> unapplySeq in Chain (issue #2960)

- core/src/main/scala/cats/data/EitherT.scala
- core/src/main/scala/cats/syntax/either.scala
- core/src/main/scala/cats/syntax/validated.scala
- tests/src/test/scala/cats/tests/EitherTSuite.scala
- tests/src/test/scala/cats/tests/ValidatedSuite.scala
This takes the changes in #2880 and extends them to a few more methods with similar usage.
> improve liftTo/rethrowT/raiseOrPure syntax to be more flexible

- core/src/main/scala/cats/data/Chain.scala
> Chain optimize map method

- core/src/main/scala-2.13+/cats/data/OneAndLowPriority4.scala
- core/src/main/scala-2.13+/cats/data/ScalaVersionSpecificPackage.scala
- core/src/main/scala-2.13+/cats/data/ZipStream.scala
- core/src/main/scala-2.13+/cats/instances/ScalaVersionSpecificParallelInstances.scala
- core/src/main/scala-2.13+/cats/instances/package.scala
- core/src/main/scala-2.13+/cats/instances/stream.scala
- kernel/src/main/scala-2.13+/cats/kernel/instances/StreamInstances.scala
- laws/src/main/scala-2.13+/cats/laws/discipline/ScalaVersionSpecific.scala
I messed this one up, hurray for stringly typed arguments! This PR does nothing but switch the `since` version and message.
> Fix argument order in deprecations

- core/src/main/scala-2.12-/cats/instances/all.scala
- core/src/main/scala-2.12-/cats/instances/package.scala
- core/src/main/scala-2.13+/cats/instances/all.scala
- core/src/main/scala-2.13+/cats/instances/package.scala
- core/src/main/scala/cats/instances/sortedMap.scala
- core/src/main/scala/cats/instances/sortedSet.scala
- kernel-laws/shared/src/test/scala/cats/kernel/laws/LawTests.scala
- kernel/src/main/scala-2.12-/cats/kernel/instances/AllInstances.scala
- kernel/src/main/scala-2.13+/cats/kernel/instances/AllInstances.scala
- kernel/src/main/scala/cats/kernel/instances/SortedMapInstances.scala
- kernel/src/main/scala/cats/kernel/instances/SortedSetInstances.scala
- kernel/src/main/scala/cats/kernel/instances/all/package.scala
- kernel/src/main/scala/cats/kernel/instances/sortedMap/package.scala
- kernel/src/main/scala/cats/kernel/instances/sortedSet/package.scala
- tests/src/test/scala/cats/tests/CatsSuite.scala
I'm splitting out some of the less controversial parts of #3000 so they're not blocked by the name fixes (which I still think should happen before 3.0, even if not in 2.0).
These instances for `SortedMap` and `SortedSet` clearly belong in cats-kernel, and while there's some overhead involved in moving them and maintaining bincompat, in this case I think it's hard to argue that it's not worth it—this isn't fixing typos, it's making `import cats.kernel.instances.all._` do the obviously correct thing.
> Move appropriate SortedSet and SortedMap instances to kernel

- core/src/main/scala/cats/Parallel.scala
- tests/src/test/scala/cats/tests/ParallelSuite.scala
I left this out of #3012 intentionally, since I generally avoid overloading and hate the `scala.DummyImplicit` hack, which is necessary here, and since I didn't think the need for it would come up that often.
As I've been working more with 2.0.0-RC2 this week, though, I've decided that we really do want this `Parallel.apply` in 2.0, for a few reasons:
1. The two-type-parameter `apply` is pretty useless.
2. The thing people do when a type class doesn't have a useful `apply` is go to `implicitly`, which in this case is pretty unhelpful for something like `Parallel[Stream]`, since its static return type is unrefined. To get a usefully typed instance, you have to go to something like Shapeless's `the` or define your own version of `Parallel.apply` with a single parameter.
3. In practice using …
> Add Parallel.apply overload with one type parameter

- core/src/main/scala-2.12-/cats/instances/ScalaVersionSpecificParallelInstances.scala
- core/src/main/scala-2.13+/cats/instances/ScalaVersionSpecificParallelInstances.scala
- core/src/main/scala/cats/data/EitherT.scala
- core/src/main/scala/cats/data/OptionT.scala
- core/src/main/scala/cats/instances/parallel.scala
Fixes #3032. Now the following works:
```scala
scala> import cats.{Id, Parallel}, cats.instances.list._, cats.instances.string._
import cats.{Id, Parallel}
import cats.instances.list._
import cats.instances.string._
scala> type EI[A] = cats.data.EitherT[Id, String, A]
defined type alias EI
scala> implicitly[Parallel[EI]]
res0: cats.Parallel[EI] = cats.data.EitherTInstances$$anon$7@3f7c7017
scala> type EL[A] = cats.data.EitherT[List, String, A]
defined type alias EL
scala> implicitly[Parallel[EL]]
res1: cats.Parallel[EL] = cats.data.EitherTInstances1$$anon$15@1124d0e8
scala> type OI[A] = cats.data.OptionT[Id, A]
defined type alias OI
scala> implicitly[Parallel[OI]]
res2: cats.Parallel[OI] = cats.data.OptionTInstances$$anon$8@3e5db9dc
```
This should have no changes for existing code that …
> Move Parallel instances for EitherT and OptionT into implicit scope

- AUTHORS.md
- CHANGES.md
- README.md
Release notes are [already up](https://github.com/typelevel/cats/releases/tag/v2.0.0-RC3).
This time I'll actually remember to open a PR merging back into master after this is merged into `2.0.x`.
> Update documentation and attribution for 2.0.0-RC3

- kernel/src/main/scala/cats/kernel/instances/finiteDuration/package.scala
I know #3036 isn't a high priority but this is a trivial fix, and I'd personally like to see it in 2.0.0. The name matches `cats.instances.finiteDuration`.
No tests, but there are no tests for the `duration` version, either. I confirmed that the following works:
```scala
scala> import cats.kernel.instances.finiteDuration._
import cats.kernel.instances.finiteDuration._
scala> import scala.concurrent.duration.FiniteDuration
import scala.concurrent.duration.FiniteDuration
scala> cats.kernel.LowerBounded[FiniteDuration]
res0: cats.kernel.LowerBounded[scala.concurrent.duration.FiniteDuration] = cats.kernel.instances.FiniteDurationOrder@5ac7386c
scala> cats.kernel.Hash[FiniteDuration]
res1: cats.kernel.Hash[scala.concurrent.duration.FiniteDuration] = …
```
> Add cats.kernel.instances.finiteDuration package

- core/src/main/scala-2.12-/cats/instances/ScalaVersionSpecificParallelInstances.scala
- core/src/main/scala-2.13+/cats/instances/ScalaVersionSpecificParallelInstances.scala
This PR includes @Billzabob's commit from #2789 but rebased against current master, where the change has to happen in two places, and slightly adjusted to avoid breaking binary compatibility.
I missed @Billzabob's PR the first time around but should have caught this in #3012.
The change does technically break source compatibility, but (while it fixes a real problem) it's also pretty minor, so I'm not worried about it causing anyone problems. I personally think we can / should try to get it into 2.0.0 today.
> Remove unused type parameter for Parallel instances

- laws/src/main/scala/cats/laws/NonEmptyParallelLaws.scala
- laws/src/main/scala/cats/laws/ParallelLaws.scala
- laws/src/main/scala/cats/laws/discipline/NonEmptyParallelTests.scala
- laws/src/main/scala/cats/laws/discipline/ParallelTests.scala
- tests/src/test/scala-2.13+/cats/tests/ScalaVersionSpecific.scala
- tests/src/test/scala/cats/tests/ParallelSuite.scala
It's a little wonky. Also I left one `.Aux` usage in the tests which came from the fact that the compiler just wasn't able to infer the dependent version. I didn't look into why, but I suspect it's wonkiness with `OneAnd` and a scalac bug. Putting up the @milessabin signal!
Also this introduces an interesting pattern, which is adding `def Aux` alongside `type Aux` when you have `def apply`. I would propose we should do this for `Parallel` itself as well, but I didn't make that change. I think this is better than the current `DummyImplicit` approach, but I'm okay with going with `DummyImplicit` instead.
> Infer dependent parameter in NonEmpty/ParallelTests/Laws

- docs/src/main/tut/typeclasses/lawtesting.md
This PR mentions `discipline-scalatest` and `discipline-specs2` in the law testing documentation.
see #3068
> Mention additional dependencies in lawtesting docs

- docs/src/main/tut/typeclasses/semigroup.md
I didn't understand that the values in Maps were also combined when two maps are combined - I thought the `"hello" -> 2` entry was simply _replacing_ the `"hello" -> 0` entry in the first map. Giving the first map's `"hello"` a value of `1` results in the combined map having a `"hello" -> 3` entry, showing that the values were combined.
After understanding that, I realized why my code couldn't find an implicit `Semigroup` for my Map - I didn't have an implicit `Semigroup` for my map's values.
> Update Semigroup docs for Map

- build.sbt
- core/src/main/scala-2.12/cats/instances/ScalaVersionSpecificParallelInstances.scala
- core/src/main/scala-2.13+/cats/instances/ScalaVersionSpecificParallelInstances.scala
- core/src/main/scala/cats/data/Op.scala
- core/src/main/scala/cats/instances/parallel.scala
- core/src/main/scala/cats/instances/sortedMap.scala
- core/src/main/scala/cats/instances/sortedSet.scala
- project/build.properties
- project/plugins.sbt
- project/project/plugins.sbt
- scalafix/project/build.properties
- scalafix/project/plugins.sbt
Includes & supersedes #2954, #3075, #3077.
Open problems:
```
[error]  * static method catsParallelForEitherTNestedValidated(cats.Monad,cats.kernel.Semigroup)cats.Parallel in class cats.implicits does not have a correspondent in current version
[error]    filter with: ProblemFilters.exclude[DirectMissingMethodProblem]("cats.implicits.catsParallelForEitherTNestedValidated")
[error]  * static method catsParallelForEitherTNestedParallelValidated(cats.kernel.Semigroup,cats.Parallel)cats.Parallel in class cats.implicits does not have a correspondent in current version
[error]    filter with: ProblemFilters.exclude[DirectMissingMethodProblem]("cats.implicits.catsParallelForEitherTNestedParallelValidated")
[error]  * static method catsParallelForOptionTNestedOption(cats.Parallel)cats.Parallel in …
```
> update to sbt 1.3.x, uses coursier by default

- core/src/main/scala/cats/data/Validated.scala
Re: Issue #2479
Add more doctest to Validated methods:
- fold
- isValid
- isInvalid
- forearch
- getOrElse
- valueOr
- exists
- forall
- orElse
- findValid
- toEither
- toOption
- toIor
- toList
- toValidatedNel
- toValidatedNec
- withEither
- bimap
- compare
- ===
- ap
- product
- map
- leftMap
- traverse
- foldLeft
- foldRight
- andThen
- combine
- swap
- merge
> Validated doctest

- core/src/main/scala/cats/data/EitherT.scala
Re: Issue #2479
Add more doctest to EitherT methods:
fold
foldF
isLeft
isRight
swap
getOrElse
getOrElseF
orElse
recover
recoverWith
rethrowT
valueOr
valueOrF
forall
exists
ensure
ensureOr
toOption
to
collectRight
bimap
> add more doctest to EitherT

- core/src/main/scala/cats/Foldable.scala
- core/src/main/scala/cats/Reducible.scala
- tests/src/test/scala/cats/tests/FoldableSuite.scala
* `mimimumByOption` / `maximumByOption` on `Foldable`
* `minumumBy` / `maximumBy` on `Reducible`
Fixes #2385
> Add minimumBy/maximumBy/Option to Foldable

- core/src/main/scala/cats/data/Ior.scala
Re: Issue #2479
Add more doctest to Ior methods:
- fold
- putLeft
- putRight
- isLeft
- isRight
- isBoth
- left
- right
- onlyLeft
- onlyRight
- onlyRightOrLeft
- onlyBoth
- pad
- unwrap
- toIorNes
- toIorNel
- toEither
- toValidated
- toOption
- toList
- to
- swap
- exists
- forall
- getOrElse
- valueOr
- bimap
- leftMap
- map
- flatMap
- foldLeft
- combine
> add more doctest to Ior

- core/src/main/scala/cats/data/WriterT.scala
Re: Issue #2479
Add more doctest to WriterT methods:
- tell
- written
- value
- listen
- ap
- map
- imap
- mapK
- flatMap
- mapBoth
- bimap
- mapWritten
- swap
- reset
- show
- foldLeft
- foldRight
- traverse
> add more doctest to WriterT

- .travis.yml
- core/src/main/scala-2.12/cats/instances/ScalaVersionSpecificParallelInstances.scala
- core/src/main/scala-2.12/cats/instances/stream.scala
- core/src/main/scala-2.13+/cats/instances/ScalaVersionSpecificParallelInstances.scala
- core/src/main/scala-2.13+/cats/instances/lazyList.scala
- core/src/main/scala-2.13+/cats/instances/stream.scala
- core/src/main/scala/cats/instances/either.scala
- core/src/main/scala/cats/instances/list.scala
- core/src/main/scala/cats/instances/vector.scala
- tests/src/test/scala-2.13+/cats/tests/LazyListSuite.scala
- tests/src/test/scala-2.13+/cats/tests/ScalaVersionSpecific.scala
- tests/src/test/scala/cats/tests/EitherSuite.scala
- tests/src/test/scala/cats/tests/ListSuite.scala
- tests/src/test/scala/cats/tests/ParallelSuite.scala
- tests/src/test/scala/cats/tests/StreamSuite.scala
- tests/src/test/scala/cats/tests/VectorSuite.scala
Addresses https://github.com/typelevel/cats/issues/3059 .
> Issue 3059: Move Parallel instances into instance packages for the type constructors they characterize

- build.sbt
The `provided` Simulacrum dependency slipped back into our poms when the group ID changed. This fixes the issue.
> Use new group ID for simulacrum

- .travis.yml
- core/src/main/scala-2.13+/cats/instances/lazyList.scala
- core/src/main/scala-2.13+/cats/instances/stream.scala
- tests/src/test/scala-2.13+/cats/tests/LazyListSuite.scala
To improve the quality of Cats, enable more Scala 2.13 builds in CI for each PR. 
- Enable scalaJS build for 2.13. 
- Enable linting for 2.13 specific sources. Because of this new check, also needed to format 2.13 sources :)
> ci: Enable 2.13 build for scalajs and linting in travis

- PULL_REQUEST_TEMPLATE.md
- core/src/main/scala-2.13+/cats/instances/lazyList.scala
- core/src/main/scala-2.13+/cats/instances/stream.scala
- project/KernelBoiler.scala
- tests/src/test/scala-2.13+/cats/tests/LazyListSuite.scala
- tests/src/test/scala/cats/tests/EqSuite.scala
resolves https://github.com/typelevel/cats/issues/2701
> Issue 2701 - Ambiguous Eq instances for tuples

- kernel/src/main/scala/cats/kernel/instances/ListInstances.scala
- kernel/src/main/scala/cats/kernel/instances/QueueInstances.scala
- kernel/src/main/scala/cats/kernel/instances/VectorInstances.scala
- tests/src/test/scala-2.13+/cats/tests/ScalaVersionSpecific.scala
- tests/src/test/scala/cats/tests/ListSuite.scala
- tests/src/test/scala/cats/tests/QueueSuite.scala
- tests/src/test/scala/cats/tests/VectorSuite.scala
Fixes https://github.com/typelevel/cats/issues/2891
> Issue 2891 - Ambiguous Vector instances

- core/src/main/scala/cats/Functor.scala
- tests/src/test/scala/cats/tests/FunctorSuite.scala
Added `ifF` function to Functor:
```scala
def ifF[A](fb: F[Boolean])(ifTrue: A, ifFalse: A): F[A] = map(fb)(x => if (x) ifTrue else ifFalse)
```
> Add `ifF` on Functor #3040

- core/src/main/scala/cats/ApplicativeError.scala
- core/src/main/scala/cats/syntax/applicativeError.scala
- tests/src/test/scala/cats/tests/ApplicativeErrorSuite.scala
Hello, I already copy-pasted this function in a few places in my codebases, so I thought it could be useful to have it in cats.
Example use case (assuming `F : ApplicativeError[F, Throwable]`):
```scala
def authenticate(r: Request[F]): F[Unit] = ???
val authentication: Kleisli[F, Request[F], Either[AuthenticationException, Unit]] =
Kleisli { request => authenticate(request).attemptCase[AuthenticationException] }
```
> add attemptNarrow to ApplicativeErrorOps

- core/src/main/scala/cats/Foldable.scala
- core/src/main/scala/cats/Reducible.scala
- tests/src/test/scala/cats/tests/FoldableSuite.scala
This is a follow-up for #3084, with three changes, two of which should be uncontroversial:
* These are methods on the `Foldable` and `Reducible` type classes, and shouldn't have `Foldable` or `Reducible` constraints, so I've removed them.
* I fixed the references in the first `@see` clauses in the API docs for the `Foldable` methods (they should point to the `*By` methods on `Reducible`).
I've also changed the method names from `minimumOptionBy` and `maximumOptionBy` to `minimumByOption` and `maximumByOption`. This is consistent with the standard library's `maxByOption`, and also with e.g. `reduceRightOption` (from both the standard library and Cats). 
Following the standard library here seems like the right thing to do, and these new methods haven't been in a release yet, so we don't …
> Follow-up #3084

- core/src/main/scala/cats/instances/sortedMap.scala
- core/src/main/scala/cats/instances/sortedSet.scala
Cleaning up a mistake I made. :smile:
I've confirmed that this change fixes this particular problem everywhere.
> Fix order of @deprecated arguments

- AUTHORS.md
- core/src/main/scala/cats/SemigroupK.scala
> SemigroupK sum: F[A], F[B] => F[A Either B]

- core/src/main/scala/cats/Bifoldable.scala
- tests/src/test/scala/cats/tests/BifoldableSuite.scala
> #2947 Added bifold to Bifoldable typeclass

- core/src/main/scala/cats/instances/queue.scala
- tests/src/test/scala/cats/tests/QueueSuite.scala
> Add TraverseFilter instance for Queue.

- core/src/main/scala/cats/data/Chain.scala
- core/src/main/scala/cats/instances/list.scala
Now
```scala
scala> Chain(1, 2, 3, 4, 5, 6).traverse { x => println(x); if(x > 2) Left("err") else Right(x)  }
6
5
4
3
2
1
res: scala.util.Either[String,cats.data.Chain[Int]] = Left(err)
scala> List(1, 2, 3, 4, 5, 6).traverseFilter { x => println(x); if(x > 2) Left("err") else Right(Option(x))  }
6
5
4
3
2
1
res: scala.util.Either[String,List[Int]] = Left(err)
```
After
```scala
scala> Chain(1, 2, 3, 4, 5, 6).traverse { x => println(x); if(x > 2) Left("err") else Right(x)  }
1
2
3
res: scala.util.Either[String,cats.data.Chain[Int]] = Left(err)
scala> List(1, 2, 3, 4, 5, 6).traverseFilter { x => println(x); if(x > 2) Left("err") else Right(Option(x))  }
1
2
3
res: scala.util.Either[String,List[Int]] = Left(err)
```
> Use Foldable foldRight for Traverse and TraverseFilter.

- .travis.yml
- build.sbt
- core/src/main/scala-2.13+/cats/instances/stream.scala
Fixes #3109. I've also added bincompat checking (currently against 2.0.0 only) for cats-laws, cats-kernel-laws, cats-testkit, alleycats-core, and alleycats-laws.
One piece of breakage slipped into the 2.13 build in #3099. I've verified that Travis CI fails with just the first two commits.
> Check bincompat on stuff we should be checking bincompat for

- core/src/main/scala/cats/Foldable.scala
- tests/src/test/scala/cats/tests/FoldableSuite.scala
Applicative is enough for this method, so it shouldn't require Monad.
> change constraint for foldMapM from Monad to Applicative

- bench/src/main/scala-2.12/cats/bench/ChainBench.scala
- bench/src/main/scala-2.12/cats/bench/MapMonoidBench.scala
- bench/src/main/scala/cats/bench/FoldMapABench.scala
- bench/src/main/scala/cats/bench/StateTBench.scala
- bench/src/main/scala/cats/bench/TrampolineBench.scala
This is a follow-up to #3130. We're making claims about performance in the API docs there, so I figured we should have a micro-benchmark to back them up.
I also ran Scalafmt on the `bench` project in a separate commit, since it doesn't look like it's been formatted in a while.
> Add benchmark for foldMapA

- core/src/main/scala-2.12/cats/instances/stream.scala
- core/src/main/scala-2.13+/cats/instances/lazyList.scala
- core/src/main/scala-2.13+/cats/instances/stream.scala
- core/src/main/scala/cats/Align.scala
- tests/src/test/scala/cats/tests/StreamSuite.scala
Follow-up to #3076 adding `Align[Stream]` with the same implementation as `Align[LazyList]`. I don't think there's any reason not to include these, @LukaJCB?
I've also added a package-private `Align.alignWithIterator` helper method to clean up some repetition in `Align` definitions.
> Add Align for Stream

- core/src/main/scala/cats/syntax/either.scala
All of these methods are available directly on `Either` now that we've dropped 2.11. We could probably just deprecate them to discourage explicit usage but I package-privated them as well since it might have some tiny effect on compile times.
> Deprecate and make private syntax methods that are now on Either

- core/src/main/scala/cats/ApplicativeError.scala
- core/src/main/scala/cats/MonadError.scala
- core/src/main/scala/cats/syntax/applicativeError.scala
- laws/src/main/scala/cats/laws/ApplicativeErrorLaws.scala
- laws/src/main/scala/cats/laws/MonadErrorLaws.scala
- laws/src/main/scala/cats/laws/discipline/ApplicativeErrorTests.scala
- laws/src/main/scala/cats/laws/discipline/MonadErrorTests.scala
- tests/src/test/scala/cats/tests/SyntaxSuite.scala
Fixes #2685.
Unfortunately I don't think we can fix the syntax without breaking bincompat due to a compiler bug: https://github.com/typelevel/cats/issues/2685#issuecomment-547862937
> Move adaptError

- core/src/main/scala/cats/Apply.scala
- core/src/main/scala/cats/FlatMap.scala
- core/src/main/scala/cats/Parallel.scala
- core/src/main/scala/cats/data/Kleisli.scala
- core/src/main/scala/cats/data/NonEmptyList.scala
- core/src/main/scala/cats/instances/duration.scala
- core/src/main/scala/cats/instances/finiteDuration.scala
- core/src/main/scala/cats/package.scala
- core/src/main/scala/cats/syntax/apply.scala
- core/src/main/scala/cats/syntax/flatMap.scala
- core/src/main/scala/cats/syntax/package.scala
- core/src/main/scala/cats/syntax/semigroupal.scala
- free/src/main/scala/cats/free/Coyoneda.scala
- free/src/main/scala/cats/free/FreeT.scala
- free/src/main/scala/cats/free/Trampoline.scala
- tests/src/test/scala/cats/tests/NonEmptyListSuite.scala
This PR makes everything that was deprecated in 1.x package-private (in the cases where that's possible without breaking bincompat).
This means less noise in the API docs, and that users will be in a better position to be ready once we can finally clean this stuff up for real.
I don't feel terribly strongly about getting this into 2.1.0, but I think it'd be nice to have.
> Make 1.x deprecation targets package-private

- core/src/main/scala/cats/ApplicativeError.scala
- core/src/main/scala/cats/Apply.scala
- core/src/main/scala/cats/Bitraverse.scala
- core/src/main/scala/cats/FlatMap.scala
- core/src/main/scala/cats/Foldable.scala
- core/src/main/scala/cats/Reducible.scala
- core/src/main/scala/cats/TraverseFilter.scala
- core/src/main/scala/cats/UnorderedFoldable.scala
- core/src/main/scala/cats/syntax/applicativeError.scala
- core/src/main/scala/cats/syntax/apply.scala
- core/src/main/scala/cats/syntax/bitraverse.scala
- core/src/main/scala/cats/syntax/flatMap.scala
- core/src/main/scala/cats/syntax/foldable.scala
- core/src/main/scala/cats/syntax/reducible.scala
- core/src/main/scala/cats/syntax/traverseFilter.scala
- core/src/main/scala/cats/syntax/unorderedFoldable.scala
- core/src/main/scala/cats/syntax/validated.scala
Between 1.0.0 and 2.0.0 we added a lot of new type class operations as syntax methods in order to avoid breaking binary compatibility on 2.11. We don't have to worry about that any more, which means these methods can go on the type classes where they belong.
There are two categories of syntax methods that can be moved. The first is something like `findM` for `Foldable`, which should live next to `find` on the type class itself, but right now only exists as syntax for `F[A]` values:
```scala
final class FoldableOps[F[_], A](private val fa: F[A]) extends AnyVal {
def findM[G[_]](p: A => G[Boolean])(implicit F: Foldable[F], G: Monad[G]): G[Option[A]] = ???
}
```
For methods like this I've added an implementation in the type class (`trait Foldable` in this case):
```scala
@noop
def …
```
> "Move" type class syntax methods onto type classes

- core/src/main/scala/cats/MonadError.scala
We have a pretty bad binary compatibility breakage in 2.1.0-RC1: if you have cats-effect 2.0.0 and cats-core 2.1.0-RC1, you get the following (on both 2.12 and 2.13):
```scala
scala> import cats.syntax.monadError._
import cats.syntax.monadError._
scala> cats.effect.IO(1).adaptError { case e => e }
java.lang.NoSuchMethodError: cats.MonadError.adaptError$(Lcats/MonadError;Ljava/lang/Object;Lscala/PartialFunction;)Ljava/lang/Object;
at cats.effect.IOLowPriorityInstances$IOEffect.adaptError(IO.scala:767)
at cats.syntax.MonadErrorOps$.adaptError$extension(monadError.scala:31)
... 36 elided
```
Or:
```scala
scala> cats.MonadError[cats.effect.IO, Throwable].adaptError(cats.effect.IO(1)) { case e => e }
java.lang.NoSuchMethodError: cats.MonadError.adaptError$(Lcats/MonadError;Ljava/lang/Object;Lsc …
```
> Add adaptError override to MonadError

- PULL_REQUEST_TEMPLATE.md
- kernel/src/main/scala/cats/kernel/instances/ListInstances.scala
- kernel/src/main/scala/cats/kernel/instances/OptionInstances.scala
- kernel/src/main/scala/cats/kernel/instances/QueueInstances.scala
- kernel/src/main/scala/cats/kernel/instances/VectorInstances.scala
- project/KernelBoiler.scala
- tests/src/test/scala/cats/tests/EqSuite.scala
- tests/src/test/scala/cats/tests/ListSuite.scala
- tests/src/test/scala/cats/tests/QueueSuite.scala
- tests/src/test/scala/cats/tests/VectorSuite.scala
Reverts #3100, #3105, and undoes part of #2834. This unfixes #2891 and #2701, which I think will have to wait for 3.0.
In the case of #2834 I don't think the move was necessary, since the `CommutativeMonoid` one is more specific. In any case moving the other back doesn't break any tests and seems fine:
```scala
scala> import cats.kernel.instances.all._
import cats.kernel.instances.all._
scala> cats.kernel.CommutativeMonoid[Int]
res0: cats.kernel.CommutativeMonoid[Int] = cats.kernel.instances.IntGroup@5c7654d1
scala> cats.kernel.Monoid[Int]
res1: cats.kernel.Monoid[Int] = cats.kernel.instances.IntGroup@5c7654d1
scala> cats.kernel.Monoid[String]
res2: cats.kernel.Monoid[String] = cats.kernel.instances.StringMonoid@77c600b4
```
I've confirmed that my quick-fix MiMa branch …
> Fix broken binary compatibility

- core/src/main/scala/cats/Reducible.scala
- tests/src/test/scala/cats/tests/ReducibleSuite.scala
Currently `foldMapM` and `foldMapA` will be lazy if the operations they're built on are sufficiently lazy, but `reduceMapM` isn't.
Take the following stand-alone non-empty stream implementation (I'm not using `NonEmptyStream` because `Stream`'s `reduceRightToOption` isn't lazy enough, which should probably be a separate issue):
```scala
import cats.{Eval, Reducible}
case class NES[A](h: A, t: Stream[A]) { def toStream: Stream[A] = h #:: t }
object NES {
implicit val nesReducible: Reducible[NES] = new Reducible[NES] {
def foldLeft[A, B](fa: NES[A], b: B)(f: (B, A) => B): B = fa.toStream.foldLeft(b)(f)
def foldRight[A, B](fa: NES[A], lb: Eval[B])(f: (A, Eval[B]) => Eval[B]): Eval[B] =
fa match {
case NES(h, Stream()) => f(h, lb)
case NES(h, th #:: tt) => f(h, Eval.defer(foldRight(NES(th, …
```
> Make default reduceMapM lazy if reduceRightTo is lazy

- bench/src/main/scala/cats/bench/ParTraverseBench.scala
- bench/src/main/scala/cats/bench/ValidatedBench.scala
- core/src/main/scala/cats/Parallel.scala
- core/src/main/scala/cats/data/Cokleisli.scala
- core/src/main/scala/cats/data/EitherT.scala
- core/src/main/scala/cats/data/Func.scala
- core/src/main/scala/cats/data/IdT.scala
- core/src/main/scala/cats/data/IorT.scala
- core/src/main/scala/cats/data/Kleisli.scala
- core/src/main/scala/cats/data/Nested.scala
- core/src/main/scala/cats/data/NonEmptyChain.scala
- core/src/main/scala/cats/data/NonEmptyList.scala
- core/src/main/scala/cats/data/NonEmptySet.scala
- core/src/main/scala/cats/data/Validated.scala
This PR replaces some instances of `andThen`, `compose`, etc. with function literals. In all of these cases I think the change improves readability—for example this:
```scala
def curry[X, Y, Z](f: (X, Y) => Z): X => Y => Z = x => y => f(x, y)
Kleisli[M, E, A](curry(Function.untupled(f)).andThen(R.tabulate))
```
Is now this:
```scala
Kleisli[M, E, A](e => R.tabulate(r => f((e, r))))
````
It also improves performance, especially in cases like `parBitraverse` where just rewriting:
```
f.andThen(P.parallel.apply(_)), g.andThen(P.parallel.apply(_))
```
To:
```
a => P.parallel.apply(f(a)), b => P.parallel.apply(g(b))
```
…avoids multiple allocations and some indirection.
I've included a couple of new benchmarks, and some example results for Scala 2.12 and JVM 8 on my desktop machine:
``` …
```
> Some minor optimizations

- core/src/main/scala/cats/data/Chain.scala
- docs/src/main/tut/datatypes/chain.md
- docs/src/main/tut/datatypes/either.md
- kernel/src/main/scala/cats/kernel/Comparison.scala
Similar to #3182. Dotty is complaining about these `final`s on objects and they're unnecessary on Scala 2.
> Remove redundant final modifiers on objects

- core/src/main/scala/cats/Eval.scala
Another Dotty-friendliness change. To be honest I don't think I even realized that eta-expansion syntax could be used for `Function0` in Scala 2. It doesn't work on Dotty:
```scala
4 |  def mk1(x: => String): Thunk = new Thunk(x _)
|                                           ^^^
|Only function types can be followed by _ but the current expression has type String
```
I think it makes sense to change these now. For me at least the `() => x` syntax is less bizarre and surprising anyway.
I double-checked that they compile to the same thing.
```scala
class Thunk(val value: () => String)
object Thunk {
def mk1(x: => String): Thunk = new Thunk(x _)
def mk2(x: => String): Thunk = new Thunk(() => x)
}
```
Becomes:
```
public static Thunk mk2(scala.Function0<java.lang.String>);
descriptor: …
```
> Update Function0 syntax

- free/src/main/scala/cats/free/FreeApplicative.scala
In Dotty `do` has a [new meaning](https://dotty.epfl.ch/docs/reference/dropped-features/do-while.html), and it doesn't really save much here. (This is the only instance in Cats.)
> Replace do-while

- core/src/main/scala-2.13+/cats/data/NonEmptyLazyList.scala
- core/src/main/scala/cats/data/Chain.scala
- core/src/main/scala/cats/data/NonEmptyList.scala
- core/src/main/scala/cats/data/NonEmptySet.scala
- core/src/main/scala/cats/data/NonEmptyVector.scala
- core/src/main/scala/cats/instances/sortedSet.scala
- core/src/main/scala/cats/syntax/list.scala
- core/src/main/scala/cats/syntax/set.scala
- kernel-laws/shared/src/test/scala/cats/kernel/laws/LawTests.scala
- laws/src/main/scala/cats/laws/discipline/arbitrary.scala
- tests/src/test/scala/cats/tests/SortedSetSuite.scala
Dotty was complaining about some of these, so I went ahead and took care of all the `Ordering` ones.
Now the only implicit vals in core without type annotations are things like `new OptionTMonad[F] { implicit val F = F0 }`, which Dotty is fine with. There are still a lot of others in cats-tests, which I'm not able to compile on Dotty yet because I don't have the laws modules working.
The cases in this PR are all local definitions and they're a little more verbose, but personally seeing `implicit val whatever =` makes me anxious even in this context, and I think it's worth making this change even apart from the Dotty considerations.
> Add explicit type annotations for implicit Ordering vals

- docs/src/main/tut/typeclasses/alternative.md
Fixing a small typo in Alternative docs.
> Fix typo in Alternative docs

- core/src/main/scala-2.12/cats/instances/stream.scala
- core/src/main/scala-2.13+/cats/instances/lazyList.scala
- core/src/main/scala/cats/FunctorFilter.scala
- core/src/main/scala/cats/data/Chain.scala
- core/src/main/scala/cats/data/Const.scala
- core/src/main/scala/cats/data/Nested.scala
- core/src/main/scala/cats/data/OptionT.scala
- core/src/main/scala/cats/instances/list.scala
- core/src/main/scala/cats/instances/map.scala
- core/src/main/scala/cats/instances/option.scala
- core/src/main/scala/cats/instances/queue.scala
- core/src/main/scala/cats/instances/sortedMap.scala
- core/src/main/scala/cats/instances/vector.scala
- laws/src/main/scala/cats/laws/FunctorFilterLaws.scala
- laws/src/main/scala/cats/laws/discipline/FunctorFilterTests.scala
> add `filterNot` to FunctorFilter

- kernel/src/main/scala/cats/kernel/instances/CharInstances.scala
Meant to do this in #3188 but missed it.
> Add type for implicit val

- core/src/main/scala/cats/data/Chain.scala
The Dotty exhaustivity checker is both smarter and more demanding than Scala 2's, and this is a case where it warns while Scala 2 just silently ignores the fact that it can't prove exhaustivity (it's the only case like this in cats-core).
It would be possible to make the match exhaustive in a way that both compilers would accept by writing something like this:
```scala
as match {
case h ==: t   => f(h, Eval.defer(loop(t)))
case _ => lb
}
```
…but that results in an extra `ArrayBuffer` instantiation in the empty case. Adding `@unchecked` seems to me like a reasonable fix, since it just flags what the Scala 2 compiler is already doing.
> Mark match that is unchecked by Scala 2 as unchecked

- core/src/main/scala/cats/ApplicativeError.scala
- core/src/main/scala/cats/Composed.scala
- core/src/main/scala/cats/data/IorT.scala
- core/src/main/scala/cats/data/Nested.scala
- core/src/main/scala/cats/instances/map.scala
- core/src/main/scala/cats/instances/sortedMap.scala
These are a few fixes for places where Dotty isn't able to get the type inference right and where I think providing the types doesn't make the code unreasonably verbose (in most of these cases I think it's a readability improvement if anything).
> Helping out Dotty's type inference

- core/src/main/scala/cats/data/Nested.scala
- tests/src/test/scala/cats/tests/OptionTSuite.scala
Another Dotty-motivated change. These are the only two places we use kind-projector's `*[_]` syntax, which I personally find pretty unreadable, and I think in both cases writing out the context bounds is a big improvement.
> Avoid unusual kind-projector syntax

- build.sbt
- core/src/main/scala/cats/NonEmptyTraverse.scala
- core/src/main/scala/cats/arrow/Choice.scala
- core/src/main/scala/cats/data/NonEmptyChain.scala
- core/src/main/scala/cats/data/NonEmptyList.scala
- core/src/main/scala/cats/data/NonEmptySet.scala
- core/src/main/scala/cats/data/NonEmptyVector.scala
- core/src/main/scala/cats/syntax/flatMap.scala
- core/src/main/scala/cats/syntax/list.scala
- core/src/main/scala/cats/syntax/set.scala
This doesn't need to happen before 2.1.0 but we should be running these tests on 2.13.
> Enable and fix doctests on 2.13

- tests/src/test/scala-2.12/cats/tests/NonEmptyStreamSuite.scala
- tests/src/test/scala-2.13+/cats/tests/NonEmptyLazyListSuite.scala
- tests/src/test/scala/cats/tests/NonEmptyChainSuite.scala
- tests/src/test/scala/cats/tests/NonEmptyListSuite.scala
- tests/src/test/scala/cats/tests/NonEmptyVectorSuite.scala
- tests/src/test/scala/cats/tests/ReducibleSuite.scala
This is one small thing that I just noticed in #3150, but I'd already caused enough trouble there so I decided it'd be best to handle in a follow-up. :smile:
I think `rangeE` was named to match `range`, but it doesn't actually create a range, and it's not in any way `Either` specific, so I replaced it with a general `fromValues` method that can be used in these tests.
> Rename rangeE for clarity

- core/src/main/scala/cats/Foldable.scala
- core/src/main/scala/cats/Reducible.scala
- tests/src/test/scala/cats/tests/FoldableSuite.scala
- tests/src/test/scala/cats/tests/ReducibleSuite.scala
As discussed in #3150, the only real reason I can see for `foldA` and `reduceA` to exist is because they can short-circuit, while `fold(fga)(Applicative.monoid)` etc. can't. This change fixes them so they actually do short-circuit, and adds some tests to verify this.
> Fix foldA, reduceA, and reduceMapA short-circuiting

- core/src/main/scala/cats/instances/sortedSet.scala
- laws/src/main/scala/cats/laws/MonadErrorLaws.scala
Fixes #3202 and all related issues I was able to turn up.
> Fix more bincompat breakage

- core/src/main/scala/cats/evidence/As.scala
Dotty currently reserves `*` for use as a type lambda placeholder for compatibility with kind-projector's syntax on Scala 2, via a currently-unimplemented `-Ykind-projector` compiler option. It's not clear whether `-Ykind-projector` should or will support kind-projector's ``λ[`-α` => Whatever[α]]`` syntax, or even `-*`. (I'm working on implementing `-Ykind-projector` at the moment, and personally I don't see compatibility with the goofier corners of kind-projector's syntax as a priority.)
Cats only uses kind-projector's variance annotations in this one file, and they're pretty easy to replace, and in my view the vanilla Scala syntax is clearer, anyway.
/cc @smarter
> Avoid kind-projector syntax with variance annotations

- project/build.properties
- scalafix/project/build.properties
- scalafix/project/plugins.sbt
Like #3210 but doesn't fail.
I've seen this error in other contexts from sbt 1.3.5:
```
[error] java.lang.NoClassDefFoundError: org/scalacheck/Test$TestCallback
[error] 	at java.lang.Class.getDeclaredFields0(Native Method)
[error] 	at java.lang.Class.privateGetDeclaredFields(Class.java:2583)
[error] 	at java.lang.Class.getDeclaredFields(Class.java:1916)
```
…and I'm pretty sure it has something to do with having both ScalaCheck 1.13 and 1.14 dependencies around (in this case via the old scalafix-testkit's dependency on some weird ScalaTest 3.2 version). In any case updating Scalafix seems to fix the issue.
> Update sbt-scalafix and sbt versions

- core/src/main/scala/cats/data/Ior.scala
- core/src/main/scala/cats/evidence/Is.scala
This is a subset of #3209 that only changes the use of kind-projector's `*` placeholder in infix types. I added support for `*` in function and tuple types to my `-Ykind-projector` [proposal](https://github.com/lampepfl/dotty/pull/7775) for Dotty, but infix types seem like more of a hassle and I don't think it's worth bothering with.
> Replace kind-projector placeholders in infix types

- core/src/main/scala/cats/Defer.scala
- tests/src/test/scala/cats/tests/FunctionSuite.scala
A pattern I often use in working with scalacheck.Gen or with Parsers is:
```
lazy val x: Gen[X] = {
val recurse = Gen.lzy(x)
//....
}
```
It occurred to me all the types I use this pattern with are generally Defer instances, and more over, we can express `fix` nicely on `Defer` instances since we know we can always return a value (there is no risk of infinite loop at fix application, although it is up to the user if evaluating `F[A]` is safe.
I think this is a useful function to have on Defer.
> Add Defer.fix

- CHANGES.md
- README.md
- version.sbt
It's on its way to Maven Central, and the [release notes](https://github.com/typelevel/cats/releases/tag/v2.1.0) are up.
If you're merging this, please only do it with a merge commit! The `v2.1.0` release tag points to one of these commits, and if it's not on master we'll have to force-push the tag and `2.1.x` branch to clean things up.
> 2.1.0 follow-up (please don't squash / rebase!)

- core/src/main/scala/cats/data/Validated.scala
Just adds a comment, regarding an unused implicit parameter. 
With a link to https://github.com/typelevel/cats/pull/1867/files#r138381991.
> Add a Developer-Comment regarding an unused parameter.

- CONTRIBUTING.md
- README.md
A PR to fix issue #3206 and remove links to waffle.io :
Files changed based on grep:
```
$ grep -rnw . -e 'waffle'
./README.md:250:via [Waffle.io](https://waffle.io/typelevel/cats).
./CONTRIBUTING.md:265:via [Waffle.io](https://waffle.io/typelevel/cats).
```
> fixes #3206 remove references to waffle.io

- DESIGN.md
- README.md
- build.sbt
- core/src/main/scala/cats/arrow/FunctionK.scala
I think we should have done this after #2925. The cats-macros project is empty, so we might as well not publish it. I've also replaced the global `-language:experimental.macros` flag with an explicit import in the one place we need it, which is a small thing but doesn't hurt.
> Drop cats-macros project

- core/src/main/scala/cats/Eval.scala
- core/src/main/scala/cats/data/AndThen.scala
These two casts are necessary to compile cats-core with Dotty. I've been using them locally in my cross-compilation experiments, but wanted to understand for myself why Dotty wants them before opening a PR.
I've just been taking a closer look and have convinced myself that in both cases Dotty is doing the right thing, and Scala 2 only compiles the current code because of soundness bugs.
In `AndThen`, the issue is that the compiler is inferring the `E` to be `Any` in the `Concat` case, which isn't sound in general. Consider the following simplification:
```scala
scala> case class Foo[A](f: A => Any)
defined class Foo
scala> def whatever(x: Any) = x match { case Foo(f) => f("") }
^
error: type mismatch;
found   : String("")
required: Nothing
```
Inferring `Nothing` here is the safe thing to …
> Add two casts to satisfy Dotty

- .scalafmt.conf
- core/src/main/scala-2.12/cats/instances/stream.scala
- core/src/main/scala-2.13+/cats/data/NonEmptyLazyList.scala
- core/src/main/scala-2.13+/cats/instances/lazyList.scala
- core/src/main/scala-2.13+/cats/instances/stream.scala
- core/src/main/scala/cats/Foldable.scala
- core/src/main/scala/cats/Monad.scala
- core/src/main/scala/cats/Reducible.scala
- core/src/main/scala/cats/data/Chain.scala
- core/src/main/scala/cats/data/EitherT.scala
- core/src/main/scala/cats/data/IndexedStateT.scala
- core/src/main/scala/cats/data/Kleisli.scala
- core/src/main/scala/cats/data/NonEmptyList.scala
- core/src/main/scala/cats/data/NonEmptyVector.scala
- core/src/main/scala/cats/data/OptionT.scala
- core/src/main/scala/cats/data/WriterT.scala
- core/src/main/scala/cats/instances/future.scala
- core/src/main/scala/cats/instances/list.scala
- core/src/main/scala/cats/instances/queue.scala
- core/src/main/scala/cats/instances/vector.scala
- free/src/test/scala/cats/free/CofreeSuite.scala
- free/src/test/scala/cats/free/FreeTSuite.scala
- laws/src/main/scala/cats/laws/discipline/Eq.scala
- laws/src/main/scala/cats/laws/discipline/InvariantSemigroupalTests.scala
- laws/src/main/scala/cats/laws/discipline/SemigroupalTests.scala
- laws/src/main/scala/cats/laws/discipline/arbitrary.scala
- tests/src/test/scala/cats/tests/FoldableSuite.scala
- tests/src/test/scala/cats/tests/FunctionSuite.scala
This is the update in #3228 but with the updated formatter actually run. Personally I like these changes, but if anyone has objections we could try to figure out whether it's possible to change the config to avoid them.
> Update Scalafmt to 2.3.2

- free/src/main/scala/cats/free/Free.scala
Due to the fact that the algebra itself is private, it is not *currently* possible to implement custom interpreters on top of `Free`. A first-order analogue for this limitation would be as if the only way to look at `List` was `foldLeft`: it's great, and technically can do anything, but it's immensely difficult to do things that are more complicated than a simple traversal. For example, imagine I want to convert a `List[A]` into a `List[(A, A)]` such that all adjacent even/odd values are paired together (i.e. index `0` with index `2`, `1` with `3` and so on). Doing this with a `foldLeft` is possible, but hard (well, at least annoying). The analogous transformation on `Free` is exponentially more difficult with `foldMap`, and also impossible to type check (due to the existentials …
> Publicize Free#foldStep

- core/src/main/scala/cats/data/OptionT.scala
- tests/src/test/scala/cats/tests/OptionTSuite.scala
In scala 2.13, we have Option.{when, unless}. So should cats, I guess 🤔
> Add when and unless to OptionT

- core/src/main/scala/cats/data/OptionT.scala
- tests/src/test/scala/cats/tests/OptionTSuite.scala
A follow up to #3233 based on the helpful comments by @fthomas and @rossabaker:  `OptionT.{whenF, unlessF}` should return `OptionT.none` when the given condition is `false`.
> Follow up to #3233

- core/src/main/scala/cats/syntax/list.scala
`.scanLeft` result is always non-empty.
> add List#scanLeftNel and List#scanRightNel

- alleycats-tests/js/src/test/scala/alleycats/tests/TestSettings.scala
- alleycats-tests/jvm/src/test/scala/alleycats/tests/TestSettings.scala
Low-priority but we might as well go ahead and do this.
> Avoid ScalaTest 3.1.0 deprecations

- free/src/main/scala/cats/free/FreeT.scala
- free/src/test/scala/cats/free/FreeTSuite.scala
- laws/src/main/scala/cats/laws/ApplicativeErrorLaws.scala
- laws/src/main/scala/cats/laws/discipline/ApplicativeErrorTests.scala
There's an explanation of this in the comments in the code. I retained the old implementation for binary compatibility, but it is somewhat unfortunate since any code which is hitting that is outright-broken and people may not know it. Then again, I'm not sure how many people (other than me) are using `FreeT`, so maybe it's okay either way.
Fixes #3240
> Reimplemented MonadError[FreeT[...]] to be correct

- tests/src/test/scala/cats/tests/AsSuite.scala
- tests/src/test/scala/cats/tests/EvalSuite.scala
- tests/src/test/scala/cats/tests/FoldableSuite.scala
- tests/src/test/scala/cats/tests/IorSuite.scala
- tests/src/test/scala/cats/tests/KleisliSuite.scala
- tests/src/test/scala/cats/tests/NonEmptyVectorSuite.scala
Okay, I think I'm really close to cross-compiling the Cats tests on Dotty, and I'm pretty sure this is the last batch of Scala 2-friendly changes that could be merged into master right now. (The rest of the changes are stubs for ScalaTest macros and explicit type parameters for cases where Dotty's type inference is worse than Scala 2's, which I'm working on feature requests for.)
Note that I've changed a few instances of `"code" shouldNot compile` to `assertDoesNotCompile("code")`, which is both more consistent with Cats's style elsewhere (e.g. using `assertTypeError` instead of `shouldNot typeCheck`) and easier to temporarily stub for Dotty. In my view this is a strict improvement even on Scala 2 (but I hate ScalaTest's matchers in general).
> More Dotty compat stuff in tests

- build.sbt
- js/src/test/scala/cats/tests/FutureTests.scala
- project/plugins.sbt
- scripts/scala.js-1.0-publish.sh
These changes make it possible to build Cats on Scala.js 1.0 (currently 1.0.0-RC2) via an environmental variable, without actually changing anything significant about the current build, which is still on Scala.js 0.6.
This approach is currently used by Simulacrum, Discipline (although Discipline does test Scala.js 1.0.0-RC2 in CI, and this change doesn't), etc.
I've confirmed that the following succeeds:
```
SCALAJS_VERSION=1.0.0-RC2 sbt +validateJS
```
> Minor changes for Scala.js 1.0 compatibility

- tests/src/test/scala/cats/tests/ContravariantSuite.scala
- tests/src/test/scala/cats/tests/ReducibleSuite.scala
The tests have been warning on these two issues for a while. The first is because of a [ScalaTest bug](https://github.com/scalatest/scalatest/issues/961), but it's easy to work around. The second is a deprecation warning for some code that's no longer necessary.
> Fix compiler warnings in tests

- build.sbt
- core/src/main/scala/cats/data/NonEmptyChain.scala
- core/src/main/scala/cats/data/NonEmptyMapImpl.scala
- core/src/main/scala/cats/data/NonEmptySet.scala
- tests/src/test/scala/cats/tests/NonEmptyMapSuite.scala
- tests/src/test/scala/cats/tests/NonEmptySetSuite.scala
This change fixes a few small things that have been bothering me.
The first is that a few files have Apache license headers, even though the project itself is MIT licensed. These also say "2018 Luka Jacobowitz", so I'm assuming this was an accidental addition from an IDE template or global sbt plugin. Can you confirm this, @LukaJCB?
The other two changes are trivial—I've just updated the copyright dates in `build.sbt` and used the `Test` configuration there instead of `"test"`.
> Copyright and license

- core/src/main/scala-2.13+/cats/instances/all.scala
- core/src/main/scala-2.13+/cats/instances/arraySeq.scala
- core/src/main/scala-2.13+/cats/instances/package.scala
- kernel/src/main/scala-2.13+/cats/kernel/instances/AllInstances.scala
- kernel/src/main/scala-2.13+/cats/kernel/instances/ArraySeqInstances.scala
- kernel/src/main/scala-2.13+/cats/kernel/instances/arraySeq/package.scala
- tests/src/test/scala-2.13+/cats/tests/ArraySeqSuite.scala
This is my attempt at adding common instances for **ArraySeq**.
I am not sure if we could implement more typeclasses and if the tests are ok. Also, many implementations of the methods were borrowed from the **Vector** and **LazySList** ones.
So, any feedback is welcome.
Closes #2994 
------
_BTW, I have a surgery this Wednesday. So, if reviewers leave feedback and I do not answer them, and some have the motivation and time to finish this PR, I would really appreciate it. Since, probably I won't touch a computer again until the next week._
> Adding instances for ArraySeq

- core/src/main/scala/cats/data/ContT.scala
> Add ContT.liftF and ContT.liftK

- bench/src/main/scala/cats/bench/EitherKMapBench.scala
- bench/src/main/scala/cats/bench/ValidatedBench.scala
- core/src/main/scala/cats/Eval.scala
- core/src/main/scala/cats/Reducible.scala
- core/src/main/scala/cats/data/EitherK.scala
- core/src/main/scala/cats/data/EitherT.scala
- core/src/main/scala/cats/data/IndexedReaderWriterStateT.scala
- core/src/main/scala/cats/data/IndexedStateT.scala
- core/src/main/scala/cats/data/IorT.scala
- core/src/main/scala/cats/data/NonEmptyList.scala
- core/src/main/scala/cats/data/NonEmptySet.scala
- core/src/main/scala/cats/data/NonEmptyVector.scala
- core/src/main/scala/cats/data/OneAnd.scala
- core/src/main/scala/cats/data/OptionT.scala
- core/src/main/scala/cats/data/WriterT.scala
This weekend I ran into a [Dotty bug](https://github.com/lampepfl/dotty/issues/8035) that turned up because of our use of `cats.syntax` methods in `cats.data`. The issues are easy enough to work around, but it's a good reminder that value classes are a mess and we might want to avoid extension methods in our own implementations.
This PR replaces all use of `cats.syntax` extension methods in `cats/*.scala` and `cats/data/*.scala`. Most of the replacements have a fairly neutral effect on readability, like using `Ior.fromEither` instead of `_.toIor`, or `algebra.remove(x, y)` instead of `x |-| y`, etc. In these cases we get to avoid some indirection and exposure to value class nonsense without bloating the code.
In a few cases the non-syntax version is a significantly more verbose—in …
> Avoid syntax methods in implementations in cats-core

- core/src/main/scala/cats/data/IndexedReaderWriterStateT.scala
- tests/src/test/scala/cats/tests/FoldableSuite.scala
- tests/src/test/scala/cats/tests/IndexedReaderWriterStateTSuite.scala
addresses the last bit of https://github.com/typelevel/cats/issues/2304
> Issue 2304: Missing functions for RWST

- bench/src/main/scala/cats/bench/TraverseBench.scala
- core/src/main/scala-2.13+/cats/instances/arraySeq.scala
- core/src/main/scala/cats/instances/list.scala
- core/src/main/scala/cats/instances/vector.scala
tl;dr: Traversing a `List` or `Vector` is probably the most common operation people do with this library, and the current implementations for these types have some room for optimization, with the changes in this PR giving up to 20% more throughput for `List` and 201% for `Vector`.
I've put together a benchmark that compares the current `traverse` for `List` with two new implementations:
```scala
def traverseFoldRight[G[_], A, B](fa: List[A])(f: A => G[B])(implicit G: Applicative[G]): G[List[B]] =
fa.foldRight[Eval[G[List[B]]]](Always(G.pure(Nil))) {
case (h, t) => G.map2Eval(f(h), Eval.defer(t))(_ :: _)
}
.value
def traverseRec[G[_], A, B](fa: List[A])(f: A => G[B])(implicit G: Applicative[G]): G[List[B]] = {
def loop(fa: List[A]): Eval[G[List[B]]] = fa match {
case h :: t => …
```
> Optimize traverse

- docs/src/main/tut/colophon.md
Machinist is an archived project and has been removed from the cats project with [PR 2925](https://github.com/typelevel/cats/pull/2925) on 1 Jul 2019.
To avoid confusion, it should be removed from the colophon page in my opinion as well.
> Remove machinist from colophon microsite page

- core/src/main/scala/cats/implicits.scala
- core/src/main/scala/cats/instances/ScalaVersionSpecificParallelInstances.scala
- core/src/main/scala/cats/instances/all.scala
- core/src/main/scala/cats/instances/either.scala
- core/src/main/scala/cats/instances/list.scala
- core/src/main/scala/cats/instances/package.scala
- core/src/main/scala/cats/instances/stream.scala
- core/src/main/scala/cats/instances/vector.scala
- tests/src/test/scala/cats/tests/CatsSuite.scala
- tests/src/test/scala/cats/tests/EitherSuite.scala
- tests/src/test/scala/cats/tests/ListSuite.scala
- tests/src/test/scala/cats/tests/ParallelSuite.scala
- tests/src/test/scala/cats/tests/StreamSuite.scala
- tests/src/test/scala/cats/tests/SyntaxSuite.scala
- tests/src/test/scala/cats/tests/VectorSuite.scala
> Backport #3099 to scala_2.11 branch

- core/src/main/scala/cats/syntax/all.scala
- core/src/main/scala/cats/syntax/bifoldable.scala
- core/src/main/scala/cats/syntax/package.scala
- tests/src/test/scala/cats/tests/BifoldableSuite.scala
> Backport `bifold` in `Bifoldable` typeclass to scala_2.11

- README.md
I noticed the readme suggest cats-core 2.0.0 as the sbt dependency, but since 2.1.0 is already out we might as well use that one. If for some reason this is not the case, please ignore this PR.
> Update readme with latest cats-core version

- core/src/main/scala/cats/TraverseFilter.scala
- laws/src/main/scala/cats/laws/TraverseFilterLaws.scala
- laws/src/main/scala/cats/laws/discipline/TraverseFilterTests.scala
I find this combinator really useful, as it doesn't discard information in the way `traverseFilter` does.
> Add traverseEither

- core/src/main/scala-2.13+/cats/instances/arraySeq.scala
- kernel/src/main/scala-2.13+/cats/kernel/instances/ArraySeqInstances.scala
- tests/src/test/scala-2.13+/cats/tests/ArraySeqSuite.scala
This builds on #3273, addressing #2994. It adds a few instances that were missing and makes the cats-kernel prioritization traits package-private.
> ArraySeq instance follow-up

- core/src/main/scala/cats/syntax/applicativeError.scala
- tests/src/test/scala/cats/tests/ApplicativeErrorSuite.scala
> Backport `attemptNarrow` from `ApplicativeError` to scala_2.11

- core/src/main/scala/cats/syntax/foldable.scala
- core/src/main/scala/cats/syntax/reducible.scala
- tests/src/test/scala/cats/tests/FoldableSuite.scala
> Backport `minimum/maximum/ByOption` from Foldable to scala_2.11

- core/src/main/scala/cats/syntax/package.scala
This seems to have been an oversight. We're not really testing these at the moment, but #3304 will help with that (it's why I noticed this was missing).
> Add cats.syntax.hash

- core/src/main/scala/cats/syntax/package.scala
`untilDefinedM` is a method on `FlatMap` and should be available via `cats.syntax.flatMap`, but it's not:
```scala
scala> import cats.instances.list._, cats.syntax.flatMap._
import cats.instances.list._
import cats.syntax.flatMap._
scala> List(Option(1)).untilDefinedM
<console>:18: error: value untilDefinedM is not a member of List[Option[Int]]
List(Option(1)).untilDefinedM
^
```
It is in `all`:
```scala
scala> import cats.instances.list._, cats.syntax.all._
import cats.instances.list._
import cats.syntax.all._
scala> List(Option(1)).untilDefinedM
res0: List[Int] = List(1)
```
This change just fixes this oversight. Like #3305 it's not currently tested, but will be in #3304.
> Make cats.syntax.flatMap include untilDefinedM

- core/src/main/scala-2.13+/cats/data/NonEmptyLazyList.scala
- core/src/main/scala/cats/data/Chain.scala
- core/src/main/scala/cats/data/NonEmptyChain.scala
- core/src/main/scala/cats/data/NonEmptyCollection.scala
- core/src/main/scala/cats/data/NonEmptyList.scala
- core/src/main/scala/cats/data/NonEmptyVector.scala
- tests/src/test/scala-2.13+/cats/tests/NonEmptyLazyListSuite.scala
- tests/src/test/scala/cats/tests/ChainSuite.scala
- tests/src/test/scala/cats/tests/NonEmptyChainSuite.scala
- tests/src/test/scala/cats/tests/NonEmptyCollectionSuite.scala
- tests/src/test/scala/cats/tests/NonEmptyListSuite.scala
- tests/src/test/scala/cats/tests/NonEmptyVectorSuite.scala
Unfortunately `cats.data` is kind of a disaster, in part because all of the `NonEmptyX` types are unrelated and don't implement any particular interface. This means that not only do we have four different ways to encode non-empty collections, each of our implementations has a fairly arbitrary grab-bag of methods attached to it.
This PR adds several "missing" methods:
* New for `Chain`: `sortBy`, `sorted`, `zipWithIndex`.
* New for `NonEmptyChain`: `sortBy`, `sorted`, `zipWithIndex`, `groupByNem`, `toNem`, `toNes`, `show`.
* New for `NonEmptyLazyList`:  `sortBy`, `sorted`, `groupBy`, `groupByNem`, `toNem`, `toNes`, `show`.
* New for `NonEmptyList`: `iterator`.
* New for `NonEmptyVector`: `iterator`, `groupBy`, `groupByNem`, `toNem`, `toNes`.
This PR also introduces a new …
> Clean up some NonEmpty stuff

- core/src/main/scala/cats/data/Ior.scala
`Ior.map` had just the copy&pasted examples from `Ior.bimap`, this PR replaces them with proper, equivalent examples for `map`.
> Fix doc examples for Ior.map

- core/src/main/scala/cats/package.scala
Documentation only PR. No code change. 
State what is in the package and what is not. Also, serve as an entry point to the Cats library and its implementation and design.
Resolves https://github.com/typelevel/cats/issues/149
> Cats package: add comprehensive scaladoc.

- kernel-laws/shared/src/test/scala/cats/kernel/laws/LawTests.scala
- kernel/src/main/scala/cats/kernel/instances/BigDecimalInstances.scala
Scala 2.13 changes the behavior of arithmetic on `BigDecimal` so that the `MathContext` of the first operand is used (instead of always using `UNLIMITED`, which is what was done in previous Scala versions; see [this issue](https://github.com/scala/bug/issues/11590) for some discussion of the change).
While this change is arguably the right thing to do in the standard library (assuming we're stuck with the mistake of carrying around a context in the first place), I think I've convinced myself that it's the wrong thing to do in Cats's instances. For one thing the 2.13 change means that operations from these instances are no longer commutative or even associative, even for fairly simple cases:
```scala
import cats.kernel.instances.bigDecimal._, cats.syntax.semigroup._
val x = …
```
> Use unlimited MathContext for BigDecimal arithmetic

- core/src/main/scala/cats/Foldable.scala
- core/src/main/scala/cats/Reducible.scala
- kernel-laws/shared/src/main/scala/cats/kernel/laws/SemigroupLaws.scala
- kernel-laws/shared/src/main/scala/cats/kernel/laws/discipline/SemigroupTests.scala
- kernel-laws/shared/src/test/scala/cats/kernel/laws/LawTests.scala
- kernel/src/main/scala/cats/kernel/Band.scala
- kernel/src/main/scala/cats/kernel/BoundedSemilattice.scala
- kernel/src/main/scala/cats/kernel/CommutativeMonoid.scala
- kernel/src/main/scala/cats/kernel/CommutativeSemigroup.scala
- kernel/src/main/scala/cats/kernel/Monoid.scala
- kernel/src/main/scala/cats/kernel/Order.scala
- kernel/src/main/scala/cats/kernel/Semigroup.scala
- kernel/src/main/scala/cats/kernel/instances/ListInstances.scala
- kernel/src/main/scala/cats/kernel/instances/StringInstances.scala
This adds a few things:
1. reverse method on Semigroup which returns a new Semigroup with the order reversed
2. intercalate method on Semigroup which returns a new Semigroup that puts an element between each combine operation
3. some optimizations of default implementations using laws.
4. reduce the width of the duration Arbitraries so we don't overflow (which causes exceptions).
> Add Semigroup and Monoid combinators reverse and intercalate

- free/src/main/scala/cats/free/FreeT.scala
The analogous function on `Free` is simply `foldMap`, but `FreeT` has an extra (monadic) suspension functor which cannot be manipulated through the same mechanism. `mapK` already exists; this simply provides a way of doing a `mapK`-like transformation where the resulting `N` is *itself* a `FreeT`. This can be useful when you want to manipulate the structure of the interpretation in a composable fashion.
> Added flatMapK to FreeT

- tests/src/test/scala/cats/tests/IndexedReaderWriterStateTSuite.scala
Trivial change: some missing parentheses slipped in and when I just tried to update the Dotty cross-building it failed here. (I'll be glad when we have Dotty cross-building in CI and don't have to worry about little stuff like this.)
> Add parentheses for Dotty

- core/src/main/scala-2.13+/cats/instances/arraySeq.scala
Another fairly trivial change that fixes Dotty breakage and avoids some arguably weird behavior on Scala 2. The code this touches has never been released and in any case these changes shouldn't affect the behavior of these implementations.
On Scala 2 you can write something like this:
```scala
scala> import scala.collection.immutable.ArraySeq
import scala.collection.immutable.ArraySeq
scala> def empty[A]: ArraySeq[A] = ArraySeq.empty
empty: [A]=> scala.collection.immutable.ArraySeq[A]
```
But it doesn't work on Dotty:
```scala
scala> import scala.collection.immutable.ArraySeq                                                                                                                                                                                            
scala> def empty[A]: …
```
> Use ArraySeq.untagged instead of ClassTag[Nothing]

- core/src/main/scala/cats/data/EitherT.scala
- tests/src/test/scala/cats/tests/EitherTSuite.scala
`semiflatTaps` functions on `EitherT` are highly useful when you have some e.g. `Logger[F]` abstractions and you don't want to lift it to `EitherT[F,A,B]`
> Add semiflatTap and leftSemiflatTap functions to EitherT

- .scalafmt.conf
- alleycats-core/src/main/scala/alleycats/std/map.scala
- core/src/main/scala/cats/data/Cokleisli.scala
- core/src/main/scala/cats/data/Func.scala
- core/src/main/scala/cats/data/Kleisli.scala
- core/src/main/scala/cats/data/WriterT.scala
- core/src/main/scala/cats/instances/map.scala
- core/src/main/scala/cats/instances/sortedMap.scala
- core/src/main/scala/cats/syntax/monadError.scala
- project/Boilerplate.scala
- tests/src/test/scala/cats/tests/AndThenSuite.scala
- tests/src/test/scala/cats/tests/EitherSuite.scala
- tests/src/test/scala/cats/tests/IndexedReaderWriterStateTSuite.scala
- tests/src/test/scala/cats/tests/RegressionSuite.scala
- tests/src/test/scala/cats/tests/ValidatedSuite.scala
This is a more conservative version of #3315 that still rewrites `{ }` to `( )` for single-line expressions, but doesn't remove newlines in cases like this, [which was my primary complaint about the default config in 2.4.2](https://github.com/typelevel/cats/pull/3315#issuecomment-590907872):
```scala
forAll { (nes: NonEmptySet[Int]) =>
nes.reduce should ===(nes.fold)
}
```
In #3315 that got rewritten to the following, which obscures what's being tested, at least to my eyes:
```scala
forAll((nes: NonEmptySet[Int]) => nes.reduce should ===(nes.fold))
```
Instead of `+495 −1,432` it's `+58, −50`, so quite a bit less dramatic, and the changes look more reasonable to me.
> Update Scalafmt to 2.4.2

- core/src/main/scala/cats/Alternative.scala
Minor though, found this when I was working on backporting `separateFoldable` to scala_2.11
> Fix `Foldable` doctest to use `separateFoldable` instead of `separate`

- core/src/main/scala/cats/instances/either.scala
- core/src/main/scala/cats/syntax/either.scala
Fixes #3343.  Thanks to @sirthias for the idea.
> Add Either.unit, use in Applicative[Either[A, ?]]

- core/src/main/scala/cats/instances/all.scala
- core/src/main/scala/cats/instances/package.scala
- core/src/main/scala/cats/instances/sortedSet.scala
- kernel/src/main/scala/cats/kernel/instances/AllInstances.scala
- kernel/src/main/scala/cats/kernel/instances/SortedSetInstances.scala
- kernel/src/main/scala/cats/kernel/instances/all/package.scala
- kernel/src/main/scala/cats/kernel/instances/sortedSet/package.scala
> Backport #3126 Remove `Order` constraint from `Hash` instance for SortedSet

- PROCESS.md
I originally proposed this policy change [on Gitter](https://gitter.im/typelevel/cats-dev?at=5e68b7c7e203784a559e5cca):
> I'd like to propose that we lower the review requirement for non-master PRs in Cats.
> 
> Specifically Gagandeep has put a huge amount of effort into backporting 2.1 changes for Scala 2.11, and these contributions have been getting merged very slowly: https://github.com/typelevel/cats/pulls?q=is%3Apr+author%3Agagandeepkalra+backport
> 
> There are currently 10 open. I've reviewed all of them, and in a few cases we've gone through several iterations to get them right.
>
> I know backport branches like this are a low priority for most maintainers (including me), but they can be very important for contributors like Gagandeep, and I think it would be reasonable to say PRs …
> Change review policy for PRs that don't target master

- bench/src/main/scala/cats/bench/TrampolineBench.scala
- core/src/main/scala/cats/Eval.scala
- core/src/main/scala/cats/instances/all.scala
- core/src/main/scala/cats/instances/package.scala
- core/src/main/scala/cats/instances/tailrec.scala
- tests/src/test/scala/cats/tests/TailRecSuite.scala
> Backport #3041 `tailrec` instances for StackSafeMonad and Defer to scala_2.11

- core/src/main/scala/cats/data/Chain.scala
- core/src/main/scala/cats/instances/list.scala
> Backport #3015 Use Foldable.foldRight for `Traverse` and `TraverseFilter`

- core/src/main/scala/cats/syntax/alternative.scala
- tests/src/test/scala/cats/tests/AlternativeSuite.scala
- tests/src/test/scala/cats/tests/SyntaxSuite.scala
> Backport #2742 Add `separateFoldable` to Alternative

- core/src/main/scala/cats/instances/future.scala
- core/src/main/scala/cats/instances/try.scala
- core/src/main/scala/cats/syntax/applicativeError.scala
- core/src/main/scala/cats/syntax/monadError.scala
- tests/src/test/scala/cats/tests/SyntaxSuite.scala
This one had few stuff to backport;
since we are not porting consistency law over, see [here](https://github.com/typelevel/cats/pull/3338#issuecomment-595196728)
and cannot override for specific instances now given we had to maintain BC while implementing, see [here](https://github.com/typelevel/cats/pull/3340#discussion_r388249553)
addresses #3143
> Backport #3146 Add redeem and redeemWith

- tests/src/test/scala/cats/tests/OptionSuite.scala
while back-porting `Align` to Scala 2.11, noticed we are missing tests for `Option` instance.
> Add Align lawful tests for Option instance

- core/src/main/scala/cats/instances/all.scala
- core/src/main/scala/cats/instances/queue.scala
- tests/src/test/scala/cats/tests/QueueSuite.scala
> Backport #3103 `traverseFilter` Queue instance to scala_2.11

- core/src/main/scala/cats/instances/all.scala
- core/src/main/scala/cats/instances/option.scala
- core/src/main/scala/cats/instances/package.scala
- kernel-laws/shared/src/test/scala/cats/kernel/laws/LawTests.scala
- kernel/src/main/scala/cats/kernel/instances/AllInstances.scala
- kernel/src/main/scala/cats/kernel/instances/OptionInstances.scala
- kernel/src/main/scala/cats/kernel/instances/all/package.scala
> Backport #2834 Add CommutativeMonoid[Option[A]] instance

- core/src/main/scala/cats/syntax/foldable.scala
- tests/src/test/scala/cats/tests/FoldableSuite.scala
> Backport #3130 Add foldMapA to foldable

- scripts/scala.js-1.0-publish.sh
- version.sbt
First, if you're merging this, please don't squash or rebase! This change is to keep master and the current release branch in sync, and rebasing would mean e.g. that the `v2.1.1` release tag isn't included in the history on master.
The issue is that I forgot to merge the `2.1.x` branch back into master when I published 2.1.1 a couple of weeks ago. This isn't a big deal, but it does mean that the `version.sbt` and the Scala.js 1.0 release script in master are out of date. This PR just does the merge, resolving some conflicts from things I had to backport in order to support Scala.js 1.0.0 in 2.1.1.
> Merge 2.1.x after 2.1.1 release

- core/src/main/scala/cats/ApplicativeError.scala
- core/src/main/scala/cats/syntax/applicativeError.scala
- tests/src/test/scala/cats/tests/ApplicativeErrorSuite.scala
This change makes it impossible to call `attemptNarrow` with a type parameter that isn't `Throwable` or one of its subtypes. This makes it slightly less easy to shoot yourself in the foot with it (see #3360), while still supporting its most common use cases.
The change doesn't break binary compatibility, but definitely does break source compatibility. It only breaks dangerous code, though, so I think that's fine for 2.2.0.
Personally I'd prefer to scrap it entirely (by making it package-private), since even in this restricted form it breaks parametricity in a way that feels un-Cats-like. I've chosen this route because of the precedent of `catchOnly`, which does a similar thing with runtime reflection but makes it relatively safe by restricting to `Throwable`.
> Restrict attemptNarrow to subtypes of Throwable

- kernel-laws/shared/src/test/scala/cats/kernel/laws/LawTests.scala
Before the fix in #3303 we were seeing occasional failed tests on Scala 2.13, and we haven't seen any since then, but I should have added some tests that specifically highlighted the fix, to make sure the instance don't accidentally get changed back, etc.
In this PR I've added two specific cases where commutativity and associativity didn't hold for the old `|+|` for `BigDecimal` on Scala 2.13, which simply called the standard library's `+`:
```scala
import java.math.MathContext
val one = BigDecimal("1", MathContext.DECIMAL32)
val small = BigDecimal("0.00001111111", MathContext.DECIMAL32)
val xs = one :: List.fill(10)(small)
```
And then:
```scala
scala> xs.reduceLeft(_ + _)
res0: scala.math.BigDecimal = 1.000110
scala> xs.reduceRight(_ + _)
res1: scala.math.BigDecimal = 1.000111
```
And …
> Specific commutativity and associativity tests for BigDecimal

- core/src/main/scala/cats/data/NonEmptyList.scala
seems like someone re-implemented Option's `getOrElse` inside NonEmptyList. Delegate to Option#getOrElse instead
> Use `getOrElse` in `NonEmptyList#last`

- core/src/main/scala/cats/data/NonEmptyVector.scala
- tests/src/test/scala/cats/tests/NonEmptyVectorSuite.scala
I needed to implement this recently and was surprised it didn't already exist.
> Prepend a Vector to a NonEmptyVector

- alleycats-core/src/main/scala/alleycats/std/set.scala
- core/src/main/scala-2.13+/cats/instances/lazyList.scala
- core/src/main/scala/cats/data/Chain.scala
- core/src/main/scala/cats/instances/queue.scala
- core/src/main/scala/cats/instances/vector.scala
Fixed short circuiting behaviour in `traverse` and `traverseFilter` for Queue, Chain, Set, Vector and LazyList instances.
resolves #3327
> Fix short circuiting behaviour in `traverse` and `traverseFilter` 

- core/src/main/scala/cats/instances/vector.scala
#3328 had been open a while and broke formatting on master when I merged it. This change fixes it.
> Fix formatting

- core/src/main/scala/cats/Align.scala
- tests/src/test/scala/cats/tests/SyntaxSuite.scala
> Add zipAll to Align typeclass

- AUTHORS.md
- CHANGES.md
- README.md
- scripts/scala.js-1.0-publish.sh
- version.sbt
Please note that this needs to be a merge commit! If we squash or rebase, then the 2.2.0-M1 tag won't be on master.
> Merge 2.2.x after 2.2.0-M1 release

- core/src/main/scala-2.12/cats/ScalaVersionSpecificInstances.scala
- kernel/src/main/scala/cats/kernel/Semigroup.scala
- tests/src/test/scala/cats/tests/MapSuite.scala
- tests/src/test/scala/cats/tests/StreamSuite.scala
Congrats to my colleague @CremboC on finding the first instance that didn't make it into implicit scope:
```scala
scala> cats.Semigroup[Map[String, List[Int]]]
^
error: could not find implicit value for parameter ev: cats.kernel.Semigroup[Map[String,List[Int]]]
```
This affects any map where the element type doesn't have a commutative semigroup. Pre-2.2.0-M1 usage continues to work fine in 2.2.0-M1, you just need at least the `cats.kernel.instances.map._` import.
I've also added a missing `Align[Stream]` on 2.12, which was turned up in #3378.
I'll give us a couple of days to find any more of these (and maybe fix #3377) and then publish a second milestone.
> First two missing instances

- core/src/main/scala/cats/data/WriterT.scala
- tests/src/test/scala/cats/tests/WriterSuite.scala
Resolves https://github.com/typelevel/cats/issues/3385
> WriterTInstances: insufficient prioritization

- docs/src/main/tut/typeclasses/traverse.md
> Fix a link in the documentation for Traverse

- core/src/main/scala/cats/data/EitherT.scala
It's not necessary. Closes #3398
> Tweak EitherT.pure and rightT to avoid a map call

- core/src/main/scala/cats/Functor.scala
- docs/src/main/tut/nomenclature.md
- tests/src/test/scala/cats/tests/SyntaxSuite.scala
> Functor - fproductLeft

- core/src/main/scala-2.13+/cats/data/NonEmptyLazyList.scala
- core/src/main/scala/cats/data/NonEmptyList.scala
- tests/src/test/scala-2.13+/cats/tests/NonEmptyLazyListSuite.scala
- tests/src/test/scala/cats/tests/NonEmptyListSuite.scala
> Add toNev to NonEmptyList variants

- core/src/main/scala/cats/data/AndThen.scala
- core/src/main/scala/cats/data/package.scala
Let me know if I need tests or documentation of any kind.
> Add Cont alias to ContT

- alleycats-tests/shared/src/test/scala/alleycats/tests/MapSuite.scala
- alleycats-tests/shared/src/test/scala/alleycats/tests/SetSuite.scala
- core/src/main/scala-2.12/cats/instances/stream.scala
- core/src/main/scala-2.13+/cats/instances/lazyList.scala
- core/src/main/scala-2.13+/cats/instances/stream.scala
- core/src/main/scala/cats/instances/queue.scala
- core/src/main/scala/cats/instances/vector.scala
- laws/src/main/scala/cats/laws/ShortCircuitingLaws.scala
- laws/src/main/scala/cats/laws/discipline/ShortCircuitingTests.scala
- tests/src/test/scala-2.12/cats/tests/NonEmptyStreamSuite.scala
- tests/src/test/scala-2.13+/cats/tests/LazyListSuite.scala
- tests/src/test/scala-2.13+/cats/tests/NonEmptyLazyListSuite.scala
- tests/src/test/scala/cats/tests/ChainSuite.scala
- tests/src/test/scala/cats/tests/ListSuite.scala
- tests/src/test/scala/cats/tests/NonEmptyChainSuite.scala
- tests/src/test/scala/cats/tests/NonEmptyListSuite.scala
- tests/src/test/scala/cats/tests/NonEmptyVectorSuite.scala
- tests/src/test/scala/cats/tests/QueueSuite.scala
- tests/src/test/scala/cats/tests/SortedMapSuite.scala
- tests/src/test/scala/cats/tests/StreamSuite.scala
- tests/src/test/scala/cats/tests/VectorSuite.scala
resolves #3355, previously #3327
> Add laws to check Short-Circuiting behaviour  

- build.sbt
Previously we'd filtered the Simulacrum dependency (which is only needed at compile-time) by matching the artifact name with `simulacrum_`. In #3424 this changed, though, from `simulacrum_2.x` to `simulacrum-scalafix-annotation_2.x`. This PR fixes the filter. I've published locally and verified that the dependency isn't included in the POM, and that everything works at runtime (by running Circe's tests using the local snapshot).
> Fix Simulacrum exclusion in POM

- AUTHORS.md
- CHANGES.md
- README.md
- scripts/scala.js-1.0-publish.sh
- version.sbt
All JVM and Scala.js 0.6 artifacts are on Maven Central now, and Scala.js 1.x is promoted and on its way. Release notes are [here](https://github.com/typelevel/cats/releases/tag/v2.2.0-M2).
Please note that this needs to be a merge commit! If we squash or rebase, then the 2.2.0-M2 tag won't be on master.
> Merge 2.2.x after 2.2.0-M2 release

- build.sbt
- project/plugins.sbt
This is like #3312, except:
* It disables coverage reporting on Scala.js, which was causing the `buildJVM` job to fail for some reason.
* It's 1.0.1 instead of 1.0.0.
* It doesn't change the `scala.js-1.0-publish.sh` script to work for 0.6.
If we decide someday that we need to publish a future release for Scala.js 0.6.x, I think we should add a new `scala.js-0.6-publish.sh` at that point, rather than repurposing the 1.0 one.
> Update Scala.js to 1.0, disable Scala.js coverage reporting

- build.sbt
This is a follow-up to #3357, where updating the default Scala.js version from 0.6 to 1.1 significantly increased test times. In a couple of quick experiments this change brings them back down part of the way.
> Use FullOptStage

- core/src/main/scala/cats/data/EitherT.scala
This is a trivial syntax switch away from kind-projector lambdas that aren't supported in Dotty.
This got merged in #3374—I just started refreshing #3269 and noticed it again. It's the only one that's snuck in, and we might as well go ahead and change it.
> Change value-level kind-projector syntax

- .codecov.yml
We currently use Codecov for test coverage reporting, which works nicely in general, but its default template for PR comments is much too verbose, especially since our use of property-based testing means there are often many files with small differences in coverage that show up in the report.
The result is that at the top of every PR thread there's an enormous comment that fills a screen or more and must be scrolled past to get to actual discussion.
I'm tempted to disable the PR comments entirely, and instead just have large changes in coverage fail the build. The reports would still be available on Codecov for anyone who needs them. Before we consider doing that, though, I thought we could try the smaller change here, which just removes the (often very long) `reach`, `flags`, and `file` …
> Configure codecov to simplify PR comments

- core/src/main/scala/cats/syntax/semigroupal.scala
- project/Boilerplate.scala
- tests/src/test/scala/cats/tests/SyntaxSerializationSuite.scala
Today I ran into a serializability issue when using `mapN` in a Spark
environment 😬.
> Make boilerplate syntax classes extend Serializable

- core/src/main/scala/cats/SemigroupK.scala
- core/src/main/scala/cats/instances/either.scala
- core/src/main/scala/cats/instances/list.scala
- core/src/main/scala/cats/instances/option.scala
- core/src/main/scala/cats/instances/vector.scala
- laws/src/main/scala/cats/laws/ShortCircuitingLaws.scala
- laws/src/main/scala/cats/laws/discipline/ShortCircuitingTests.scala
- tests/src/test/scala/cats/tests/ListSuite.scala
- tests/src/test/scala/cats/tests/SortedSetSuite.scala
- tests/src/test/scala/cats/tests/SyntaxSerializationSuite.scala
- tests/src/test/scala/cats/tests/VectorSuite.scala
> Add combineKEval and add short-circuiting for foldMapK

- core/src/main/scala/cats/Foldable.scala
- tests/src/test/scala-2.12/cats/tests/NonEmptyStreamSuite.scala
- tests/src/test/scala-2.13+/cats/tests/LazyListSuite.scala
- tests/src/test/scala-2.13+/cats/tests/NonEmptyLazyListSuite.scala
- tests/src/test/scala/cats/tests/ChainSuite.scala
- tests/src/test/scala/cats/tests/NonEmptyChainSuite.scala
- tests/src/test/scala/cats/tests/NonEmptyListSuite.scala
- tests/src/test/scala/cats/tests/NonEmptySetSuite.scala
- tests/src/test/scala/cats/tests/NonEmptyVectorSuite.scala
- tests/src/test/scala/cats/tests/QueueSuite.scala
- tests/src/test/scala/cats/tests/SortedMapSuite.scala
- tests/src/test/scala/cats/tests/SortedSetSuite.scala
- tests/src/test/scala/cats/tests/StreamSuite.scala
Resolves https://github.com/typelevel/cats/issues/3447
> Issue 3447: Add more foldMapK shortcircuiting

- core/src/main/scala/cats/data/EitherT.scala
- core/src/main/scala/cats/data/IorT.scala
- core/src/main/scala/cats/data/OptionT.scala
- docs/src/main/tut/datatypes/eithert.md
- docs/src/main/tut/datatypes/iort.md
- docs/src/main/tut/jump_start_guide.md
- docs/src/main/tut/nomenclature.md
- tests/src/test/scala/cats/tests/EitherTSuite.scala
- tests/src/test/scala/cats/tests/IorTSuite.scala
- tests/src/test/scala/cats/tests/OptionTSuite.scala
In practice the `OptionT[F, A]` => `EitherT[F, E, A]` transformation may also require the left to be calculated as `F[E]`. I didn't find anything handy neither in `OptionT` nor `EitherT` having to work-around with `.leftSemiflatMap(identity)` like
```scala
OptionT(...) 
.toRight(fe) // EitherT[F, F[E], A]
.leftSemiflatMap(identity)
```
or 
```scala
EitherT.fromOptionF(..., fe) // EitherT[F, F[E], A]
.leftSemiflatMap(identity)
```
> Add EitherT and IorT constructors from Option with monadic default

- core/src/main/scala-2.13+/cats/data/NonEmptyLazyList.scala
- core/src/main/scala/cats/data/NonEmptyChain.scala
- core/src/main/scala/cats/data/NonEmptyList.scala
- core/src/main/scala/cats/data/NonEmptyMapImpl.scala
- core/src/main/scala/cats/data/NonEmptyVector.scala
- core/src/main/scala/cats/data/OneAnd.scala
- laws/src/main/scala/cats/laws/ShortCircuitingLaws.scala
- laws/src/main/scala/cats/laws/discipline/ShortCircuitingTests.scala
- tests/src/test/scala-2.12/cats/tests/NonEmptyStreamSuite.scala
- tests/src/test/scala-2.13+/cats/tests/NonEmptyLazyListSuite.scala
- tests/src/test/scala/cats/tests/NonEmptyChainSuite.scala
- tests/src/test/scala/cats/tests/NonEmptyListSuite.scala
- tests/src/test/scala/cats/tests/NonEmptyMapSuite.scala
- tests/src/test/scala/cats/tests/NonEmptyVectorSuite.scala
resolves #3381
depends on #3375
> Optimise NonEmptyTraverse implementation

- docs/src/main/tut/faq.md
* Partial unification is not a setting for 2.13 so this gives an error
* Bump from cats 1 to 2
> Update faq for ammonite

- core/src/main/scala/cats/syntax/list.scala
- tests/src/test/scala/cats/tests/ListSuite.scala
> NonEmptyList.groupByNelA

- core/src/main/scala/cats/data/EitherT.scala
- core/src/main/scala/cats/data/IorT.scala
- core/src/main/scala/cats/data/OptionT.scala
- docs/src/main/tut/datatypes/eithert.md
- docs/src/main/tut/datatypes/iort.md
- docs/src/main/tut/jump_start_guide.md
- docs/src/main/tut/nomenclature.md
- tests/src/test/scala/cats/tests/EitherTSuite.scala
- tests/src/test/scala/cats/tests/IorTSuite.scala
- tests/src/test/scala/cats/tests/OptionTSuite.scala
This is to follow-up on feedback for https://github.com/typelevel/cats/pull/3426
@kailuowang I'm trying to understand the idea in your feedback comment
> `Option`, like several other data types, already has a `liftTo[F]` that can "lift" it into any `F[_]` with an `ApplicativeError[F]`, which is the case for both `IorT` and `EitherT`.
> For lifting to the left side, I believe we had a PR adding a `raiseTo[F]` but somehow I couldn't find it anymore.
> I am thinking that instead of adding n - 1 methods to n datatypes to support transformation between we can just add a `liftTo[F]` and a `raiseTo[F]` to n data types?
> In this example, we can add those to `OptionT` and `F[Option]`
>
>update: I found the raiseTo PR #3358
Do you mean that we can add something like
```scala
val foa = F[Option[A]] …
```
> Add EitherT and IorT constructors from Option with monad left value

- core/src/main/scala/cats/syntax/package.scala
This helps with specific import for apply
`import cats.syntax.apply._` would now bring `ifA` to scope
> Add BinCompat extensions to syntax.apply import

- README.md
This is to make it official, we've already spoken to current maintainers.
Welcome @barambani! 🎉
> Add Filippo Mariotti as a maintainer

- .travis.yml
This PR addresses the Coursier warning in Travis CI
```
Warning: a legacy coursier cache was found at /home/travis/.coursier/cache/v1 and is currently being used.
Support for that cache location will be removed in coursier 2.0.0 final, whose release is imminent.
Follow the instructions at
https://github.com/coursier/cache-migration#cache-migration
in order to migrate your cache to the newer location.
```
(an example [here](https://travis-ci.org/github/typelevel/cats/jobs/697278210#L243)) just changing the cache location without migrating the existing.
Also it updates the Scala Version and runs explicitly the Microsite build on 2.12.
**UPDATE**: I have to force Microsite make to 2.12.10. I hope it's ok while waiting for the docs port to alternatives (paradox + mdoc ?).
> Some travis ci updates

- docs/src/main/tut/nomenclature.md
> Move nomenclature questions below introductory paragraph

- core/src/main/scala/cats/Parallel.scala
- core/src/main/scala/cats/syntax/all.scala
- core/src/main/scala/cats/syntax/package.scala
- core/src/main/scala/cats/syntax/parallel.scala
> Add Parallel traverseFilter functions

- core/src/main/scala/cats/Align.scala
- core/src/main/scala/cats/FunctorFilter.scala
- core/src/main/scala/cats/Invariant.scala
- core/src/main/scala/cats/SemigroupK.scala
- core/src/main/scala/cats/Semigroupal.scala
- core/src/main/scala/cats/Show.scala
- core/src/main/scala/cats/UnorderedFoldable.scala
- core/src/main/scala/cats/data/NonEmptyMapImpl.scala
- core/src/main/scala/cats/instances/sortedMap.scala
- kernel/src/main/scala/cats/kernel/Eq.scala
- kernel/src/main/scala/cats/kernel/Semigroup.scala
- kernel/src/main/scala/cats/kernel/instances/SortedMapInstances.scala
These are @joroKr21's commits from #3397, but rebased to resolve a conflict. (I'm opening this as a new PR since I messed up the conflict resolution in #3397, but the commits / PR credit will go to @joroKr21.)
> Remove Order constraints from SortedMap and NonEmptyMap instances

- README.md
This is a minor thing, but the "Community Announcements" section now fills most of the screen on my laptop, and since it's at the top of the page I think it could use some occasional curation. This change just drops most of the entries, leaving the ones that seem to me likely to be of continuing interest.
> Clean up Community Announcements a little

- core/src/main/scala/cats/data/Ior.scala
> Add ior docs

- build.sbt
- tests/src/test/scala/cats/tests/SemigroupSuite.scala
The update in #3483 fails because it transitively bumps ScalaTest to 3.2.0, which splits some packages into their own modules, which have to be added to the build, which I've done here.
> Add ScalaTest 3.2.0 dependencies

- core/src/main/scala/cats/Invariant.scala
Just noticed this because it makes this instance show up in some failed implicit searches on Dotty for some reason. This change technically breaks source compatibility, but it's a method that was introduced in 2.2.0-M1 and fixing it is very unlikely to cause anyone problems.
> Remove unnecessary type parameter

- .travis.yml
- build.sbt
- core/src/main/scala-2.x/src/main/scala/cats/arrow/FunctionKMacros.scala
- core/src/main/scala-3.x/src/main/scala/cats/arrow/FunctionKMacros.scala
- core/src/main/scala/cats/arrow/FunctionK.scala
- laws/src/main/scala/cats/laws/ApplicativeErrorLaws.scala
- laws/src/main/scala/cats/laws/NonEmptyTraverseLaws.scala
- laws/src/main/scala/cats/laws/discipline/Eq.scala
- laws/src/main/scala/cats/laws/discipline/NonEmptyParallelTests.scala
- laws/src/main/scala/cats/laws/discipline/ParallelTests.scala
- project/plugins.sbt
- tests/src/test/scala/cats/tests/SemigroupSuite.scala
This PR partially includes and supersedes #3269. It also depends on #3484, which is ~trivial and should be merged soon.
There are a lot of issues with building and running our tests on Dotty, and I don't have the interest or will to deal with them right now, but I don't think that should block getting the core modules cross-building now. This PR enables Dotty cross-building (on the JVM only) for kernel, kernel-laws, core, laws, alleycats, and alleycats-laws, but does not run any tests.
Merging this now gets us a couple of things:
* We catch changes that break on Dotty sooner, at least for most of the code.
* It's easier for people other than me to work on the issues that are turning up in the tests.
None of the changes here should have any impact on the Scala 2 build, except for the …
> Another attempt at Dotty cross-building

- docs/src/main/tut/typeclasses/typeclasses.md
Small (opinionated) improvement. 
I've just read the documentation for typeclasses on the microsite and I was very confused by the use of duplicate name `A`. Although it compiles either way, I think this change will cause less confusion to future readers. Feel free to dismiss this PR if you feel different.
> Improve documentation for typeclasses

- .scalafmt.conf
- core/src/main/scala/cats/syntax/either.scala
A little formatting is required by this https://github.com/typelevel/cats/pull/3487 . It's actually not bad as those 2 examples were kind of unique in the style.
> Scalafmt core 2.6.1

- docs/src/main/resources/microsite/data/menu.yml
- docs/src/main/tut/typeclasses/arrowchoice.md
`Choice` is actually very useful typeclass, we use that a lot in our Scala and PureScript project, but it seems lack of document in cats elaborate how to actually make use of it.
> Add document about Arrow Choice

- kernel-laws/shared/src/main/scala/cats/kernel/laws/discipline/EqTests.scala
PartialOrderTests' transitivity and antisymmetry properties are shadowed by EqTests'.  When discipline finds duplicate laws in parent rulesets, the child's properties are silently dropped.  This counterintuitive behavior and sent us on a wild chase on http4s/http4s#3518.
We work around this by changing the EqTests' names to match the law names.
> Don't skip PartialOrder antisymmetry and transitivity

- core/src/main/scala/cats/syntax/option.scala
Add a `raiseOption` method to the `ApplicativeError` type-class, to raise possible errors if they are in there.
> ApplicativeError: add raiseOption operation.

- docs/src/main/tut/datatypes/kleisli.md
- docs/src/main/tut/typeclasses/typeclasses.md
I modified some expressions because they sounded a little difficult to understand for non native English speaker, like me, in the aspect of grammar.
`so long as` -> `as long as`
> Modify document expressions

- core/src/main/scala/cats/arrow/Profunctor.scala
- core/src/main/scala/cats/conversions/VarianceConversions.scala
- tests/src/test/scala/cats/tests/VarianceSuite.scala
> Add implicit variance support for Profunctor typeclass

- core/src/main/scala/cats/data/Tuple2K.scala
Closes #3410.
I wasn't really sure where in the Tuple2kInstances this should be added so I just put it in the last one so please tell me if there is somewhere else it should go. Also, should tests be added because I had a bit of trouble doing so. Thanks!
> Add Tuple2K Semigroupal

- build.sbt
This is a follow-up to @djspiewak's question [here](https://github.com/typelevel/cats/pull/3486#discussion_r442866335) about whether the Simulacrum Scalafix annotations dependency needs to be in the runtime classpath.
With Simulacrum 1 we used the following approach:
* Simulacrum's annotations extended `StaticAnnotation`.
* The annotations were themselves annotated with `@compileTimeOnly`.
* The Simulacrum macro removed the annotations.
* Cats's Simulacrum dependency had `Provided` scope.
* Cats used [POM postprocessing](https://github.com/typelevel/cats/blob/v2.1.1/build.sbt#L90-L101) to remove the dependency entirely from the published artifact configuration.
With Simulacrum Scalafix we currently do the following:
* The annotations only extend `scala.annotation.Annotation`.
* Cats uses …
> Review Simulacrum Scalafix annotation practices

- core/src/main/scala/cats/Invariant.scala
> Add invariant docs

- core/src/main/scala/cats/MonoidK.scala
> improved MonoidK docs

- core/src/main/scala-2.12/cats/evidence/AsSupport.scala
- core/src/main/scala-2.12/cats/evidence/IsSupport.scala
- core/src/main/scala-2.13+/cats/evidence/AsSupport.scala
- core/src/main/scala-2.13+/cats/evidence/IsSupport.scala
- core/src/main/scala/cats/evidence/As.scala
- core/src/main/scala/cats/evidence/Is.scala
- tests/src/test/scala/cats/tests/AsSuite.scala
- tests/src/test/scala/cats/tests/IsSuite.scala
close #2569
There is no reason not to create Is and As instances from the predef ones. The changes in 2.13 make this perfectly safe, but nothing in 2.12 (or before) made it unsafe, the types just lacked a substitute method.
This PR improves matters a bit.
I did notice that `Is` is not sealed, but `As` is. In general these two types have a pretty different API considering how similar they are conceptually.
I only did a bit, I added `toPredef` to both of them to convert back to predef types.
> Put implicit support for evidence from predef types

- build.sbt
This change is something I introduced when first setting up the Dotty build, and it's causing `sbt +package` to fail. It should be unnecessary now, I think, since Dotty isn't in `crossScalaVersions`.
> Fix cross-versioning for docs

- AUTHORS.md
- CHANGES.md
- README.md
- version.sbt
Please note that this needs to be a merge commit! If we squash or rebase, then the 2.2.0-RC1 tag won't be on master.
> Merge 2.2.x after 2.2.0-RC1 release

- core/src/main/scala/cats/instances/function.scala
This is just filling out some methods on these Monads that were left to default implementations. I think implementing them by hand slightly reduces the stack depth we are at when calling these
> Add some more implementations to Function0 and Function1 Monads

- core/src/main/scala/cats/data/AndThen.scala
before scala 2.12, you could not use `tailrec` with generics that changed types as the recursion went on. But now, we only support 2.12 and later.
That pattern is used in a few places in cats. This PR removes those casts and shortens the code in AndThen.
It helps see that the code is safe and should be just as fast.
> remove some casts in AndThen

- core/src/main/scala/cats/instances/option.scala
The Option Applicative is very simple, but the default implementations have a lot of closures and falls back to flatMap/map quite a bit.
By implementing these in terms of ifDefined/get then most of it should be simple JVM bytecode that the jit is very good at optimizing.
> Override some Option Apply/Applicative methods

- alleycats-core/src/main/scala/alleycats/std/map.scala
- alleycats-tests/shared/src/test/scala/alleycats/tests/MapSuite.scala
- core/src/main/scala/cats/data/Chain.scala
- core/src/main/scala/cats/instances/list.scala
- core/src/main/scala/cats/instances/queue.scala
- core/src/main/scala/cats/instances/sortedMap.scala
- core/src/main/scala/cats/instances/vector.scala
- tests/src/test/scala/cats/tests/ChainSuite.scala
- tests/src/test/scala/cats/tests/ListSuite.scala
- tests/src/test/scala/cats/tests/QueueSuite.scala
- tests/src/test/scala/cats/tests/SortedMapSuite.scala
- tests/src/test/scala/cats/tests/VectorSuite.scala
close #3517 
This makes all the traversals of all collections stack safe.
It follows the approach of: https://github.com/functional-streams-for-scala/fs2/pull/1957 but it is lazier (and maybe a bit slower because of that).
Cats has some tests that traversals on Applicatives that have lazy map2Eval instances that it won't trigger the function in those cases, so these laws require the traverse not only to have a certain result, but also invoke a function a known number of times.
I added tests before making each change and showed that the collection would fail a certain traversal (using Function0 as an example monad with poor stack safety).
> make collection traversals stack safe

- core/src/main/scala/cats/Eval.scala
- core/src/main/scala/cats/instances/list.scala
- core/src/main/scala/cats/instances/vector.scala
- docs/src/main/tut/datatypes/eval.md
- docs/src/main/tut/typeclasses/foldable.md
- tests/src/test/scala/cats/tests/EvalSuite.scala
similar to #3518 we use the 2.12 ability to do tailrec when the generic parameter changes to remove the casts.
Instead of using `List[Any => Eval[Any]]` we have to introduce a new type-aligned stack of functions, but I make this private.
This simplification leads to one optimization: if we have a finished `Memoize` in FlatMap we don't need to `loop(Now...` we can directly apply the flatMap function.
Also, I noticed perhaps the source of stack overflows I've seen in the past: #2587
> remove casts from Eval, fix stack overflow in Eval

- core/src/main/scala/cats/Foldable.scala
- core/src/main/scala/cats/Reducible.scala
- core/src/main/scala/cats/data/NonEmptyChain.scala
- core/src/main/scala/cats/data/NonEmptyList.scala
- core/src/main/scala/cats/instances/list.scala
- tests/src/test/scala/cats/tests/ReducibleSuite.scala
now
```scala
import cats.data.NonEmptyList
val notAllEven = NonEmptyList.of(2, 4, 6, 9, 10, 12, 14)
notAllEven.reduceMapA { a => println(a); if (a % 2 == 0) Some(a) else None }
14
12
10
9
6
4
2
res: Option[Int] = None
```
After applying this PR
```scala
import cats.data.NonEmptyList
val notAllEven = NonEmptyList.of(2, 4, 6, 9, 10, 12, 14)
notAllEven.reduceMapA { a => println(a); if (a % 2 == 0) Some(a) else None }
2
4
6
9
res: Option[Int] = None
```
> Enable breakout in functions reduceRightToOption and reduceRightTo.

- alleycats-core/src/main/scala/alleycats/std/map.scala
- core/src/main/scala/cats/data/Chain.scala
- core/src/main/scala/cats/instances/list.scala
- core/src/main/scala/cats/instances/queue.scala
- core/src/main/scala/cats/instances/sortedMap.scala
- core/src/main/scala/cats/instances/vector.scala
- kernel/src/main/scala/cats/kernel/instances/StaticMethods.scala
follow up to #3521 
In that PR, I added an API that consumes an Iterator. That is a bummer to have an API with a mutable arg, even if most people know that iterators must be considered with ownership semantics.
In fact, the first thing we do is materialize an IndexedSeq, so, why not just take an IndexedSeq and have callers materialize one if needed. This also removes duplication since Vector can share the same implementation now.
As an added bonus, you can use `Chain.traverseViaChain(0 until 100000)(f)` since Range is an IndexedSeq as well, which is nice.
It would be nice to get this in before 2.2.0 so we aren't stuck with the mutable API.
> Improve traverseViaChain API

- build.sbt
> Test freeJS with FastOptStage to save some CO2

- core/src/main/scala/cats/Reducible.scala
- tests/src/test/scala/cats/tests/ReducibleSuite.scala
> Enable breakout in functions nonEmptyTraverse_ and nonEmptySequence_

- .travis.yml
- alleycats-tests/js/src/test/scala/alleycats/tests/TestSettings.scala
- build.sbt
* Add them to the PR build
* Some minor build tweaks
I guess accidentally broken by #3538 and went unnoticed because it was not part of the build.
> Fix alleycats-tests on Scala.js

- core/src/main/scala/cats/Traverse.scala
I'm not quite sure how this got here, but it's messing up things in dotty 0.25 so we should get rid of it asap.
> Remove traverseForEither in Traverse companion object

- core/src/main/scala/cats/data/Ior.scala
- tests/src/test/scala/cats/tests/IorSuite.scala
> Order for Ior

- AUTHORS.md
- CHANGES.md
- README.md
- version.sbt
I meant to open this after publishing [2.2.0-RC2](https://github.com/typelevel/cats/releases/tag/v2.2.0-RC2) but forgot. It'll need to be merged before the next release (which should probably be another RC).
Please note that this PR should be merged with a merge commit, since if it is squashed or rebased the `v2.2.0-RC2` tag won't point to a commit on the main branch.
> Merge 2.2.x after 2.2.0-RC2 release

- core/src/main/scala/cats/data/IorT.scala
- tests/src/test/scala/cats/tests/IorTSuite.scala
> Order for IorT

- core/src/main/scala/cats/Reducible.scala
- core/src/main/scala/cats/data/NonEmptyList.scala
- core/src/main/scala/cats/data/NonEmptyVector.scala
`NonEmptyReducible` is not a typeclass and should not be used outside of Cats. Thus, the corresponding comments are added to the `NonEmptyReducible` along with `catsDataInstancesForNonEmptyVector` and `catsDataInstancesForNonEmptyList` implementing it.
> Comments on NonEmptyReducible not being a typeclass

- core/src/main/scala/cats/data/WriterT.scala
- tests/src/test/scala/cats/tests/WriterTSuite.scala
> Order for writert

- laws/src/main/scala/cats/laws/ReducibleLaws.scala
The test `reduceRightConsistentWithReduceRightOption` currently calls
`value` on an `Eval` before the end of the computation, i.e. it calls `value`
inside the functions passed to `reduceRight` and `reduceRightOption`.
This can cause a stack overflow in otherwise lawful `Reducible` instances.
The test has been changed to instead use `map` on the `Eval` which is
the intended way of using `Eval` in methods like `reduceRight`.
> Fix ReducibleLaws causing stack overflow by calling `Eval.now` early

- core/src/main/scala/cats/data/AndThen.scala
follow up to #3527 
Here we still do O(1) work on andThen and compose, but we check improve in two ways:
1. we check to see if we have a `Concat(_, Single(_, _))` that we can extend. Otherwise the first Concat will break the andThen chaining up to fusionMaxStackDepth.
2. we check to see if the andThen/compose arguments are AndThen instances early. This is a safety fix, otherwise Concat(_, _).andThen(Concat(_, _)) puts the right concat inside a single apply call in the loop, which could blow the stack since inside there could also do the same.
Note, in the fallback we were already testing for `_: AndThen`, here we inline that test to always happen early so we can leverage that information.
> Improve AndThen use of Single

- core/src/main/scala/cats/data/AndThen.scala
- tests/src/test/scala/cats/tests/AndThenSuite.scala
fix #3568 
The change to address the above is to avoid `equal` which on a very deep structure can blow the stack. Instead, directly check the property we want: isRightAssociated.
I removed a microoptimization (using != instead of <) since I would be *SHOCKED* if that changed the perf of this code which has to do quite a bit of pattern matching already. The != is not very safe since if a refactor gets it wrong, it can easily blow past the limit.
Lastly, I couldn't resist a bit of refactoring to share more of the code and improve associations (still at O(1) cost per andThen/compose).
cc @travisbrown
> Change AndThen to directly check isRightAssociated

- AUTHORS.md
- CHANGES.md
- README.md
- version.sbt
Pretty routine. One thing to note is that I put the adopter list PRs into the release notes this time, because I think it makes sense to give them more visibility, but didn't add the authors to the contributors list (which has always been the policy for changes like that).
Needs to be a merge commit to get the release tag on master.
> Merge 2.2.x after 2.2.0-RC3

- core/src/main/scala/cats/Invariant.scala
- core/src/main/scala/cats/Semigroupal.scala
- js/src/test/scala/cats/tests/FutureTests.scala
- jvm/src/test/scala/cats/tests/FutureSuite.scala
- kernel/src/main/scala/cats/kernel/Semigroup.scala
See discussion [here](https://github.com/typelevel/cats/pull/3566#issuecomment-674367117). I've not built or run tests locally yet but I think it should work.
> Add Future instances to implicit scope

- CONTRIBUTING.md
Reading the CONTRIBUTING.md guide I spot a missing "]". Easy fix, don't even need to clone the repo 😸
> Missing a "]" in CONTRIBUTING.md

- AUTHORS.md
- CHANGES.md
- README.md
- version.sbt
The usual for [2.2.0-RC4](https://github.com/typelevel/cats/releases/tag/v2.2.0-RC4). Needs to be a merge commit for the release tag.
> Merge 2.2.x after 2.2.0-RC4

- core/src/main/scala/cats/syntax/TrySyntax.scala
> Add `toValidated` to TrySyntax

- laws/src/main/scala/cats/laws/discipline/FoldableTests.scala
Fixes test name `ordered constistency` to `ordered consistency`.
> Fix typo in FoldableTests (constistency -> consistency)

- core/src/main/scala/cats/TraverseFilter.scala
- tests/src/test/scala-2.13+/cats/tests/ScalaVersionSpecific.scala
- tests/src/test/scala/cats/tests/TraverseFilterSuite.scala
It comes from Data.Witherable's hashNub and ordNub.
> Add method `distinct` to TraverseFilter

- CONTRIBUTING.md
Has commented here: https://github.com/typelevel/cats/issues/3599#issuecomment-691477329
The jekyll command to lunch the microsite locally is wrong. This fix it.
> Fixes #3599

- scalafix/README.md
The `scalafixAll` task is available as of [sbt-scalafix 0.9.18](https://github.com/scalacenter/sbt-scalafix/releases/tag/v0.9.18). See https://scalacenter.github.io/scalafix/docs/users/installation.html#settings-and-tasks.
For the record, that's what scala-steward uses as of https://github.com/scala-steward-org/scala-steward/pull/1523.
> scalafix: document scalafixAll to migrate test code as well

- core/src/main/scala-2.12/cats/compat/Seq.scala
- core/src/main/scala-2.12/cats/instances/all.scala
- core/src/main/scala-2.12/cats/instances/package.scala
- core/src/main/scala-2.13+/cats/compat/Seq.scala
- core/src/main/scala-2.13+/cats/instances/all.scala
- core/src/main/scala-2.13+/cats/instances/package.scala
- core/src/main/scala/cats/Align.scala
- core/src/main/scala/cats/FunctorFilter.scala
- core/src/main/scala/cats/Invariant.scala
- core/src/main/scala/cats/SemigroupK.scala
- core/src/main/scala/cats/Semigroupal.scala
- core/src/main/scala/cats/Show.scala
- core/src/main/scala/cats/UnorderedFoldable.scala
- core/src/main/scala/cats/data/NonEmptySeq.scala
- core/src/main/scala/cats/data/ZipSeq.scala
- core/src/main/scala/cats/instances/seq.scala
- core/src/main/scala/cats/syntax/all.scala
- core/src/main/scala/cats/syntax/package.scala
- core/src/main/scala/cats/syntax/seq.scala
- kernel/src/main/scala-2.12/cats/kernel/instances/AllInstances.scala
- kernel/src/main/scala-2.13+/cats/kernel/instances/AllInstances.scala
- kernel/src/main/scala/cats/kernel/Eq.scala
- kernel/src/main/scala/cats/kernel/instances/SeqInstances.scala
- kernel/src/main/scala/cats/kernel/instances/seq/package.scala
- laws/src/main/scala/cats/laws/discipline/arbitrary.scala
- tests/src/test/scala/cats/tests/SeqSuite.scala
Adds type class instances for `immutable.Seq`. This is based off of the implementations of the `List` and `Vector` typeclasses.
Closes #1222
> Add typeclasses for immutable.Seq

- tests/src/test/scala/cats/tests/ChainSuite.scala
Noticed while poking around to add `zipAll` that `zipWithIndex` on `Chain` (also called from `NonEmptyChain`) isn’t tail recursive. It’ll blow the stack if the chain is built from many `concat`s meaning we have a highly nested `Append` structure. E.g.
```
scala> List.fill(10000)(1).foldLeft(Chain(1)) { case (acc, next) => acc.concat(Chain(next)) }.zipWithIndex
java.lang.StackOverflowError
at scala.collection.AbstractIterable.<init>(Iterable.scala:56)
at scala.collection.AbstractSeq.<init>(Seq.scala:45)
```
This wasn’t caught by tests as the arbitrary instances generate only small collections - I guess this was a conscious decision?
Either way worth flagging 😄 
Edit: has since been fixed in https://github.com/typelevel/cats/pull/3533 so this change only adds a unit test. Changed title to …
> Add unit test to verify Chain.zipWithIndex stack safety

- kernel/src/main/scala/cats/kernel/Semigroup.scala
Looks like I missed adding a semigroup instances on `immutable.Seq`.
Before: 
```scala
scala> import cats._, cats.syntax.all._, scala.collection.immutable.Seq
import cats._
import cats.syntax.all._
import scala.collection.immutable.Seq
scala> Seq(1, 2, 3) |+| Seq(3, 4, 5)
<console>:19: error: value |+| is not a member of scala.collection.immutable.Seq[Int]
Seq(1, 2, 3) |+| Seq(3, 4, 5)
```
After:
```scala
scala> import cats._, cats.syntax.all._, scala.collection.immutable.Seq
import cats._
import cats.syntax.all._
import scala.collection.immutable.Seq
scala> Seq(1, 2, 3) |+| Seq(3, 4, 5)
res0: scala.collection.immutable.Seq[Int] = List(1, 2, 3, 3, 4, 5)
```
See: #3622
> immutable.Seq missing semigroup

- core/src/main/scala/cats/arrow/FunctionK.scala
This can also be done without `asInstanceOf` but that requires a wasteful allocation.
> FunctionK: methods to narrow input / widen output types

- .gitignore
Directory .bsp is created,  it is usually empty when creating the microsite.  Not sure it is useful
> add .bsp/ directory to gitignore, I suspect it is because of mdoc

- core/src/main/scala/cats/Traverse.scala
- laws/src/main/scala/cats/laws/TraverseLaws.scala
- laws/src/main/scala/cats/laws/discipline/TraverseTests.scala
I'd like to introduce `traverseTap`. I found it would be useful for me when attempting to perform debug log executing an effect, but dropping the result.
I'd like to add some tests, could someone please advice the best place to add them?
> Implement traverseTap

- build.sbt
I just released an RC1 of discipline-munit. If this builds and I get a :+1: on this PR I'll release the 1.0.0 final.
> use native Dotty build of ScalaCheck

- core/src/main/scala/cats/data/OptionT.scala
According to the signature, the scaladoc should say "Transform this `OptionT[F, A]` into a `F[B]`"
> Fix typo in the OptionT#foldF scaladoc

- .github/workflows/ci.yml
- build.sbt
This would replace 2.3.0-M1 entirely. We would need to release an M2. This also builds on 3.0.0-M1.
> Things weren't working, now I think they are

- docs/src/main/mdoc/faq.md
We should stop recommending sbt-catalysts.
There is only one remaining Typelevel project using it (cats-tagless), and ideally, we should migrate away from it there.
> remove mention of sbt-catalysts

- .github/workflows/ci.yml
- build.sbt
This is cool but I think we should wait until Scala 3.0.0-M2 for a proper release to get rid of all matrix exclusion shenanigans.
> enable DottyJS

- docs/src/main/mdoc/faq.md
The lack of instances for `Seq` is a puzzler for cats new users. A section in the faq would help a lot. See #1222.
> This is a kind reminder to run `sbt +prePR` and commit the changed files, if any, before submitting.
`+prePR` failed on my machine
```
...
[error] /home/tim/dev/projects/cats/free/src/main/scala-3.x/cats/free/FreeFoldStep.scala:19: error: identifier expected but [ found
[error]     onFlatMapped: [X] => (S[X], X => Free[S, A]) => B
[error]                   ^: /home/tim/dev/projects/cats/free/src/main/scala-3.x/cats/free/FreeFoldStep.scala
[error] /home/tim/dev/projects/cats/free/src/main/scala-3.x/cats/free/FreeFoldStep.scala:19: error: identifier expected but [ found
[error]     onFlatMapped: [X] => (S[X], X => Free[S, A]) => B
...
```
> add faq section for `Seq`

- kernel/src/main/scala/cats/kernel/Band.scala
- kernel/src/main/scala/cats/kernel/Order.scala
This is helpful for noncommutative idempotent instances.
Without this change, the `monoid.repeat0` law fails for these instances unless the `combineN` method is overridden (which is why it worked with the original `Monoid[Order[A]] with Band[Order[A]]` instance).
> tweak Band impl so it can more easily be combined with Monoid in a single instance

- kernel-laws/shared/src/test/scala/cats/kernel/laws/LawTests.scala
Reverts typelevel/cats#3470
I think this is what broke the build
> Revert "Issue 3353: Investigate antisymmetry failure for UpperBounded for Duration"

- core/src/main/scala/cats/Invariant.scala
- core/src/main/scala/cats/instances/future.scala
- core/src/main/scala/cats/instances/try.scala
- core/src/main/scala/cats/package.scala
- core/src/main/scala/cats/syntax/TrySyntax.scala
- tests/src/test/scala/cats/tests/OptionTSuite.scala
- tests/src/test/scala/cats/tests/TrySuite.scala
I noticed that the `ApplicativeThrow` and `MonadThrow` type aliases had been added to cats-effect:
https://github.com/typelevel/cats-effect/blob/series/2.x/core/shared/src/main/scala/cats/effect/package.scala#L41-L43
I felt that it made more sense for it to be cats as `ApplicativeError` and `MonadError` are in cats rather than cats-effect.
Also, it seems like `ApplicativeThrow` has erroneously had an unused `A` type param added, so I figured it was best to remove it. I'm not sure if that will clash or cause problems if both `cats._` and `cats.effect._` are imported. I'll open a separate PR against cats-effect 2.x branch to remove the `A`
> This is a kind reminder to run `sbt +prePR` and commit the changed files, if any, before submitting.
As an aside, I tried running this task but it …
> Add `ApplicativeThrow` and `MonadThrow` to cats package object (from cats-effect)

- core/src/main/scala/cats/data/Ior.scala
- tests/src/test/scala/cats/tests/IorSuite.scala
> Add addLeft/addRight for Ior

- core/src/main/scala/cats/Apply.scala
- core/src/main/scala/cats/FlatMap.scala
- core/src/main/scala/cats/Monad.scala
I noticed a few places where we do `map(f)(_ => a)`. This is the same as Functor.as, but it hides it from the typeclass implementation. Some types can optimize as by discarding any trailing map operators from their internal AST (such as parsers or other compute types that are not evaluated until later). By not calling typeclass methods we potentially slow those implementations down.
> Use as rather than map and discard

- alleycats-core/src/main/scala/alleycats/Empty.scala
- alleycats-core/src/main/scala/alleycats/EmptyK.scala
- alleycats-core/src/main/scala/alleycats/std/map.scala
I added the missing `EmptyK` instance for a `Map`.
Also, I made the `Empty.fromEmptyK` function implicit. I don't know why it was not marked as implicit, and it looks like it is a pretty safe change. This change automatically added an `Empty` instance for a `Map` too.
> Added EmptyK instance for Map

- kernel/src/main/scala/cats/kernel/PartialOrder.scala
use Markdown tables and lists, so that it renders nicely in the output HTML
> scaladoc fixes for PartialOrder

- core/src/main/scala/cats/data/NonEmptyList.scala
- tests/src/test/scala/cats/tests/NonEmptyListSuite.scala
This adds `NonEmptyList.zip` as it was still missing and we could use it for our project. Including tests.
I don't know why the unrelated test is failing. Is it flaky?
> Add NonEmptyList.zip

- docs/src/main/mdoc/nomenclature.md
I believe `mproduct` is the available name and not `productM`. At least I couldn't find `productM` in the documentation nor in the code.
> Rename productM to mproduct in the glossary

- core/src/main/scala/cats/Foldable.scala
- core/src/main/scala/cats/Reducible.scala
- tests/src/test/scala/cats/tests/FoldableSuite.scala
Whereas before you could only retrieve a single maximum or minimum item for a Foldable/Reducible, this allows getting all of the maximum or minimum items, since there can be several that are all equal.
> Allow finding a list of maxiumum/minimum items for Foldable/Reducible

- kernel-laws/shared/src/test/scala/cats/kernel/laws/LawTests.scala
- kernel/src/main/scala/cats/kernel/Enumerable.scala
- kernel/src/main/scala/cats/kernel/instances/ByteInstances.scala
> Provide BoundedEnumerable[Byte] instance

- free/src/main/scala/cats/free/Free.scala
- free/src/test/scala/cats/free/FreeSuite.scala
> deprecate Free.inject

- core/src/main/scala/cats/data/ContT.scala
- tests/src/test/scala/cats/tests/ContTSuite.scala
Add "call with current continuation" to ContT
> Add callCC to ContT

- core/src/main/scala/cats/data/NonEmptyList.scala
- tests/src/test/scala/cats/tests/NonEmptyListSuite.scala
Adds `NonEmptyList.take` including tests for convenience.
Returns a `List` because for `n < 1` we can't return a `NonEmptyList`.
Again some flaky test that is unrelated to my changes.
> Add NonEmptyList.take

- kernel-laws/shared/src/test/scala/cats/kernel/laws/LawTests.scala
This is #3470 redux, although with another approach.
Contains code by @barambani to test the issue.
I've confirmed that the newly-added tests fail _without_ the `Cogen` change.
cc @TimWSpence
> another attempt at Cogen for (Finite)Duration

- core/src/main/scala/cats/data/EitherT.scala
Fixes #3776 
This is source breaking, but *silently* so. Anyone relying on the error-accumulating behavior in the old instance will be surprised by the new one, which will continue to compile on all the same call-sites, but which will exhibit different semantics than previously.
> Removed and replaced inconsistent Parallel derivation for EitherT

- alleycats-core/src/main/scala/alleycats/Empty.scala
This breaks kittens: typelevel/kittens#299
PR that made it implicit: #3677
But more importantly, `MonoidK -> Monoid` and `SemigroupK -> Semigroup`
are not implicit either. I would err on the side of consistency here.
> Revert implicitness of Empty.fromEmptyK

- kernel-laws/shared/src/test/scala/cats/kernel/laws/LawTests.scala
- kernel/src/main/scala/cats/kernel/Enumerable.scala
> Add BoundedEnumerable.reverse

- core/src/main/scala/cats/Foldable.scala
PR #3727 introduced a compilation error when the compilation runs from scratch with the scalafix rules applied (which is still not tested in CI since the migration to `simulacrum-scalafix`).
This is to address this error.
> Fix scalafix rewriting for Foldable typeclass

- kernel-laws/shared/src/test/scala/cats/kernel/laws/LawTests.scala
> remove unnecessary Duration scalacheck instances

- bench/src/main/scala-2.12/cats/bench/ChainBench.scala
- core/src/main/scala/cats/data/Chain.scala
- tests/src/test/scala/cats/tests/ChainSuite.scala
```
bench/ jmh:run -i 5 -wi 3 -f1 -t1 cats.bench.ChainBench
[info] Benchmark                         Mode  Cnt          Score         Error  Units
[info] ChainBench.createChainOption     thrpt    5  190985469,005 ± 5173146,902  ops/s
[info] ChainBench.createChainSeqOption  thrpt    5   24305512,739 ±  594330,476  ops/s
```
> Chain add fromOption factory method

- build.sbt
See https://github.com/lampepfl/dotty/issues/9783#issuecomment-731718011.
> Use -scalajs-mapSourceURI in Scala 3 builds

- core/src/main/scala/cats/data/Tuple2K.scala
- tests/src/test/scala/cats/tests/Tuple2KSuite.scala
> Representable instance for Tuple2K

- core/src/main/scala/cats/data/NonEmptyMapImpl.scala
> Make deprecated catsDataInstancesForNonEmptyMap not implicit

- CONTRIBUTING.md
- build.sbt
- docs/src/main/mdoc/typeclasses/lawtesting.md
Use discipline-munit in documentation. Reduces our set of dependencies.
> drop ScalaTest in docs

- alleycats-core/src/main/scala/alleycats/std/set.scala
- alleycats-tests/shared/src/test/scala/alleycats/tests/SetSuite.scala
This allows the use of methods from [`Alternative`](https://typelevel.org/cats/typeclasses/alternative.html) on a `Set` - for instance, I want to be able to use `separate` on a `Set`:
```scala
import alleycats.std.set._
val stringsAndInts: Set[Either[String, Int]] = Set(Right(6),Left("Foo"))
val (strings: Set[String], ints: Set[Int]) = stringsAndInts.separate
```
The `Alternative` typeclass just requires `MonoidK` (already provided for `Set` in `cats-core`) & `Applicative` (already provided for `Set` by [`Monad`](https://typelevel.org/cats/typeclasses/monad.html) in [`alleycats`](https://github.com/typelevel/cats/tree/main/alleycats-core#set_-instances)), so adding it to `alleycats` is a small change.
Here's a diagram I drew mainly for myself (!), as a novice …
> Provide instance of `Alternative[Set]` in alleycats

- core/src/main/scala/cats/syntax/parallel.scala
Binary compatible version of #2180
Fixes #2254
> Remove redundant Monad constraints from Parallel syntax

- core/src/main/scala/cats/Applicative.scala
Cheat by creating an IndexedSeq that always returns the same element
* Before: List -> ArrayBuffer -> Chain -> List
* After: Chain -> List
> Save a few allocations in Applicative.replicateA

- core/src/main/scala/cats/Invariant.scala
- core/src/main/scala/cats/package.scala
- free/src/test/scala/cats/free/FreeApplicativeSuite.scala
- laws/src/main/scala/cats/laws/NonEmptyTraverseLaws.scala
- tests/src/test/scala-2.13+/cats/tests/ScalaVersionSpecific.scala
- tests/src/test/scala/cats/tests/IdSuite.scala
- tests/src/test/scala/cats/tests/MonadSuite.scala
- tests/src/test/scala/cats/tests/UnorderedTraverseSuite.scala
> Move Id instances into implicit scope for Scala 3

- core/src/main/scala/cats/Apply.scala
- core/src/main/scala/cats/syntax/apply.scala
So, a year and a half ago, [somebody thought](https://github.com/typelevel/cats/pull/2609) that having an `ifA` method, an _applicative_ counterpart of the `ifM` method from `FlatMap` (or M for Monad), would be a good idea. Turns out, having an "If-then-else" that actually performs  _both_ effects is hardly ever desirable, but the name naturally suggests it would not, so that was quite misleading. This has tripped some people. Thus the time has come to deprecate it, and retire it soon.
Resolves https://github.com/typelevel/cats/issues/3889
> Deprecate ifA.

- alleycats-core/src/main/scala/alleycats/ReferentialEq.scala
- alleycats-tests/shared/src/test/scala/alleycats/tests/ReferentialEqSuite.scala
- kernel/src/main/scala/cats/kernel/Eq.scala
This PR implements a helper `Eq.fromReferentialEquals[A]` to provide an instance of `Eq[A]` based on referential equality `eq`.
It is similar in spirit to `Eq.fromUniversalEquals[A]` and, as the [finest](https://en.wikipedia.org/wiki/Equivalence_relation#Comparing_equivalence_relations) possible equivalence relation, I believe makes it the dual of the coarsest `Eq.allEqual[A]`.
My use case is for fast equivalence comparisons in certain situations with nested case classes (where using universal equals could involve traversing the entire object hierarchy).
> Add `ReferentialEq[A]` to Alley Cats

- build.sbt
This is a minor thing but cleans up warnings in the console.
> Use new sbt syntax for fmt commands

- core/src/main/scala-2.12/cats/instances/all.scala
- core/src/main/scala-2.12/cats/instances/package.scala
- core/src/main/scala-2.13+/cats/instances/all.scala
- core/src/main/scala-2.13+/cats/instances/package.scala
- core/src/main/scala/cats/instances/deadline.scala
- kernel-laws/shared/src/test/scala/cats/kernel/laws/LawTests.scala
- kernel/src/main/scala-2.12/cats/kernel/instances/AllInstances.scala
- kernel/src/main/scala-2.13+/cats/kernel/instances/AllInstances.scala
- kernel/src/main/scala/cats/kernel/instances/DeadlineInstances.scala
- kernel/src/main/scala/cats/kernel/instances/all/package.scala
- kernel/src/main/scala/cats/kernel/instances/deadline/package.scala
- tests/src/test/scala/cats/tests/OrderSuite.scala
We wanted to have `min` and `max` on a `NonEmptyList`. That requires a `cats.Order[A]`.
For the standard library's `Deadline` no instances were defined. This adds it.
(I'm sure I need to touch some other places to make it available everywhere. Please tell me where. Thanks!)
> Add DeadlineInstances

- core/src/main/scala/cats/FlatMap.scala
We noticed that if not explicitly overridden to support lazy evaluation of the right argument, `map2Eval` can cause StackOverflowErrors for effect types.
Relevant Cats Effect issue.
https://github.com/typelevel/cats-effect/issues/2095
> Override `map2Eval` in `FlatMap`

- core/src/main/scala/cats/ApplicativeError.scala
I added these to IO previously, but was lazy and didn't add them to the
typeclass. Oops
Also, I ran the `sbt +prePR` step as instructed but it errored out.
<details>
<summary>+prePR errors</summary>
```
[info] Forcing Scala version to 3.0.1 on all projects.
[info] Reapplying settings...
[info] set current project to cats (in build file:/Users/gavin/Code/cats/)
[info] Formatting 2 Scala sources...
[info] Formatting 2 Scala sources...
[info] Formatting 2 Scala sources...
[info] Formatting 1 Scala sources...
[info] Formatting 1 Scala sources...
[info] Formatting 1 Scala sources...
[error] /Users/gavin/Code/cats/free/src/main/scala-3.x/cats/free/FreeFoldStep.scala:19: error: identifier expected but [ found
[error]     onFlatMapped: [X] => (S[X], X => Free[S, A]) => B
[error] …
```
> Add `raiseWhen` and `raiseUnless` helpers to ApplicativeError

- CONTRIBUTING.md
- core/src/main/scala/cats/Eval.scala
- core/src/main/scala/cats/data/Chain.scala
- core/src/main/scala/cats/data/Ior.scala
- core/src/main/scala/cats/data/Validated.scala
- core/src/main/scala/cats/instances/either.scala
- core/src/main/scala/cats/instances/map.scala
- core/src/main/scala/cats/instances/sortedMap.scala
- core/src/main/scala/cats/instances/try.scala
- core/src/main/scala/cats/syntax/either.scala
- free/src/main/scala/cats/free/FreeApplicative.scala
- kernel-laws/shared/src/main/scala/cats/kernel/laws/SerializableLaws.scala
- kernel/src/main/scala-2.13+/cats/kernel/compat/HashCompat.scala
- kernel/src/main/scala-2.13+/cats/kernel/instances/arraySeq/package.scala
- kernel/src/main/scala/cats/kernel/Comparison.scala
- kernel/src/main/scala/cats/kernel/instances/StaticMethods.scala
- kernel/src/main/scala/cats/kernel/instances/bigDecimal/package.scala
- kernel/src/main/scala/cats/kernel/instances/bigInt/package.scala
- kernel/src/main/scala/cats/kernel/instances/bitSet/package.scala
This fixes the contributing guide and rm ScalaStyle settings from the source code.
> Cleanup ScalaStyle things

- README.md
Some logos (ebiznext, Evolution Gaming) still won't show up since their logos are not placed in https://github.com/typelevel/typelevel.github.com/tree/development/img/media/sponsors.
> Update sponsor logos in README.md

- core/src/main/scala/cats/data/NonEmptySet.scala
Addresses #3957 
`+prePR` failed on my local machine for some reason complaining about code I was nowhere near, so I'm opening it as is for now and I'll fix whatever issues occur on CI if necessary
> Eq[NonEmptySet[A]] now needs Eq[A], not Order[A]

- build.sbt
Fixes #3690.  I'm just trying to put out a fire, and circling back with a more thoughtful approach from someone who understands jekyll would be good.
Concerns:
* I don't know why the source is in `docs` while the output is in `cats-docs`.
* There are a bunch more directory settings and I don't know what else is subtly broken.  I'm just taking care of the sponsors.
> Configure microsite image directory

- free/src/main/scala-2.12/cats/free/FreeStructuralInstances.scala
- free/src/main/scala-2.13+/cats/free/FreeStructuralInstances.scala
- free/src/main/scala/cats/free/Free.scala
- free/src/test/scala-2.13+/cats/free/FreeStructuralSuite.scala
Look ma, no documentation! Okay that's not *entirely* true, but it's close to true. Documentation coming.
So this probably looks a little odd if you're unfamiliar with recursion schemes. `Free` *is* a fixed point (similar to `Fix` or `Mu`), but we don't normally think of it that way. IMO `Free` is a lot more useful in this role than `Fix` is, and this `Eq` instance is one of the first steps in being able to unlock this power on top of vanilla Cats (rather than requiring something like Droste for even trivial cases).
Anyway, examples to come. There are some nice ones of how this can be leveraged in practice, I just haven't written them down yet.
Poke @Baccata since I promised you this a while back.
> Added implementation of Eq[Free]

- core/src/main/scala/cats/data/Kleisli.scala
- core/src/main/scala/cats/instances/list.scala
- core/src/main/scala/cats/instances/vector.scala
- core/src/main/scala/cats/package.scala
- laws/src/main/scala/cats/laws/TraverseLaws.scala
- tests/src/test/scala/cats/tests/KleisliSuite.scala
- tests/src/test/scala/cats/tests/TraverseSuite.scala
This fixes traverse_ for List and Vector to avoid stack overflow errors.
This is a partial fix for #3947
> Fix traverse_ for List and Vector to be stack safe.

- alleycats-core/src/main/scala/alleycats/std/map.scala
- alleycats-core/src/main/scala/alleycats/std/set.scala
- core/src/main/scala/cats/Composed.scala
- core/src/main/scala/cats/Foldable.scala
- core/src/main/scala/cats/data/NonEmptyList.scala
- core/src/main/scala/cats/data/NonEmptySeq.scala
- core/src/main/scala/cats/data/NonEmptySet.scala
- core/src/main/scala/cats/data/NonEmptyVector.scala
- core/src/main/scala/cats/instances/either.scala
- core/src/main/scala/cats/instances/list.scala
- core/src/main/scala/cats/instances/queue.scala
- core/src/main/scala/cats/instances/seq.scala
- core/src/main/scala/cats/instances/sortedMap.scala
- core/src/main/scala/cats/instances/sortedSet.scala
- core/src/main/scala/cats/instances/tuple.scala
- core/src/main/scala/cats/instances/vector.scala
Noticed this in #2363 
We have toIterable in Foldable, but most structures were not overriding it.
Here I do that, and also use it in preference to foldRight for some default implementations in Foldable since foldRight is fundamentally hard to optimize due to the reliance on `Eval[A]`. By contrast, many things can implement `toIterable` very cheaply and we can very safely use local mutability `(via .iterator)` to reduce trampolining via Eval.
> override toIterable more and use it

- README.md
- build.sbt
- docs/src/main/resources/microsite/img/missing-avatar.svg
- docs/src/main/resources/microsite/js/sponsors.js
Makes sponsors appear automatically on the site, at the expense of appearing in the README.
1. Call the Open Collective REST API to retrieve all the active sponsors
2. Merge with sponsors who donated through other means
3. Remove obsolete language about previous sponsorship levels
Issues:
* This makes the README a bit unsightly.  Help wanted.
* I don't think it will render in local jekyll without doing unspeakable things to disable CORS.
* I didn't implement pagination, if we get more sponsors.  Help wanted.
* This is more JavaScript than I've written in at least a decade.
Local rendering below:
> Render sponsors from Open Collective REST API

- build.sbt
- docs/src/main/resources/microsite/js/sponsors.js
This should close #3974 once and for all. It reverts my previous fix in #3977 and instead uses the latest and greatest OpenCollective GraphQL v2 API to get a live list of sponsors on page load. Turns out we don't need an API key to use it after all. Bonus points: fixes the missing avatar issue.
> Use OpenCollective GraphQL API to render sponsors

- build.sbt
- free/src/main/scala/cats/free/ContravariantCoyoneda.scala
- free/src/main/scala/cats/free/Coyoneda.scala
- free/src/main/scala/cats/free/InvariantCoyoneda.scala
- free/src/test/scala/cats/free/InvariantCoyonedaSuite.scala
This came up in https://github.com/typelevel/vault/pull/264, but @tpolecat's stack was about to overflow 😝
> Implement `InvariantCoyoneda`

- core/src/main/scala/cats/data/NonEmptyMapImpl.scala
- tests/src/test/scala/cats/tests/NonEmptyMapSuite.scala
Inspired by [this](https://discord.com/channels/632277896739946517/632278570512678923/875434472735146024) discussion.
Introduces a few new methods which make `NonEmptyMap` more convenient and useful:
- `leftMap`: maps over the keys rather than values (in contrast to `map` which maps over the values).
The name `leftMap` looks `Bifunctor`-ish although there's a required `Order` constraint added to the method.
- `fullMap`: maps over both keys and values. It behaves like a regular `Map.map` from Scala collections, but also includes the `Order` constraint. The name is controversial though, just the best one I managed to come up with. But I am totally open to change it to something better.
- `transform`: looks and behaves like `Map.transform`. Does not require any additional constraint.
Nothing …
> NonEmptyMap: add new methods

- algebra-core/src/main/scala/algebra/ring/CommutativeSemifield.scala
- algebra-core/src/main/scala/algebra/ring/DivisionRing.scala
- algebra-core/src/main/scala/algebra/ring/Field.scala
- algebra-core/src/main/scala/algebra/ring/Semifield.scala
- algebra-laws/shared/src/main/scala/algebra/laws/RingLaws.scala
Introduces a `Semifield` and `CommutativeSemifield` to algebra. I'm going by the [second definition on Wikipedia](https://en.wikipedia.org/wiki/Semifield):
* a commutative monoid for addition (+)
* a group for multiplication (*)
Thanks in advance!
> Add `Semifield` and `CommutativeSemifield` to algebra

- core/src/main/scala/cats/package.scala
- tests/src/test/scala/cats/tests/IdSuite.scala
I hope there isn't a reason for not doing this.
> Adding Id.apply

- docs/src/main/mdoc/typeclasses/arrow.md
> Typo fix: ',' instead of '=>'

- core/src/main/scala/cats/syntax/vector.scala
- tests/src/test/scala/cats/tests/ListSuite.scala
- tests/src/test/scala/cats/tests/VectorSuite.scala
Adds methods `groupByNev`, `groupByNevA`, `scanLeftNev` and `scanRightNev` to `VectorOps`,
which are similar to the methods found in `ListOps`.
The implementation is mostly copied from `ListOps` and adjusted accordingly.
Initial discussion is [here](https://discord.com/channels/632277896739946517/632278570512678923/857709871448588309).
> Add missing methods to VectorOps

- docs/src/main/mdoc/typeclasses/applicativemonaderror.md
Minor correction to an example in documentation for ApplicativeError. Fixes [issue 4045](https://github.com/typelevel/cats/issues/4045)
> 4045 Add missing else keyword to example

- core/src/main/scala-2.13+/cats/ScalaVersionSpecificInstances.scala
The deprecated messages were referring to incorrect methods.
> Incorrect deprecated messages

- .scalafmt.conf
- core/src/main/scala-3.x/src/main/scala/cats/syntax/MonadOps.scala
- free/src/main/scala-3.x/cats/free/FreeFoldStep.scala
Addresses #4027 and prepares for upgrading to ScalaFmt 3.1.x.
This also fixes `sbt +prePR` which was broken for Scala3-specific source files.
> Fix scalafmt config file

- .scalafmt.conf
- build.sbt
- tests/src/test/scala/cats/tests/ApplicativeErrorSuite.scala
- tests/src/test/scala/cats/tests/FunctorSuite.scala
- tests/src/test/scala/cats/tests/IndexedStateTSuite.scala
- tests/src/test/scala/cats/tests/NestedSuite.scala
- tests/src/test/scala/cats/tests/OptionTSuite.scala
- tests/src/test/scala/cats/tests/RepresentableStoreTSuite.scala
- tests/src/test/scala/cats/tests/Tuple2KSuite.scala
Discussion on why to do a manual upgrade: #4031
Things done in this PR:
1 . scalafmt version is set to 3.1.1 in `.scalafmt.conf`
2. `sbt +prePR` is applied.
> Upgrade scalafmt version to 3.1.1

- core/src/main/scala/cats/Alternative.scala
- core/src/main/scala/cats/Composed.scala
- core/src/main/scala/cats/Monad.scala
- core/src/main/scala/cats/NonEmptyAlternative.scala
- core/src/main/scala/cats/syntax/all.scala
- core/src/main/scala/cats/syntax/nonEmptyAlternative.scala
- core/src/main/scala/cats/syntax/package.scala
- laws/src/main/scala/cats/laws/AlternativeLaws.scala
- laws/src/main/scala/cats/laws/NonEmptyAlternativeLaws.scala
- laws/src/main/scala/cats/laws/discipline/AlternativeTests.scala
- laws/src/main/scala/cats/laws/discipline/NonEmptyAlternativeTests.scala
- laws/src/main/scala/cats/laws/discipline/SemigroupalTests.scala
- testkit/src/main/scala/cats/tests/ListWrapper.scala
- tests/src/test/scala/cats/tests/AlternativeSuite.scala
- tests/src/test/scala/cats/tests/NonEmptyAlternativeSuite.scala
- tests/src/test/scala/cats/tests/SyntaxSuite.scala
There's a pretty common pattern can be found for `Alternative` even in the Cats sources:
`F.combineK(F.pure(a), fa)` and `F.combineK(fa, F.pure(a))`
which basically means prepending or appending an element `a` lifted into `F[_]`.
But when it is used for some standard collections like `List` or `Vector` it basically results in creating an interim singleton collection on each `F.pure` which gets discarded right after `F.combineK` is completed.
The proposed PR allows to avoid creating the interim singleton collections by various `Alternative` implementations in many cases.
This PR does the following:
1. Introduces a new type class `NonEmptyAlternative` as a combination of `Applicative` and `SemigroupK`. 
2. Adds `prependK` and `appendK` methods to `NonEmptyAlternative`. These methods have …
> [proposal] optimize Alternative (part 1): introduce NonEmptyAlternative with prependK and appendK methods

- core/src/main/scala/cats/Alternative.scala
- core/src/main/scala/cats/syntax/alternative.scala
- tests/src/test/scala/cats/tests/AlternativeSuite.scala
- tests/src/test/scala/cats/tests/SyntaxSuite.scala
The initial discussion is [here](https://discord.com/channels/632277896739946517/632278570512678923/888660638073749514).
- The `unite` and `separate` methods don't need a `Monad` actually to do their job, because they only use `flatMap` in addition to methods from `Alternative`. Therefore the `FlatMap[F]` constraint is just enough there.
- Moreover, both `Alternative` and `Monad` implement `Applicative`. That means the `Applicative` methods can come by two different paths which creates sort of a loophole for ambiguity:
```scala
implicit val fooMonad: Monad[Foo] = ??? // assume Monad[Foo] is different from Alternative[Foo]
Alternative[Foo].unite[Bar, Int](Foo(Bar(123)) // which `pure` should it use – one from `Alternative` or `Monad` ? 
```
In fact, if it is okay to constraint the `unite` …
> Relax a constraint for Alternative's unite and separate methods from Monad to FlatMap

- alleycats-core/src/main/scala/alleycats/std/set.scala
- core/src/main/scala-2.12/cats/instances/stream.scala
- core/src/main/scala-2.13+/cats/instances/arraySeq.scala
- core/src/main/scala-2.13+/cats/instances/lazyList.scala
- core/src/main/scala-2.13+/cats/instances/stream.scala
- core/src/main/scala/cats/instances/list.scala
- core/src/main/scala/cats/instances/option.scala
- core/src/main/scala/cats/instances/queue.scala
- core/src/main/scala/cats/instances/seq.scala
- core/src/main/scala/cats/instances/vector.scala
See initial PR #4014 for details.
Subsequent PRs:
- add prependK/appendK specializations for cats.data collections.
- add prependK/appendK specializations for all other cats containers.
This PR adds optimized specializations for the new `prependK`/`appendK` methods introduced in the initial PR.
> Optimize Alternative (part 2): add prependK/appendK specializations for std containers

- core/src/main/scala/cats/Semigroupal.scala
- tests/src/test/scala/cats/tests/IdSuite.scala
I missed that in #3906
I think this is the only instance that is missing.
The rest is covered by `Invariant` and `UnorderedFoldable`.
> Add Semigroupal[Id] to implicit scope

- project/Boilerplate.scala
- tests/src/test/scala-2.13+/cats/tests/ScalaVersionSpecific.scala
- tests/src/test/scala/cats/tests/FoldableSuite.scala
We piggy-back on `toIterable`.
This is also an easy way to avoid stack overflow.
Fixes #4066
> More efficient slidingN functions

- core/src/main/scala/cats/data/IorT.scala
- tests/src/test/scala/cats/tests/IorTSuite.scala
- version.sbt
Bump version to 2.8.0-SNAPSHOT to account for new symbols.
> Add foldF To IorT

- .github/workflows/ci.yml
- build.sbt
It seems that the Jabba index is redundant now.
> Rm Jabba index

- README.md
Throwing this out there — I'm not sure what the best structure or wording is, exactly.
There seems to be a persistent misconception that you're supposed to have some kind of basic grounding in category theory in order to learn or use Cats; maybe this, or something like it, would help dispel that a little.
> cats and category theory in readme

- README.md
The SQL analysis module in our company's data analysis platform is refactored with Cats, which significantly improves the maintainability of the code!
> Add iofod to users

- kernel/src/main/scala/cats/kernel/instances/FunctionInstances.scala
- tests/src/test/scala/cats/tests/FunctionSuite.scala
Fixes #4089.
This adds `CombineFunction0` and `CombineFunction1` classes as suggested by @johnynek in [this comment](https://github.com/typelevel/cats/issues/4089#issuecomment-998166820) to call and combine the results of two functions in a stack-safe way. Two things to note:
- This won't magically make any function passed to `Semigroup#combine` stack-safe, it just ensures that the combined function itself won't be the cause of a `StackOverflowError`
- I haven't added anything special to address the other idea of tracking call depth. If others feel this is important, I can look into doing so but may need some guidance
> Lastly, you could track the depth of CombineFn when you are building it so you do the expensive apply when the depth gets greater than something like 500 or something, and …
> Return stack-safe `Function0` and `Function1` from `Semigroup#combine`

- .scalafmt.conf
- core/src/main/scala/cats/instances/try.scala
After #4097 has been closed, Scala Steward is not going to resume updating `scalafmt-core` until we restart it manually.
Therefore this PR restarts these updates.
Note: there's `scalafmt-core` v3.3.1 available already and I tried to jump to that version directly, but seems that the most recent version introduces even more weird formatting changes which need to be discussed separately.
> Update scalafmt-core to 3.3.0

- core/src/main/scala/cats/data/EitherT.scala
- tests/src/test/scala/cats/tests/EitherTSuite.scala
Similar to `toEither` on `IorT`.
> Add toIorT On EitherT

- docs/src/main/mdoc/typeclasses/arrowchoice.md
The `choice` function in the `Choice` typeclass documentation has an unused/unnecessary type parameter `D`.
> Remove unused type parameter in Choice typeclass doc

- build.sbt
This is necessary so that Cats can be updated in the Scala 3 community build.
See https://github.com/lampepfl/dotty/pull/14071#issuecomment-988528745. **tl;dr** `isDotty` conflicts with a setting of the same name injected by the community build plugin.
> Rename `isDotty` -> `isScala3`

- project/Boilerplate.scala
> Clean up `GenTupleParallelSyntax`

- core/src/main/scala/cats/syntax/functor.scala
- tests/src/test/scala/cats/tests/SyntaxSuite.scala
Resolving #4144 
This is my first contribution, sorry if it's missing anything.
I am also not sure if this is "the correct way" to add this functionality to Functor. 
It seemed clean, but on the other hand - I have copied docs for the function, is that ok?
> added ifF to Functor

- core/src/main/scala/cats/Reducible.scala
added few doctests to reducible, 
its my first pr, im open to comments and suggestions
> more doctests to Reducible

- tests/src/test/scala-2.12/cats/tests/ScalaVersionSpecific.scala
- tests/src/test/scala-2.13+/cats/tests/FoldableLazyListSuite.scala
- tests/src/test/scala-2.13+/cats/tests/ScalaVersionSpecific.scala
- tests/src/test/scala/cats/tests/ChainSuite.scala
- tests/src/test/scala/cats/tests/FoldableSuite.scala
- tests/src/test/scala/cats/tests/IndexedStateTSuite.scala
- tests/src/test/scala/cats/tests/KleisliSuite.scala
- tests/src/test/scala/cats/tests/ParallelSuite.scala
- tests/src/test/scala/cats/tests/ReducibleSuite.scala
- tests/src/test/scala/cats/tests/RegressionSuite.scala
- tests/src/test/scala/cats/tests/StreamSuite.scala
- tests/src/test/scala/cats/tests/TraverseFilterSuite.scala
- tests/src/test/scala/cats/tests/TraverseSuite.scala
This is an attempt to improve code hygiene a bit by reducing amount of warnings while compiling the `testsJVM`, `testsJS` and `testsNative` modules.
No tests are removed nor disabled, no other changes besides the `tests*` modules. But some tests were tossed over different suites or suite mixins.
Caveat: because `@nowarn` annotation is not supported in Scala 3.0.x, for this cross-build configuration most of the warnings will still remain. But things should get improved once the project upgrades to Scala 3.1.x.
Note: also in all changed files the "Organize Imports" (vs-code+metals) command was applied.
> Reduce compilation warnings in `tests`

- core/src/main/scala/cats/data/Chain.scala
- tests/src/test/scala/cats/tests/ChainSuite.scala
Adds quite useful `knownSize`, `lengthCompare` (and `sizeCompare` as an alias) which can be found in Scala Library.
> Add Chain#knownSize and Chain#lengthCompare (sizeCompare) methods

- core/src/main/scala/cats/data/Chain.scala
- tests/shared/src/test/scala-2.12/cats/tests/compat/ScalaVersionSpecificSyntax.scala
- tests/shared/src/test/scala-2.12/cats/tests/compat/SeqOps.scala
- tests/shared/src/test/scala-2.13+/cats/tests/compat/ScalaVersionSpecificSyntax.scala
- tests/shared/src/test/scala/cats/tests/ChainSuite.scala
- tests/shared/src/test/scala/cats/tests/package.scala
Core:
* Adds the missing `Chain#distinctBy` method.
* Slightly optimizes its implementation (replaces two accesses to `TreeSet` via `contains` followed by `+=` with just one access via `add`).
Tests:
* Introduces `trait cats.tests.compat.ScalaVersionSpecificSyntax` that implements an extension method `distinctBy` for any `Seq`-derived collection in Scala 2.12 (and does nothing for other Scala versions).
* Adds a test for `Chain#distinctBy` to `ChainSuite`.
> Add missing Chain#distinctBy method

- core/src/main/scala/cats/Invariant.scala
I initially kept this public, because usually static forwarders go away when a method is package-private, and we need them for complete binary-compatibility. However, I learned in https://github.com/lampepfl/dotty/issues/10842 that this is not the case on Scala 3. So, there is no reason to leak this method in the public API.
> Make `catsInstancesForIdCompat2_6_1` package-private

- COPYING
- core/src/main/scala/cats/data/Chain.scala
- kernel/src/main/scala-2.12/cats/kernel/compat/HashCompat.scala
- kernel/src/main/scala-2.13+/cats/kernel/compat/HashCompat.scala
- kernel/src/main/scala/cats/kernel/instances/MapInstances.scala
- kernel/src/main/scala/cats/kernel/instances/SortedMapInstances.scala
- kernel/src/main/scala/cats/kernel/instances/SortedSetInstances.scala
- kernel/src/main/scala/cats/kernel/instances/StaticMethods.scala
- tests/shared/src/test/scala-2.12/cats/tests/compat/SeqOps.scala
Fixes #4189 by adding the Scala license to the COPYING file, and adding the suggested copyright notice to code adapted from the standard library.
Contributed on behalf of the @opencastsoftware open source team. 👋
> Add copyright notices and Scala license for code derived from the standard library

- .scala-steward.conf
Ross [has suggested](https://github.com/typelevel/cats/pull/4194#issuecomment-1107987610) removing part of benchmarks that depends on fs2. Until that cleanup, we could just ignore updates.
> Add Scala Steward conf

- core/src/main/scala/cats/syntax/applicative.scala
- tests/shared/src/test/scala/cats/tests/ApplicativeSuite.scala
Fixes https://github.com/typelevel/cats/issues/3687, supersedes https://github.com/typelevel/cats/pull/3899.
These changes are based on https://github.com/typelevel/cats/pull/3899 but binary and source compatible without introducing any new methods.
Note that `replicateA` also becomes by-name in these changes. This is unnecessary and possibly a minor de-optimization, but I don't see any way around it. Note that the usual package-private tricks don't work well with syntax e.g. see https://github.com/scala/bug/issues/12578.
Edit: although, I suppose there's an argument that `replicateA` should be made by-name on the typeclass itself for when `n = 0`, but that's another can of worms :)
> Make `whenA`/`unlessA` syntax by-name lazy

- core/src/main/scala/cats/syntax/applicative.scala
The current implementation of the `.whenA`/`.unlessA` syntax extensions doesn't respect `F[A]` being passed as call-by-name.
This leads to issues where it's important.
See: https://github.com/typelevel/fs2/pull/2412
Unfortunately we can't change whenA/unlessA directly due to bincompat guarantees.
But the new method names even better reflect that we throw `A` out (as in `traverse_`). I would also deprecate the old ones.
Closes #3687
> Applicative whenA/unlessA syntax extensions should respect call-by-name parameter

- core/src/main/scala/cats/data/EitherT.scala
- core/src/main/scala/cats/data/IorT.scala
- core/src/main/scala/cats/data/OptionT.scala
- tests/shared/src/test/scala/cats/tests/EitherTSuite.scala
- tests/shared/src/test/scala/cats/tests/IorTSuite.scala
- tests/shared/src/test/scala/cats/tests/OptionTSuite.scala
I've recently opened and merged a PR for mouse adding `getOrRaise` method to `F[Option[A]]` and `F[Either[A, B]]`. 
https://github.com/typelevel/mouse/pull/323
Since I found this method useful I'd like to introduce it to `OptionT`, `EitherT` and `IorT`. 
What do you think ? 
--- 
P.S. For mouse, I've added `getOrRaiseMsg` as well which accepts a `String` and lifts it to `RuntimeException`.
Honestly, I've always missed this feature in cats since in 99% of the cases I've seen this: 
```scala
IO.raiseError(new RuntimeException("ERROR"))
``` 
It would be great to have either 
- `raiseErrorMsg` which accepts a string
- An overload of `raiseError` which accepts a string
- A string interpolator to lift a string to an `Exception` like `val ex: RuntimeException = ex"ERROR"` in order to keep all …
> Add getOrRaise for OptionT, EitherT and IorT

- core/src/main/scala/cats/Composed.scala
- core/src/main/scala/cats/Traverse.scala
- core/src/main/scala/cats/data/Chain.scala
- core/src/main/scala/cats/data/Nested.scala
- core/src/main/scala/cats/data/NonEmptyChain.scala
- core/src/main/scala/cats/data/NonEmptyList.scala
- core/src/main/scala/cats/data/NonEmptySeq.scala
- core/src/main/scala/cats/data/NonEmptyVector.scala
- core/src/main/scala/cats/instances/StaticMethods.scala
- core/src/main/scala/cats/instances/list.scala
- core/src/main/scala/cats/instances/queue.scala
- core/src/main/scala/cats/instances/seq.scala
- core/src/main/scala/cats/instances/vector.scala
- laws/src/main/scala/cats/laws/TraverseLaws.scala
- laws/src/main/scala/cats/laws/discipline/TraverseTests.scala
- tests/shared/src/test/scala/cats/tests/TraverseSuite.scala
> Add mapAccumulate to Traverse

- README.md
URLs at https://github.com/typelevel/cats return 404
> Fix broken URLs in README.md

- alleycats-core/src/main/scala/alleycats/std/iterable.scala
- alleycats-core/src/main/scala/alleycats/std/map.scala
- alleycats-core/src/main/scala/alleycats/std/set.scala
- core/src/main/scala-2.13+/cats/data/NonEmptyLazyList.scala
- core/src/main/scala-2.13+/cats/instances/arraySeq.scala
- core/src/main/scala/cats/data/Const.scala
- core/src/main/scala/cats/data/EitherT.scala
- core/src/main/scala/cats/data/IdT.scala
- core/src/main/scala/cats/data/Ior.scala
- core/src/main/scala/cats/data/OneAnd.scala
- core/src/main/scala/cats/data/OptionT.scala
- core/src/main/scala/cats/data/Validated.scala
- core/src/main/scala/cats/instances/either.scala
- core/src/main/scala/cats/instances/option.scala
- core/src/main/scala/cats/instances/sortedMap.scala
- core/src/main/scala/cats/instances/try.scala
- core/src/main/scala/cats/instances/tuple.scala
- core/src/main/scala/cats/package.scala
follow up to #4209 to override I think all the remaining values for mapAccumulate.
Also did a few minor changes I noticed along the way.
> override more mapAccumulate methods in Traverse

- core/src/main/scala/cats/data/NonEmptyChain.scala
- core/src/main/scala/cats/data/NonEmptyMapImpl.scala
- core/src/main/scala/cats/data/NonEmptySet.scala
The motivation for this PR is discussed here: https://github.com/typelevel/cats/pull/4187#discussion_r851928327
> Expose newtype objects to Mima

- core/src/main/scala/cats/Applicative.scala
follow up to #4208
This implements replicateA in the same was as replicateA_. The benefit over using traverse, which was the previous implementation, is that traverse ignores that all the items in the sequence are identical. This implementation leverages that to get `O(log n)` calls to `map2` instead of `O(n)` calls to `map2`.
Note, it is still an `O(n)` method in the worst case since finally we have to materialize the `List[A]` which is length `n`, but often it is the `map2` calls that are expensive, not iterating the list.
> Optimize replicateA to have same recursive structure as replicateA_

- core/src/main/scala-2.12/cats/instances/package.scala
- core/src/main/scala-2.13+/cats/instances/package.scala
- core/src/main/scala/cats/Invariant.scala
- core/src/main/scala/cats/Semigroupal.scala
- core/src/main/scala/cats/instances/future.scala
- kernel/src/main/scala/cats/kernel/Semigroup.scala
Closes https://github.com/typelevel/cats/issues/4190.
This PR executes a **soft deprecation** of `Future` instances in Cats. The [`@deprecated` annotation](https://www.scala-lang.org/api/2.13.8/scala/deprecated.html) is _not_ used. Instead, a [`@deprecated` tag](https://docs.scala-lang.org/overviews/scaladoc/for-library-authors.html#other-tags) is used in the Scaladoc comment. This only affects rendering of API docs.
**The compiler does not read Scaladoc comments, and therefore this cannot "junk" anyone's build.** This addresses the concern from https://github.com/typelevel/cats/pull/4182#issuecomment-1099647958.
Odds are, nobody will ever see these, because these are implicit instances that don't need to be imported or directly referenced in modern Cats. But it's better than nothing. I …
> Recommend Cats Effect `IO` as a replacement for every use case of `Future`

- core/src/main/scala/cats/Defer.scala
What we want is to evaluate `fn` and pass the recursive value lazily in case `fn` doesn't need to evaluate it ie `fn(defer(res))`.
`defer(fn(res))` also works but it suspends the initial `fn` invocation, which is pointless as we must always evaluate `fn` at least once to produce a result
> Change the ordering of invocations in `Defer#fix`

- docs/datatypes/freemonad.md
`Type Mismatch Error` occurred `impureCompiler` and `pureCompiler` in scalaVersion 3.1.3
```scala
kvs.get(key).map(_.asInstanceOf[A])
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Found:    Option[A]
Required: cats.Id[A]
State.inspect(_.get(key).map(_.asInstanceOf[A]))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Found:    Option[A]
Required: A
```
> Documentation: update freemonad.md

- docs/datatypes/either.md
> Mention `asRight` and `asLeft` for constructing Either values

- docs/datatypes/freemonad.md
I think the program don't crash when key is not found, because `kvs.get(key)` returns `Option`.
> Fix comment in Free Monad example

- core/src/main/scala/cats/Traverse.scala
- core/src/main/scala/cats/data/Chain.scala
- core/src/main/scala/cats/data/NonEmptyChain.scala
- core/src/main/scala/cats/data/NonEmptyList.scala
- core/src/main/scala/cats/data/NonEmptyVector.scala
- core/src/main/scala/cats/instances/StaticMethods.scala
- core/src/main/scala/cats/instances/list.scala
- core/src/main/scala/cats/instances/queue.scala
- core/src/main/scala/cats/instances/vector.scala
- laws/src/main/scala/cats/laws/TraverseLaws.scala
- tests/shared/src/test/scala/cats/tests/TraverseSuite.scala
> Added `updated` to `Traverse`

- core/src/main/scala/cats/Traverse.scala
- core/src/main/scala/cats/data/Chain.scala
- core/src/main/scala/cats/data/NonEmptyChain.scala
- core/src/main/scala/cats/data/NonEmptyList.scala
- core/src/main/scala/cats/data/NonEmptyVector.scala
- core/src/main/scala/cats/instances/StaticMethods.scala
- core/src/main/scala/cats/instances/list.scala
- core/src/main/scala/cats/instances/queue.scala
- core/src/main/scala/cats/instances/vector.scala
- laws/src/main/scala/cats/laws/TraverseLaws.scala
- tests/shared/src/test/scala/cats/tests/TraverseSuite.scala
> Added `zipWithLongIndex`, `mapWithLongIndex` and `traverseWithLongIndexM`

- docs/datatypes/validated.md
- docs/typeclasses/parallel.md
> Add proof of inconsistency for a `Validated` Monad

- docs/typeclasses/applicative.md
In my experiences working with Cats users, awareness of `tupled` and `parTupled` is not high, considering how fundamental and useful these operations are. Attempt to raise the exposure plus a bit of relevant cross-linking in the docs.
> Mention `tupled` syntax, a Cats workhorse that deserves to be more well known

- docs/typeclasses/applicativemonaderror.md
So the code is properly highlighted.
https://typelevel.org/cats/typeclasses/applicativemonaderror.html#typeclass-definition-1
> Add missing `scala` modifier to code block

- core/src/main/scala/cats/data/NonEmptyCollection.scala
- core/src/main/scala/cats/data/NonEmptyList.scala
- core/src/main/scala/cats/data/NonEmptySeq.scala
- core/src/main/scala/cats/data/NonEmptyVector.scala
- tests/shared/src/test/scala/cats/tests/NonEmptyCollectionSuite.scala
This work was initially done on PR #4193 to support the `cats.data.HashMap` implementation, but now that that PR is being retargeted onto cats-collections I'd like to make sure this change isn't lost.
> Add `collectFirst` to the `NonEmptyCollection` interface

- core/src/main/scala/cats/ApplicativeError.scala
- core/src/main/scala/cats/data/Validated.scala
- core/src/main/scala/cats/instances/try.scala
- core/src/main/scala/cats/syntax/either.scala
- kernel-laws/shared/src/main/scala/cats/kernel/laws/SerializableLaws.scala
Allows to skip an allocation of Option. It is a tiny micro-optimization, but since it not make code more complicated and less readable, why not ?)
> Avoid using `NonFatal.unapply`

- laws/src/main/scala/cats/laws/discipline/TraverseTests.scala
Added laws tests for methods added in #4248 and #4245. @armanbilge can you take a look?
> Added discipline tests for the new `Traverse` laws

- core/src/main/scala/cats/TraverseFilter.scala
- core/src/main/scala/cats/syntax/traverseFilter.scala
- laws/src/main/scala/cats/laws/TraverseFilterLaws.scala
- laws/src/main/scala/cats/laws/discipline/TraverseFilterTests.scala
- tests/shared/src/test/scala/cats/tests/SyntaxSuite.scala
> Add `traverseCollect` to `TraverseFilter` typeclass

- core/src/main/scala/cats/data/NonEmptyList.scala
- core/src/main/scala/cats/data/NonEmptySeq.scala
- core/src/main/scala/cats/data/NonEmptyVector.scala
- tests/shared/src/test/scala/cats/tests/NonEmptyListSuite.scala
- tests/shared/src/test/scala/cats/tests/NonEmptySeqSuite.scala
- tests/shared/src/test/scala/cats/tests/NonEmptyVectorSuite.scala
- tests/shared/src/test/scala/cats/tests/NonEmtpySeqSuite.scala
- tests/shared/src/test/scala/cats/tests/SeqSuite.scala
`NonEmptyList` was missing a `prependAll`/`++:`. This adds the method and the alias and tests. The implementation may not be most efficient.
I also added an override for `concat` to append an `Option` to a `NonEmptyList`. I would have used `IterableOnce` as in the standard library for Scala 2.13 with `Seq`. But I didn't know how to do that cross-version with Scala 2.12 and `TraversableOnce`. Maybe I could use `Foldable`? Any help appreciated.
> Add `NonEmptyList#prependAll`

- docs/datatypes/statet.md
- docs/typeclasses/arrow.md
This PR adds the needed blank newline before lists in the markdown of our docs.
At time of writing the list formatting is currently broken in [Arrow](https://typelevel.org/cats/typeclasses/arrow.html) and [StateT](https://typelevel.org/cats/datatypes/statet.html) docs:
After this the list formatting should take effect and look like this:
> Fix list formatting in docs / site

- core/src/main/scala/cats/data/EitherT.scala
- tests/shared/src/test/scala/cats/tests/EitherTSuite.scala
Mostly a ergonomics style PR 😄 
I did notice some chatter around not wrapping/unwrapping so much because this method could be reduced to chaining `semiflatTap ` + `leftSemiflatTap`. Doesn't make too much of a difference to me either way if you guys want me to change it to chaining. 
Fixes https://github.com/typelevel/cats/issues/4292
> Add `EitherT#biSemiflatTap` which combines `leftSemiflatTap` and `semiflatTap`

- core/src/main/scala-2.13+/cats/data/NonEmptyLazyList.scala
- core/src/main/scala/cats/data/AbstractNonEmptyInstances.scala
- core/src/main/scala/cats/data/NonEmptyChain.scala
- core/src/main/scala/cats/data/NonEmptyList.scala
- core/src/main/scala/cats/data/NonEmptySeq.scala
- core/src/main/scala/cats/data/NonEmptyVector.scala
- core/src/main/scala/cats/data/OneAnd.scala
- tests/shared/src/test/scala-2.13+/cats/tests/NonEmptyLazyListSuite.scala
- tests/shared/src/test/scala/cats/tests/NonEmptyChainSuite.scala
- tests/shared/src/test/scala/cats/tests/NonEmptyListSuite.scala
- tests/shared/src/test/scala/cats/tests/NonEmptySeqSuite.scala
- tests/shared/src/test/scala/cats/tests/NonEmptyVectorSuite.scala
Adds optimized specializations for the new `prependK`/`appendK` methods introduced in the initial PR (#4014).
Previous PR:
- add specializations for `NonEmptyAlternative` instances for Scala library collections #4052.
Subsequent PR:
- add specializations for Cats monad transformers.
> Optimize `Alternative` (part 3): add `prependK`/`appendK` specializations for Cats NE wrappers

- project/Boilerplate.scala
- tests/shared/src/test/scala/cats/tests/ParallelSuite.scala
- tests/shared/src/test/scala/cats/tests/SyntaxSuite.scala
Hello 👋!
Taking inspiration from https://github.com/typelevel/cats/pull/4009 I added `flatParMapN` generation in `Boilerplate`. Let me know if it works for you or if something needs to be changed.
> Added `parFlatMapN`

- core/src/main/scala/cats/data/Chain.scala
- kernel/src/main/scala-2.13+/cats/kernel/instances/LazyListInstances.scala
- kernel/src/main/scala/cats/kernel/instances/ListInstances.scala
- kernel/src/main/scala/cats/kernel/instances/QueueInstances.scala
- kernel/src/main/scala/cats/kernel/instances/SeqInstances.scala
- kernel/src/main/scala/cats/kernel/instances/VectorInstances.scala
Prompted by https://github.com/http4s/http4s/pull/6712, which locally caches a particular Monoid[List[*]] instance - the issue is a generic one so it seems better to apply this optimisation here.
There are other cases where this kind of change could be made too but I wanted to get feedback before doing any more work on it.
Carries on the work done in https://github.com/typelevel/cats/pull/4309. Many thanks to @bplommer for doing most of the work!
> Singleton monoid instances

- core/src/main/scala/cats/data/Chain.scala
- kernel/src/main/scala-2.13+/cats/kernel/instances/LazyListInstances.scala
- kernel/src/main/scala/cats/kernel/instances/ListInstances.scala
- kernel/src/main/scala/cats/kernel/instances/QueueInstances.scala
- kernel/src/main/scala/cats/kernel/instances/SeqInstances.scala
- kernel/src/main/scala/cats/kernel/instances/VectorInstances.scala
Prompted by https://github.com/http4s/http4s/pull/6712, which locally caches a particular `Monoid[List[*]]` instance - the issue is a generic one so it seems better to apply this optimisation here.
There are other cases where this kind of change could be made too but I wanted to get feedback before doing any more work on it.
> Avoid allocations for `Monoid` instances where possible

- laws/src/main/scala/cats/laws/discipline/arbitrary.scala
It seems we don't need to require an `Order` instance for `Cogen` of `SortedMap` and `NonEmptyMap`. We only need it for the keys
Fixes https://github.com/typelevel/cats/issues/4295
> Don't require `Order` for the value on `Cogen` for `SortedMap` and `NonEmptyMap`

- core/src/main/scala-3/src/main/scala/cats/compat/package.scala
- mima.sbt
Hello! This should address #4304 in a bincompat way. Thanks to @bishabosha for the suggestion in https://github.com/typelevel/cats/issues/4304#issuecomment-1266562018
It was tested publishing the dep locally using the same scala-cli script mentioned in the issue
```scala
//> using scala "2.13.8"
//> using option "-Ytasty-reader"
//> using lib "org.typelevel:cats-core_3:2.8.0"
import cats.syntax.all._
object Main extends App {
}
```
> Recreated compat as a package object in scala_3 to make the artifact usable from scala 2

- core/src/main/scala/cats/data/Kleisli.scala
- core/src/main/scala/cats/package.scala
- tests/shared/src/test/scala/cats/tests/IdSuite.scala
- tests/shared/src/test/scala/cats/tests/KleisliSuite.scala
This PR adds Align instances for Kleisli and Id.
I realized these two were not available while trying some code like (simplified):
```scala
type Env = Map[String, String]
type FromEnvPrefixed[A] = Reader[Env, A]
def prefixed(prefix: String): Reader[Env, Map[String, String]] = {
Reader { (env: Env) => 
env.filter(_._1.startsWith(prefix)).foldLeft(Map.empty[String, String]) { case (acc, (k, v)) =>
val tKey = k.replace(prefix, "")
acc + (tKey, v)
}
}
}
val inConfig = prefixed("label").align(prefixed("label2")).value.run(Map("labelprop1" -> "prop1", "label2prop1" -> "prop1", "labelprop2" -> "prop2")
inConfig.toList.traverse {
case (k, Ior.Both(one, two)) => Right(k -> (one, two)) //Yeah!!
case (k, _) => Left(s"Missing property for key '$k'") //Missing for one of the prefixes
}
```
Looking at …
> Added `Align` instances for `Id` and `Kleisli`

- docs/datatypes/optiont.md
It works, but wrong.
Thank you :)
> Fix markdown syntax for link to `Applicative` in `OptionT`

- core/src/main/scala/cats/TraverseFilter.scala
- free/src/test/scala-2.13+/cats/free/FreeStructuralSuite.scala
- kernel-laws/shared/src/main/scala/cats/kernel/laws/HashLaws.scala
- kernel-laws/shared/src/main/scala/cats/kernel/laws/discipline/HashTests.scala
- tests/shared/src/test/scala/cats/tests/FunctionSuite.scala
And also `sameAsScalaHashing`, based on this comment:
https://github.com/typelevel/cats/blob/f47123e338cf79304240b070528074e5611d1bd5/kernel/src/main/scala/cats/kernel/Hash.scala#L40-L41
Closes https://github.com/typelevel/cats/issues/4284.
I think there may be a couple other places we are relying on this behavior in Cats (@satorg do you remember?). We should make sure to quash those.
> Deprecate `HashLaws#sameAsUniversalHash`

- algebra-laws/shared/src/main/scala/algebra/laws/Rules.scala
- core/src/main/scala-2.13+/cats/instances/lazyList.scala
- core/src/main/scala-2.13+/cats/instances/stream.scala
- core/src/main/scala-2/src/main/scala/cats/arrow/FunctionKMacros.scala
- core/src/main/scala/cats/data/EitherT.scala
- core/src/main/scala/cats/data/Func.scala
- core/src/main/scala/cats/data/IndexedReaderWriterStateT.scala
- core/src/main/scala/cats/data/IndexedStateT.scala
- core/src/main/scala/cats/data/Ior.scala
- core/src/main/scala/cats/data/Validated.scala
- core/src/main/scala/cats/instances/either.scala
- core/src/main/scala/cats/instances/list.scala
- core/src/main/scala/cats/instances/map.scala
- core/src/main/scala/cats/instances/queue.scala
- core/src/main/scala/cats/instances/seq.scala
- core/src/main/scala/cats/instances/sortedMap.scala
- core/src/main/scala/cats/instances/vector.scala
- kernel-laws/shared/src/main/scala/cats/kernel/laws/SerializableLaws.scala
- laws/src/main/scala/cats/laws/ApplicativeErrorLaws.scala
- laws/src/main/scala/cats/laws/DeferLaws.scala
- laws/src/main/scala/cats/laws/ShortCircuitingLaws.scala
Although it was decided to postpone Cats codebase cleanup for a while until the Scalac options set gets settled completely, some compiler warnings are so obvious and easy-to-fix that I couldn't refrain from fixing them up. Apparently, it is not a complete solution but rather some small relief.
Can be considered as a prelude for #4187 series.
UPD. Turned out, there are also quite a bit of small code optimizations included.
> Fix obvious and straightforward warnings

- core/src/main/scala/cats/data/NonEmptySeq.scala
String building from `Iterator` is about 5% more efficient than from `Seq`. [Benchmarked](https://github.com/http4s/http4s/pull/6766) on 2.13, it should be the same on 2.12, I suppose.
> Make string building a bit more efficient for `NonEmptySeq`

- core/src/main/scala/cats/ApplicativeError.scala
- core/src/main/scala/cats/syntax/applicativeError.scala
- laws/src/main/scala/cats/laws/ApplicativeErrorLaws.scala
- laws/src/main/scala/cats/laws/discipline/ApplicativeErrorTests.scala
- laws/src/main/scala/cats/laws/discipline/ApplicativeTests.scala
- tests/shared/src/test/scala/cats/tests/SyntaxSuite.scala
Fixes https://github.com/typelevel/cats-effect/issues/3152.
> Add `ApplicativeError#voidError`

- tests/shared/src/test/scala/cats/tests/ContTSuite.scala
Issue #2950 has a test that, as of its writing, blows up with a stack safety bug. Sometime in the subsequent 3 years, it must have been fixed. This PR adds the test.
cc @johnynek 
Closes #2950.
> Add stack-safety test for `ContT#map`

- core/src/main/scala/cats/data/OptionT.scala
> Add more DocTests for `OptionT`

- bench/src/main/scala/cats/bench/MapMonoidBench.scala
- build.sbt
It's been 6+ years since these benchmarks were added. They are seemingly outdated nowadays. More context https://github.com/typelevel/cats/pull/4354#pullrequestreview-1203676071.
Closes https://github.com/typelevel/cats/pull/4354.
> Clean up benchmarks' dependencies

- core/src/main/scala/cats/UnorderedFoldable.scala
Hi, first (try)pr here. Trying to solve the bug at [issue #4370](https://github.com/typelevel/cats/issues/4370).
I followed the idea to de-prioritize the Seq instance. Though it solves the issue mentioned, it prompts some other warnings at compilation time (I'm not sure it's specific to this change). 
As told in the issue, I'll be reading a bit if there is another way around it, unless the solution is considered good enough.
Any ideas or directions are welcome.
> Move `catsTraverseForSeq` to lower-priority implicit scope

- core/src/main/scala/cats/Bifunctor.scala
- tests/shared/src/test/scala/cats/tests/BifunctorSuite.scala
Motivated by the desire to `leftMap` on a tuple inside an effect, e.g.
```scala
val fab: F[(A, B)] = ???
val f: A => C = ???
Bifunctor[λ[(A, B) => F[(A, B)]]].leftMap(fab)(f) // returns F[(C, B)]
```
If folks aren't comfortable adding this kind of instance, it'd be pretty easy to implement this via a new wrapper class, similar to `Binested`. AFAICT `Bifunctor[λ[(A, B) => F[G[A, B]]]]` is lawful, but it doesn't infer very well—I don't think you can summon it using the syntax enhancements (e.g. `Option("a" -> "b").leftMap(_.length)` doesn't work, but `Bifunctor[λ[(A, B) => Option[(A, B)]]].leftMap(Option("a" -> "b"))(_.length)` should). Or, we could add both this instance and a new wrapper class.
Just for clarity, [cats already has …
> add Bifunctor[λ[(A, B) => F[G[A, B]]]] instance for F[_]: Functor and G[_, _]: Bifunctor

- core/src/main/scala/cats/data/OptionT.scala
- docs/nomenclature.md
- tests/shared/src/test/scala/cats/tests/OptionTSuite.scala
- `OptionT[F, A].filterF(p: A => F[Boolean])` to filter on effectful F[Boolean]
- `OptionT.whenM[F[_], A](fp: F[Boolean])(a: => F[A])` to construct based on effectful F[Boolean]
> Add `OptionT` combinators for effectful Boolean

- README.md
fixes #4395 
Updated these empty hrefs to point to the section in the page. I can see what the javascript should be doing, but doesn't work in Github -- I presume it's used elsewhere so I've left it
> Update no script links in readme

- CONTRIBUTING.md
Update information on the microsite generation and pinned the blob to the latest release to avoid confusion if the site job gets moved around or changed.
> Update CONTRIBUTING.md microsite information

- build.sbt
- docs/datatypes/chain.md
- docs/datatypes/ior.md
This PR updates the Chain documentation to include links to API docs & other sections of the local site, as part of #2862 
* adds Laika configuration to build.sbt to use its API link feature
* adds an mdoc variable to point to the API doc base URL. This is a workaround, because Laika can't link to `NonEmptyChain`, which is an alias for `NonEmptyChainImpl`.
* Updates the Chain documentation to include links to other documentation pages & to API pages. References to types in the cats documentation are updated to point to those pages. References to undocumented types & scala base library types point to the API docs instead. The first reference to Chain & NonEmptyChain point to their API documentation.
* Adds some headers to the Ior page to enable linking to its section about NonEmptyChain
* …
> Improve `Chain` Documentation

- docs/algebra.md
Just a small fix the link in algebra docs
> Fix outdated edit link in algebra docs

- core/src/main/scala/cats/data/NonEmptySeq.scala
- tests/shared/src/test/scala/cats/tests/NonEmptySeqSuite.scala
Currently, there is a zip method defined on _NonEmptyList_ (apparently added by a colleague of mine), but none defined for _NonEmptySeq_. So this adds _NonEmptySeq.zip_ too 😸 .
> add `zip` for `NonEmptySeq`

- core/src/main/scala/cats/Bifunctor.scala
- core/src/main/scala/cats/Composed.scala
- core/src/main/scala/cats/Functor.scala
- tests/shared/src/test/scala/cats/tests/BifunctorSuite.scala
This PR proposes a different encoding of https://github.com/typelevel/cats/pull/4362 (note, which is not yet released). /cc @bpholt
Specifically, Cats has a precedent of offering various `compose` methods for creating nested instances, but I'm not sure if there is much precedent for offering these instances as `implicit`s. Furthermore as noted in https://github.com/typelevel/cats/pull/4362 inference does not work very well for this implicit anyway.
So I think replacing the implicit with a `composeBifunctor` method may yield better and more consistent ergonomics i.e. Instead of:
```scala
Bifunctor[λ[(A, B) => F[(A, B)]]].leftMap(fab)(f)
```
now you would write:
```scala
Functor[F].composeBifunctor[(*, *)].leftMap(fab)(f)
// or
F.composeBifunctor[(*, *)].leftMap(fab)(f)
```
Thoughts?
> Add `Functor#composeBifunctor`

- core/src/main/scala/cats/data/NonEmptyList.scala
Change `NonEmptyList#last` to avoid allocating an `Option` via `lastOption`
This is a possible micro-optimization.
I did not benchmark this.
> Avoid allocating an `Option` in `NonEmptyList#last`

- core/src/main/scala/cats/syntax/either.scala
- tests/shared/src/test/scala/cats/tests/EitherSuite.scala
> Add `raiseWhen`/`raiseUnless` convenience methods to `EitherObjectOps`

- laws/src/main/scala/cats/laws/discipline/ExhaustiveCheck.scala
Noticed this while implementing one for otel4s.
> ExhaustiveCheck is a list, not a stream

- core/src/main/scala/cats/package.scala
> Fix typo in core's package object docs

- PULL_REQUEST_TEMPLATE.md
Stop asking contributors to run `+prePR`.
That's a way too heavy operation for a laptop due to Scala native. It's better to open a PR and let CI check it.
> Thank you for contributing to Cats!
> This is a kind reminder to run `sbt +prePR` and commit the changed files, if any, before submitting.
No, thanks! I have to `kill -9` it if I try 😄
> Delete PR template

- docs/jump_start_guide.md
Correcting a simple typo I found when reading the docs
> Fix jump_start_guide.md typo

- bench/src/main/scala/cats/bench/TraverseBench.scala
Basically replacing all of the `traverse` benchmarks with something more representative and projecting it onto a more useful scale. This makes it possible to directly compare `Traverse[List].traverse` and `List#map`, for example, as well as ultimately experiment with different implementation strategies that potentially avoid extra `Eval` wrapping.
> Replaced `traverse` benchmarks with something more representative

- core/src/main/scala/cats/data/OneAnd.scala
- tests/shared/src/test/scala/cats/tests/OneAndSuite.scala
* Adds the missing `PartialOrder` and `Order` instances to `OneAnd`.
* Re-arranges the `PartialOrder`, `Order` and already existing `Eq` instances according to their supposed resolution order.
* Adds corresponding tests.
> `OneAnd`: add `PartialOrder` and `Order` instances

- bench/src/main/scala/cats/bench/UnorderedTraverseMapBench.scala
- core/src/main/scala/cats/instances/map.scala
- tests/shared/src/test/scala/cats/tests/MapSuite.scala
Fixes #4461.
The implementation is copied from `List.traverse_`. 
I added just simple tests for the Map implementation, that is the only one that changed.
I'm not sure where to add tests for other unorderedTraverse implementations, they're not worth a TestLaw class IMHO.
> Making Map.unorderedTraverse stack safe

- core/src/main/scala-2.12/cats/instances/all.scala
- core/src/main/scala-2.12/cats/instances/package.scala
- core/src/main/scala-2.13+/cats/instances/all.scala
- core/src/main/scala-2.13+/cats/instances/package.scala
- core/src/main/scala/cats/Defer.scala
- core/src/main/scala/cats/instances/eq.scala
- core/src/main/scala/cats/instances/equiv.scala
- core/src/main/scala/cats/instances/function.scala
- core/src/main/scala/cats/instances/hash.scala
- core/src/main/scala/cats/instances/order.scala
- core/src/main/scala/cats/instances/ordering.scala
- core/src/main/scala/cats/instances/partialOrder.scala
- core/src/main/scala/cats/instances/partialOrdering.scala
- core/src/main/scala/cats/instances/show.scala
- tests/shared/src/test/scala/cats/tests/EqSuite.scala
- tests/shared/src/test/scala/cats/tests/EquivSuite.scala
- tests/shared/src/test/scala/cats/tests/HashSuite.scala
- tests/shared/src/test/scala/cats/tests/OrderSuite.scala
- tests/shared/src/test/scala/cats/tests/OrderingSuite.scala
- tests/shared/src/test/scala/cats/tests/PartialOrderSuite.scala
- tests/shared/src/test/scala/cats/tests/PartialOrderingSuite.scala
- tests/shared/src/test/scala/cats/tests/ShowSuite.scala
> Add `Defer` instances for `Eq`, `Hash`, `Order`, `Show`, and variants

- core/src/main/scala/cats/data/Const.scala
- tests/shared/src/test/scala/cats/tests/ConstSuite.scala
- Reorder instances in `Const` systematically
- Fix ambiguous `InvariantMonoidal` instance
- Add `ContravariantSemigroupal` instance
- Deprecate unnecessary `Functor` instance
- Add `Hash` instance and `hash` method
- Add `SemigroupK` and `MonoidK` instances
> Fix ambiguous `Const` instances and add missing instances

- core/src/main/scala/cats/data/IdT.scala
PR for part of #2479
Adding doctest for IdT typeclass.
> Add doctest for `IdT`

- build.sbt
In anticipation of the next round of feature PRs. If the need arises to make a backwards+forwards compatible patch release, we can cut a `series/2.10` branch.
> Bump base version to 2.11

- build.sbt
```
/home/runner/work/cats/cats/build.sbt:287: warning: method apply in object LinkConfig is deprecated (since 0.19.4): use LinkConfig.empty.addXXX(...).addYYY(...)
LinkConfig(apiLinks =
^
```
> fix warning in `build.sbt`

- core/src/main/scala/cats/data/OptionT.scala
- tests/shared/src/test/scala/cats/tests/OptionTSuite.scala
Perhaps I'm missing something, but this seems like an obvious counterpart to `whenM` and I was surprised to not find it? There are already `unlessF` and `unlessK` but no `unlessM`.
> Add `OptionT#unlessM`

- docs/nomenclature.md
Fix type signature of flatMapF:
https://www.javadoc.io/static/org.typelevel/cats-docs_2.13/2.10.0/cats/data/OptionT.html#flatMapF[B](f:A=%3EF[Option[B]])(implicitF:cats.Monad[F]):cats.data.OptionT[F,B]
> Update flatMapF in nomenclature.md

- .scalafmt.conf
- algebra-core/src/main/scala/algebra/ring/Additive.scala
- build.sbt
- core/src/main/scala/cats/ApplicativeError.scala
- core/src/main/scala/cats/data/Chain.scala
- core/src/main/scala/cats/data/EitherT.scala
- core/src/main/scala/cats/data/IorT.scala
- core/src/main/scala/cats/data/Kleisli.scala
- core/src/main/scala/cats/data/OptionT.scala
- core/src/main/scala/cats/instances/try.scala
- core/src/main/scala/cats/syntax/applicativeError.scala
- core/src/main/scala/cats/syntax/either.scala
- core/src/main/scala/cats/syntax/monadError.scala
- core/src/main/scala/cats/syntax/option.scala
- core/src/main/scala/cats/syntax/validated.scala
- free/src/main/scala/cats/free/FreeApplicative.scala
- kernel/src/main/scala/cats/kernel/Semigroup.scala
- tests/shared/src/test/scala/cats/tests/EitherSuite.scala
- Scala 3 report warnings since 3.4 https://github.com/lampepfl/dotty/pull/18813
- Scala 2.12 and 2.13 support new syntax without `-Xsource:3` option https://github.com/scala/scala/pull/10005
> enforce new wildcard syntax

- core/src/main/scala/cats/Foldable.scala
Just swaps a `G.pure(())` for `G.unit` to leverage when an instance has an overridden `G.unit` implementation.
> Use `Applicative#unit` in `Foldable#traverse_`

- free/src/test/scala/cats/free/FreeTSuite.scala
- laws/src/main/scala/cats/laws/ApplicativeLaws.scala
A follow up for #4557 – other uses of `Applicative.pure(())` are found (with **grep**) and replaced with `.unit`.
Note, that there are other places where `.pure(())` is in use, however those calls don't belong to `Applicative` and to replace them the `.unit` methods have to be added accordingly:
```
./free/src/main/scala/cats/free/FreeInvariantMonoidal.scala:104:      def unit: FA[S, Unit] = FreeInvariantMonoidal.pure(())
./tests/shared/src/test/scala/cats/tests/IndexedReaderWriterStateTSuite.scala:111:      val rws: ReaderWriterState[String, String, Int, Unit] = ReaderWriterState.pure(())
```
> Replaces other `Applicative.pure(())` with `.unit`

- core/src/main/scala/cats/data/EitherT.scala
- tests/shared/src/test/scala/cats/tests/EitherTSuite.scala
> Fix EitherT Bifunctor priority, add Bifoldable instance

- core/src/main/scala/cats/Show.scala
- tests/shared/src/test/scala/cats/tests/ShowSuite.scala
> fix ambiguous ContravariantShow[SortedSet[A]] (& SortedMap)

- docs/nomenclature.md
In the current docs `choice` alias rendered like this:
Meanwhile it should be rendered as `|||`. I closed markdown table row with `|`, I hope it fixes the problem, because I am unable to render docs locally
> Fix `choice` alias render in docs

- core/src/main/scala/cats/data/NonEmptyMapImpl.scala
- core/src/main/scala/cats/data/NonEmptySet.scala
Simple fix for this annoying behaviour:
```scala
//> using dep org.typelevel::cats-core::2.10.0
import cats.data.NonEmptyMap
val nem: NonEmptyMap[Int,Int] = NonEmptyMap.of(1 -> 1)
val alsoNem: NonEmptyMap[Int,Int] = nem.value.value.value.value
```
The fix passes the Mima check, but ofc it will become impossible to explicitly call `.value` on `NonEmptyMap` instances (but that's what we want, right?)
Thanks to @reardonj for the solution
> Reduce visibility of value member in the `NonEmptyMap` syntax

- core/src/main/scala/cats/Functor.scala
- docs/nomenclature.md
- laws/src/main/scala/cats/laws/FunctorLaws.scala
- laws/src/main/scala/cats/laws/discipline/FunctorTests.scala
I've found myself (and others) repeating this over and over, and it seems as primitive as `void` or `as`, so would be nice to have it here. If this looks fine, i can also add `flatMapOrKeep` to `Monad` in another PR
> Add `mapOrKeep` to Functor

- core/src/main/scala-2/cats/arrow/FunctionKMacros.scala
- core/src/main/scala/cats/arrow/FunctionKLift.scala
- tests/shared/src/test/scala-3/cats/tests/FunctionKLiftSuite.scala
This PR adds liftFunction into the Scala 3 API. 
That would help us to remove [FunctionKLift](https://github.com/typelevel/cats-tagless/blob/master/core/src/main/scala/cats/tagless/FunctionKLift.scala) from cats-tagless and from a couple of other libraries. Right now I'm just borrowing this file around :D
Closes #4449
cc @joroKr21
> Expose FunctionK.liftFunction as a part of the Scala 3 API

- core/src/main/scala-2/cats/syntax/MonadOps.scala
- core/src/main/scala-3/cats/syntax/MonadOps.scala
- core/src/main/scala/cats/Monad.scala
- laws/src/main/scala/cats/laws/MonadLaws.scala
- laws/src/main/scala/cats/laws/discipline/MonadTests.scala
> Add `flatMapOrKeep` to `Monad`

- core/src/main/scala-2.13+/cats/data/NonEmptyLazyList.scala
- core/src/main/scala/cats/data/NonEmptyChain.scala
- core/src/main/scala/cats/data/NonEmptyCollection.scala
- core/src/main/scala/cats/data/NonEmptyList.scala
- core/src/main/scala/cats/data/NonEmptySeq.scala
- core/src/main/scala/cats/data/NonEmptyVector.scala
- tests/shared/src/test/scala-2.13+/cats/tests/NonEmptyLazyListSuite.scala
- tests/shared/src/test/scala/cats/tests/NonEmptyChainSuite.scala
- tests/shared/src/test/scala/cats/tests/NonEmptyListSuite.scala
- tests/shared/src/test/scala/cats/tests/NonEmptySeqSuite.scala
- tests/shared/src/test/scala/cats/tests/NonEmptyVectorSuite.scala
First time contributor... 👋 
- Added `distinctBy` to `NonEmptyCollection` and implementations.
- When migrating some existing code from `List` to `NonEmptyList` I noticed that `distinctBy` was missing. This addition adds parity with `distinct/distinctBy` in the scala standard library, and also with `cats.data.Chain`.
> Add distinctBy to NonEmptyCollection and all impls

- kernel-laws/shared/src/main/scala/cats/kernel/laws/MonoidLaws.scala
- kernel-laws/shared/src/main/scala/cats/kernel/laws/OrderLaws.scala
- kernel-laws/shared/src/main/scala/cats/kernel/laws/discipline/BoundedTests.scala
- kernel-laws/shared/src/main/scala/cats/kernel/laws/discipline/EnumerableTests.scala
- kernel-laws/shared/src/main/scala/cats/kernel/laws/discipline/HashTests.scala
- kernel-laws/shared/src/main/scala/cats/kernel/laws/discipline/MonoidTests.scala
- kernel-laws/shared/src/main/scala/cats/kernel/laws/discipline/OrderTests.scala
- kernel-laws/shared/src/main/scala/cats/kernel/laws/discipline/PartialOrderTests.scala
- kernel/src/main/scala-2.12/cats/kernel/compat/HashCompat.scala
- kernel/src/main/scala/cats/kernel/instances/MapInstances.scala
- kernel/src/main/scala/cats/kernel/instances/SeqInstances.scala
Supersedes #4187.
This PR fixes or suppresses compiler warnings in the **kernel** and **kernel-laws** modules.
> Fix/suppress warnings in kernel and kernel-laws

- CONTRIBUTING.md
[Current version](https://github.com/typelevel/cats/blob/main/CONTRIBUTING.md#write-code) of the link 404s.
> Fix broken internal link

- CONTRIBUTING.md
I don't know if this is strictly necessary, but it aligns with the [build.properties](https://github.com/typelevel/cats/blob/main/project/build.properties) file.
> Point to sbt 1.x

- .jvmopts
It's been five years since these options were last touched. Too many things have become complicated since then. But let's see if this actually fixes the Native build.
> Adjust the JVM options to heal the Native build on CI

- core/src/main/scala/cats/syntax/either.scala
- tests/shared/src/test/scala/cats/tests/EitherSuite.scala
These are companions to `Functor#mapOrKeep` and `cats.Monad#flatMapOrKeep`, but for the left-hand side of `Either[A, B]`.
> Add `EitherOps#leftMapOrKeep` and `EitherOps#leftFlatMapOrKeep`

- docs/typeclasses.md
FWIW, if we keep this link, it should be correct (surprisingly, GitHub Gist doesn't support forwarding, but GitHub itself does).
> Fix the broken link on the typeclasses page

- core/src/main/scala/cats/Eval.scala
Same as https://github.com/typelevel/cats/pull/937
fixes https://github.com/typelevel/cats/issues/4631
> Issue #4631: Make Later covariant

- core/src/main/scala/cats/Defer.scala
- tests/shared/src/test/scala/cats/tests/EvalSuite.scala
It took me a bit of thinking to implement this, so I think it could be of use. This simplifies writing a recursive function over a `Defer[F]` instance. This is particularly useful with monad transformers that give you Defer instances, e.g. `EitherT[IO, MyError, A]`
> Add Defer.recursiveFn to aid in recursion

- core/src/main/scala/cats/Bifunctor.scala
- core/src/main/scala/cats/Functor.scala
- tests/shared/src/test/scala/cats/tests/IndexedStateTSuite.scala
There are some imports in examples that look like `import cats.implicits.catsStdInstancesForOption`
I don't think we should ever suggest such imports.
This PR replaces such imports with the "officially" recommended `import cats.syntax.all._`
> Fix some awkward imports

- docs/js/sponsors.js
This PR updates sponsors.js to work with the new  OpenCollective API values.
> Fix Sponsors section

- .github/workflows/ci.yml
- build.sbt
GraalVM is no longer available under the free license: graalvm/setup-graalvm#notes-on-oracle-graalvm-for-jdk-17
sbt-typelevel already did the same: typelevel/sbt-typelevel#763
See: #4666
> Update GraalVM from 17 to 21

- core/src/main/scala/cats/Align.scala
- laws/src/main/scala/cats/laws/AlignLaws.scala
- laws/src/main/scala/cats/laws/discipline/AlignTests.scala
`alignWith` is usually overridden for efficiency
> Use alignWith in alignMergeWith

- project/Boilerplate.scala
It makes the generated code a bit simpler
> Use helper functions in generated code

- kernel/src/main/scala/cats/kernel/Semigroup.scala
> Semigroup object additions

- bench/src/main/scala/cats/bench/TraverseBench.scala
- core/src/main/scala-2.13+/cats/instances/arraySeq.scala
- core/src/main/scala/cats/Foldable.scala
- core/src/main/scala/cats/Parallel.scala
- core/src/main/scala/cats/Reducible.scala
- core/src/main/scala/cats/Traverse.scala
- core/src/main/scala/cats/data/Chain.scala
- core/src/main/scala/cats/instances/list.scala
- core/src/main/scala/cats/instances/queue.scala
- core/src/main/scala/cats/instances/seq.scala
- core/src/main/scala/cats/instances/vector.scala
- core/src/main/scala/cats/syntax/foldable.scala
- core/src/main/scala/cats/syntax/parallel.scala
- laws/src/main/scala/cats/laws/ReducibleLaws.scala
- laws/src/main/scala/cats/laws/discipline/ReducibleTests.scala
- mima.sbt
- tests/shared/src/test/scala-2.13+/cats/tests/ScalaVersionSpecific.scala
- tests/shared/src/test/scala/cats/tests/KleisliSuite.scala
- tests/shared/src/test/scala/cats/tests/ParallelSuite.scala
- tests/shared/src/test/scala/cats/tests/ReducibleSuite.scala
- tests/shared/src/test/scala/cats/tests/RegressionSuite.scala
- tests/shared/src/test/scala/cats/tests/SyntaxSuite.scala
- tests/shared/src/test/scala/cats/tests/TraverseSuite.scala
Closes #4611.
The feedback on the original proposal seems generally favorable, therefore here is the PR. Overall, it does the following:
- adds `traverseVoid`/`sequenceVoid` to `Foldable` (convering `traverse_` and `sequence_` to aliases for the new methods);
- similarly, adds `nonEmptyTraverseVoid`/`nonEmptySequenceVoid`;
- similarly, adds corresponding new methods to `Parallel`/`NonEmptyParallel`;
- redirects customized implementations in data instances to the new methods;
- makes laws and tests using the new methods instead of the old ones.
Also it adds some comments to the places that haven't been changed but could be and thereby explaining why.
> Aliases `traverseVoid`/`sequenceVoid` and their counterparts

- core/src/main/scala/cats/data/Chain.scala
This is basically a followup to #3967. The justification is also exactly the same.
> Override Foldable#toIterable for Chain

- core/src/main/scala/cats/data/Chain.scala
- tests/shared/src/test/scala/cats/tests/TraverseSuite.scala
we can directly iterate through traverseVoid (which is really a kind of monoidal aggregation), so we don't need to use the expensive foldRight to do this.
> Optimize Chain.traverseVoid

- core/src/main/scala-2.12/cats/data/ChainCompanionCompat.scala
- core/src/main/scala-2.13+/cats/data/ChainCompanionCompat.scala
- core/src/main/scala/cats/data/Chain.scala
- tests/shared/src/test/scala/cats/tests/ChainSuite.scala
I reached for drop on Chain and realized we never implemented it however, we could implement it and using internal structure it can be more efficient than using iterators/toList.
> Add take/takeRight/drop/dropRight to Chain

- build.sbt
Seems required to prevent CI from failing with
> java.lang.RuntimeException: Your tlBaseVersion 2.12 is behind the latest tag 2.13.0
(see https://github.com/typelevel/cats/pull/4703#issuecomment-2605753073)
> set tlBaseVersion := "2.13"

- docs/faq.md
Based on [this discussion](https://discord.com/channels/632277896739946517/633329569402978313/1338065853718990908).
I feel it would be beneficial for everyone to have this section to avoid coming back to this matter over and over again.
> Add FAQ section on `Functor[Set]`

- kernel/src/main/scala-2.13+/cats/kernel/compat/HashCompat.scala
Either this or #4718 is sufficient to fix #4716.  I propose we want both, but they are orthogonal.
Original problem and solution are from https://github.com/scala/scala/pull/10912.
> Backport hash improvements from Scala 2.13.16's MurmurHash3

- docs/js/sponsors.js
Fixes #4663
There were actually 2 issues. Some sponsors were duplicated, with and without a tier in the GraphQL response. The switch was also falling through due to lack of breaks. I added code to sort by level + name, then only add a sponsor the first time they are seen.
Testing locally, we can see Aruna now only appears in Gold, and Silver sponsors are no longer duplicated to backers. @jducoeur is no longer duplicated in other contributors.
> Fix Sponsor Duplicates

- alleycats-core/src/main/scala/alleycats/Empty.scala
- alleycats-core/src/test/scala/alleycats/SyntaxSuite.scala
This is solving the case where we have an instance of `Empty[T]` but looking for a `Empty[Option[T]]`:
https://scastie.scala-lang.org/Jv24ybPQRQeQ2IEZy5azmA
> Create Empty from EmptyK

- alleycats-core/src/main/scala/alleycats/Empty.scala
It turns out that an instance of `alleycats.Empty[Option[A]]` isn't automatically derived if there is no `Semigroup` instance for `A` in scope. See the example: https://scastie.scala-lang.org/gndrZPa1QA6deeYzhNhvQw. Interestingly, adding an import of `alleycats.std.option` doesn't help either.
> Add the `Empty[Option[A]]` instance in alleycats 

- kernel/src/main/scala/cats/kernel/Order.scala
- tests/shared/src/test/scala/cats/tests/OrderSuite.scala
The `Order.fromComparable` method signature in `Order.scala` has been modified to allow it to accept `java.sql.Date`.
This change enables the method to work with types such as `java.sql.Date` and other subtypes of `java.util.Date` which implements `Comparable<java.util.Date>`.
> `Order.fromComparable` Method Signature Change to Allow `java.sql.Date`

- alleycats-core/src/main/scala/alleycats/Empty.scala
- alleycats-core/src/test/scala/alleycats/SyntaxSuite.scala
Adding yet another instance of `Empty` that might be commonly used (at the very least, I need it). I thought of adding this:
```scala
implicit def alleycatsEmptyForMap[CC[_, _] <: Iterable[(_, _)], A, B](implicit
factory: Factory[(A, B), CC[A, B]]
): Empty[CC[A, B]] = Empty(factory.newBuilder.result())
```
but as @johnynek pointed out in #4733, it will also add support for `mutable.Map`, which isn't a desirable outcome.
The existing derivation capabilities fail to derive `Empty[Map[A, B]]` when the key/value types are case classes or more sophisticated than primitives. See https://scastie.scala-lang.org/ggnoSWYGTFiGGqD6wA0VuQ
> Add the `Empty[Map[A, B]]` instance in alleycats
