- core/src/main/scala/cats/Functor.scala
- examples/FunctorExamples.scala
- project/build.scala
* adds some derrived methods to Functor
* add an examples sub-project
* add examples for creating / using Functor
> increase the Functor

- std/src/main/scala/cats/std/all.scala
- std/src/main/scala/cats/std/function.scala
A first set of instances for `Function1`.
> Functor, Contravariant, and Arrow instances for Function1

- build.sbt
- core/src/main/scala/cats/Applicative.scala
- core/src/main/scala/cats/Apply.scala
- core/src/main/scala/cats/Functor.scala
- data/src/main/scala/cats/data/Or.scala
Upgrades simulacrum and paradise.
> Restore ScalaDoc generation for most types

- build.sbt
- project/plugins.sbt
This replaces #35, which I'd submitted against `topic/law-checking`, since it built on changes in that branch. `topic/law-checking` got merged and GitHub doesn't let me change the target of #35, so I'm resubmitting the rebased commit.
> Add Unidoc for merging subproject API docs

- README.md
This commit adds:
1. List of maintainers
2. How do I get involved?
3. Explicit discussion of PR merging
4. More detailed treatment of CoC & related
Review by @stew et al.
This fixes #43.
> First pass at some README updates.

- .travis.yml
> Add .travis.yml file with gitter integration.

- core/src/main/scala/cats/arrow/NaturalTransformation.scala
I think NaturalTransformation is not typeclass.
`NaturalTransformation.apply` should not exists
> remove NaturalTransformation.apply

- examples/ApplyExamples.scala
This commit adds some creation/usage examples for Apply based on @stew's work
and his other examples.
> Add Apply examples.

- CONTRIBUTING.md
- README.md
I also did some line wrapping in CONTRIBUTING.md and made the
prose a little bit tighter. Obviously there are still lots of
TODOs but I think we're headed in the right direction.
> Update README and CONTRIBUTING to mention unidoc and scalastyle.

- std/src/main/scala/cats/std/all.scala
- std/src/main/scala/cats/std/map.scala
- std/src/main/scala/cats/std/package.scala
> Map Instance Implementation

- .travis.yml
- CONTRIBUTING.md
- README.md
- build.sbt
Fixes #112
This alias aggregates the compile, test, scalastyle, and unidoc
tasks.
Thanks to @fthomas for doing all of the hard work and figuring out how
to make this work.
> Add SBT validate alias

- core/src/main/scala/cats/MonoidK.scala
- core/src/main/scala/cats/SemigroupK.scala
> Add some initial documentation for univeral algebras. closes #120

- core/src/main/scala/cats/Apply.scala
I find this a lot easier to read, and it's how we're doing it everywhere else
> Use kind-projector plugin wherever possible

- std/src/main/scala/cats/std/either.scala
I should have merged master into #150, which would have
caught this problem earlier. Mea culpa.
> This commit fixes an implicit merge conflict.

- docs/src/main/tut/functor.md
> Escaped underscores in Functor docs.

- docs/src/main/tut/apply.md
- docs/src/main/tut/functor.md
http://non.github.io/cats//tut/apply
http://non.github.io/cats//tut/functor
> fix apply.md and functor.md

- core/src/main/scala/cats/CoflatMap.scala
- core/src/main/scala/cats/Comonad.scala
- core/src/main/scala/cats/syntax/all.scala
- core/src/main/scala/cats/syntax/coflatMap.scala
- core/src/main/scala/cats/syntax/package.scala
- data/src/main/scala/cats/data/Cokleisli.scala
- laws/src/main/scala/cats/laws/CoflatMapLaws.scala
- laws/src/main/scala/cats/laws/ComonadLaws.scala
- laws/src/main/scala/cats/laws/discipline/ComonadTests.scala
- std/src/main/scala/cats/std/list.scala
- std/src/main/scala/cats/std/option.scala
- std/src/main/scala/cats/std/stream.scala
> Rename CoFlatMap to CoflatMap.

- build.sbt
- docs/src/main/tut/semigroupk.md
- std/src/main/scala/cats/std/function.scala
- std/src/main/scala/cats/std/list.scala
- std/src/main/scala/cats/std/option.scala
also sucks in list monoid from spire
creates monoid instances for Option, Function1
> add docs for SemigroupK

- tests/src/test/scala/cats/tests/FutureTests.scala
This PR addresses #216 by replace ApplicativeTests with MonadTests
> Update FutureTests to check Monad laws (address #216)

- build.sbt
- core/build.sbt
Just noticed this little straggler, thought he can live with his friends now.
> Move sourceGenerators into main build.sbt, kill core/build.sbt.

- core/src/main/scala/cats/Lazy.scala
see https://github.com/scalaz/scalaz/issues/428, https://github.com/scalaz/scalaz/pull/422
> change ByNeed internal representation. avoid memory leak

- docs/src/main/tut/applicative.md
As mentioned in
https://github.com/non/cats/pull/238#discussion_r25338218
> Split up a run-on sentence in applicative docs.

- .gitignore
- build.sbt
- docs/src/site/_layouts/default.html
- docs/src/site/colophon.md
- docs/src/site/contributing.md
- docs/src/site/css/custom.css
- docs/src/site/css/styles.css
- docs/src/site/index.md
- docs/src/site/typeclasses.md
This makes the website look sane from a phone.
preview at https://stew.github.io/cats
> Mobile site

- build.sbt
- project/build.properties
`: _*` for settings is not needed anymore!
> Update to sbt 0.13.8

- core/src/main/scala/cats/Applicative.scala
- core/src/main/scala/cats/Traverse.scala
- core/src/main/scala/cats/Unapply.scala
- core/src/main/scala/cats/syntax/all.scala
- core/src/main/scala/cats/syntax/package.scala
- core/src/main/scala/cats/syntax/traverse.scala
- tests/src/test/scala/cats/tests/UnapplyTests.scala
also adds traverseU / sequenceU and adds syntax for traverse.
> add an Unapply typeclass

- core/src/main/scala/cats/Lazy.scala
Simple documentation comment type fix.
> Fix typo "will cached" -> "will cache"

- data/src/main/scala/cats/data/Ior.scala
- data/src/main/scala/cats/data/Xor.scala
- laws/src/main/scala/cats/laws/discipline/Arbitrary.scala
- laws/src/main/scala/cats/laws/discipline/ArbitraryK.scala
- tests/src/test/scala/cats/tests/IorTests.scala
Adds data type described in #273. Note: should be merged after #274.
> Add cats.data.Ior

- core/src/main/scala/cats/Alternative.scala
- core/src/main/scala/cats/syntax/apply.scala
- core/src/main/scala/cats/syntax/coflatMap.scala
- core/src/main/scala/cats/syntax/comonad.scala
- core/src/main/scala/cats/syntax/contravariant.scala
- core/src/main/scala/cats/syntax/flatMap.scala
- core/src/main/scala/cats/syntax/foldable.scala
- core/src/main/scala/cats/syntax/functor.scala
- core/src/main/scala/cats/syntax/invariant.scala
- core/src/main/scala/cats/syntax/monadFilter.scala
- core/src/main/scala/cats/syntax/semigroupk.scala
- core/src/main/scala/cats/syntax/traverse.scala
- docs/src/site/index.md
Adds some unapply shapes for monad transformers.
Uses unapply for most bedazzlers into syntax.
> More unapply

- core/src/main/scala/cats/data/Kleisli.scala
It's not currently possible to use Kleisli arrows in e.g. a `for`-comprehension because the `flatMap` method doesn't have the appropriate type and blocks the enriched `flatMap` you'd get from `cats.syntax.flatMap`.
We have at least three choices for the name of the non-`flatMap` `flatMap` (the one that takes a `B => F[C]`). Scalaz uses `flatMapK` for this, but I prefer `flatMapF` (and `mapF`), which is consistent with e.g. the `flatMapF` on Scalaz's `OptionT`. It's different from the `flatMapF` on cats's `XorT`, though. We could also do something else entirely.
I don't care too much about what these things get named, as long as the real `flatMap` works.
> Rename Kleisli's flatMap and variants

- docs/src/main/tut/apply.md
> Add missing newline in Apply's documentation.

- docs/src/main/tut/functor.md
- docs/src/main/tut/typeclasses.md
Two changes to add a header to the Typeclasses documentation and a capitalization fix for Functor docs.
> Minor doc changes

- docs/src/main/tut/freemonad.md
This commit fixes some formatting issues, and also contains some edits to
smooth out the text a bit.
> Formatting and other edits.

- .travis.yml
Pretty much what it says on the tin.
> Try shell-escaping sonatype password before encryption.

- docs/src/site/index.md
Very minor corrections to grammar, punctuation, capitalization and spelling.
> Minor typos in index.md homepage

- docs/src/site/index.md
> Fix type classes link

- build.sbt
- core/src/main/scala/cats/Alternative.scala
- core/src/main/scala/cats/Applicative.scala
- core/src/main/scala/cats/Apply.scala
- core/src/main/scala/cats/Bimonad.scala
- core/src/main/scala/cats/CoflatMap.scala
- core/src/main/scala/cats/Comonad.scala
- core/src/main/scala/cats/FlatMap.scala
- core/src/main/scala/cats/Foldable.scala
- core/src/main/scala/cats/Functor.scala
- core/src/main/scala/cats/Monad.scala
- core/src/main/scala/cats/MonadCombine.scala
- core/src/main/scala/cats/MonadFilter.scala
- core/src/main/scala/cats/MonoidK.scala
- core/src/main/scala/cats/Reducible.scala
- core/src/main/scala/cats/SemigroupK.scala
- core/src/main/scala/cats/Show.scala
- core/src/main/scala/cats/Traverse.scala
- core/src/main/scala/cats/functor/Contravariant.scala
- core/src/main/scala/cats/functor/Invariant.scala
- laws/src/main/scala/cats/laws/TraverseLaws.scala
- laws/src/main/scala/cats/laws/discipline/EqK.scala
- laws/src/main/scala/cats/laws/discipline/SerializableTests.scala
- state/src/test/scala/cats/state/StateTests.scala
- std/src/main/scala/cats/std/set.scala
- tests/src/test/scala/cats/tests/EitherTests.scala
- tests/src/test/scala/cats/tests/FutureTests.scala
- tests/src/test/scala/cats/tests/UnapplyTests.scala
- tests/src/test/scala/cats/tests/ValidatedTests.scala
Many thanks to @tpolecat for helping me turn off the setting for `tut`
> Turn on -Ywarn-unused-import

- core/src/main/scala/cats/Foldable.scala
- core/src/main/scala/cats/data/OneAnd.scala
- laws/src/main/scala/cats/laws/FoldableLaws.scala
- laws/src/main/scala/cats/laws/discipline/FoldableTests.scala
- std/src/main/scala/cats/std/list.scala
- std/src/main/scala/cats/std/map.scala
- std/src/main/scala/cats/std/option.scala
- std/src/main/scala/cats/std/set.scala
- std/src/main/scala/cats/std/stream.scala
- std/src/main/scala/cats/std/vector.scala
- tests/src/test/scala/cats/tests/OneAndTests.scala
And override it on some std lib structures for efficiency.
> Add Foldable.exists

- build.sbt
- free/src/main/scala/cats/free/Free.scala
- free/src/test/scala/cats/free/FreeTests.scala
Also add implicit Monad for FreeC, since implicit resolution was
not working for this case.
> Add tests for Free

- AUTHORS.md
- CHANGES.md
- AUTHORS.md: lists everyone who has contributed
- CHANGES.md: lists changes by version
Unlike Spire's AUTHORS.md, I have not tried to summarize
everyone's contribution(s). I would like to do that but
the list is already too long, so for now we will just have
names.
> This commit adds two markdown files:

- build.sbt
Original version lost build settings when new state created
> Fix git described snapshots on 2.10

- docs/src/main/tut/apply.md
Walk through `Apply` documentation
> Apply documentation

- .travis.yml
- build.sbt
- laws/js/src/main/scala/cats/laws/Platform.scala
I've updated the versions and settings and tested the build twice on local travis eg https://travis-ci.org/InTheNow/cats/builds/74782890
> Fix cross build settings

- docs/src/site/index.md
Just copied the content from README.md for now.
> Update 'Getting Started' in the website

- core/src/main/scala/cats/Traverse.scala
Can find any place we use this, if we aren't using it, should we just remove it?
To me it doesn't look like it adds much value on its own.
> this traversal method is undocumented and unused

- build.sbt
- docs/src/main/tut/kleisli.md
Also disable -Ywarn-dead-code in tut - I found myself wanting
to stub irrelevant code/details in tut with ??? but that would
trigger a dead code warning which got turned into a failure due
to fatal warnings.
> Kleisli tut

- docs/src/site/_layouts/default.html
- docs/src/site/resources_for_learners.md
> Adds "resources for learners" docs section with link to herding cats

- core/src/main/scala/cats/Foldable.scala
- docs/src/main/tut/applicative.md
- docs/src/main/tut/freeapplicative.md
- docs/src/main/tut/freemonad.md
- docs/src/main/tut/typeclasses.md
> Small doc fixes

- project/build.properties
> upgrade to sbt 0.13.9

- .travis.yml
Our Travis credentials stopped working. Hopefully these new ones
will start publishing correctly again.
> Maybe these credentials will work?

- free/src/main/scala/cats/free/Free.scala
- free/src/main/scala/cats/free/FreeApplicative.scala
- free/src/main/scala/cats/free/Trampoline.scala
- free/src/test/scala/cats/free/FreeApplicativeTests.scala
- free/src/test/scala/cats/free/FreeTests.scala
Taken from
https://github.com/scalaz/scalaz/commit/783eb0ed7f6aec56d6245e9b2b9bac97aab74d22#diff-afd5b6310425d773ca3459ebb17ed594
> Rework Free to use Coyoneda behind the scenes

- .gitignore
- .travis.yml
- README.md
- build.sbt
- scripts/sbtrc-JVM
- scripts/travis-publish.sh
Fixes https://github.com/non/cats/issues/155
Fixes https://github.com/non/cats/issues/429
Site push is untested.
> Build tweaks

- docs/src/main/tut/monoid.md
I can't help feeling there's more profound practical motivations for Monoid, beyond `combineAll`, but here's at least a first attempt at docs for Monoid.
> Monoid docs

- scripts/travis-publish.sh
Fixing these issues will hopefully be easy, but I want to
get everything into a working state first.
> Temporarily disable site generation to get Travis building.

- core/src/main/scala/cats/data/Kleisli.scala
It just needs an Applicative, not a Monad.
> Relax Kleisli.lower constraint

- core/src/main/scala/cats/Task.scala
- tests/shared/src/test/scala/cats/tests/TaskTests.scala
obviously this is just scratching the surface of what should be tested
> start adding some tests to task, 

- core/src/main/scala/cats/Eval.scala
Minor typo fix (implementat -> implementation)
> Fixed typo in comments

- docs/src/main/tut/foldable.md
More examples for `Foldable`. 
I don't like the `sequence_` and `traverse_` examples that much. Happy to hear something better!
> more examples for Foldable

- build.sbt
- js/src/main/scala/cats/js/std/future.scala
- js/src/main/scala/cats/jvm/std/future.scala
- js/src/test/scala/cats/tests/FutureTests.scala
- jvm/src/main/scala/cats/jvm/std/future.scala
- jvm/src/test/scala/cats/tests/FutureTests.scala
- scripts/travis-publish.sh
Fix https://github.com/non/cats/issues/458
> Add future{Comonad, Eq, Order, PartialOrder} to js

- tests/src/test/scala/cats/tests/EitherTests.scala
I think some of this code must have been written before we had
law-checking infrastructure in place for Eq/Order.
> Clean up Either tests

- docs/src/main/tut/kleisli.md
I found the Kleisli docs to generally be really helpful, but I thought that they could do with an intro that described their utility a bit more quickly, which is what I've attempted here.
> Edit Kleisli intro for brevity

- .gitignore
Just trying to make it less likely people will commit sublime "stuff".
> Add sublime files to gitignore.

- core/src/main/scala/cats/data/Validated.scala
This fixes a minor typo in comments of Validated.
> Fix a typo in Validated comments

- README.md
- docs/src/site/index.md
Hi,
this is just a version bump in the README.md.
Matthias
> Change cats version to 0.3.0 in README.md

- tests/src/test/scala/cats/tests/IorTests.scala
- tests/src/test/scala/cats/tests/OneAndTests.scala
- tests/src/test/scala/cats/tests/ValidatedTests.scala
- tests/src/test/scala/cats/tests/XorTests.scala
> Avoid `whenever` in tests

- core/src/main/scala/cats/MonadCombine.scala
- laws/src/main/scala/cats/laws/SerializableLaws.scala
Just a few minor comment changes to fix typos I came across this evening.
> Minor typos

- tests/src/test/scala/cats/tests/ValidatedTests.scala
Some minor additional condition checks to existing validated tests.
> Minor additions to validated tests conditions

- tests/src/test/scala/cats/tests/MapTests.scala
> Add a test for Show[Map]

- docs/src/main/tut/freemonad.md
This makes a couple small changes to the free monad docs.
1. Change most of the `tut` sheds to `tut:silent`. In most of these blocks, we are just defining objects/methods. There are only a few blocks where we are actually running things and care about the output. This makes things look a little cleaner.
2. One of the code blocks didn't use tut because it had a `readLine()` call that caused tut to hang. Unfortunately, this means that the code block wasn't compiler-verified, and it couldn't display its output. I've hacked around this by creating an invisible tut shed that defines `readLine` as a method that returns a canned String.
> Minor cleanup in free monad doc

- tests/src/test/scala/cats/tests/OneAndTests.scala
Adds a test for the Show instance for OneAnd
> Add test for Show[OneAnd]

- laws/src/main/scala/cats/laws/SerializableLaws.scala
This is the same work that was done in algebra in
[#117](https://github.com/non/algebra/pull/117).
> Pass along error when serializable tests fail

- laws/src/main/scala/cats/laws/discipline/MonadTests.scala
This is basically the same story as #728, but it was introduced in
fa6457a61b527736d88a5192e9fae060db2b3ffe.
> Test Monad map/flatMap coherence law

- core/src/main/scala/cats/arrow/Choice.scala
This is an attempt to be helpful while learning more about some methods that I've never directly used. So please feel free to chime in if the descriptions could be improved or if there are examples that might provide more insight.
> Add ScalaDocs for Choice methods

- core/src/main/scala/cats/data/Ior.scala
- tests/src/test/scala/cats/tests/IorTests.scala
> Slightly optimize Ior.toEither

- tests/src/test/scala/cats/tests/EvalTests.scala
> Check alternate Comonad laws

- core/src/main/scala/cats/NotNull.scala
- core/src/main/scala/cats/data/OptionT.scala
> Rewrite OptionT.flatMap in terms of flatMapF

- AUTHORS.md
> Update list of authors

- README.md
@non can you update the site URL at the top of the repo? It won't let me edit it, so I'm guessing you need to be owner.
> Update URLs in readme after org change

- build.sbt
Note that after we do a new release to this new organization,
we'll need to update two files:
* README.md - update information about finding the release
* docs/src/site/index.md - same idea
> We should start publishing to org.typelevel.

- .travis.yml
> Remove duplicated cache directories in .travis.yml

- CHANGES.md
@DavidGregory084 just [pointed out](https://github.com/typelevel/cats/pull/848#issuecomment-178183604) that I jumped the gun on #809.
> Remove premature item in release notes

- core/src/main/scala/cats/Foldable.scala
- tests/src/test/scala/cats/tests/FoldableTests.scala
This is based off #356, but adds back stack-safety.
> Stack-safe foldM

- CHANGES.md
> updated release notes

- AUTHORS.md
- CHANGES.md
I also noticed a bunch of folks who were missing from our list
of authors, so I made a pass through git log to add people that
I noticed were missing.
> Since the last release notes updates I merged a few more things.

- AUTHORS.md
I forgot to do this in my last PR. Sorry.
> Add Aaron Levin to AUTHORS.md

- docs/src/site/resources_for_learners.md
This adds Functional Programming in Scala to the "Resources for Learners" section in our docs. FPiS does not specifically cover Cats but it is IMO one of the best introduction to functional programming in general and to some of the abstractions that are provided by Cats.
> Add FPiS to the "Resources for Learners" section

- docs/src/main/tut/symbols.md
Adding a symbols chart to the docs.
This is a copy of PR #1094 with commits merged.
> Symbols Chart

- docs/src/main/tut/traverse.md
> Use tut:silent for Traverse example

- _tut/semigroup.md
Note: this is a PR to the gh-pages branch for a manual edit of the website. We want to keep the website in sync with the latest stable release, so we can't just publish the site from the current master branch.
Fixes #1187.
> Fix imports in Semigroup doc

- core/src/main/scala/cats/syntax/package.scala
Add piecemeal `monoid` import.
> Add piecemeal Monoid import

- core/src/main/scala/cats/Functor.scala
This is a followup on [this
discussion](https://github.com/typelevel/cats/issues/1080#issuecomment-225892635).
> Add a note about issues with Functor.widen

- README.md
@adelbertc @ceedubs Added some missing descriptions for Fetch and Monix. Thanks!
> Added descriptions for Fetch and Monix libraries

- README.md
Also alphabetize Related Projects list
/cc @mpilquist
> Add FS2 to Related Projects section

- README.md
@adelbertc I hope the description is ok. `eff-cats` is not so easy to describe in one sentence :-).
> Added the eff-cats project

- build.sbt
Pinging @johnynek, @peterneyens, and @kailuowang
> Add new maintainers to pomExtra

- README.md
in action: https://github.com/MasseGuillaume/cats/tree/scaladex-badge#cats
> scaladex badge

- build.sbt
> Include generated files in source JARs

- docs/src/main/tut/typeclasses/typeclasses.md
fix as suggested in https://github.com/typelevel/cats/issues/1438#issuecomment-256524362
> Fixes #1438 by replacing quoted entry name

- docs/src/main/tut/index.md
I somehow forgot to actually change the version on the index page in #1437. Oops.
> Update version on index

- version.sbt
not sure if 0.9.0 is the right one to put here but we already released 0.8.1
> update the version

- build.sbt
Update Discipline and ScalaTest to the latest versions.
> Update Discipline and ScalaTest

- README.md
Didn't notice that we had an ETA before.
> update ETA for 1.0.0

- README.md
Plugin argued for in https://github.com/typelevel/general/issues/69.
EDIT: it seems this is needed because of https://github.com/typelevel/cats/pull/1679. This particular PR is just one way to solve it.
> Link to sbt-partial-unification plugin

- docs/src/main/tut/resources_for_learners.md
The Advanced scala with cats book by underscore.io (freely available) can be a good resource for users of FP in Scala and Cats.
> Add underscore.io Advanced Scala with Cats

- core/src/main/scala/cats/syntax/flatMap.scala
- tests/src/test/scala/cats/tests/SyntaxTests.scala
resolves https://github.com/typelevel/cats/issues/1568
> Add tailRecM syntax for FlatMap

- .travis.yml
I saw a notification on our build pointing users to add this setting. Detail here: 
https://blog.travis-ci.com/2017-06-19-trusty-updates-2017-Q2
> update travis according to their upgrade guidance.

- project/build.properties
I updated sbt version to 0.13.16.
> Bump sbt version to 0.13.16

- build.sbt
I updated machinist version to 0.6.2.
> Bump machinist version to 0.6.2

- build.sbt
I updated scalacheck version to 1.13.5.
> Bump scalacheck version to 1.13.5

- build.sbt
I updated discipline version to 0.8.
> Bump discipline version to 0.8

- docs/src/main/tut/typeclasses/typeclasses.md
> Add size control for typeclass diagram

- README.md
@kailuowang As discussed in https://github.com/durban/seals/issues/62.
> Add seals to related projects

- build.sbt
I updated scalatest version to 3.0.3.
> Bump scalatest version to 3.0.3

- build.sbt
I updated kind-projector version to 0.9.4
> Bump kind-projector version to 0.9.4

- project/plugins.sbt
> Update sbt-pgp to 1.1.0-M1

- README.md
as per https://mvnrepository.com/artifact/org.typelevel/alleycats-core_2.12
> Fix alleycats module name

- build.sbt
- core/src/main/scala/cats/Applicative.scala
- tests/src/test/scala/cats/tests/ApplicativeSuite.scala
> Remove Applicative#traverse and Applicative#sequence

- docs/src/main/tut/faq.md
> added entry for sbt-catalysts

- core/src/main/scala/cats/data/Ior.scala
> Add doctests for `Ior.fromOptions`

- .travis.yml
These patch versions include a [security update](http://www.scala-lang.org/news/security-update-nov17.html).
> Update to latest patch versions of scala

- scalafix/rules/src/main/scala/fix/Cats_v1_0_0.scala
Fixes #2136   
This is a workaround until we fix the problem upstream in Scalafix. See https://github.com/scalacenter/scalafix/issues/543
Tested locally with
```
scalafix github:gabro/cats/v1.0.0?sha=trailing-comma-fix
```
> Remove trailing comma in Scalafix rewrites as a workaround for #2136

- docs/src/main/tut/resources_for_learners.md
Seems to me to be a missing resource, I was wondering if you had considered this video already and have some sort of policy... up to you.
> adding validation video

- project/plugins.sbt
- version.sbt
mainly to merge in the version change commits
> merge 1.1.x back to master

- project/plugins.sbt
- project/project/plugins.sbt
ref https://gitter.im/typelevel/cats-dev?at=5ab0392be4d1c636041b5183
> Use helper addSbtCoursier in project/plugins.sbt

- project/Boilerplate.scala
> Specify the source of the autogenerated boilerplate

- README.md
We're very proud of our lowercase name 😆 
Thank you again for cats 🙏
> Pedantic case rename

- README.md
Adding ITV as an adopter of Typelevel Cats
> Adding ITV as an adopter

- README.md
We are using `cats` in production in various project and applications.
Anyone interested, you can apply to jobs listed on [our job board](https://workforus.theguardian.com/)
> Add the guardian to adopters

- README.md
Adds Earnest to Adopters List in README.md
> Add Earnest to Adopters List

- README.md
I wasn't sure if this should be based on master or #2392, so I'm happy to change it if I guessed wrong.
> add Dwolla to list of cats-users

- README.md
> Add Colisweb to adopters

- README.md
We have been using early version of cats in production for quite a while now
> Add Anduin Transactions as cats adopter

- README.md
I am the development manager for Basefarm, and I would like to add our company to the adopters list.
> Add Basefarm as adopter to README.md

- README.md
The syntax of capitalization versus lowercase was not exceptionally clear. Would Like some guidance on proper formatting.
Fixes https://github.com/ChristopherDavenport/cats-time/issues/11
> Add Various Projects to Ecosystem List

- docs/src/main/resources/microsite/data/menu.yml
- docs/src/main/tut/datatypes/chain.md
Some documentation for `Chain`. Partially adopted from the blog post I wrote recently, but with more detail and a short mention of `NonEmptyChain` as well.
> Add Chain docs

- README.md
Changing Year From 2017 => 2018
> Updating Year.

- docs/src/main/tut/typeclasses/typeclasses.md
First, thank you for the wonderful libraries and documentation.  
When reading the documentation I did not know what "point-wise" meant.  A quick Google search produced mathematical explanations that were a bit over my head.  I posted a question on the chat channel and @SystemFw provided a clear definition that I've included in this PR.
Perhaps others will not know what "point-wise" means and this addition will help them proceed with a little more understanding as they are working through the documentation.
It is kind of a long addition. I certainly understand if you'd like to keep the docs lean and pass on this PR. 
Thanks for all the hard work.
> Add definition of point-wise to README

- core/src/main/scala/cats/data/ContT.scala
- tests/src/test/scala/cats/tests/ContTSuite.scala
The PR was submitted before the scalafmt check was added to the build. 
Thus merging it broke build on master. This is to fix that.
> reformat code from old PR #2506

- CHANGES.md
- README.md
- project/plugins.sbt
- scripts/releaseNotes.scala
- version.sbt
> merge 1.5.x back to master

- PULL_REQUEST_TEMPLATE.md
> A bit clarification on PULL Request template

- README.md
> Add Reality Games to Adopters

- project/build.properties
> Update SBT 1.2.7

- README.md
> Add sup to ecosystem

- README.md
> added a community announcement section.

- README.md
> make the announcement section more prominent.

- alleycats-core/src/main/scala/alleycats/std/try.scala
> typo in Comanad[Try]

- README.md
> update the copyright

- README.md
> Update community announcements

- CHANGES.md
- README.md
- version.sbt
> Post 1.6.0-RC1 release, merge 1.6.x to master

- README.md
> added proposal for 2019 to announcements

- scripts/parse-test-durations.awk
> Fix minor typo in parse-test-durations.awk example

- README.md
> Add Packlink to the adopters list

- README.md
- ROADMAP_2019.md
> Publishing Roadmap 2019

- README.md
> Add Sigma to Cats adopters list

- ROADMAP_2019.md
> minor fix of road map - update link

- CHANGES.md
- build.sbt
- version.sbt
> Post 2.0.0-M1 Release

- CHANGES.md
> added availability information

- README.md
> Remove 'cats experimental' clause from README.md.

- build.sbt
> removing unused resolver

- README.md
> Add Netflix as users of Cats

- README.md
> added sponsors

- .travis.yml
- build.sbt
Just dependency updates, fixes #2864.
> Updates for 2.13.0-RC3

- docs/src/main/tut/resources_for_learners.md
> mention cats by example

- CHANGES.md
- README.md
> 2.0.0-M4 Post release

- README.md
> Update README.md to add phony library

- README.md
we use cats in many internal and external services
> add MYOB as Adopter

- build.sbt
Updated discipline deps. Note that target branch is 2.0.x to ease incoming release process. will merge the branch back to master after release.
> updated discipline

- README.md
- core/src/main/scala-2.13+/cats/instances/lazyList.scala
- core/src/main/scala/cats/Parallel.scala
- core/src/main/scala/cats/syntax/all.scala
- core/src/main/scala/cats/syntax/package.scala
- core/src/main/scala/cats/syntax/parallel.scala
- tests/src/test/scala/cats/tests/SyntaxSuite.scala
> merge master back into 2.0.x

- CHANGES.md
- README.md
- build.sbt
- version.sbt
Please use the merge with merge commit
> Post 2.0-RC1 Release merge 2.0.x back to master

- docs/src/main/tut/typeclasses/monad.md
Small, but maybe it will make someone's day better :)
> [DOC] Fix optionT link in monad documentation

- docs/src/main/tut/typeclasses/comonad.md
Fix typo in Comonad documentation
> Fix typo in Comonad documentation

- tests/src/test/scala/cats/tests/ParallelSuite.scala
> minor typo fixed

- core/src/main/scala-2.12-/cats/instances/ScalaVersionSpecificParallelInstances.scala
- core/src/main/scala-2.13+/cats/instances/ScalaVersionSpecificParallelInstances.scala
- laws/src/main/scala/cats/laws/NonEmptyParallelLaws.scala
- laws/src/main/scala/cats/laws/ParallelLaws.scala
- laws/src/main/scala/cats/laws/discipline/NonEmptyParallelTests.scala
- laws/src/main/scala/cats/laws/discipline/ParallelTests.scala
- tests/src/test/scala-2.13+/cats/tests/ScalaVersionSpecific.scala
- tests/src/test/scala/cats/tests/ParallelSuite.scala
> Merge master back to 2.0.x

- README.md
> added RBC Capital Markets as adopter

- README.md
- docs/src/main/tut/typeclasses/lawtesting.md
> minor update to the doc to include cats-testkit-scalatest

- README.md
> Add morphling to ecosystem

- README.md
We are using cats-effects extensively in few projects.
> Datum Brain added in adopters

- README.md
Hey all,
I haven't officially announced ScalaRL yet, but the project makes heavy use of Cats's typeclasses, so I wanted to make sure to include it here.
Thanks for everything!
> Add ScalaRL to Cats README

- docs/src/main/tut/typeclasses/comonad.md
> Correct some mistakes in Comonad documentatoin

- AUTHORS.md
> add hamednourhani to Authors.md

- docs/src/main/tut/faq.md
Took me a bit of time to figure out the current way to enable kind projector so this might be helpful for anyone else
> Update faq.md repl documentation

- docs/src/main/tut/typeclasses/alternative.md
> fix link to moniodK and Applicative

- docs/src/main/tut/datatypes/id.md
This fixes two broken links in the docs.
> Fix link to Monad and Comonad

- AUTHORS.md
- CHANGES.md
- README.md
- version.sbt
Includes the version and documentation updates.
> 2.1.0-RC1 follow-up

- README.md
> update links to sustainability program

- README.md
We have a lot of Cats at Permutive. :smile:
> Add Permutive to the adopters list

- AUTHORS.md
- CHANGES.md
- README.md
- version.sbt
This PR includes the release commit tagged by sbt-release—if you're merging it please be sure to choose the merge commit option.
> 2.1.0-RC2 follow-up

- docs/src/main/tut/datatypes/eithert.md
> Add ApplicativeError for EitherT documentation

- AUTHORS.md
- CHANGES.md
- README.md
- version.sbt
This PR includes the release commit tagged by sbt-release—if you're merging it please be sure to choose the merge commit option.
> 2.1.0-RC3 follow-up

- build.sbt
See https://github.com/typelevel/discipline-scalatest/releases/tag/v1.0.0-RC2.
> Update discipline-scalatest and scalatestplus dependency

- bench/src/main/scala/cats/bench/FoldMapABench.scala
- tests/src/test/scala/cats/tests/ApplicativeErrorSuite.scala
- tests/src/test/scala/cats/tests/MapSuite.scala
> Use dotty-friendly kind-projector placeholder

- docs/src/main/tut/datatypes/chain.md
> Fix typo on Chain docs

- README.md
> Please add hellosoda

- core/src/main/scala/cats/syntax/all.scala
- core/src/main/scala/cats/syntax/package.scala
- core/src/main/scala/cats/syntax/semigroupk.scala
> Backport `sum` from SemigroupK to scala_2.11 

- docs/src/main/tut/guidelines.md
This TODO is solved by fixing issue #2514. 
It is added as a separate chapter, but could also be elided.
> Remove TODO from guidelines

- core/src/main/scala/cats/syntax/partialOrder.scala
- tests/src/test/scala/cats/tests/PartialOrderSuite.scala
> Add partialComparison syntax

- README.md
> add Iterators to adopters

- .scalafmt.conf
- tests/src/test/scala/cats/tests/SyntaxSerializationSuite.scala
I thought #3433 would work after the big 2.5.2 update but it does need one code change.
> Scalafmt 2.5.3

- core/src/main/scala/cats/data/EitherT.scala
- core/src/main/scala/cats/data/IorT.scala
- core/src/main/scala/cats/data/OptionT.scala
- docs/src/main/tut/datatypes/eithert.md
- docs/src/main/tut/datatypes/iort.md
- docs/src/main/tut/jump_start_guide.md
- docs/src/main/tut/nomenclature.md
- tests/src/test/scala/cats/tests/EitherTSuite.scala
- tests/src/test/scala/cats/tests/IorTSuite.scala
- tests/src/test/scala/cats/tests/OptionTSuite.scala
> Revert "Add EitherT and IorT constructors from Option with monadic default"

- core/src/main/scala/cats/data/EitherT.scala
- core/src/main/scala/cats/data/Kleisli.scala
- core/src/main/scala/cats/data/OptionT.scala
- core/src/main/scala/cats/data/WriterT.scala
- tests/src/test/scala/cats/tests/KleisliSuite.scala
> Override map2Eval and combineKEval for monad transformers

- core/src/main/scala/cats/data/IndexedReaderWriterStateT.scala
This fixes master's formatting after https://github.com/typelevel/cats/pull/3336
> Fixed formatting on master

- README.md
- adding Wejo to the cats adopters list
> adding additional cats adopter to readme

- .scalafmt.conf
- tests/src/test/scala/cats/tests/RepresentableStoreSuite.scala
This https://github.com/typelevel/cats/pull/3513 just needed a formatting.
> Scalafmt-core 2.6.3

- README.md
> adding Hootsuite Inc. to the list of Adopters

- AUTHORS.md
- CHANGES.md
- README.md
- version.sbt
Merge commit, please, for the release tag.
> 2.2.0 follow-up

- docs/src/main/mdoc/typeclasses/applicativeerror.md
> Added and edited new applicativeerror.md

- laws/src/main/scala/cats/laws/DeferLaws.scala
- laws/src/main/scala/cats/laws/discipline/DeferTests.scala
It occurred to me that we can write a law relating defer and fix somewhat. It is a bit weak, but it is better than nothing.
> Add a law relating defer and fix in Defer

- README.md
Thank you for developing and maintaining Cats!
> docs: add Cleverbase as adopter

- .github/workflows/ci.yml
- build.sbt
Trivial build changes, basically.
> Updated for 3.0.0-M2

- free/src/main/scala/cats/free/Free.scala
> Add missing Free.liftK and Free.liftId #3707

- build.sbt
Context: https://gitter.im/typelevel/cats-dev?at=5fca59d6538b144f11d80143
> Use FastOptStage in tests

- README.md
> Update README (2019 -> 2021)

- core/src/main/scala/cats/data/EitherT.scala
Resolves https://github.com/typelevel/cats/issues/3741
> Improve scaladoc for EitherT.rethrowT

- kernel-laws/shared/src/test/scala/cats/kernel/laws/LawTests.scala
- kernel/src/main/scala/cats/kernel/Comparison.scala
> Monoid[Comparison] - lexographical ordering (take 2)

- core/src/main/scala/cats/data/NonEmptyChain.scala
- tests/src/test/scala/cats/tests/NonEmptyChainSuite.scala
> add NonEmptyChain.of

- build.sbt
Resolves https://github.com/typelevel/cats/issues/3780
> Set semver-spec version scheme in build.sbt

- CHANGES.md
> Fix year in changelog

- core/src/main/scala/cats/syntax/parallel.scala
- tests/src/test/scala/cats/tests/SyntaxSuite.scala
> Add syntax for parProduct* and parAp

- core/src/main/scala/cats/data/NonEmptyMapImpl.scala
- tests/src/test/scala/cats/tests/NonEmptyMapSuite.scala
Fixes #3377 
:warning: This is source-breaking!
> Replace Band instance for NonEmptyMap with a Semigroup instance consistent with SortedMap

- core/src/main/scala/cats/Align.scala
- core/src/main/scala/cats/data/Ior.scala
- tests/src/test/scala/cats/tests/IorSuite.scala
- tests/src/test/scala/cats/tests/SyntaxSuite.scala
> Add Ior.mergeWith and AlignMergeWith

- core/src/main/scala/cats/data/Nested.scala
- tests/src/test/scala/cats/tests/NestedSuite.scala
> Add Align instance for Nested

- core/src/main/scala/cats/Foldable.scala
- tests/src/test/scala/cats/tests/FoldableSuite.scala
> Add sumAll & productAll

- core/src/main/scala/cats/Show.scala
- tests/src/test/scala/cats/tests/ShowSuite.scala
> fix show interpolation ambiguity with Seq/List

- docs/src/main/mdoc/jump_start_guide.md
> Update 'Jump Start Guide' page to modern cats

- README.md
> Add Wolt in README adopters list

- build.sbt
https://www.scala-sbt.org/1.x/docs/Migrating-from-sbt-013x.html#Migrating+to+slash+syntax
> Apply Scalafix rule to migrate to sbt slash syntax

- kernel/src/main/scala/cats/kernel/Group.scala
Just a small typo, as far as I can tell.
> Fix GroupFunctions inheritance

- core/src/main/scala/cats/data/Tuple2K.scala
- tests/src/test/scala/cats/tests/Tuple2KSuite.scala
Had a use case at typelevel/cats-tagless#231
> Add Tuple2K firstK and secondK

- docs/src/main/mdoc/datatypes/writer.md
> Update broken link to log4cats project.

- README.md
> add Rewards Network to list of adopters

- README.md
> Adding new company name to README

- README.md
> [Documentation/README] Fix minor punctuation issue and add link to Typelevel Discord

- docs/src/main/mdoc/nomenclature.md
This PR updates `when` and `unless` to `whenA` and `unlessA`.
> Update nomenclature for Applicative

- .github/workflows/ci.yml
- build.sbt
> Upgrade versions of Scala 2.12 and Scala 2.13

- .github/workflows/ci.yml
- build.sbt
Trying to fix the ongoing build flakiness.
> Trying to fix the build flakiness

- README.md
Adding Medidata (https://www.medidata.com/) to the list of adopters
> Adding Medidata as an Adopter in the README.md

- README.md
> Added OVO Energy to the list

- README.md
> add ClearScore to Adopters

- build.sbt
> Thank you for contributing to Cats!
> This is a kind reminder to run `sbt +prePR` and commit the changed files, if any, before submitting.
The suggestion above is kind of a joke: `prePR` won't be successful until this PR gets merged :)
See also #4160 for more details.
> temporarily disable tlFatalWarningsInCi

- README.md
Using lots of cats to run our internal Spark as a Service!
> Add Cognite to list of adopters

- README.md
> Readme: Remove references to old Scala versions

- build.sbt
Follow-up to https://github.com/typelevel/cats/pull/4073. @danicheg and @satorg thank you for all of your work this cycle 🙏
> Add new maintainers to developer list

- build.sbt
Closes https://github.com/typelevel/cats/issues/510.
> Include laws in published API docs

- build.sbt
> remove unused version number

- README.md
- docs/index.md
> Fix readme

- docs/typeclasses/alternative.md
> Fix the nested unordered list HTML view of docs/typeclasses/alternative.md

- docs/datatypes/functionk.md
I just copy-pasted this header from the previous code block, same as in the other code examples.
> Add missing syntax highlightning

- ADOPTERS.md
We use Cats in Big Data projects with batch and stream processing.
> Add IPONWEB as an adopter

- core/src/main/scala/cats/data/Kleisli.scala
A tiny FunctionK helper, especially useful when combining Kleisli-based algebras to a unified input parameter
> Add `Kleisli.localK` `FunctionK` helper

- docs/algebra.md
xref https://github.com/typelevel/cats/pull/3979#issuecomment-1509747901
> Update Ring-like table in Algebra for Semifield added in #3979

- docs/typeclasses/foldable.md
copy with edit from [Foldable.scala](https://github.com/typelevel/cats/blob/main/core/src/main/scala/cats/Foldable.scala#L106)
> Add `foldr` note to `Foldable` doc

- core/src/main/scala/cats/instances/seq.scala
by using `Foldable.iterateRight`
Implements #4439
> Improve `foldRight` for `Seq` instance

- docs/nomenclature.md
> Fix `traverseWithIndex` => `traverseWithIndexM`

- core/src/main/scala/cats/Foldable.scala
- core/src/main/scala/cats/Inject.scala
- core/src/main/scala/cats/InjectK.scala
- core/src/main/scala/cats/data/Chain.scala
- core/src/main/scala/cats/data/Nested.scala
- core/src/main/scala/cats/data/Tuple2K.scala
- free/src/main/scala/cats/free/FreeT.scala
- kernel-laws/shared/src/main/scala/cats/kernel/laws/EnumerableLaws.scala
- kernel/src/main/scala/cats/kernel/instances/ListInstances.scala
- kernel/src/main/scala/cats/kernel/instances/StringInstances.scala
- laws/src/main/scala/cats/laws/discipline/ApplyTests.scala
- laws/src/main/scala/cats/laws/discipline/BitraverseTests.scala
- laws/src/main/scala/cats/laws/discipline/ContravariantMonoidalTests.scala
- laws/src/main/scala/cats/laws/discipline/ContravariantSemigroupalTests.scala
- laws/src/main/scala/cats/laws/discipline/InvariantMonoidalTests.scala
- laws/src/main/scala/cats/laws/discipline/InvariantSemigroupalTests.scala
- tests/shared/src/test/scala/cats/tests/FoldableSuite.scala
prepare Scala 2.13.12
- https://github.com/scala/scala/pull/10439
> add explicit type

- core/src/main/scala/cats/Functor.scala
As we agreed with @satorg in #4582
> Use syntax in Functor's doc examples

- tests/shared/src/test/scala-2/cats/tests/FunctionKLiftSuite.scala
- tests/shared/src/test/scala/cats/tests/FunctionKLiftCrossBuildSuite.scala
- tests/shared/src/test/scala/cats/tests/FunctionKLiftFuctionSuite.scala
A followup PR based on https://github.com/typelevel/cats/pull/4600#discussion_r1597788256
I could come up with a goofy name for the test suite only 🤦
> FunctionKLift cross compiled liftFunction suite

- docs/nomenclature.md
It's been here for at least 6 years 😱
> Fix foldLeft nomenclature signature

- ADOPTERS.md
We'd like to acknowledge cats in our usage.
> add Blue Insight Digital to ADOPTERS.md
