typelevel/cats

core/src/main/scala/cats/Applicative.scala, core/src/main/scala/cats/Apply.scala, core/src/main/scala/cats/Functor.scala
`sbt doc` currently fails with a bunch of errors like this:
```
error] /home/travis/code/projects/typelevel/cats/core/src/main/scala/cats/Applicative.scala:14: not found: type F
[error] @typeclass trait Applicative[F[_]] extends Apply[F] {
[error]                                                  ^
```
This means it's not possible to publish the project locally.
This is a [known Macro Paradise bug](https://github.com/scalamacros/paradise/issues/53#issuecomment-70427156)—it seems that any ScalaDoc comment on a trait or class definition that's been rewritten by a macro annotation will result in errors while producing the docs (even if it compiles just fine).
One option would be to disable ScalaDoc altogether, but this is only an issue in a few cases, so it's probably more practical simply …
=> Temporarily remove ScalaDoc comments on traits with macro annotations

build.sbt
Simulacrum only supports 2.11, so it's not possible to build this project for 2.10.4.
=> Remove 2.10.4 from cross-build configuration

laws/src/main/scala/cats/laws/Arbitrary.scala, laws/src/main/scala/cats/laws/ArbitraryK.scala, tests/src/test/scala/cats/tests/OrTests.scala
Also clean up ArbitraryK names:
* No abbreviations.
* Partially applied types are suffixed with the applied param names.
=> Test the functor laws of Or.

CONTRIBUTING.md, README.md
It still has a lot of TODOs, but I'm a fan of getting something out
there and letting people iterate on it. None of this is set in stone -
I'm fully expecting that even out of the small amount that's here people
will suggest improvements.
=> First draft/skeleton of a contributor guide

core/src/main/scala/cats/arrow/Kleisli.scala, core/src/main/scala/cats/free/Coyoneda.scala, core/src/main/scala/cats/free/Free.scala, core/src/main/scala/cats/free/Yoneda.scala, data/src/main/scala/cats/data/OneAnd.scala, project/plugins.sbt, scalastyle-config.xml, std/src/main/scala/cats/std/list.scala, std/src/main/scala/cats/std/set.scala, std/src/main/scala/cats/std/stream.scala
This addresses one of the requests made in #50.
I just kind of went with rules that seemed right for the project. People are free to suggest changes.
Currently one has to explicitly run the `scalastyle` or `test:scalastyle` task to check style. Adding linting to the compile task would probably be too slow. We could potentially add it to the test task, but I gave that a quick try and was having some trouble getting it to check the main source in addition to the test source with that approach. Once we have Travis CI integration, we should be able to run the linting without slowing down our compile or test tasks. It might still be worth making one uber sbt task to test and run linting, and I would encourage someone who understands SBT much better than I do to do so! :)
=> Add Scalastyle

laws/src/main/scala/cats/laws/ComonadLaws.scala, tests/src/test/scala/cats/tests/LawTests.scala
This is a first draft of the comonad laws. I copied the structure of `ComonadLaws` from `FunctorLaws`. One thing I don't like about it is that the laws are somewhat hidden between all those `Arbitrary` defs and the discipline glue code. I would love to move them right under the instance definition like scalaz does. The reason is that the instance definition is incomplete without the associated laws.
=> Add Comonad laws and check that Function0 satisfies them

core/src/main/scala/cats/Foldable.scala, core/src/main/scala/cats/MonoidK.scala, core/src/main/scala/cats/SemigroupK.scala
These are causing the build to fail both locally for me and [on Travis](https://travis-ci.org/non/cats/builds/49631620).
=> Remove imports now that we have package-level aliases

build.sbt, core/src/main/scala/cats/Foldable.scala, core/src/main/scala/cats/MonoidK.scala, core/src/main/scala/cats/SemigroupK.scala, core/src/main/scala/cats/arrow/Category.scala, core/src/main/scala/cats/arrow/Compose.scala, core/src/main/scala/cats/package.scala, core/src/main/scala/cats/syntax/eq.scala, core/src/main/scala/cats/syntax/order.scala, core/src/main/scala/cats/syntax/partialOrder.scala, data/src/main/scala/cats/data/Const.scala, data/src/main/scala/cats/data/Or.scala, laws/src/main/scala/cats/laws/ComonadLaws.scala, laws/src/main/scala/cats/laws/FunctorLaws.scala, macros/src/main/scala/cats/macros/Ops.scala
This commit adds cats-macros, upon which cats depends.
Right now, the only macros being used are Machinist's
operator macros, which are configured in cats.macros.Ops.
The punchline of doing this is that:
def xyz[A: Eq](x: A, y: A): Boolean =
x === y
is now exactly the same as:
def xyz[A](x: A, y: A)(implicit A: Eq[A]): Boolean =
A.eqv(x, y)
i.e. the syntax implicit conversions are completely erased.
This eliminates the performance penalty that syntax normally
implies. It also means the syntax classes don't need to be
value classes (or specialized) since they are not used at
runtime.
=> Set up Machinist, use macros for Eq through Order syntax.

data/src/main/scala/cats/data/Or.scala
The unidoc task was failing with "Could not find any member to link for "LeftOr" because
scaladoc for cats.data.Or is trying to to find LeftOr and RightOr in cats.data instead of cats.data.Or.
=> Fix Or's scaladoc references to LeftOr and RightOr.

core/src/main/scala/cats/FlatMap.scala
This commit adds some scaladoc for FlatMap -- in particular, I add
a brief explanation of why its useful to have FlatMap separated from
Monad and link to the discussion at https://github.com/non/cats/issues/3.
=> Add scaladoc for FlatMap.

data/src/main/scala/cats/data/Or.scala
We discussed on gitter that we don't like override keyword for
implementations of abstract methods.  This removes some IDE-generated
cruft.
=> Remove unnecessary overrides from `Or`.

tests/src/test/scala/cats/tests/StdTests.scala
This renames `LawTests` to `StdTests` (since it tests the instances of the  `std` package) and moves it into the `cats.tests` package where `ConstTests` and `OrTests` live.
=> Rename LawTests to StdTests

.travis.yml
Currently the scalastyle checks are not running on test source. Luckily
the test source all conforms!
=> Run test:scalastyle in Travis CI script

core/src/main/scala/cats/Applicative.scala, laws/src/main/scala/cats/laws/FunctorLaws.scala
Given on the [Haskell wiki](http://en.wikibooks.org/wiki/Haskell/Applicative_Functors) as `pure (.) <*> u <*> v <*> w = u <*> (v <*> w)`.
I think I have this right since it compiles and tests pass, but please review carefully - I want to make sure I didn't mess anything up.
Also this law is notably missing from scalaz, which makes me wonder if there is a good reason for that.
=> Add applicative composition law

core/src/main/scala/cats/arrow/Arrow.scala, core/src/main/scala/cats/functor/Profunctor.scala
what do you think about using dimap as a single abstract method instead of lmap and rmap?
Anyway if you want an efficient implementation you need to override all of them and if you don't care, you only need to implement one method
=> remove UpStar and DownStar and add doc for Profunctor

core/src/main/scala/cats/Applicative.scala, core/src/main/scala/cats/Apply.scala, core/src/main/scala/cats/CoFlatMap.scala, core/src/main/scala/cats/Comonad.scala, core/src/main/scala/cats/Functor.scala, core/src/main/scala/cats/functor/Invariant.scala, laws/src/main/scala/cats/laws/ApplicativeLaws.scala, laws/src/main/scala/cats/laws/ApplyLaws.scala, laws/src/main/scala/cats/laws/CoFlatMapLaws.scala, laws/src/main/scala/cats/laws/ComonadLaws.scala, laws/src/main/scala/cats/laws/FunctorLaws.scala, laws/src/main/scala/cats/laws/InvariantLaws.scala, laws/src/main/scala/cats/laws/discipline/Arbitrary.scala, laws/src/main/scala/cats/laws/discipline/ArbitraryK.scala, laws/src/main/scala/cats/laws/discipline/ComonadTests.scala, laws/src/main/scala/cats/laws/discipline/FunctorTests.scala, tests/src/test/scala/cats/tests/ConstTests.scala, tests/src/test/scala/cats/tests/OrTests.scala, tests/src/test/scala/cats/tests/StdTests.scala
This PR decouples the laws from the test code by adding a dedicated `Laws` class in the `cats.laws` package for each typeclass. The laws are stated such that they return a pair of values of the same type which will be equal for lawfull instances. The intention for this PR is to make the laws more visible by putting them in their own classes and by decoupling them from the test framework. See #81 for more details.
fixes #81
=> Decouple laws from discipline test code

core/src/main/scala/cats/free/Free.scala, core/src/main/scala/cats/free/Trampoline.scala, core/src/main/scala/cats/free/package.scala
Prior to this PR, in order to use `Trampoline`, you'd have to import the type alias from `cats.free.Free.Trampoline` and the object from `cats.free.Trampoline`. After this PR, 1 import serves both purposes.
=> Move cats.free.Free.Trampoline alias to cats.free package object

build.sbt, project/plugins.sbt
Enabling `autoAPIMappings` and adding `apiURL` means two things: first, the API docs URL will be added to the published POM, and any project that depends on cats can now (optionally) have references to cats types and methods automatically linked in its own API docs.
Second, once docs are published for algebra (and other cats dependencies), cats's documentation will get this same kind of automatic external linking. This didn't work with sbt-unidoc [until this morning's release](https://twitter.com/eed3si9n/status/564646946506567680), so I've also updated the sbt-unidoc version.
I've also included one tiny mostly unrelated change here—it would be best to use HTTPS for the homepage link, so I've changed that.
=> Add API mapping metadata and update sbt-unidoc

std/src/main/scala/cats/std/list.scala, tests/src/test/scala/cats/tests/RegressionTests.scala
This commit fixes this issue (which had to do with passing
arguments to G.map2 in the wrong order) and adds a regression
test to be sure we don't accidentally mess this up in the
future.
Fixes #140 
Review by @refried et al.
=> List's traverse method was applying effects in reverse.

.travis.yml, build.sbt
Attempting to publish currently fails during Scaladoc generation with a lot of "Could not find any member to link for…" errors, due to the fact that we have links across subprojects in the API docs (and that we treat warnings as failures).
It seems like `autoAPIMappings` should fix this, but it currently doesn't have any effect. It's possible to make automatic mapping work in this situation by jumping through [this hoop](http://stackoverflow.com/a/23177275/334519), but the fact that we don't really care about the `doc` task (since we're using `unidoc`) means it's probably simplest just to remove it from publishing.
I've also added `publishLocal` to the Travis build to help ensure that we don't break publishing in the future. It could be added to `validate` command alias, but it has wider …
=> Disable API doc generation when publishing

core/src/main/scala/cats/Fold.scala, core/src/main/scala/cats/Foldable.scala, core/src/main/scala/cats/syntax/foldable.scala, data/src/main/scala/cats/data/Const.scala, data/src/main/scala/cats/data/Or.scala, std/src/main/scala/cats/std/list.scala, std/src/main/scala/cats/std/map.scala, std/src/main/scala/cats/std/option.scala, std/src/main/scala/cats/std/set.scala, std/src/main/scala/cats/std/stream.scala, std/src/main/scala/cats/std/vector.scala, tests/src/test/scala/cats/tests/FoldableTests.scala
This method introduces a new data type, Fold[A]. This type
allows to programmer to decide whether to continue evaluating
the fold (and provide an appropriate continuation function),
or to return immediately.
This fixes #88
=> Renamed lazy foldRight to foldLazy, and made it stack-safe.

build.sbt
This is analogous to [this PR](https://github.com/non/algebra/pull/46) I just submitted for algebra. My #158 yesterday wasn't quite complete—it set up automatic API mapping to work for cats's dependencies, but not to publish the metadata for cats itself. I've confirmed that this fix publishes the metadata. Apologies for the noise—
=> Publish API mappings metadata

core/src/main/scala/cats/Monad.scala, laws/src/main/scala/cats/laws/ApplicativeLaws.scala, laws/src/main/scala/cats/laws/ApplyLaws.scala, laws/src/main/scala/cats/laws/CoFlatMapLaws.scala, laws/src/main/scala/cats/laws/ComonadLaws.scala, laws/src/main/scala/cats/laws/ContravariantLaws.scala, laws/src/main/scala/cats/laws/FlatMapLaws.scala, laws/src/main/scala/cats/laws/FunctorLaws.scala, laws/src/main/scala/cats/laws/InvariantLaws.scala, laws/src/main/scala/cats/laws/MonadLaws.scala, laws/src/main/scala/cats/laws/ProfunctorLaws.scala, laws/src/main/scala/cats/laws/discipline/ComonadTests.scala, laws/src/main/scala/cats/laws/discipline/FunctorTests.scala
This one adds `MonadLaws`. In order to let `MonadLaws` inherit laws from both `ApplicativeLaws` and `FlatMapLaws`, I reorganized the laws into traits instead of classes. I also added corresponding companion objects with a single `apply` method to create `Laws` instances more easily.
=> Add MonadLaws and organize laws in traits

core/build.sbt, core/src/main/scala/cats/syntax/apply.scala
This is a quick demonstration of a codegen-based alternative to #174's macro annotations for #162. The generated source should probably be properly indented, etc. before this would be a candidate for merging.
The advantage over using macro annotations is simplicity—macro annotations are pretty big guns for a little boilerplate-removal problem. The big disadvantage is that it's easier to make syntax errors in these strings than it would be if we had quasiquotes (although of course any errors would be caught by the compiler immediately after code generation).
The same treatment could be applied to `ApplyArityFunctions`, and the result would only be a little more complex.
=> Codegen demonstration for ApplyBuilder

core/src/main/scala/cats/Show.scala, std/src/main/scala/cats/std/anyval.scala, std/src/main/scala/cats/std/bigDecimal.scala, std/src/main/scala/cats/std/bigInt.scala, std/src/main/scala/cats/std/string.scala
In the long run Algebra will provide these instances,
but the situation right now is complex, so we will
paper things over here in Cats-land.
It also introduces a Show.ToStringShow[A] class that
can be used to provide Show[A] instances for concrete
types (this replaces many boilerplate definitions).
=> Add Group instances for numbers.

build.sbt
This pair of options seems to do the trick.
=> Fix source URLs in Scaladoc, closes #207

laws/src/main/scala/cats/laws/ApplicativeLaws.scala, laws/src/main/scala/cats/laws/CoflatMapLaws.scala, laws/src/main/scala/cats/laws/ComonadLaws.scala, laws/src/main/scala/cats/laws/ComposeLaws.scala, laws/src/main/scala/cats/laws/FlatMapLaws.scala, laws/src/main/scala/cats/laws/FunctorLaws.scala, laws/src/main/scala/cats/laws/MonadLaws.scala
This changes some minor stuff in the laws:
* use `andThen` in associativity laws since I think they are easier to read
with left-to-right composition
* add the Comonad identity laws with Cokleisli; analogous to the Monad
identity laws with Kleisli
* use IsEq in ComposeLaws
* link consistently to other laws with Scaladoc links
=> Minor laws cleanup

laws/src/main/scala/cats/laws/discipline/ApplicativeTests.scala, laws/src/main/scala/cats/laws/discipline/ApplyTests.scala, laws/src/main/scala/cats/laws/discipline/CoflatMapTests.scala, laws/src/main/scala/cats/laws/discipline/ComonadTests.scala, laws/src/main/scala/cats/laws/discipline/FlatMapTests.scala, laws/src/main/scala/cats/laws/discipline/FunctorTests.scala, laws/src/main/scala/cats/laws/discipline/InvariantTests.scala, laws/src/main/scala/cats/laws/discipline/MonadTests.scala, tests/src/test/scala/cats/tests/CokleisliTests.scala, tests/src/test/scala/cats/tests/ConstTests.scala, tests/src/test/scala/cats/tests/FutureTests.scala, tests/src/test/scala/cats/tests/KleisliTests.scala, tests/src/test/scala/cats/tests/OrTests.scala, tests/src/test/scala/cats/tests/StdTests.scala
This adds `FlatMapTests` and `MonadTests` so that we can finally check the `FlatMap` and `Monad` laws and it splits the existing `FunctorTests` and `ComonadTests` into separate tests for each typeclass so that each typeclass has its own `Laws` and `Tests` traits. The split results in a little bit more code but IMO makes those `Tests` traits a lot clearer and I think it should now also be easier to just add another `Tests` trait.
The discipline tests are implemented similarly to those in @mpilquist's Structures
=> Split discipline tests and add FlatMap and MonadTests

laws/src/main/scala/cats/laws/MonadFilterLaws.scala, laws/src/main/scala/cats/laws/discipline/MonadFilterTests.scala, tests/src/test/scala/cats/tests/StdTests.scala
This fixes one half of #135, namely adding laws and tests for `MonadFilter`.
=> Add laws/tests for MonadFilter

build.sbt
My initial motive is so that's what it reads in IntelliJ, but it's also
(possibly) nicer for certain commands in the sbt shell.
=> Change top, aggregating project id to cats.

README.md
This commit also standardizes the maintainers list order
using alphabetization by last name.
Review by @fthomas and @rossabaker.
=> Add Ross Baker and Frank Thomas as maintainers.

CONTRIBUTING.md, tests/src/test/scala/cats/tests/CatsSuite.scala, tests/src/test/scala/cats/tests/CokleisliTests.scala, tests/src/test/scala/cats/tests/ConstTests.scala, tests/src/test/scala/cats/tests/FoldableTests.scala, tests/src/test/scala/cats/tests/FutureTests.scala, tests/src/test/scala/cats/tests/KleisliTests.scala, tests/src/test/scala/cats/tests/LazyTests.scala, tests/src/test/scala/cats/tests/OrTests.scala, tests/src/test/scala/cats/tests/RegressionTests.scala, tests/src/test/scala/cats/tests/StdTests.scala
* Opinionated for consistency.
* DRY to support evolution of these opinions.
* Reduces boilerplate to encourage more tests.
=> Provide a common CatsSuite trait for cats.tests.

data/src/main/scala/cats/data/Cokleisli.scala, data/src/main/scala/cats/data/Kleisli.scala
This changes the names of some typeclass instances in `Kleisli` and `Cokleisli` according to the convention agreed upon in #27
=> Follow the naming convention for typeclass instances

build.sbt
It seems unnecessary to me to let `std` depend on `laws`.
=> Do not let std depend on laws

core/src/main/scala/cats/syntax/all.scala, core/src/main/scala/cats/syntax/package.scala, core/src/main/scala/cats/syntax/split.scala, laws/src/main/scala/cats/laws/SplitLaws.scala, laws/src/main/scala/cats/laws/discipline/Eq.scala, laws/src/main/scala/cats/laws/discipline/SplitTests.scala, tests/src/test/scala/cats/tests/FunctionTests.scala
This PR adds `SplitLaws`, `SplitTests`, and `SplitSyntax`. I'm submitting this PR although I'm not totally confident that the `splitInterchange` law I've defined is sound. I just tried to relate `split` with `andThen` in a minimal fashion. I've not seen this law anywhere else and I still want to check if it can be derived from the [arrow laws](https://hackage.haskell.org/package/base-4.7.0.2/docs/Control-Arrow.html).
Anyone know where `Split` is originally coming from and which laws it should obey?
=> Add SplitLaws, SplitTests, and SplitSyntax

core/src/main/scala/cats/Apply.scala, project/Boilerplate.scala, std/src/main/scala/cats/std/list.scala, tests/src/test/scala/cats/tests/RegressionTests.scala
Fixes #167
I think one thing that everyone agrees on is that if we are going to
require a predictable order of effects with apply2, map2, traverse, etc
that order should be left to right.
=> Swap effect order of apply2 and map2

build.sbt, core/src/main/scala/cats/functor/Strong.scala, laws/src/main/scala/cats/laws/StrongLaws.scala, laws/src/main/scala/cats/laws/discipline/SplitTests.scala, laws/src/main/scala/cats/laws/discipline/StrongTests.scala, tests/src/test/scala/cats/tests/FunctionTests.scala, tests/src/test/scala/cats/tests/KleisliTests.scala
This adds `StrongLaws` and `StrongTests`. Since Scalaz didn't have any laws for `Strong`, I had the chance to invent my own. The laws demand that `first` and `second` distribute over `dimap`:
```
first (dimap fab f g) = dimap (first fab) (first f) (first g)
```
The laws use the `Strong[Function1]` instance and therefore require the dependency on `std`.
=> Add StrongLaws and StrongTests

project/plugins.sbt
Was there a reason `sbt-pgp` version `0.8.3` was being used? According to [the docs](http://www.scala-sbt.org/sbt-pgp/), version `1.0.0` is acceptable for sbt versions 0.13.5+, and we're on sbt version 0.13.7.
Quick background /cc @milessabin and @ceedubs 
This turned out to actually be the cause of my sbt build issues earlier today. `0.8.3` brings in `dispatch-http_2.9.1` while `1.0.0` brings in `dispatch-http_2.10`. I had a global plugin using `1.0.0`, while the cats project was using `0.8.3`. And this caused the "conflicting cross-version suffixes" sbt build issue I was seeing.
=> Upgrades to sbt-pgp 1.0.0. This is recommended for sbt versions 0.13.5+

laws/src/main/scala/cats/laws/ArrowLaws.scala, laws/src/main/scala/cats/laws/discipline/ArrowTests.scala, tests/src/test/scala/cats/tests/FunctionTests.scala
Finally, the `ArrowLaws`. The laws and their names come from http://haskell.cs.yale.edu/wp-content/uploads/2012/06/FromJFP.pdf and https://wiki.haskell.org/Typeclassopedia#Laws_7
Btw: I can't believe I'm seriously proposing to add a function with 24 implicit parameters...
=> Add ArrowLaws and ArrowTests

docs/src/main/tut/applicative.md
Functor and Apply had links to non-existing .html files, which led to 404.
=> Updated links in applicative.md

data/src/main/scala/cats/data/Kleisli.scala, tests/src/test/scala/cats/tests/KleisliTests.scala
This adds `Arrow[Kleisli[F, ?, ?]]` and lowers the priority of `Strong[Kleisli[F, ?, ?]]` to not have ambiguous implicits.
=> Add Arrow instance for Kleisli

data/src/main/scala/cats/data/Kleisli.scala
A `Split[Kleisli[F, ?, ?]]` only requires a `FlatMap[F]` while `Arrow[Kleisli[F, ?, ?]]` (which also provides the `Split` instance) requires a `Monad[F]`.
=> Extract KleisliSplit from KleisliArrow

laws/src/main/scala/cats/laws/MonoidKLaws.scala, laws/src/main/scala/cats/laws/SemigroupKLaws.scala, laws/src/main/scala/cats/laws/discipline/MonoidKTests.scala, laws/src/main/scala/cats/laws/discipline/SemigroupKTests.scala, tests/src/test/scala/cats/tests/OptionTests.scala
Since laws are mixed in, this helps preventing name clashes, and it makes the Scaladoc more clear since the laws are then grouped by their typeclass, see:
http://non.github.io/cats/api/#cats.laws.MonadCombineLaws
The second commit removes an unnecessary test because the `alternative` `RuleSet` is included in the `monadCombine` `RuleSet`.
=> Prefix laws with the name of their typeclass

data/src/main/scala/cats/data/Cokleisli.scala, tests/src/test/scala/cats/tests/CokleisliTests.scala
This replaces `CokleisliStrong` with `CokleisliArrow` because both require a `Comonad` and adds `CokleisliSplit` which only requires a `CoflatMap`.
=> Add Arrow instance for Cokleisli

data/src/main/scala/cats/data/Xor.scala
- Removes `Xor#filter`, as the dependency on a `Monoid[A]` is ad-hoc
- Adds `orElse`, `valueOr`, and `ensure` methods to `Xor`
- Adds `Xor.fromOption`
- Miscellaneous ScalaDoc
- Miscellaneous formatting cleanup
=> Miscellaneous cleanup to Xor

core/src/main/scala/cats/data/Xor.scala, core/src/main/scala/cats/data/XorT.scala, laws/src/main/scala/cats/laws/discipline/Arbitrary.scala, laws/src/main/scala/cats/laws/discipline/ArbitraryK.scala, tests/src/test/scala/cats/tests/XorTTests.scala
Adds a transformer form of `Xor`.
Note that the `MonadFilter` and `MonadCombine` instances are included but commented out due to failing laws. @larsh has confirmed that this implementation matches Haskell's. We should look at the laws for these type classes and perhaps split them in to weak/strong characterizations.
This PR is missing lots of docs and tests. It is on par with `Xor` though, and I'd like to get this in so folks can work with the implementation in the development of weak/strong laws.
=> Adds cats.data.XorT transformer

core/src/main/scala/cats/Applicative.scala
Fixes #285.
Scalaz has a style convention that kinds always go before types in
method signatures. Should we adopt the same convention?
=> Swap order of G[_] and A in Applicative.sequence

docs/src/main/tut/freemonad.md
This renames `runPure` to `compilePure` which it is called later in the file and wraps the definition with tut sheds. Unfortunately `compilePure(program)` returns an empty `Map` instead of `Map(wild-cats -> 14)`. @mandubian pleas help :-)
=> Free doc: wrap compilePure in tut sheds

std/src/main/scala/cats/std/map.scala
This commit does a few different things:
1. Changes the flatMap implementation
2. Adds efficiency overrides for apply, apply2, map2
3. Does some reformatting
The first is the most important. I don't think the
existing implementation is predictable -- the result
you get will be highly-dependent on the order that
the maps are iterated over. The new implementation
should behave the same no matter the order.
The second change is a trade-off. I feel like it is
worth it for us to make the standard instances a bit
more verbose to help improve users' performance.
The format changes were primarily around readability.
For example, I worried about people trying to read
two levels of string interpolation in Show. Other
parts were just personal taste (i.e. using a
non-anonymous class).
=> Make some changes to the Map[K, ?] instances.

laws/src/main/scala/cats/laws/discipline/AlternativeTests.scala
This reverts a small change of #303 that wasn't necessary, see also https://github.com/non/cats/pull/303#discussion_r29773243.
=> Do not use explicit parameters for the Alternative laws

core/src/main/scala/cats/arrow/Arrow.scala, core/src/main/scala/cats/data/Cokleisli.scala, core/src/main/scala/cats/data/Kleisli.scala, std/src/main/scala/cats/std/function.scala
We can provide a default implementation of `split` in `Arrow` using `first` and `second` from `Strong`.
=> Provide a default implementation of split in Arrow

build.sbt
This replaces the very hacky static URL we were previously using.
=> Use algebra-0.2.0-SNAPSHOT dependency.

build.sbt, state/src/main/scala/cats/state/State.scala, state/src/main/scala/cats/state/package.scala, state/src/test/scala/cats/state/StateTests.scala, tests/src/test/scala/cats/tests/XorTTests.scala
Fixes #122.
To avoid stack overflows, a couple design choices were made that make
State more complicated than it seems like it should be.
State wraps F[S => F[(S, A)]] instead of the more familiar S => F[(S, A)]. This allows for effective trampolining.
State[S, A] is a type alias for StateT[Trampoline, S, A] to avoid stack
overflows that are easy to hit if Id is used instead of Trampoline.
State is currently in its own module because it depends on Free (for
trampolining) but doesn't seem to belong in the Free module. Since it's
tough to avoid trampolining in FP Scala, we may want to reconsider
whether Free should be in core.
There is a brief ScalaDoc comment on StateT, but a proper markdown file
should probably be created. If this gets merged, I can send a follow-up
PR with some more …
=> Add State/StateT

build.sbt
Defining both `scmInfo` and a `scm` element in `pomExtra` results in two `scm` elements in the poms. I've changed the `connection` value in `scmInfo` to what I understand to be the correct format.
=> Remove unnecessary SCM metadata

build.sbt
`tutSettings` is added twice to the docs setting. Adding it once should be enough, right?
=> Remove duplicated tutSettings

core/src/main/scala/cats/data/Validated.scala, tests/src/test/scala/cats/tests/ValidatedTests.scala
Ensure failures are combined in order. This required a bugfix.
Also test filter and fromTryCatch since these aren't covered by a typeclass instance and are complex enough to need comments.
Traverse laws are added in the separate PR for #224.
=> Tests for Validated.

free/src/main/scala/cats/free/Trampoline.scala, free/src/main/scala/cats/free/package.scala, state/src/main/scala/cats/state/State.scala, state/src/main/scala/cats/state/package.scala
As it stands, `State` causes strange behaviors like State.apply working
the first time, but failing the second time to find apply. See https://gist.github.com/eed3si9n/9804d496bfeb457282c2
@retronym pointed me to [SI-7139](https://issues.scala-lang.org/browse/SI-7139), which says that the REPL gets
confused about the type when there's a type alias and an object named
the same.
This adds the workaround posted on SI-7139, which is to move the name `State` into package object.
=> Move State companion to the package object

laws/src/main/scala/cats/laws/FoldableLaws.scala, laws/src/main/scala/cats/laws/TraverseLaws.scala, laws/src/main/scala/cats/laws/discipline/FoldableTests.scala, laws/src/main/scala/cats/laws/discipline/TraverseTests.scala, std/src/main/scala/cats/std/list.scala, std/src/main/scala/cats/std/vector.scala, tests/src/test/scala/cats/tests/ConstTests.scala, tests/src/test/scala/cats/tests/EitherTests.scala, tests/src/test/scala/cats/tests/FoldableTests.scala, tests/src/test/scala/cats/tests/IorTests.scala, tests/src/test/scala/cats/tests/ListTests.scala, tests/src/test/scala/cats/tests/MapTests.scala, tests/src/test/scala/cats/tests/OptionTests.scala, tests/src/test/scala/cats/tests/SetTests.scala, tests/src/test/scala/cats/tests/StreamTests.scala, tests/src/test/scala/cats/tests/ValidatedTests.scala, tests/src/test/scala/cats/tests/VectorTests.scala, tests/src/test/scala/cats/tests/XorTests.scala
Laws for Foldable:
- foldMap must be consistent with foldLeft
- foldMap must be consistent with foldRight
Laws for Traverse:
- identity
- sequential composition
- parallel composition
Added TraverseTests to std instances for:
- List
- Option
- Stream
- Vector
Added FoldableTests to std instances for:
- Set
Also fixed bugs in the Traverse instances for List and Vector.
They were using mutable state (ListBuffer/VectorBuilder) in traverse which caused them to fail tests of the parallel composition law.
=> 224 - Test Traverse and Foldable

core/src/main/scala/cats/Lazy.scala, laws/src/main/scala/cats/laws/ComonadLaws.scala, laws/src/main/scala/cats/laws/discipline/ArbitraryK.scala, laws/src/main/scala/cats/laws/discipline/ComonadTests.scala, laws/src/main/scala/cats/laws/discipline/EqK.scala, std/src/main/scala/cats/std/map.scala, tests/src/test/scala/cats/tests/FutureTests.scala
This commit adds some new laws, as well as adding an EqK[F[_]]
which makes it a bit easier to write tests. Like ArbitraryK,
EqK is defined in the laws module, rather than core.
It also adds some Eq and EqK instances that were previously
absent (the EqK instances are also in laws not core or std).
=> Add six new Comonad laws.

macros/src/main/scala/cats/macros/Ops.scala
This is a bit more friendly on the eyes. It also makes it easier to point someone to a description of the supported operations.
=> Use NameTransformer to encode op names

core/src/main/scala/cats/data/Kleisli.scala, tests/src/test/scala/cats/tests/KleisliTests.scala
I thought it was suspicious that `G[_]` doesn't have any bounds, then I realized the whole thing is implemented wrong. Added a simple test as well.
=> Fix Kleisli's lift method

core/src/main/scala/cats/syntax/apply.scala, core/src/main/scala/cats/syntax/semigroupk.scala
All but two places were using `fa: FA` for `Unapply` syntax methods.
=> Use consistent naming in unapply syntax

core/src/main/scala/cats/Unapply.scala, state/src/test/scala/cats/state/StateTests.scala, tests/src/test/scala/cats/tests/UnapplyTests.scala
This resolves an issue with ambiguous implicits that resulted in
Apply syntax not working on State. I imagine it probably also
helps syntax in a bunch of other cases.
The added unit test did not compile before this change.
=> Prioritize Unapply instances

build.sbt
Removed `tests, docs, bench` dependencies from `cats` module, and made the `tests` dependency in `state` internal so that it is not published in the POM
=> Fix cats POM dependencies

core/src/main/scala/cats/data/Const.scala
Const.show was outputting an extra } after the Const value as part of
the string generated. Updated code to render as Const(value) instead of
Const(value}), which is consistent with the other show methods.
This PR is kind of a test bed for me, I’m really just learning github and trying to get a feel for cats, which is where I came across the inconsistency in the text generated.
I’ve not added a test as part of this, but happy to add one. The only reason I have not added a test to verify the output is as expected is because it didn’t seem to fit with the other tests in ConstTest.scala which all seemed to be related to law checking, so I wasn’t sure whether you had alternative approach for these kinds of tests or not.
More than happy to create some tests around this (and the same for other …
=> Fixed typo in the output of Const.show

.travis.yml, build.sbt, std/src/main/scala/cats/std/stream.scala, tests/src/test/scala/cats/tests/FoldableTests.scala
Previously some of our dependencies were only available for
Scala 2.11. Since that is no longer the case, let's add
2.10.5 to the versions we build for.
=> Support building for 2.10 as well as 2.11.

docs/src/site/css/styles.css
If a user doesn't have any of the enumerated fonts, the code samples render in proportional width.  This restores the spirit of `<pre>` and `<code>` with a last resort.
=> Fallback to monospace font for code samples.

build.sbt, docs/src/main/tut/state.md
Fixes #314.
This is a reworked version of #379 based on some feedback I received. It still needs a little work explaining StateT and State's use of Trampoline, but I'd prefer for that to be handled after people are happy with the first part.
If you want to see the formatted version, it's currently posted [here](http://non.github.io/cats//tut/state.html). Sorry, I tried to push it to the gh-pages branch on my fork instead of the official repo (again), but still messed it up. It looks like I need to change my git settings, and that it isn't enough to change `git.remoteRepo`.
=> Add tut doc for State (take 2)

core/src/main/scala/cats/data/Kleisli.scala, core/src/main/scala/cats/data/package.scala, tests/src/test/scala/cats/tests/KleisliTests.scala
Changed Kleisli.kleisli to Kleisli.function for a more
generic name.. mostly to make ReaderT value alias usage
look a bit more natural.. ReaderT.function instead of
ReaderT.kleisli.
=> ReaderT and Reader type and value aliases, closes #382

README.md
Cody Allen suggested that since Adelbert has been very active
and helpful we should add him as a maintainer. I agree.
This PR adds him to the maintainers section in the README.
Assuming @adelbertc signs-off on this PR and no one objects
in the next few days, I'll add him as a committer.
=> Add Adelbert Chang to Cats maintainers.

state/src/main/scala/cats/state/State.scala, state/src/test/scala/cats/state/StateTests.scala
Similar to the extract method on the State companion object.
The name "extract" seems meaningful to me, but I realized that it
is a bit unfortunate that it's also the name of the method on
Comonad. Since State is implemented in terms of Trampoline, I thought
it might be kind of handy to have a runExtract method on StateT
that requires a Comonad and runs the State and extracts the value
in one go. This would make the name collision particularly unfortunate.
Anybody have any thoughts/ideas? One that comes to mind for me is
renaming the current State.extract to zoom.
=> Add extract method to State instances

build.sbt
In particular, this uses the first non-snapshot algebra
release (confusing numbered 0.2.1). It also updates
to Scala 2.11.7 as well as some test dependencies.
=> Update some version numbers.

CONTRIBUTING.md, docs/src/site/index.md
Currently the site docs point to an old snapshot, this updates the docs to point to the currently released version instead.
=> Released version on site

.travis.yml
https://github.com/travis-ci/travis-ci/issues/4527 has been fixed and we can remove the temporary workaround.
=> Remove temporary fix for travis-ci#4527

core/src/main/scala/cats/Eval.scala
This commit allows instances of Later[A] to "forget" the
thunk they use to lazily-evaluate their computation. This
means that expensive objects used to compute Later[A]
instances will be garbage-collected once the value is
computed.
Previously, a Later[A] instance would have held onto the
captured thunk, which in turn would have held onto its
captured objects. If those objects were large, this could
manifest as a larger-than-necessary memory footprint.
=> Optimize Later[A].

build.sbt, tests/js/src/test/scala/cats/tests/Platform.scala, tests/jvm/src/test/scala/cats/tests/Platform.scala, tests/shared/src/test/scala/cats/tests/CatsSuite.scala
These settings should fix the new intermittent test failures by reverting to scalatest 2.2.5 values. If successful, I shall raise issue to scalatest.
=> Set scalatest 3.0.0 defaults to mirror 2.2.5

README.md, core/src/main/scala/cats/FlatMap.scala, core/src/main/scala/cats/Show.scala, core/src/main/scala/cats/Unapply.scala, core/src/main/scala/cats/functor/Bifunctor.scala, core/src/main/scala/cats/std/anyval.scala, docs/src/main/tut/apply.md, docs/src/main/tut/functor.md, docs/src/main/tut/monad.md, docs/src/main/tut/semigroupk.md, docs/src/main/tut/typeclasses.md, docs/src/site/colophon.md, docs/src/site/index.md
This changes all occurences of "typeclass" to "type class" in user
visible places. Filenames or technical strings like "typeclasses.md"
or the Jekyll "typeclasses" section are not changed.
closes: #441
=> Make the spelling of "type class" consistent

docs/src/main/tut/semigroup.md
Even though Semigroup is defined in Algebra, it seems useful to provide some documentation for it here, as cats provides an alias.
=> Provide some documentation for Semigroup

docs/src/main/tut/freemonad.md
The reasons are:
- The version number would be mostly out of date because it currently
needs to be updated manually.
- We can assume that the reader has the "cats" module in their
libraryDependencies and all examples work with just this.
- Other docs don't have this.
see also #450
=> Remove section about adding cats-free to build.sbt

docs/src/main/tut/applicative.md, docs/src/main/tut/apply.md, docs/src/main/tut/id.md, docs/src/main/tut/monad.md, docs/src/main/tut/semigroupk.md
Documentation improvements I made while going through cats' documentation for the first time. 
* Adds many markup changes for inline code and references to other sections
* Revises explanation text to be more accessible for newcomers (hopefully!)
* Modifies explanation and code example comparing `Semigroup` vs `SemigroupK`
=> Improves miscellaneous items in documentation

docs/src/site/_layouts/default.html
Adds [MathJax TeX and LaTeX Support](http://docs.mathjax.org/en/latest/tex.html) for the documentation.
Example screenshot:
=> Add TeX and LaTeX support

core/src/main/scala/cats/data/Cokleisli.scala, core/src/main/scala/cats/data/Kleisli.scala, docs/src/main/tut/kleisli.md, laws/shared/src/main/scala/cats/laws/discipline/ArbitraryK.scala, tests/shared/src/test/scala/cats/tests/CokleisliTests.scala, tests/shared/src/test/scala/cats/tests/KleisliTests.scala
Replaced original `Semigroup` and `Monoid` instances for endomorphic `Kleisli` and `Cokleisli` with `SemigroupK` and `MonoidK` instances, and added additional Semigroup and `Monoid` instances to `Kleisli` that use an underlying `Semigroup` or `Monoid` instance. Updated the documentation to reflect this.
=> Fixed Semigroup and Monoid instances for Kleisli and Cokleisli (#477)

state/src/main/scala/cats/state/StateT.scala
This now lives within core, so we can use it directly instead of
requiring it as a parameter.
=> Remove Functor[Function0] constraint from state monad

free/src/main/scala/cats/free/Free.scala, free/src/main/scala/cats/free/FreeApplicative.scala, free/src/main/scala/cats/free/package.scala
* Have Free extend Product to avoid strange type inference
* FreeApplicative extends Product and Serializable to avoid strange type inference
* Make FreeApplicative.Ap a case class and remove type casing
* Remove FreeC type alias - Free uses Coyoneda behind the scenes so F[_] is unconstrained
=> Free touch up

core/src/main/scala/cats/syntax/all.scala, core/src/main/scala/cats/syntax/either.scala, core/src/main/scala/cats/syntax/option.scala, core/src/main/scala/cats/syntax/package.scala, core/src/main/scala/cats/syntax/xor.scala
Is there interest in the following syntax?
```scala
scala> none[Int]
res0: Option[Int] = None
scala> 1.some
res1: Option[Int] = Some(1)
scala> none[Int].toRightXor("a")
res2: cats.data.Xor[String,Int] = Left(a)
scala> 2.some.toRightXor("b")
res3: cats.data.Xor[String,Int] = Right(2)
scala> 3.some.toLeftXor("c")
res4: cats.data.Xor[Int,String] = Left(3)
scala> none[List[Int]].orEmpty
res5: List[Int] = List()
```
=> add a touch of OptionSyntax

docs/src/main/tut/validated.md
Fixed typo (hesistant -> hesitant)
Slight change of text (“validated separate” -> “validated separately”).
=> Minor documentation updates to validated.md

README.md
Add a button to the latest version of cats on maven central. Moved all buttons to page header.
If accepted, perhaps this could be merged _after_ @non has updated the travis build with ghpages login.
=> Add maven shield to README

docs/src/main/tut/foldable.md, docs/src/site/css/custom.css
@adelbertc's comment in #460 made me realise that Foldable doesn't currently have any docs.
Once again, these are largely based off the Scaladoc, with a few examples added. 
This was based on the branch for #460, but if for some reason, you don't want that and do want this, I'm happy to rebase.
=> Add some basic docs for Foldable

AUTHORS.md, CHANGES.md, build.sbt, version.sbt
I reviewed the git logs since v0.1.2 to find the relevant commits,
manually checked the commit authors against our current list, and
tried to summarize the work and changes that users should expect
to see.
For reference, the command I used was `git log v0.1.2..HEAD`.
(This PR also includes the version tags, and a change I needed to
make for the build to succeed.)
=> Topic/release notes 0.2.0

docs/src/main/tut/monoid.md
This is based on feedback from @adelbertc to a previous PR.
I've also changed 'typeclass' to 'type class'.
=> Add an example using foldMap on to a tuple

free/src/main/scala/cats/free/Free.scala
This makes it consistent with conventions used elsewhere in Cats.
=> Return Xor instead of Either in Free.resume

.travis.yml
Currently the Cats Travis build seems to be resolving and downloading SBT dependencies every run.  This uses the container based infrastructure to avoid having to cache assets between runs and so shorten builds.
Hat-tip to @rtyley for doing the grunt work of working out what these settings were on another project.
=> Cache SBT assets on Travis

core/src/main/scala/cats/std/future.scala, free/src/test/scala/cats/free/FreeTests.scala, laws/shared/src/main/scala/cats/laws/BimonadLaws.scala, laws/shared/src/main/scala/cats/laws/CoflatMapLaws.scala, laws/shared/src/main/scala/cats/laws/ComonadLaws.scala, laws/shared/src/main/scala/cats/laws/MonadLaws.scala, laws/shared/src/main/scala/cats/laws/discipline/BimonadTests.scala, laws/shared/src/main/scala/cats/laws/discipline/ComonadTests.scala, laws/shared/src/main/scala/cats/laws/discipline/EqK.scala, laws/shared/src/main/scala/cats/laws/discipline/MonadCombineTests.scala, laws/shared/src/main/scala/cats/laws/discipline/MonadErrorTests.scala, laws/shared/src/main/scala/cats/laws/discipline/MonadFilterTests.scala, laws/shared/src/main/scala/cats/laws/discipline/MonadReaderTests.scala, laws/shared/src/main/scala/cats/laws/discipline/MonadStateTests.scala, laws/shared/src/main/scala/cats/laws/discipline/MonadTests.scala, laws/shared/src/main/scala/cats/laws/discipline/package.scala, state/src/test/scala/cats/state/StateTTests.scala, tests/jvm/src/test/scala/cats/tests/FutureTests.scala, tests/shared/src/test/scala/cats/tests/FunctionTests.scala
The law requires that extract(pure(a)) = a.
This commit also updates the Monad* tests to use the new EqK
typeclass, and also relocates some laws from ComonadLaws to
CoflatMapLaws.
There is a fair amount of plubming that had to change to get
all of this working. A really important but thankless task
will be to go through all of our tests and use EqK and
ArbitraryK where possible to create a more consistent
experience. This will only get harder once we have a new
ScalaCheck release and we have to worry about Cogen as well.
=> Add a Bimonad law.

core/src/main/scala/cats/Foldable.scala
=> add combineAll alias for Foldable's fold

core/src/main/scala/cats/std/set.scala, tests/shared/src/test/scala/cats/tests/SetTests.scala
[gitter discussion](https://gitter.im/non/cats?at=55e23450fbbdfcbd3b5de06f)
=> add setMonoid

core/src/main/scala/cats/data/OptionT.scala, tests/shared/src/test/scala/cats/tests/OptionTTests.scala
Strikingly similar to `fromXor` found in `XorT`, this adds `fromOption` to `OptionT` wrapping the Option in the appropriate applicative.
=> Add fromOption to OptionT

free/src/main/scala/cats/free/Coyoneda.scala, free/src/test/scala/cats/free/CoyonedaTests.scala
Not sure what `by` does and how the implicit `F[A]` param would be used.
=> Add Coyoneda tests and remove `by`

free/src/test/scala/cats/free/FreeApplicativeTests.scala, state/src/test/scala/cats/state/WordCountTest.scala, tests/src/test/scala/cats/tests/EvalTests.scala, tests/src/test/scala/cats/tests/FoldableTests.scala, tests/src/test/scala/cats/tests/FuncTests.scala, tests/src/test/scala/cats/tests/KleisliTests.scala, tests/src/test/scala/cats/tests/ListTests.scala, tests/src/test/scala/cats/tests/RegressionTests.scala, tests/src/test/scala/cats/tests/UnapplyTests.scala, tests/src/test/scala/cats/tests/ValidatedTests.scala, tests/src/test/scala/cats/tests/XorTTests.scala, tests/src/test/scala/cats/tests/XorTests.scala
I grabbed the ones that I could easily grep for with `assert`. There are more that I want to change inside Scalacheck `forAll` blocks, but I think I'm going to make that a separate PR that introduces `GeneratorDrivenPropertyChecks` into `CatsSuite`.
=> Use type-safe equals checks in tests

build.sbt
Partial implementation for https://github.com/non/cats/issues/95. Example output [in gitter](https://gitter.im/non/cats?at=55fa781618e0111d7e4f4a8b)
If accepted, gh-pages will have to be pushed too.
=> Add diagrams to scaladoc

core/src/main/scala/cats/data/OneAnd.scala, tests/src/test/scala/cats/tests/OneAndTests.scala
```
scala> implicitly[Functor[NonEmptyList]]
<console>:27: error: ambiguous implicit values:
both method oneAndFunctor in trait OneAndInstances ...
and method oneAndMonad in trait OneAndInstances ...
match expected type cats.Functor[cats.data.NonEmptyList]
```
There were two bugs: one is that the Monad implicit
conflicts with the Functor implicit. The other is that
this construction doesn't work:
`object OneAnd extends OneAndInstances with OneAndLowPriority`
If it DID work, this ordering would give priority to the
implicits found in OneAndLowPriority, so it's reversed - but
more to the point, implicit priority isn't based on linearization.
One of the traits has to be a subtrait of the other to have
higher priority, and as written they had no relationship.
=> Adjust implicit priorities in OneAnd.

core/src/main/scala/cats/data/OneAnd.scala, tests/src/test/scala/cats/tests/OneAndTests.scala
Add `Semigroup` instance for OneAnd based on its `SemigroupK`.
I couldn't find any examples on how to write tests for this, so any help is appreciated.
=> Add Semigroup instance for OneAnd

core/src/main/scala/cats/std/anyval.scala
Fixes #301.
This was ignored for far too long (even though there was #301 for it).
We should really have test coverage on this. I say we merge this for now
but discuss whether this should just be coming from algebra and add
tests to whichever project it comes from.
=> Fix monoid zeros for Float/Double

CONTRIBUTING.md
- The second paragraph ended with the sentence "For more information, check out the contributor guide.", I've removed that sentence.
- The 4th and 5th paragraphs contained links to "#maintainers" even though there is no maintainers section in the contributor's guide, I've linked them to the #maintainers section of the readme
Fixes #550
=> Fix copy/paste errors in the contributor's guide

core/src/main/scala/cats/data/Ior.scala, core/src/main/scala/cats/data/Validated.scala, core/src/main/scala/cats/data/Xor.scala, core/src/main/scala/cats/data/XorT.scala, laws/src/main/scala/cats/laws/BifunctorLaws.scala, laws/src/main/scala/cats/laws/discipline/BifunctorTests.scala, tests/src/test/scala/cats/tests/IorTests.scala, tests/src/test/scala/cats/tests/ValidatedTests.scala, tests/src/test/scala/cats/tests/XorTTests.scala, tests/src/test/scala/cats/tests/XorTests.scala
- Create BifuncorLaws
- Create BifunctorTests
- Add Bifunctor instances for Validated, Ior, Xor, and XorT
- Add Bifunctor tests for Validated, Ior, Xor, and XorT
Fixes: 557
=> Introduce Bifunctor Laws

core/src/main/scala/cats/MonadError.scala, core/src/main/scala/cats/MonadReader.scala, core/src/main/scala/cats/MonadState.scala, core/src/main/scala/cats/data/Kleisli.scala, core/src/main/scala/cats/data/Xor.scala, core/src/main/scala/cats/data/XorT.scala, core/src/main/scala/cats/std/function.scala, core/src/main/scala/cats/std/future.scala, js/src/test/scala/cats/tests/FutureTests.scala, jvm/src/test/scala/cats/tests/FutureTests.scala, laws/src/main/scala/cats/laws/MonadErrorLaws.scala, laws/src/main/scala/cats/laws/MonadReaderLaws.scala, laws/src/main/scala/cats/laws/MonadStateLaws.scala, laws/src/main/scala/cats/laws/discipline/Eq.scala, laws/src/main/scala/cats/laws/discipline/MonadErrorTests.scala, laws/src/main/scala/cats/laws/discipline/MonadReaderTests.scala, laws/src/main/scala/cats/laws/discipline/MonadStateTests.scala, state/src/main/scala/cats/state/StateT.scala, state/src/test/scala/cats/state/StateTTests.scala, tests/src/test/scala/cats/tests/FunctionTests.scala, tests/src/test/scala/cats/tests/KleisliTests.scala, tests/src/test/scala/cats/tests/XorTTests.scala, tests/src/test/scala/cats/tests/XorTests.scala
I was working with MonadError today and the `F[_, _]` approach made me use
quite a few type lambdas when I was working with types like Future/Task.
Since the error type is already encoded as another type parameter, as
far as I know we don't really lose anything by using a type constructor
with a single parameter for `F`.
It's quite possible that there's a reason for using `F[_, _]`. If anyone
knows of one, please speak up.
=> Change MonadError from F[_, _] to F[_]

build.sbt
Increments scalacheck to version 1.12.5 fixing an annoying bug https://github.com/rickynils/scalacheck/issues/173 whereby scalacheck was preventing test arguments from being passed to the test runner.
=> Bump scalacheck version to 1.12.5

core/src/main/scala/cats/MonadError.scala, core/src/main/scala/cats/data/Xor.scala, core/src/main/scala/cats/data/XorT.scala, core/src/main/scala/cats/std/future.scala, js/src/test/scala/cats/tests/FutureTests.scala, jvm/src/test/scala/cats/tests/FutureTests.scala, laws/src/main/scala/cats/laws/MonadErrorLaws.scala, laws/src/main/scala/cats/laws/discipline/Arbitrary.scala, laws/src/main/scala/cats/laws/discipline/MonadErrorTests.scala
You should make me write unit tests and ScalaDocs for these before you
merge. I wanted to open a PR before I forgot about this though.
=> Add some helper methods to MonadError

free/src/test/scala/cats/free/CoyonedaTests.scala, free/src/test/scala/cats/free/YonedaTests.scala, state/src/test/scala/cats/state/StateTTests.scala, tests/src/test/scala/cats/tests/CatsSuite.scala, tests/src/test/scala/cats/tests/EitherTests.scala, tests/src/test/scala/cats/tests/FoldableTests.scala, tests/src/test/scala/cats/tests/IorTests.scala, tests/src/test/scala/cats/tests/KleisliTests.scala, tests/src/test/scala/cats/tests/ListTests.scala, tests/src/test/scala/cats/tests/NaturalTransformationTests.scala, tests/src/test/scala/cats/tests/OneAndTests.scala, tests/src/test/scala/cats/tests/OptionTTests.scala, tests/src/test/scala/cats/tests/StreamingTests.scala, tests/src/test/scala/cats/tests/ValidatedTests.scala, tests/src/test/scala/cats/tests/XorTTests.scala, tests/src/test/scala/cats/tests/XorTests.scala
This makes CatsSuite extend Scalatest's GeneratorDrivenPropertyChecks, which allows us to use Scalatest matches inside of our `forAll`-style generator-driven property checks.
Example:
```scala
test("OptionT[Id, A].isEmpty consistent with Option.isEmpty")(check {
forAll { o: Option[Int] =>
o.isEmpty == OptionT[Id, Int](o).isEmpty
}
})
```
```scala
test("OptionT[Id, A].isEmpty consistent with Option.isEmpty") {
forAll { o: Option[Int] =>
o.isEmpty should === (OptionT[Id, Int](o).isEmpty)
}
}
```
This allows us to drop the awkward `check` call and use a type-safe equals comparison.
For those of you looking at this and thinking "wow, I can't believe this person is meticulous enough to go through and change all of these": hi, I'm Cody; I don't believe we've met. In my defense, a vim macro or …
=> Use GeneratorDrivePropertyChecks in tests

core/src/main/scala/cats/data/Ior.scala, tests/src/test/scala/cats/tests/IorTests.scala
`(Option[A], Option[B]) => Option[A Ior B]`
=> Add Ior.fromOptions

core/src/main/scala/cats/Unapply.scala, tests/src/test/scala/cats/tests/UnapplyTests.scala
This commit adds Unapply shapes which will match a datum with a type in the
shape `F[X[_], Y]` with a typeclass expecting a `F[_]`
Thanks to @smungee who noticed that apply syntax was not working with
FreeApplicative because of this.
=> Add new shapes to Unapply

free/src/test/scala/cats/free/FreeApplicativeTests.scala
This is a test that is fixed by #568. I just thought it might be nice to have a regression test for the specific case that was discovered to not work before that PR.
Big thanks to @stew for the fix and @smungee for reporting the issue.
=> Add syntax test for |@| on FreeApplicative

free/src/main/scala/cats/free/FreeApplicative.scala, free/src/test/scala/cats/free/FreeApplicativeTests.scala
In trying to port the FreeApplicative example from @jdegoes's ScalaWorld
2015 talk[1] to cats, I found that cats does not have a
FreeApplicative.analyze method, which allows us to compile a
FreeApplicative into a monoid.
This commit adds FreeApplicative.analyze, as well as a new test for
this, as per a discussion on gitter [2].
[1] https://github.com/jdegoes/scalaworld-2015/blob/master/src/main/scala/asmfree.scala#L32
[2] https://gitter.im/non/cats?at=561ed5373a0d354869528194
=> Add FreeApplicative.analyze

core/src/main/scala/cats/data/Xor.scala
The whole point of orElse is to drop the left hand value of a Disjunction, no sense having the type that is dropped influence the resulting type.
Let me know if I am missing something! :-)
=> Improve the type signature of orElse

tests/src/test/scala/cats/tests/EvalTests.scala, tests/src/test/scala/cats/tests/FunctionTests.scala
Recreating PR: #583 from a fresh branch to clean commit history.
* Adds some law checking for the Eval Bimonad instance.
* Adds a check that the instance is also serializable
Additionally, in Function Tests
* Changes serializable test for Bimonad[Function0] to use Bimonad instance instead of Comonad instance.
Let me know if these make sense or if some additional checks would be better.
=> Add test of Bimonad laws for Eval

core/src/main/scala/cats/syntax/all.scala, core/src/main/scala/cats/syntax/option.scala, core/src/main/scala/cats/syntax/package.scala, core/src/main/scala/cats/syntax/validated.scala
Add syntax to values for lifting them into `Valid`, `Invalid` and the Nel versions of those. Currently no tests as I was unable to figure out which mechanism was preferred for testing syntax.
Let me know how that should be done.
Addresses #585.
=> Add syntax for validated.

core/src/main/scala/cats/data/OptionT.scala, core/src/main/scala/cats/data/Validated.scala, core/src/main/scala/cats/data/Xor.scala, core/src/main/scala/cats/data/XorT.scala
We currently have a few helper classes that have an `Aux` suffix
for emulating currying type parameters. These helper classes have
an `apply` method which allows some type parameters of a function
to be inferred while others need to be specified. @tpolecat has
nice explanation of this trick here:
http://tpolecat.github.io/2015/07/30/infer.html
Unfortunately the suffix `Aux` is an overloaded term that is most
prominently used to provide terser syntax for type refinements, e.g.:
```scala
type Aux[F[_], A, B] = Coyoneda[F, A] { type Pivot = B }
```
I'm wondering if we should use `Curried` instead of `Aux` for classes
that enable type parameter currying. This could make the purpose of
those classes clearer to those who are unfamiliar with this trick.
=> Rename *Aux helper classes to *Curried

core/src/main/scala/cats/data/Streaming.scala, core/src/main/scala/cats/syntax/all.scala, core/src/main/scala/cats/syntax/package.scala, core/src/main/scala/cats/syntax/streaming.scala, docs/src/main/tut/streaming.md, tests/src/test/scala/cats/tests/StreamingTests.scala
This tutorial mostly just shows some uses of Streaming[A].
It doesn't go as deeply as it could into the relationship
with Eval[A], or with things like Monad[A] and Traverse[A].
It also adds the Streaming syntax to implicits, and
renames concat to ++ for consistency.
This pull request replaces #548. Review by @ceedubs et al.
=> Added streaming.tut, a tutorial on cats.data.Streaming.

laws/src/main/scala/cats/laws/BimonadLaws.scala, laws/src/main/scala/cats/laws/discipline/BimonadTests.scala
These laws are taken from this paper:
http://arxiv.org/pdf/0710.1163v3.pdf
Thanks to @jedws and @tpolecat for bringing this up.
We may also want to remove one of our existing
laws (F.pure(F.extract(fa)) <-> fa), but for now
I have left it alone.
This fixes #595
=> Add two new laws for Bimonad.

core/src/main/scala/cats/data/OneAnd.scala, core/src/main/scala/cats/data/package.scala, laws/src/main/scala/cats/laws/discipline/Arbitrary.scala, tests/src/test/scala/cats/tests/ListWrapper.scala, tests/src/test/scala/cats/tests/OneAndTests.scala
This is a delayed follow up to #292 which sets a precedent of a
preference for higher-kinded types coming first in type parameters.
=> Swap type parameter order in OneAnd

laws/src/main/scala/cats/laws/BimonadLaws.scala, laws/src/main/scala/cats/laws/discipline/BimonadTests.scala
This picks up the question @non asked in https://github.com/non/cats/issues/595#issuecomment-153259535 and removes one of the `Bimonad` laws: `F.pure(F.extract(fa)) <-> fa`. @milessabin noted on Gitter that this law makes any `Bimonad` isomorphic to `Id` (modulo evaluation order) and I think that makes `Bimonad` less useful. For example, `NonEmptyList` which is both monadic and comonadic isn't a lawful `Bimonad` because of the above law and I think it could be a lawful `Bimonad` if we remove that law (but I haven't proved that).
If people find this law useful I'd suggest introducing another type class which extends `Bimonad` and has this additional law.
=> Remove Bimonad law: F.pure(F.extract(fa)) <-> fa

core/src/main/scala/cats/Eval.scala, core/src/main/scala/cats/Unapply.scala, core/src/main/scala/cats/data/Cokleisli.scala, core/src/main/scala/cats/data/Const.scala, core/src/main/scala/cats/data/Func.scala, core/src/main/scala/cats/data/Ior.scala, core/src/main/scala/cats/data/Kleisli.scala, core/src/main/scala/cats/data/OneAnd.scala, core/src/main/scala/cats/data/OptionT.scala, core/src/main/scala/cats/data/Prod.scala, core/src/main/scala/cats/data/Streaming.scala, core/src/main/scala/cats/data/StreamingT.scala, core/src/main/scala/cats/data/Validated.scala, core/src/main/scala/cats/data/WriterT.scala, core/src/main/scala/cats/data/Xor.scala, core/src/main/scala/cats/data/XorT.scala, core/src/main/scala/cats/functor/Invariant.scala, core/src/main/scala/cats/std/either.scala, core/src/main/scala/cats/std/future.scala, core/src/main/scala/cats/std/list.scala, core/src/main/scala/cats/std/option.scala, js/src/main/scala/cats/js/std/future.scala, jvm/src/main/scala/cats/jvm/std/future.scala, state/src/main/scala/cats/state/StateT.scala
This is related to #496, but it's a broader issue than just this change.
These instances traits/classes are used internally for code organization
and implicit prioritization, but they aren't really meant to be part of
the public API. Making them private/sealed may be helpful for binary
compatibility in the future. It also may be a helpful indicator to
newcomers which traits/classes are actually meant for consumption, so
they can ignore some of the noise.
So far, I have left the traits for orphans from `std` (such as
`StringInstances`), and I have left the omni-instance traits exposed.
=> Make a bunch of instances traits/classes private/sealed

core/src/main/scala/cats/data/XorT.scala, tests/src/test/scala/cats/tests/XorTTests.scala
This makes `toOption` on `XorT[F, A, B]` return `OptionT[F, B]` instead
of `F[Option[B]]`. This makes it symmetrical with `toRight` and `toLeft`
on `OptionT`. My assumption here is that if you are working with `XorT`
instead of `F[Xor...]` that you would also prefer to work with `OptionT`
rather than `F[Option[...]]`. And if not, it's easy enough to call
`.value`.
=> XorT.toOption returns an OptionT

core/src/main/scala/cats/NotNull.scala, core/src/main/scala/cats/data/Validated.scala, core/src/main/scala/cats/data/Xor.scala, docs/src/main/tut/traverse.md, docs/src/main/tut/xor.md, tests/src/test/scala/cats/tests/ValidatedTests.scala, tests/src/test/scala/cats/tests/XorTests.scala
This is the start of a fix for #591. So far I've only change `Xor`, because I wanted to run this approach by people. If people like this approach, then I can also update `Validated` and try to add some more tests to this PR.
I also renamed `fromTryCatch` to `catching`, because it's a bit less verbose and I like the sound of it a little more. I can change it back if people would prefer though.
=> Don't infer Null in fromTryCatch

core/src/main/scala/cats/data/Validated.scala
This is the same as #575 but for Validated instead of Xor.
=> Remove EE >: E constraint from Validated.orElse

core/src/main/scala/cats/data/OptionT.scala, core/src/main/scala/cats/std/option.scala, tests/src/test/scala/cats/tests/OptionTTests.scala, tests/src/test/scala/cats/tests/OptionTests.scala
The OptionT Show instance just uses the Show instance for the wrapped
`F[Option[A]]` as opposed to wrapping it in `OptionT(...)`. This is to
match the current behavior of `XorT`, but I'm wondering if that's
something we would want to change on both. It seems to me like the Show
output should reflect the fact that the value is wrapped in a monad
transformer, but I don't have particularly strong feelings about this.
=> Add Show for Option and OptionT

free/src/main/scala/cats/free/Free.scala, free/src/main/scala/cats/free/FreeApplicative.scala, free/src/main/scala/cats/free/Trampoline.scala
There are a couple of reasons this might be a good idea.
Currently it's possible to observe a difference when calling
`.map(identity)` on a `Free` instance:
```scala
scala> import cats.free._; import cats.implicits._
import cats.free._
scala> def f(x: Free[Option, Int]) = x match {
|   case Free.Pure(i) => i
|   case _ => 0
| }
f: (x: cats.free.Free[Option,Int])Int
scala> val x: Free[Option, Int] = Free.pure(3)
x: cats.free.Free[Option,Int] = Pure(3)
scala> f(x)
res0: Int = 3
scala> f(x.map(identity))
res1: Int = 0
```
Making these private also frees us up to change the internal
representation in the future without breaking user code.
=> Make Free/FreeApplicative constructors private

core/src/main/scala/cats/data/Validated.scala, tests/src/test/scala/cats/tests/ValidatedTests.scala
I think this was leftover from copy/paste from `Xor`. It mentions that
it's useful when using `Validated` in for-comprehensions, but you can't
actually use `Validated` in for-comprehensions since it doesn't have a
`flatMap` method :).
Also, `Xor` no longer has a `filter` method. It was removed in #276
since using the monoid zero when the predicate doesn't match is rather
arbitrary and can lead to surprises. I think we should follow that
precedent for `Validated`.
=> Remove Validated.filter

CHANGES.md
I just wrote up a draft of some release notes (rendered version [here](https://github.com/travisbrown/cats/blob/topic/0.3.0-release-notes/CHANGES.md)). I didn't do much synthesizing, but it seems like the nature of this release is that there are a lot of little improvements and additions that don't really fit into a bigger story.
Let me know if I'm missing anything important, or if we want to aim for less detail and more of a narrative.
Also @non, I don't see a `v0.3.0` tag, so I'm not sure exactly when you cut the release yesterday—we might need to mention a few other changes here if they made it in.
It'd be nice to include the release notes on the GitHub page for the tag as well (see e.g. [the last circe release](https://github.com/travisbrown/circe/releases/tag/v0.2.0)), since that …
=> Release notes for 0.3.0

core/src/main/scala/cats/data/Validated.scala, docs/src/main/tut/validated.md, docs/src/main/tut/xor.md, tests/src/test/scala/cats/tests/ValidatedTests.scala
Fixes #604.
This is essentially `flatMap` for `Validated`, but since `flatMap`
suggests monadic bind in Cats and this is not consistent with `ap`,
another name is being used.
This PR is not complete yet. I need to add a Scaladoc comment and tut documentation about this change. However, I figured there might be some discussion about the name of the method, so I want to wait until a name is decided to start writing docs :). Is `andThen` too overloaded?
=> Add Validated.andThen

core/src/main/scala/cats/data/OptionT.scala, core/src/main/scala/cats/data/XorT.scala, tests/src/test/scala/cats/tests/OptionTTests.scala, tests/src/test/scala/cats/tests/XorTTests.scala
As per [gitter discussion](https://gitter.im/non/cats?at=561f87d9c1c9c8640b034d75); proposing to add `transform` and `subflatMap` methods to `OptionT` and `XorT`. I suppose they should be in `StreamingT` as well but it's not currently obvious to me how to go about the implementation.
TODO:
=> Add transform and subflatMap to OptionT and XorT

core/src/main/scala/cats/data/Const.scala, core/src/main/scala/cats/data/Kleisli.scala, tests/src/test/scala/cats/tests/ConstTests.scala, tests/src/test/scala/cats/tests/KleisliTests.scala
I realise that this is very similar to @vikraman's work in #590, but I think this addresses the issues raised by @ceedubs and it was much easier to get this working against master than raising a PR onto that branch, thanks to the removal of `ArbitraryK`.
=> Add contravariant instances for Const and Kleisli

core/src/main/scala/cats/data/Kleisli.scala, tests/src/test/scala/cats/tests/KleisliTests.scala
=> Add explicit Id instances for Kleisli

core/src/main/scala/cats/package.scala, tests/src/test/scala/cats/tests/IdTests.scala
We should also be able to add a `Reducible` instance for `Id`, but I think that should wait for #629.
=> Add Traverse[Id] and Id law-checking

core/src/main/scala/cats/Eval.scala, tests/src/test/scala/cats/tests/EvalTests.scala, tests/src/test/scala/cats/tests/ListWrapper.scala
This makes `Eval` serializable and adds law-checking for its `Group`, `Monoid`,
`Semigroup`, `Order`, `PartialOrder`, and `Eq` instances.
Fixes #630.
=> Check more Eval instance laws

core/src/main/scala/cats/data/Kleisli.scala
It is the same as Kleisli.local.
Fixes #624.
=> Remove Kleisli.lmap

build.sbt, laws/src/main/scala/cats/laws/SerializableLaws.scala, tests/src/test/scala/cats/tests/CatsSuite.scala
I believe this change replaces #633.
=> Update simulacrum and change bricks to catalysts

core/src/main/scala/cats/data/Streaming.scala, core/src/main/scala/cats/data/StreamingT.scala
This helps type inference by fixing the least upper bound of subtypes of
Streaming(T).
Before:
```scala
scala> val x = if (true) Cons(1, Now(Streaming.empty[Int])) else Streaming.Empty[Int]()
x: Product with Serializable with cats.data.Streaming[Int] = Streaming(1, ...)
```
After:
```scala
scala> val x = if (true) Cons(1, Now(Streaming.empty[Int])) else Streaming.Empty[Int]()
x: cats.data.Streaming[Int] = Streaming(1, ...)
```
=> Streaming and StreamingT extend Product with Serializable

core/src/main/scala/cats/data/Streaming.scala, tests/src/test/scala/cats/tests/XorTTests.scala
Add a bunch of tests that XorT[Id, A, B] methods are consistent with
Xor[A, B].
=> Tests: XorT with Id as F should be consistent with Xor

core/src/main/scala/cats/data/WriterT.scala, laws/src/main/scala/cats/laws/discipline/Arbitrary.scala, tests/src/test/scala/cats/tests/WriterTTests.scala
This is a partial fix for #620. There are still more `WriterT` instances that could be added, but this is already a sizable PR, so I thought getting in the supertypes of `Monad` would be a good chunk of work to split off.
I've gone to fairly great lengths to ensure that implicit resolution works in various cases in the tests. Perhaps I've even gone a bit overboard, but I think that these tests are kind of necessary, because there are some inference issues with `Id` that are compounded by issues with type aliases. In fact I had to rework the prioritization hierarchy several times as these tests uncovered issues.
=> Add WriterT instances for supertypes of Monad

core/src/main/scala/cats/data/Prod.scala
This makes the `Prod` instances hierarchy names consistent with instances for
other data types. Mostly this is to make them easier to find with
grepping.
=> Change ProdInstance to ProdInstances for consistency

core/src/main/scala/cats/data/Xor.scala
Just noticed that the example didn't get the rename.
=> Fix outdated example in Scaladoc for catchOnly

core/src/main/scala/cats/syntax/bifunctor.scala, laws/src/main/scala/cats/laws/BifunctorLaws.scala, laws/src/main/scala/cats/laws/discipline/BifunctorTests.scala
This PR would add tests that should cover identity for the derived leftMap and rightMap on BiFunctor.
I guess this PR is exploratory:
* Is this a suitable use of the laws infrastructure? Seems to be a good use, but not sure if you would actually consider them laws.
Also:
* There is no syntax for leftMap and rightMap at this stage, just bimap; would it make sense to add these as syntax also. I’ve not done that in this PR, but if it is generally in line with what we want to do I can add.
=> Add tests to cover derived methods leftMap and rightMap on BiFunctor

tests/src/test/scala/cats/tests/IorTests.scala, tests/src/test/scala/cats/tests/XorTests.scala
Test that `Xor.to` and `Ior.to` are consistent with the less general
`toOption` and `toList` methods
=> Tests: Xor.to and Ior.to consistency

laws/src/main/scala/cats/laws/discipline/Arbitrary.scala
This still isn't a perfect Arbitrary instance for StreamingT, but I
think it will help us hit more test cases than the current
implementation. For example, I don't think the current instance ever
results in `Wait` instances.
@non could you please be one of the reviewers of this?
=> Make Arbitrary StreamingT more arbitrary

core/src/main/scala/cats/data/OptionT.scala, core/src/main/scala/cats/data/Prod.scala, core/src/main/scala/cats/data/StreamingT.scala, core/src/main/scala/cats/data/XorT.scala, core/src/main/scala/cats/syntax/bifunctor.scala, core/src/main/scala/cats/syntax/compose.scala, core/src/main/scala/cats/syntax/either.scala, core/src/main/scala/cats/syntax/eq.scala, core/src/main/scala/cats/syntax/flatMap.scala, core/src/main/scala/cats/syntax/foldable.scala, core/src/main/scala/cats/syntax/group.scala, core/src/main/scala/cats/syntax/monadCombine.scala, core/src/main/scala/cats/syntax/option.scala, core/src/main/scala/cats/syntax/order.scala, core/src/main/scala/cats/syntax/partialOrder.scala, core/src/main/scala/cats/syntax/profunctor.scala, core/src/main/scala/cats/syntax/semigroup.scala, core/src/main/scala/cats/syntax/split.scala, core/src/main/scala/cats/syntax/streaming.scala, core/src/main/scala/cats/syntax/strong.scala, core/src/main/scala/cats/syntax/traverse.scala, core/src/main/scala/cats/syntax/validated.scala, core/src/main/scala/cats/syntax/xor.scala, project/Boilerplate.scala, state/src/main/scala/cats/state/StateT.scala
Probably best to default to `final` and `private` until we run into a
reason to expose these for extension.
=> Make a bunch of classes final and a few private

core/src/main/scala/cats/data/StreamingT.scala, tests/src/test/scala/cats/tests/StreamingTTests.scala
And add a couple unit tests for take/drop on StreamingT
=> Add StreamingT tests and fix some uncovered bugs

laws/src/main/scala/cats/laws/ProfunctorLaws.scala, laws/src/main/scala/cats/laws/discipline/ProfunctorTests.scala, laws/src/main/scala/cats/laws/discipline/StrongTests.scala
This adds additional tests for Profunctor which utilise the laws
infrastructure to exercise the derived lmap and rmap operations.
=> Additional Profunctor tests covering lmap and rmap

core/src/main/scala/cats/data/XorT.scala, tests/src/test/scala/cats/tests/XorTTests.scala
=> Add PartialOrder and Eq instances for XorT

laws/src/main/scala/cats/laws/discipline/Arbitrary.scala
This commit does two things.
1. Use a frequency distribution in the `StreamingT` generator as
suggested by @non [here](https://github.com/non/cats/pull/649#issuecomment-156856211).
It is now twice as likely to generate a Wait as an Empty and 6 times as
likely to generate a Cons as an Empty.
2. Update the `Streaming` generator to be similar to the `StreamingT`
generator (use a frequency distribution generator of Empty, Wait, and
Cons).
=> Make Arbitrary Streaming instances more arbitrary

core/src/main/scala/cats/data/WriterT.scala, tests/src/test/scala/cats/tests/WriterTTests.scala
Knocks one item off of the checklist on #620.
=> Add WriterT Bifunctor

tests/src/test/scala/cats/tests/StreamingTests.scala
Previously many Streaming tests were always generating streams via
`fromList`. This meant that the Wait cases of streams were not getting
hit in tests.
Many of these tests now use an `Arbitrary[Streaming[A]]` instance to
generate streams, which should help hit the `Wait` case in tests.
=> Improve Streaming test coverage

core/src/main/scala/cats/data/Streaming.scala, tests/src/test/scala/cats/tests/StreamingTests.scala
This commit fixes a bug noticed by @ceedubs. The basic issue
is that we have to be sure to memoize the Eval instance holding
the tail while *also* memoizing the tail itself when it is
calculated. Previously we were only memoizing the head node.
=> Fix Streaming#memoization.

tests/src/test/scala/cats/tests/StreamingTests.scala
I haven't included the one that I posted in the description of #677
since I'm not yet sure what the right fix for it is.
=> Add some more Streaming tests

tests/src/test/scala/cats/tests/XorTTests.scala
There was a typo before that caused the XorT tests to only check the
Foldable laws for the Traverse instance.
=> Check Traverse laws for XorT

tests/src/test/scala/cats/tests/EitherTests.scala
I think we were trying to do this before, but the approach we were
taking was testing the Order instance instead of the Eq instance.
=> Add law-checking for Either Eq instance

core/src/main/scala/cats/data/Validated.scala
Am I correct in assuming that these were:
1.  supposed to say "validated"
2.  probably copy-paste errors
3.  in any case, not semantically meaningful, as they are usually imported as a group of implicits rather than individually?
=> Fix copy-paste naming errors (xor -> validated)

core/src/main/scala/cats/data/Streaming.scala, tests/src/test/scala/cats/tests/StreamingTests.scala
The .thunk method is not supposed to memoize the results,
allowing the caller to provide an impure function which
returns different values on different calls.
However, .thunk's definition used .knot with memoization,
which completely defeated the point. This commit removes
the memoization allowing this method to function correctly.
Fixes #677.
=> Fix bug with Streaming#thunk.

tests/src/test/scala/cats/tests/OptionTTests.scala
* Tests consistency between `flatMap` and `flatMapF`
* Tests consistency between `Show[OptionT]` instance and `OptionT.show`
=> Adds additional tests for Option T

core/src/main/scala/cats/std/function.scala, tests/src/test/scala/cats/tests/FunctionTests.scala
This PR address #684 by adding MonoidK and SemigroupK instances for Function1; it also adds a Semigroup instance for Funcion1.
=> Add MonoidK and SemigroupK instances for Function1 and also a Semigroup instance for Function1

core/src/main/scala/cats/arrow/NaturalTransformation.scala, docs/src/main/tut/freemonad.md, free/src/test/scala/cats/free/InjectTests.scala, tests/src/test/scala/cats/tests/NaturalTransformationTests.scala
I think this provides slightly nicer syntax for combining natural
transformations, and it makes it more consistent with `andThen` and
`compose`. If people like it, they can merge, but if not it's no
problem.
=> Move NaturalTransformation.or from companion to trait

core/src/main/scala/cats/data/WriterT.scala, tests/src/test/scala/cats/tests/ListWrapper.scala, tests/src/test/scala/cats/tests/WriterTTests.scala
* SemigroupK
* MonoidK
* Alternative
* MonadFilter
* MonadCombine
=> Add more WriterT instances

core/src/main/scala/cats/data/OptionT.scala, tests/src/test/scala/cats/tests/OptionTTests.scala
Reduces `OptionT` `MonadCombine` instance to `Monad`. 
The `MonadCombine` instance for `OptionT` was not tested and does not pass laws.
This addresses #693. 
#694 exists for tracking potential changes to laws which may allow this instance, or an alternative type class instance, to be reinstated.
=> Reduce OptionT from MonadCombine to Monad

scripts/travis-publish.sh
This PR is to add some documentation to the Travis build script based on the discussion in #699. 
I’ve just put some information in the script and I haven’t gone into a huge amount of detail. The main thing I wanted to capture was the rationale for building the JVM twice rather than once - which makes perfect sense once you understand the coverage tool; but confused me at first.
Happy to restructure or move elsewhere if that is preferred.
=> Add some documentation to the Travis script.

tests/src/test/scala/cats/tests/ConstTests.scala
Adds a test for `Show[Const]`, includes:
* Simple test of a specific value
* Test that all output starts with “Const(“
* Test that the `Show` for the result of `const.getConst` is contained in the result
* Test that implicitly obtained `Show` instance produces a result consistent with direct method invocation.
* Tests that retagging the `Const` does not affect the `Show` result
The last one raises an interesting question. The phantom type of the `Const` might be interesting enough information in some cases. The question is whether it is interesting enough to show.
Basically, `Const[Int, String]` and `Const[Int, Boolean]` produce the same show result. I implemented a test for the behaviour primarily to demonstrate that it is the case, and to raise a discussion on whether it warrants …
=> Adds test for Show[Const]

tests/src/test/scala/cats/tests/StreamingTTests.scala
Tests in `StreamingT` called `MonadCombineTests.monad` instead of `monadCombine`. 
Tests for `monadCombine` pass fine so increasing to test this.
=> Increase StreamingT tests from Monad to MonadCombine

core/src/main/scala/cats/data/XorT.scala
This trait is currently unused, because the implicit def that uses it is
commented out until we have separated weak/strong laws for `MonadCombine`. We probably shouldn't expose it if it doesn't satisfy our current `MonadCombine` laws.
=> Comment out unused XorTMonadCombine

docs/src/main/tut/oneand.md
Hi all, I wrote a quick introduction to the `OneAnd` data type.  It is not especially fancy but it should at least give a brief overview and is better than an empty page ;)
I'd be happy to apply any additions / modifications, so let me know.
Best,
Markus
-- 24pullrequests
[![](http://24pullrequests.com/assets/logo-8a77737f86fec8def19a1c9a605c9841dbd44e59f243ed3bf64bbdf3214d6fa1.png)](http://24pullrequests.com/)
=> Add documentation for `OneAnd`

docs/src/main/tut/apply.md, docs/src/main/tut/const.md, docs/src/main/tut/foldable.md, docs/src/main/tut/functor.md, docs/src/main/tut/kleisli.md, docs/src/main/tut/monad.md, docs/src/main/tut/monoid.md, docs/src/main/tut/semigroup.md, docs/src/main/tut/semigroupk.md, docs/src/main/tut/traverse.md, docs/src/main/tut/typeclasses.md, docs/src/main/tut/validated.md, docs/src/main/tut/xor.md
This PR adds the `:silent` modifier to code blocks that contain only definitions (and in a few cases splits mixed blocks). The resulting **tut** doc is much cleaner.
=> make tut doc ever so slightly less hideous

docs/src/main/tut/invariant.md
Adds a `tut` section about `Invariant` as discussed in #164.  I oriented the explanation according to @ceedubs example, I hope this is okay.
I wasn't able to test the `jekyll serve` because it fails on my pc due to a missing ruby dependency, so I am not sure if adding the file is enough to make it show up on the [typeclasses](http://non.github.io/cats//typeclasses.html) site?  If someone could check that that'd be great :).
If merged this fixes #164.
-- 24pullrequests
[![](http://24pullrequests.com/assets/logo-8a77737f86fec8def19a1c9a605c9841dbd44e59f243ed3bf64bbdf3214d6fa1.png)](http://24pullrequests.com/)
=> Documentation for the `Invariant` typeclass

core/src/main/scala/cats/data/Validated.scala, tests/src/test/scala/cats/tests/ValidatedTests.scala
Adds a `Monoid` instance for `Validated`
=> Adds Monoid instance for Validated

core/src/main/scala/cats/data/Validated.scala, tests/src/test/scala/cats/tests/ValidatedTests.scala
Added a `Semigroup` for `Validated` based on comment:
https://github.com/non/cats/pull/715#issuecomment-162326224
On a side note, I think there is at least one other `Monoid` instance (`Xor`) that has the same characteristics, i.e. no separate `Semigroup` instance . Seems based on the referenced comment it would be good to add these too?
=> Adds Semigroup for Validated

core/src/main/scala/cats/data/Const.scala, tests/src/test/scala/cats/tests/ConstTests.scala
Adding a `Semigroup` for `Const` to allow `Semigroup` behaviour for data
types with no valid `Monoid` instance.
=> Adds Semigroup for Const

core/src/main/scala/cats/data/Xor.scala, tests/src/test/scala/cats/tests/XorTests.scala
As per #716, adding a `Semigroup` for the `Xor` data type which currently
has a `Monoid` instance but no `Semigroup` instance.
=> Adds Semigroup for Xor

free/src/main/scala/cats/free/Free.scala, free/src/test/scala/cats/free/FreeTests.scala
This PR does a couple of things.
Firstly, it includes `Gosub` in the instances generated by the `Free` `Arbitrary` instance. This reveals a bug that caused the "mapSuspension id" test to fail.
It also reverts most of the changes made in #702. This fixes the failing "mapSuspension id" test and #712. Unfortunately, it comes at the cost of reintroducing the stack safety issue with `Free.foldMap`, and therefore I have its stack-safety unit test ignored for now. I'm hoping that we can address this issue with a separate PR in the future.
=> Revert regression in Free.foldMap

core/src/main/scala/cats/data/StreamingT.scala, tests/src/test/scala/cats/tests/StreamingTTests.scala
Before this, StreamingT was always returning "StreamingT(...)" for its
toString. It's now similar to Streaming in that it will return
"StreamingT()" in the case of Empty and will show the head element in
the case of Cons.
I also added a pretty weak test for its toString (which actually doesn't
capture my changes at all). It may be good to add further tests in the
future, but I've got to get to work, and I think this is at least an
improvement to the current status.
=> Make StreamingT toString more like Streaming toString

laws/src/main/scala/cats/laws/discipline/MonadFilterTests.scala
A `monadFilterConsistency` law was added in
8f7a110d536c087c8b70032103fb5a51fab5f34f but wasn't hooked up in the
tests. This might be better accomplished with something like #370, but
in the interim I think we should at least hook it up.
=> Add MonadFilter consistency to MonadFilter tests

tests/src/test/scala/cats/tests/OptionTests.scala
=> Test associativity of (Co)Kleisli composition

CONTRIBUTING.md
This PR looks to address #719 which was raised to add some guidance on test writing to the contributor guide related to conventions which have evolved over the course of cats development.
* Note, that there seems to be a mix of “type class” and “typeclass” used throughout the codebase/docs so I chose “type class”; happy to change if a decision has been made on that.
* This is far from perfect, but it’s a start and hopefully accurate.
=> Add some notes on conventions in test writing

core/src/main/scala/cats/data/Validated.scala, tests/src/test/scala/cats/tests/CoproductTests.scala, tests/src/test/scala/cats/tests/ValidatedTests.scala, tests/src/test/scala/cats/tests/XorTests.scala
Also add unit tests for similar methods on Xor and Coproduct.
=> Add Validated.swap

docs/src/main/tut/freemonad.md, docs/src/main/tut/invariant.md, docs/src/main/tut/monad.md, docs/src/main/tut/semigroup.md
In the documentation, most occurrences use "type class", but there are some occurrences of "typeclass" as well, this commit replaces all occurrences of "typeclass" with "type class" for a uniform naming.
-- 24pullrequests
[![](http://24pullrequests.com/assets/logo-8a77737f86fec8def19a1c9a605c9841dbd44e59f243ed3bf64bbdf3214d6fa1.png)](http://24pullrequests.com/)
=> typeclass -> type class

docs/src/main/tut/kleisli.md
The table in the docs for [Kleisli](http://non.github.io/cats//tut/kleisli.html) is not readable, because it is missing markup.  I added ``` such that the table should now display properly
-- 24pullrequests
[![](http://24pullrequests.com/assets/logo-8a77737f86fec8def19a1c9a605c9841dbd44e59f243ed3bf64bbdf3214d6fa1.png)](http://24pullrequests.com/)
=> Make table in Kleisli readable

laws/src/main/scala/cats/laws/discipline/MonadErrorTests.scala
`monadErrorHandleWith` was being checked twice, but the second one was
meant to be `monadErrorHandle`.
=> Fix monadErrorHandleWith/monadErrorHandle mix up in laws

tests/src/test/scala/cats/tests/OptionTests.scala
=> Add tests of kleisli left and right identity laws

project/plugins.sbt
see https://github.com/tpolecat/tut/issues/71 for more info
=> Remove now unnecessary tut resolver

core/src/main/scala/cats/SemigroupK.scala, tests/src/test/scala/cats/tests/ComposeTests.scala
+ Renamed SemigroupK composedWith to compose for consistency with
Applicative, Foldable, Reducible.
+ Fixed non-termination bug in SemigroupK compose(dWith).
+ Added tests for Applicative, Foldable, Reducible, SemigroupK
composition.
=> SemigroupK consistency and fix; added compose tests.

core/src/main/scala/cats/data/Coproduct.scala
Use `coflatMap` instead of `duplicate` to be consistent with `CoflatMap`
and make `CoproductComonad` extend `CoproductCoflatMap` to reduce a couple
duplicated methods.
@raulraja would you want to take a look at this one?
=> Minor cleanup to Coproduct

core/src/main/scala/cats/data/Cokleisli.scala, core/src/main/scala/cats/data/Kleisli.scala, core/src/main/scala/cats/data/package.scala, tests/src/test/scala/cats/tests/KleisliTests.scala
This method currently isn't used. Since `Cokleisli` is already a case
class with an equivalent auto-generated `apply` method, I don't think I
see the usefulness of it. Feel free to let me know if you would prefer
to keep this around.
=> Remove unused Cokleisli.cokleisli method

core/src/main/scala/cats/Eval.scala, tests/src/test/scala/cats/tests/FoldableTests.scala
I think that the awesome speed boost for `Eval` introduced by `Eval.Call` has broken the stack-safety of `Eval.defer` and that this is the reason that the `FoldableTestsAdditional` suite is failing now and then.
I have tried to reduce the stack consumption of `Eval.Call` by forcing thunks in such a way that the compiler can eliminate most of the stack.
=> Improve stack consumption of `Eval.Call`

docs/src/main/tut/xor.md, docs/src/site/_config.dev.yml, docs/src/site/_config.yml, docs/src/site/_layouts/default.html
I'm not super experienced with Jekyll but I took a shot at fixing some of the urls in the documentation by following the advice here in http://stackoverflow.com/a/21441767, there were duped slashes in the URLs that were really annoying me for no good reason. I took a cursory once-over if anything was 404'ing and couldn't find anything.
note: went ahead and deleted the `.config.dev.yml` since that wasn't working and testing with the regular `.config.yml` was good and dandy.
=> Fix docs duped url slashes

core/src/main/scala/cats/std/stream.scala, tests/src/test/scala/cats/tests/StreamTests.scala
Adds a `Show` instance for `Stream`.
Of note, unlike `Stream.toString`, this proposed implementation is referentially transparent.
A test exists for this property. 
I thought about adding some checks in that test to demonstrate that `toString` exhibits behaviour that violates referential transparency, but I thought that would be too brittle to included in this test, as if a future Scala version rectifies this behaviour in`Stream`, then the test might break, which might not be nice. It is straightforward to add something that shows this however.
=> Adds Show[Stream]

core/src/main/scala/cats/std/vector.scala, tests/src/test/scala/cats/tests/VectorTests.scala
Adds a `Show` instance for `Vector`.
=> Adds Show[Vector]

build.sbt
This change addresses the errors mentioned [here](https://gitter.im/non/cats?at=568e7fc7d739f50a360243c2).
The issue is that Unidoc supports cross-module links, but Scaladoc does not. Since we're using Unidoc, it's reasonable to want to be able to have links between modules, but the publish task will still use Scaladoc to create the docs for the javadoc.jar artifacts. Any cross-module links will result in warnings, which will currently fail the build.
This change makes all warnings non-fatal for Scaladoc, but then turns fatal warnings back on for Unidoc. This allows publishing to succeed even with cross-module link warnings from Scaladoc, but the build will still fail if Unidoc runs into warnings.
An alternative solution would be to use `publishArtifact in (Compile, packageDoc) := false` …
=> Make Scaladoc (but not Unidoc) warnings non-fatal

core/src/main/scala/cats/state/StateT.scala, core/src/main/scala/cats/state/package.scala, docs/src/main/tut/state.md, tests/src/test/scala/cats/tests/StateTTests.scala, tests/src/test/scala/cats/tests/WordCountTest.scala
This may provide the following benefits:
1) It should be a bit more efficient.
2) It removes the need to `import cats.std.function._` for some
operations, which may make it a bit more newcomer friendly.
3) We are already using Eval for things like foldRight, so it seems more
consistent to use it for `State`.
4) I think it's a bit easier to explain `Eval` than `Trampoline`, since
it's hard to explain the latter without first explaining `Free`. So
again, this may be a bit more newcomer friendly.
However, there may be downsides I haven't thought of. I thought I would throw this PR together for discussion. Thoughts?
=> Use Eval instead of Trampoline for State

core/src/main/scala/cats/Eval.scala
I think the existing implementation will retain a reference to the outer-most `Call` by referencing its ` cats$Eval$Call$$loop$1` member.  This patch makes `loop` private/static instead.
=> factor out a static inner method from #769 for better GC

core/src/main/scala/cats/Foldable.scala
- Also remove unused type parameter in sequence_
=> Add traverseU_ and sequenceU_

core/src/main/scala/cats/data/StreamingT.scala, tests/src/test/scala/cats/tests/StreamingTTests.scala
As reported by @liff [here](https://gitter.im/non/cats?at=5694ce218fdd3c0c382e20f1).
=> Fix StreamingT.filter bug

core/src/main/scala/cats/free/FreeApplicative.scala, tests/src/test/scala/cats/tests/FreeApplicativeTests.scala
=> Fix order of effects in FreeApplicative.foldMap

core/src/main/scala/cats/syntax/coproduct.scala, core/src/main/scala/cats/syntax/package.scala
Also add the missing `coproduct` syntax `object`.
=> Add ScalaDoc examples for Coproduct syntax

core/src/main/scala/cats/data/XorT.scala, tests/src/test/scala/cats/tests/XorTTests.scala
This PR adds `XorT#valueOr` which behaves similar to `Xor#valueOr`.
=> Add XorT#valueOr

core/src/main/scala/cats/data/XorT.scala
This PR makes `XorT#recoverWith` more readable.
=> Prettify XorT#recoverWith

core/src/main/scala/cats/ApplicativeError.scala, core/src/main/scala/cats/MonadError.scala, core/src/main/scala/cats/data/Validated.scala, laws/src/main/scala/cats/laws/ApplicativeErrorLaws.scala, laws/src/main/scala/cats/laws/MonadErrorLaws.scala, laws/src/main/scala/cats/laws/discipline/ApplicativeErrorTests.scala, laws/src/main/scala/cats/laws/discipline/MonadErrorTests.scala, tests/src/test/scala/cats/tests/ValidatedTests.scala
This is a follow-up to [a question](https://gitter.im/non/cats?at=56983e475de13b3f15e3263c) I asked on Gitter a few days ago.
The basic idea is that it seems useful to be able to abstract over `Validated[E, ?]` as a context in which errors can be raised and handled, but `Validated` isn't monadic, so we can't provide a `MonadError` instance. None of the `MonadError` operations require monadic binding, though, and at least in the case of `Validated[E, ?]` there are reasonable implementations. The only `MonadError` law we lose is the left zero law.
This PR adds an `ApplicativeError` type class above `MonadError`, together with laws for `ApplicativeError` and an instance and tests for `Validated`. Current `MonadError` usage should be unaffected.
=> Add ApplicativeError

core/src/main/scala/cats/std/vector.scala, tests/src/test/scala/cats/tests/VectorTests.scala
This PR brings the `CoflatMap` typeclass instance for `Vector`.
Here an example session:
```
scala> :paste
// Entering paste mode (ctrl-D to finish)
import cats._, cats.std.all._, cats.syntax.coflatMap._
def foo(vector: Vector[Int]) = vector map (_ + 1)
def bar(vector: Vector[Int]) = vector map (_ - 1)
scala> Vector(1).coflatMap(foo(_))
res0: Vector[scala.collection.immutable.Vector[Int]] = Vector(Vector(2))
scala> Vector(1).coflatMap(bar(_))
res1: Vector[scala.collection.immutable.Vector[Int]] = Vector(Vector(0))
```
@non @ceedubs @adelbertc @milessabin Thanks for your consideration.
=> Request to Add CoflatMap Instance for Vector

build.sbt, core/src/main/scala/cats/Foldable.scala, core/src/main/scala/cats/SemigroupK.scala, core/src/main/scala/cats/Show.scala, core/src/main/scala/cats/functor/Invariant.scala
Simulacrum 0.6.1 was just released. Type classes automatically extend `Any` and `Serializable` now, so explicit declarations of these super types are not necessary any longer.
=> Upgrade to simulacrum 0.6.1

core/src/main/scala/cats/data/OneAnd.scala, tests/src/test/scala/cats/tests/OneAndTests.scala
This PR adds `Traverse` instance for `OneAnd[F, ?]` where `F: Traverse`
=> Traverse instance for OneAnd

docs/src/main/tut/optiont.md
Fixed a small error I noticed where Option[Future[String]] was supposed to say Future[Option[String]]. Also added a "]" where one was missing.
I'm really interested in this project so I'll probably be reading a lot of the documentation. I'll try to keep an eye out for things like this as I go.
=> Fix two small errors in OptionT docs

core/src/main/scala/cats/data/OneAnd.scala
I didn't add a test for `oneAndReducible` because I couldn't find tests for `Reducible`.  If they're here already, could you point me to them?
Because the new type suggested a name change, I left a `Foldable` instance in as `@deprecated`, non-`implicit`.  Let me know if I should do something else.
=> add Reducible instance for OneAnd, deprecate Foldable instance

core/src/main/scala/cats/MonadCombine.scala, core/src/main/scala/cats/MonoidK.scala, core/src/main/scala/cats/SemigroupK.scala, core/src/main/scala/cats/arrow/Category.scala, core/src/main/scala/cats/arrow/Compose.scala, core/src/main/scala/cats/data/Cokleisli.scala, core/src/main/scala/cats/data/Kleisli.scala, core/src/main/scala/cats/data/OneAnd.scala, core/src/main/scala/cats/data/Prod.scala, core/src/main/scala/cats/data/Streaming.scala, core/src/main/scala/cats/data/StreamingT.scala, core/src/main/scala/cats/data/WriterT.scala, core/src/main/scala/cats/data/XorT.scala, core/src/main/scala/cats/std/function.scala, core/src/main/scala/cats/std/list.scala, core/src/main/scala/cats/std/option.scala, core/src/main/scala/cats/std/set.scala, core/src/main/scala/cats/std/stream.scala, core/src/main/scala/cats/std/vector.scala, docs/src/main/tut/semigroupk.md, laws/src/main/scala/cats/laws/MonadCombineLaws.scala, laws/src/main/scala/cats/laws/MonoidKLaws.scala, laws/src/main/scala/cats/laws/SemigroupKLaws.scala, tests/src/test/scala/cats/tests/ListWrapper.scala
=> Rename SemigroupK.combine to combineK

build.sbt, core/src/main/scala/cats/Apply.scala, core/src/main/scala/cats/FlatMap.scala, core/src/main/scala/cats/data/Const.scala, core/src/main/scala/cats/data/Func.scala, core/src/main/scala/cats/data/Kleisli.scala, core/src/main/scala/cats/data/OneAnd.scala, core/src/main/scala/cats/data/Prod.scala, core/src/main/scala/cats/data/Validated.scala, core/src/main/scala/cats/data/WriterT.scala, core/src/main/scala/cats/data/XorT.scala, core/src/main/scala/cats/free/FreeApplicative.scala, core/src/main/scala/cats/package.scala, core/src/main/scala/cats/std/map.scala, docs/src/main/tut/apply.md, docs/src/main/tut/const.md, docs/src/main/tut/validated.md, laws/src/main/scala/cats/laws/AlternativeLaws.scala, laws/src/main/scala/cats/laws/ApplicativeLaws.scala, laws/src/main/scala/cats/laws/ApplyLaws.scala, laws/src/main/scala/cats/laws/FlatMapLaws.scala, laws/src/main/scala/cats/laws/TraverseLaws.scala, project/Boilerplate.scala, tests/src/test/scala/cats/tests/RegressionTests.scala, tests/src/test/scala/cats/tests/SyntaxTests.scala, tests/src/test/scala/cats/tests/ValidatedTests.scala
This is a follow-up to #821 that rebases @lukewyman's changes, makes some fixes supported by the new version of Simulacrum, and updates the docs.
Note that I've renamed `ap` on `CartesianBuilderN` to `apWith` to avoid confusion (since the function comes after the arguments in that case).
=> Reverse order of arguments for ap

core/src/main/scala/cats/data/StateT.scala, core/src/main/scala/cats/data/package.scala, core/src/main/scala/cats/state/package.scala, docs/src/main/tut/state.md, tests/src/test/scala/cats/tests/FreeApplicativeTests.scala, tests/src/test/scala/cats/tests/StateTTests.scala, tests/src/test/scala/cats/tests/WordCountTest.scala
This is a partial partial fix for #785. So far I've moved `state` but not `free`. There are several different types within the `free` package, so it might warrant its own package. However, `State`/`StateT` was just sitting in the `state` package by itself, so I've gone ahead and moved it (so it now parallels `Writer/WriterT`).
=> Move State to data package

docs/src/main/tut/freemonad.md
This resolves #804.
I also updated the "pure" compiler to use `State`. It previously had
said that a pure compiler couldn't be written and used with `foldMap`,
but that's not really true if you use something like `State`. I think
this is probably a cleaner and more useful solution.
@mandubian @raulraja would you be available to review?
=> Update free monad docs

CHANGES.md
I'll update if any last-minute stuff makes it in before the release. Rendered version available [here](https://github.com/travisbrown/cats/blob/topic/0.4.0-release-notes/CHANGES.md) for now.
=> Draft of 0.4.0 release notes

CHANGES.md, CONTRIBUTING.md, README.md, docs/src/site/index.md
…and also the organization change.
=> Update README and other documents for 0.4.0

docs/src/main/tut/contravariant.md, docs/src/main/tut/invariant.md
Preview http://vpavkin.github.io/cats/tut/contravariant.html
=> Add Contravariant documentation page

core/src/main/scala/cats/data/Streaming.scala, core/src/main/scala/cats/data/StreamingT.scala, laws/src/main/scala/cats/laws/discipline/Arbitrary.scala
Default `Int => Boolean` in scalacheck just returns a function which
always returns the same value (`true` or `false`). This means that
operations like `dropWhile` are not tested accurately, as whilst the bounds (all `true` and all `false`) are checked, intermediate results which return different values based on input are not tested.
This fix creates a temporary `Arbitrary` instance for `Int => Boolean` and fixes the `dropWhile` on `Streaming` and `StreamingT` which were broken, and didn’t show up due to the deficiency in the `Arbitrary[Int => Boolean]` instance provided by scalacheck.
Maybe there is a better way to do these instances? This kind of hardcodes that the `Int => Boolean` returned is always just a comparison between the `Int` values, but seems better than always …
=> Fix Streaming and StreamingT dropWhile functions

core/src/main/scala/cats/TransLift.scala, core/src/main/scala/cats/data/Kleisli.scala, core/src/main/scala/cats/data/OptionT.scala, core/src/main/scala/cats/data/StateT.scala, core/src/main/scala/cats/data/StreamingT.scala, core/src/main/scala/cats/data/WriterT.scala, core/src/main/scala/cats/data/XorT.scala, core/src/main/scala/cats/syntax/all.scala, core/src/main/scala/cats/syntax/package.scala, core/src/main/scala/cats/syntax/transLift.scala, tests/src/test/scala/cats/tests/TransLiftTests.scala
This typeclass adds a `liftT` function which is similar to the liftM
function on the scalaz MonadTrans typeclass, however this one takes into
account that you might not need the power of a monad in order to be able
to lift into a transformer, for example, we are able to Lift any M[A]
into a Kleisli[M, B, A] regardless of whether or not M is a Monad,
Functor, or any other such thing. Thish would be useful in cases where
you are constructing an applicative computation using values for which
you don't have a monad.
=> Adds a new LiftTrans typeclass

core/src/main/scala/cats/Bifoldable.scala, core/src/main/scala/cats/MonadCombine.scala, core/src/main/scala/cats/data/Const.scala, core/src/main/scala/cats/data/Xor.scala, core/src/main/scala/cats/std/all.scala, core/src/main/scala/cats/std/either.scala, core/src/main/scala/cats/std/package.scala, core/src/main/scala/cats/std/tuple.scala, core/src/main/scala/cats/syntax/all.scala, core/src/main/scala/cats/syntax/bifoldable.scala, core/src/main/scala/cats/syntax/package.scala, laws/src/main/scala/cats/laws/BifoldableLaws.scala, laws/src/main/scala/cats/laws/discipline/BifoldableTests.scala, tests/src/test/scala/cats/tests/ConstTests.scala, tests/src/test/scala/cats/tests/EitherTests.scala, tests/src/test/scala/cats/tests/MonadCombineTests.scala, tests/src/test/scala/cats/tests/SyntaxTests.scala, tests/src/test/scala/cats/tests/TupleTests.scala, tests/src/test/scala/cats/tests/XorTests.scala
Also:
- Add MonadCombine separate
- Add serializability check for Bifunctor[Xor]
=> Add Bifoldable, fixes #94

core/src/main/scala/cats/data/StateT.scala, tests/src/test/scala/cats/tests/StateTTests.scala
This gets the input state without modifying the state component.
=> Add .get method to StateT

core/src/main/scala/cats/std/vector.scala
* Check size equality first.
* Avoid pattern matching on Vector via `x +: xs`, which creates a new Vector instance via `Vector.tail`.
* Added `@tailrec` annotation to the `loop` method.
I used this mini-benchmark to assess the improvement:
```scala
import cats.Eq
import cats.std.vector._
import cats.std.int._
val v = (1 to 10000000).toVector
val EqV = Eq[Vector[Int]]
{
val t0 = System.currentTimeMillis
EqV.eqv(v, v)
val t1 = System.currentTimeMillis
println(s"${t1 - t0}ms")
}
```
The result is 
before refactoring | after refactoring
--------- | -------
6542ms | 161ms
=> Optimize Eq[Vector[A]] instance

core/src/main/scala/cats/data/OneAnd.scala, tests/src/test/scala/cats/tests/OneAndTests.scala
OneAnd was missing an instance of map. This commit tries to solve this.
=> Add map method to OneAnd. Fix for #885

core/src/main/scala/cats/Applicative.scala
The previous approach duplicated the implementation of `sequence`, which
is a slight code stink. More importantly though, this approach will
benefit from an optimized override implementation of `sequence` if the
`Traverse` instance has one.
=> Delegate to Traverse.sequence in Applicative.sequence

docs/src/main/tut/freemonad.md
Thanks to @tek for pointing out that the "pure" `State`-based compiler
was using the mutable map from the "impure" example.
=> Fix bug in freemonad doc

core/src/main/scala/cats/syntax/option.scala, tests/src/test/scala/cats/tests/OptionTests.scala
=> Fix OptionIdOps.some to always return Some

core/src/main/scala/cats/syntax/all.scala, core/src/main/scala/cats/syntax/applicative.scala, core/src/main/scala/cats/syntax/package.scala, tests/src/test/scala/cats/tests/SyntaxTests.scala
This PR adds `Applicative` syntax. Fixes #882.
Not sure if I should test for `Applicative#traverse` and `Applicative#sequence`.
I don’t know if simulacrum generates anything for these methods.
=> Add Applicative syntax

core/src/main/scala/cats/Bitraverse.scala, core/src/main/scala/cats/data/Xor.scala, core/src/main/scala/cats/std/either.scala, core/src/main/scala/cats/std/tuple.scala, core/src/main/scala/cats/syntax/all.scala, core/src/main/scala/cats/syntax/bitraverse.scala, core/src/main/scala/cats/syntax/package.scala, laws/src/main/scala/cats/laws/BitraverseLaws.scala, laws/src/main/scala/cats/laws/discipline/BitraverseTests.scala, tests/src/test/scala/cats/tests/EitherTests.scala, tests/src/test/scala/cats/tests/SyntaxTests.scala, tests/src/test/scala/cats/tests/TupleTests.scala, tests/src/test/scala/cats/tests/XorTests.scala
=> Add Bitraverse, fixes #800

core/src/main/scala/cats/Unapply.scala, tests/src/test/scala/cats/tests/UnapplyTests.scala
This will enable typeclasses that uses Unapply to be serializable themselves.
=> make Unapply serializable

core/src/main/scala/cats/syntax/all.scala, core/src/main/scala/cats/syntax/package.scala, core/src/main/scala/cats/syntax/writer.scala, tests/src/test/scala/cats/tests/WriterTests.scala
This adds the following syntax for the `Writer` monad, as outlined in #920:
~~~ scala
log.tell
result.writer(log)
~~~
This is my first PR to Cats so there's probably stuff that's wrong in here. I'm happy to fix stuff if required, or close the PR if people think it's not worthwhile. I figured it was easier to have a discussion over a concrete PR than an issue.
=> Add .tell and .writer syntax for creating Writers. Fixes #920.

core/src/main/scala/cats/Eval.scala
Ensure `Call.loop` is `@tailrec` optimized. Elegance of the code suffered a bit, but I guess it's worth it?
The fact that `@tailrec` could not be put on `loop` as it was actually seems like a Scala bug, because the second call to `loop` is not a recursive call.
=> Make Call.loop @tailrec optimized.

.gitignore, core/src/main/scala/cats/data/Xor.scala, core/src/main/scala/cats/data/XorT.scala, tests/src/test/scala/cats/tests/XorTTests.scala
=> XorT.ensure method

core/src/main/scala/cats/data/WriterT.scala, core/src/main/scala/cats/std/tuple.scala, tests/src/test/scala/cats/tests/TupleTests.scala, tests/src/test/scala/cats/tests/WriterTTests.scala
Randomly picked up this issue as I saw it was marked as "low hanging fruit" and I wanted to get more familiar with cats (and associated FP concepts).
One thing of note: I had to add a show instance for Tuple2 to make this work.  I can't claim to be intimately familiar with Miles' Kittens project (see: https://github.com/milessabin/kittens), but it seemed like defining Show instances for Tuples and case classes would be particularly tedious and _possibly_ something that Kittens/Shapeless could make a lot easier.
Without further ado, here is my initial attempt to address issue #607 and add a Show instance for WriterT.
=> #607: Add missing Show instances

.travis.yml, build.sbt
By default, scala.js compiler uses `Rhino` as the js environment. But it
usually requires a lot of memory and often lead to OOM. This PR replace
the default to a node.js one that should be much faster and slimer.
=> Switch to use nodeJsEnv as default jsEnv to build scala.js

core/src/main/scala/cats/syntax/all.scala, core/src/main/scala/cats/syntax/applicativeError.scala, core/src/main/scala/cats/syntax/package.scala, tests/src/test/scala/cats/tests/ApplicativeErrorTests.scala, tests/src/test/scala/cats/tests/SyntaxTests.scala
I've added syntax for the methods I mentioned in #561.
I'm happy with `raiseError`, `handleError`, `handleErrorWith`, `recover`, and `recoverWith`. However, I'm not sure about `attemptT` because the tests in `ApplicativeErrorTests.scala` required a bunch of heavyweight type hinting.
My inclination is to remove `attempt` and `attemptT` and leave the other methods intact. What do you think?
=> Syntax for ApplicativeError

.gitignore
I just installed and started using ensime in Atom. For cats it created a .ensime_cache directory following the default setup steps, so I guess it makes sense to add this .gitignore for the project.
=> Add .ensime_cache to gitignore

build.sbt
This PR would switch off scaladoc generation for Scala 2.10 during the makeSite process. The site generated in 2.10 mode would not have scaladoc generated, but would be otherwise identical to the site generated in 2.11 mode.
This allows documentation to be put together for all classes, and should allow #898 to pass the build.
=> Switch off scaladoc generation for Scala 2.10 due to macro problems

core/src/main/scala/cats/data/OptionT.scala, docs/src/main/tut/optiont.md, tests/src/test/scala/cats/tests/OptionTTests.scala
I also added an alias from pure to some - that was never mentioned in the issue but seemed reasonable to me.
=> Added OptionT.none, resolving #935

build.sbt
My previous PR #958 missed the fact that the shell script which executes the build runs a publish as the final command. In the case of Pull Requests this is a publishLocal. On master it runs something different, which appears to publish snapshots.
As such, the previous PR allowed #898 to pass the site generation process, but it failed during the publish stage - the last command executed during the pull request build process.
Sorry about that.
This one disables the scaladoc packaging phase during publish for 2.10, which hopefully finally allows #898 to pass.
I tested publishLocal and it passes fine on 2.10 now albeit with docs not generated. 2.11 still generates scaladoc during the publish phase.
=> Disable scaladoc during packaging for scala 2.10

core/src/main/scala/cats/data/Kleisli.scala
Addressed #969. Renamed old `Kleisli#apply` to `Kleisli#ap`, and added `Kleisli#apply` which is an alias for `Kleisli#run`.
=> Renamed `Kleisli#apply`

core/src/main/scala/cats/data/Xor.scala, tests/src/test/scala/cats/tests/XorTests.scala
As a convenient shorthand for `xor.toValidated.toValidatedNel`.
I suppose `.toValidatedNel` should be the version more often used since the point of `Validated` is to accumulate errors?
=> Add toValidatedNel to Xor

core/src/main/scala/cats/data/StateT.scala, tests/src/test/scala/cats/tests/StateTTests.scala
I wanted this today and it seems like a reasonable thing to have.
=> Add flatMapF for StateT

docs/src/main/tut/apply.md
Spotted this little inconsistency.
=> Fix outdated import for `cats.syntax.apply._`

core/src/main/scala/cats/syntax/package.scala, core/src/main/scala/cats/syntax/reducible.scala
Seems like there is no object for `cats.syntax.reducible` ;)
=> Add object `reducible` for reducible syntax

core/src/main/scala/cats/MonadWriter.scala, core/src/main/scala/cats/data/WriterT.scala, laws/src/main/scala/cats/laws/MonadWriterLaws.scala, laws/src/main/scala/cats/laws/discipline/MonadWriterTests.scala, tests/src/test/scala/cats/tests/WriterTTests.scala
Other instances are possible: https://hackage.haskell.org/package/mtl-2.2.1/docs/Control-Monad-Writer-Class.html
But I realized we also don't have similar instances for the other MTL type classes, so I'll add it all in one fell swoop
=> Monad writer, fixes #889

laws/src/main/scala/cats/laws/discipline/Eq.scala, tests/src/test/scala/cats/tests/CatsSuite.scala
This is an experiment to see if builds time out less if we don't run as
many samples with Scalacheck.
=> Reduce maxSize and minSuccessful in Scalacheck params

core/src/main/scala/cats/syntax/monadCombine.scala, tests/src/test/scala/cats/tests/SyntaxTests.scala
I based myself on the structure in syntax.bitraverse for the two implicit conversions (the
existing for unite and the new for separate).
MonadCombine separate was added in #864 by @adelbertc.
=> Add syntax for separate from MonadCombine.

.travis.yml, scripts/travis-publish.sh
Use new command in Travis for coverage, not the old "curl-and-bash" method.
see https://gitter.im/typelevel/cats?at=571ccb8dd47413c07dccc27c
=> Move coverage away from bash

core/src/main/scala/cats/free/Inject.scala, docs/src/main/tut/freemonad.md
The URL to Data types à la carte seems to have changed to this URL http://www.staff.science.uu.nl/~swier004/publications/2008-jfp.pdf
=> correct the url to Data types à la carte

core/src/main/scala/cats/data/Xor.scala, core/src/main/scala/cats/data/XorT.scala, tests/src/test/scala/cats/tests/XorTTests.scala, tests/src/test/scala/cats/tests/XorTests.scala
Xor's SemigroupK instance follows that of XorT.
=> Add SemigroupK instance for Xor + tests

core/src/main/scala/cats/data/Validated.scala, core/src/main/scala/cats/data/Xor.scala, core/src/main/scala/cats/data/XorT.scala, tests/src/test/scala/cats/tests/ValidatedTests.scala, tests/src/test/scala/cats/tests/XorTTests.scala
While experimenting with `MonadCombine.separate` (for #975), I noticed there were no `Bitraverse` instances for `Validated` and `XorT`.
I would welcome suggestions, possible improvements, ... (maybe for `XorTBifoldable` ?)
=> Add `Bitraverse` instances for `Validated` and `XorT`.

docs/src/main/tut/foldable.md
The link for "A tutorial on the universality and expressiveness of fold" in the docs for foldable incorrectly uses `https` instead of `http` - this is enough to break the link. This change resolves this.
=> fix broken link in foldable docs

build.sbt
Disabling docs for scala 2.10 can't be achieved by this change alone. Sonatype release requires javadoc jars, this is now blocking the 0.5.0 release. My proposal is that we revert this for now and find a more comprehensive solution for https://github.com/typelevel/cats/pull/898 later. I know it's kicking the can down the road, but this PR itself does not bring any value to 0.5.0, so I think it is sensible to not having it blocking the release. 
Update: #898 is not included in the 0.5.0 release.
=> Revert "Disable scaladoc during packaging for scala 2.10"

kernel/src/main/scala/cats/kernel/Order.scala, kernel/src/main/scala/cats/kernel/PartialOrder.scala
We had left out some type parameters in `cats.kernel` which leads to errors when trying to use those methods.
=> Add missing type parameters.

core/src/main/scala/cats/std/future.scala
Since `Now` already has performed the work required to calculate the result value, we can lift the result into a Future using `Future#successful` instead of unwrapping the `Now` inside the block run by the `Future` (which potentially has to use another thread).
=> Use Future#successful in pureEval when possible

core/src/main/scala/cats/Traverse.scala, core/src/main/scala/cats/syntax/traverse.scala, tests/src/test/scala/cats/tests/SyntaxTests.scala
I have added `Traverse.traverseM` and added some examples to the `traverse` syntax.
=> Add Traverse.traverseM 

core/src/main/scala/cats/data/Validated.scala, tests/src/test/scala/cats/tests/ValidatedTests.scala
Adds the `ensure` method known from `Xor` to `Validated`:
```
scala> Validated.valid("").ensure(new IllegalArgumentException("Must not be empty"))(_.nonEmpty)
res0: Validated[IllegalArgumentException,String] = Invalid(java.lang.IllegalArgumentException: Must not be empty)
```
=> Add Validated.ensure

core/src/main/scala/cats/data/XorT.scala, tests/src/test/scala/cats/tests/XorTTests.scala
Adds the ability to call `XorT.fromEither` to lift from `Either[A,B]` .  This is sugar for the more verbose `x => XorT(Xor.fromEither(x))` and complements the ability to go from `XorT` to `Either` via `toEither`
=> Add XorT#fromEither

kernel-laws/src/test/scala/cats/kernel/laws/LawTests.scala, kernel/src/main/scala/cats/kernel/PartialOrder.scala
Also add some law-checking for reversed and double-reversed
Order/PartialOrder instances.
=> Override reverse on reversed PartialOrder to return original instance

docs/src/main/tut/traverse.md
The necessary `Semigroup` instance has been added to cats, so this is no
longer necessary.
=> Remove unnecessary nelSemigroup from traverse doc

core/src/main/scala/cats/Apply.scala, core/src/main/scala/cats/Foldable.scala, core/src/main/scala/cats/Reducible.scala, core/src/main/scala/cats/data/OneAnd.scala, core/src/main/scala/cats/data/Xor.scala, core/src/main/scala/cats/std/either.scala, core/src/main/scala/cats/std/list.scala, core/src/main/scala/cats/std/map.scala, core/src/main/scala/cats/std/option.scala, core/src/main/scala/cats/std/stream.scala, core/src/main/scala/cats/std/vector.scala, tests/src/test/scala/cats/tests/EitherTests.scala, tests/src/test/scala/cats/tests/OptionTests.scala, tests/src/test/scala/cats/tests/RegressionTests.scala, tests/src/test/scala/cats/tests/XorTests.scala
Fixes #513.
I think this should solve the majority of use-cases for lazy traversal.
One thing I noticed is that both `reduceRightToOption` and `traverse1_`
(which uses the former) seem to be impossible to implement lazily such
that they allow for short-circuiting. At least I couldn't figure out a
way. I left a note in the `traverse1_` scaladoc, but in practice I don't
anticipate this being a problem, because at the cost of just having an
`Applicative` instance as opposed to `Apply`, you can use `traverse_`
which is sufficiently lazy.
=> Add Apply.map2Eval and allow traverse laziness

core/src/main/scala/cats/data/WriterT.scala, tests/src/test/scala/cats/tests/WriterTTests.scala
Adding WriterT Monoid as referenced in #1012. 
It's also come to my attention that it's one of the subtasks in #620.
=> Adding WriterT Monoid

core/src/main/scala/cats/data/OptionT.scala, tests/src/test/scala/cats/tests/OptionTTests.scala
From #981, hopefully I did this correctly.
=> Added withFilter for OptionT

core/src/main/scala/cats/data/Coproduct.scala
Add the `fold` operation for `Coproduct` mentioned in #987.
I am not sure how I could test this ?
=> Add Coproduct fold

scripts/travis-publish.sh
This seems to have been missed in the build script
=> Run kernel-law tests for JS as part of build

README.md
Cats `0.5.0` is up in Maven and there's already a `0.6.0-M1` release out as well. This suggests this message is redundant, and it may be encouraging developers to use `0.4.x` instead.
=> Cats 0.5.0 no longer pre-release

core/src/main/scala/cats/arrow/NaturalTransformation.scala, core/src/main/scala/cats/data/Kleisli.scala, docs/src/main/tut/freemonad.md, free/src/main/scala/cats/free/Coyoneda.scala, free/src/main/scala/cats/free/Free.scala, free/src/main/scala/cats/free/FreeApplicative.scala, free/src/test/scala/cats/free/FreeApplicativeTests.scala, free/src/test/scala/cats/free/FreeTests.scala, free/src/test/scala/cats/free/InjectTests.scala, tests/src/test/scala/cats/tests/KleisliTests.scala, tests/src/test/scala/cats/tests/NaturalTransformationTests.scala
After having read `NaturalTransformation.scala` several times for reference, I found it much easier to read by replacing `NaturalTransformation[A,B]` with the much better `A ~> B`.
This pr replaces the occurrences where possible in `NaturalTransformation.scala`, `Free.scala` and `FreeApplicative.scala`. 
I am sure there are more places where you could do this, but I first wanted to check if this change is welcome at all ;)
=> Replace  `~>` with `NaturalTransformation`

docs/src/main/tut/monad.md
The monad docs uses `OptionT` as an example about how to compose (some) monads, but doesn't include a link to the `OptionT` documentation.
=> Add a link to the OptionT documentation from the monad docs.

docs/src/main/tut/const.md, docs/src/main/tut/freeapplicative.md, docs/src/main/tut/freemonad.md, docs/src/main/tut/kleisli.md, docs/src/main/tut/monad.md, docs/src/main/tut/validated.md, docs/src/main/tut/xor.md
Resolves #1033 although in all but one place, a simple type alias was
not possible.
=> Add notes about kind-projector usage in docs

core/src/main/scala/cats/data/Xor.scala, core/src/main/scala/cats/data/XorT.scala
Resolves #888
I don't think there's really a _right_ answer here. Both methods of
combining `Xor`s are straightforward and law-abiding. However, I think
that since in pretty much every other context (including the
`SemigroupK` instances), `Xor` does not combine failures and `Validated`
does, it is less surprising behavior to not combine left values in
`combine` methods for `Xor` and `XorT`.
Some notes about related implementations:
- Scalaz's respective methods (and semigroup instances) _do_ combine
errors, so this is a deviation from that.
- The `Semigroup` for `Either` in Haskell has doesn't combine values at
all, but returns the first `Right` (if any), making it equivalent to
the behavior of `orElse` and the `SemigroupK` instance for `Xor`.
Since we have already decided to not go with …
=> Don't combine lefts on Xor and XorT combine

PROCESS.md
At the Typelevel Summit in Philly, people brought up confusion around
the site not always being up to date with the latest release.
Also, we always seem to forget to update the release notes until
@travisbrown kindly volunteers to :)
cc @non @travisbrown
=> Add updating site and release notes to release process

core/src/main/scala/cats/data/WriterT.scala, laws/src/main/scala/cats/laws/discipline/CoflatMapTests.scala, tests/src/test/scala/cats/tests/WriterTTests.scala
Adding a `CoflatMap` instance to `WriterT`, as required in #620 
Added all laws in `CoflatMapLaws` to `CoflatMapTests`
=> Adding CoflatMap and tests to WriterT and fixed laws for CoflatMap

project/KernelBoiler.scala, tests/src/test/scala/cats/tests/TupleTests.scala
Before this fix:
```
scala> import cats.implicits._
scala> (1 -> 2) === (1 -> 3)
res0: Boolean = true
scala> import scala.reflect.runtime.universe._
import scala.reflect.runtime.universe._
scala> showCode(reify { (1 -> 2) === (1 -> 3) }.tree)
res1: String = implicits.eqSyntax(Predef.ArrowAssoc(1).->(2))(implicits.tuple2Order(implicits.intOrder, implicits.intOrder)).===(Predef.ArrowAssoc(1).->(3))
```
This is because we pick up the `Order[Tuple2[..]]` instance, which is erroneously defined like this:
```
implicit def tuple2Order[A0, A1](implicit A0: Order[A0], A1: Order[A1]): Order[(A0, A1)] =
new Order[(A0, A1)] {
def compare(x: (A0, A1), y: (A0, A1)): Int =
A0.compare(x._1, y._1)
}
```
I think we should probably publish a 0.6.1 with this fix too as it is really …
=> Fixed a bug in the Order and PartialOrder instances for Tuple2+ where only the first element was used in comparisons

build.sbt
Hopefully this would unblock #898 and #1041
=> skip javadoc compilation for 2.10

docs/src/site/_config.yml
It appears that GitHub is already using rouge instead of pygments for
the cats site, because it doesn't support pygments. This change is so I
stop getting the following email every time I push the cats website:
> You are attempting to use the 'pygments' highlighter, which is currently
> unsupported on GitHub Pages. Your site will use 'rouge' for highlighting
> instead. To suppress this warning, change the 'highlighter' value to
> 'rouge' in your '_config.yml' and ensure the 'pygments' key is unset.
=> Use pygments instead of rouge for syntax highlighting

core/src/main/scala/cats/Eval.scala
The reason is that `Eval` should be a drop-in replacement for by-name parameters. Noticed that changing it wouldn't break anything within Cats.
=> Issue #934 - Make Eval covariant

core/src/main/scala/cats/FlatMapRec.scala, core/src/main/scala/cats/MonadRec.scala, core/src/main/scala/cats/data/OptionT.scala, core/src/main/scala/cats/data/Xor.scala, core/src/main/scala/cats/data/XorT.scala, core/src/main/scala/cats/package.scala, core/src/main/scala/cats/std/either.scala, core/src/main/scala/cats/std/list.scala, core/src/main/scala/cats/std/option.scala, free/src/main/scala/cats/free/Free.scala, free/src/test/scala/cats/free/FreeTests.scala, laws/src/main/scala/cats/laws/FlatMapRecLaws.scala, laws/src/main/scala/cats/laws/MonadRecLaws.scala, laws/src/main/scala/cats/laws/discipline/FlatMapRecTests.scala, laws/src/main/scala/cats/laws/discipline/MonadRecTests.scala, tests/src/test/scala/cats/tests/EitherTests.scala, tests/src/test/scala/cats/tests/IdTests.scala, tests/src/test/scala/cats/tests/MonadRecInstancesTests.scala, tests/src/test/scala/cats/tests/OptionTTests.scala, tests/src/test/scala/cats/tests/OptionTests.scala, tests/src/test/scala/cats/tests/XorTTests.scala, tests/src/test/scala/cats/tests/XorTests.scala
Some `MonadRec` instances to get started. This is a follow-up on #1040.
=> Some MonadRec instances.

free/src/main/scala/cats/free/Free.scala, free/src/test/scala/cats/free/FreeTests.scala
Fixes #721.
The fix is now possible by strengthening constraints on the target monad from `Monad` to `MonadRec`.
This is not binary compatible, and will not be source compatible for users that used this with a non-`MonadRec` monad.
=> Make Free.foldMap stack-safe.

docs/src/main/tut/freemonad.md
Isn't it supposed to be the free functor?
=> Left-adjoint of forgetful functor

free/src/main/scala/cats/free/Free.scala, free/src/main/scala/cats/free/FreeApplicative.scala, free/src/test/scala/cats/free/FreeApplicativeTests.scala, free/src/test/scala/cats/free/FreeTests.scala
Previously calling .toString on a Free value would traverse
the entire ADT of case classes. In some cases this would
actually cause a stack overflow in the printing code. It
also represented a (small) law violation (you could use the
output to distinguish x and x.map(identity) in some cases).
This change replaces the output with opaque "Free(...)"
and "FreeApplicative(...)" strings.
=> Provide concise .toString for free structures.

core/src/main/scala/cats/Alternative.scala, core/src/main/scala/cats/Applicative.scala, core/src/main/scala/cats/Apply.scala, core/src/main/scala/cats/Bifoldable.scala, core/src/main/scala/cats/Bitraverse.scala, core/src/main/scala/cats/Composed.scala, core/src/main/scala/cats/Foldable.scala, core/src/main/scala/cats/Functor.scala, core/src/main/scala/cats/MonoidK.scala, core/src/main/scala/cats/Reducible.scala, core/src/main/scala/cats/SemigroupK.scala, core/src/main/scala/cats/Traverse.scala, core/src/main/scala/cats/data/Cokleisli.scala, core/src/main/scala/cats/data/Func.scala, core/src/main/scala/cats/data/Kleisli.scala, core/src/main/scala/cats/data/Prod.scala, core/src/main/scala/cats/functor/Bifunctor.scala, core/src/main/scala/cats/functor/Contravariant.scala, core/src/main/scala/cats/functor/Invariant.scala, core/src/main/scala/cats/std/function.scala, free/src/main/scala/cats/free/FreeApplicative.scala, free/src/test/scala/cats/free/FreeApplicativeTests.scala, tests/src/test/scala/cats/tests/CokleisliTests.scala, tests/src/test/scala/cats/tests/FunctionTests.scala, tests/src/test/scala/cats/tests/KleisliTests.scala, tests/src/test/scala/cats/tests/ProdTests.scala, tests/src/test/scala/cats/tests/TransLiftTests.scala
Like @InTheNow said in #1069: it's probably better to be consistent in our kind projection syntax.
Since the `Lambda` syntax was used quite a lot more than the `λ` syntax, I changed the occurrences of the last to the first.
I have also replaced the last type lambdas in `TransLiftTests` by kind projections.
=> Make the usage of kind projections more consistent.

core/src/main/scala/cats/std/try.scala, tests/src/test/scala/cats/tests/TryTests.scala
=> Add Traverse[Try]

core/src/main/scala/cats/data/Kleisli.scala
I'm new to Kleislis and found myself wanting a function like this. Scalaz has a `.liftKleisli` function, but I wasn't sure what would be preferred: `Kleisli.pureF(fa)` or `fa.liftKleisli`.
=> Adding a way to create a Kleisli with just F[B]

docs/src/main/tut/faq.md, docs/src/site/_layouts/default.html, docs/src/site/css/custom.css
This is just a start, and there are some more items that we will
probably want to add.
The import section probably is really a start to #912, and may end up
simply referencing a separate import document, as discussed in #936. But
I thought it would be nice to get something out there as an interim
resolution.
=> Add FAQ section to site

core/src/main/scala/cats/Reducible.scala, free/src/main/scala/cats/free/Inject.scala, free/src/test/scala/cats/free/InjectTests.scala
`Inject.prj(null)` with the provided reflexive Inject instance (`Inject[F, F]`) returns None, but `Inject.inj(null)` returns null. I am fairly sure that inj and prj should be mutual inverses, this fixes that. It works the same way now as in Scalaz.
=> Fix Inject instance and reduceRightToOption null behavior

scalastyle-config.xml
Now Scalastyle is working again, I have added the Scalastyle rule I mentioned in #1092 to make sure the `Lambda[...]` style is not use are used.
=> Enforce kind projection style using Scalastyle

core/src/main/scala/cats/data/Ior.scala, core/src/main/scala/cats/data/Xor.scala, core/src/main/scala/cats/data/XorT.scala
Replace seperate constraints `MonoidK` and `Applicative` with `Alternative`.
=> Simplify the constraint on Xor/XorT/Ior to[] by using Alternative

core/src/main/scala/cats/Functor.scala, core/src/main/scala/cats/functor/Contravariant.scala, docs/src/main/tut/contravariant.md, docs/src/main/tut/functor.md, tests/src/test/scala/cats/tests/ContravariantTests.scala, tests/src/test/scala/cats/tests/FunctorTests.scala
This uses casts to implement `Functor.widen` and `Contravariant.narrow` to take advantage of the natural variance of Functors with respect to subtyping. `Functor.widen` in Scalaz works similarly (though it uses Liskov and `@uncheckedVariance` in its implementation, it has the same underlying optimization).
=> Explicit functor variance

core/src/main/scala/cats/Unapply.scala, tests/src/test/scala/cats/tests/UnapplyTests.scala
This would make it possible to use the syntax classes with `Nested`.
=> Add an Unapply with the signature of Nested.

kernel-laws/src/test/scala/cats/kernel/laws/LawTests.scala, kernel/src/main/scala/cats/kernel/Comparison.scala, kernel/src/main/scala/cats/kernel/Order.scala, kernel/src/main/scala/cats/kernel/PartialOrder.scala
=> Add {C,c}omparison to Order, fixes #1101

free/src/main/scala/cats/free/Free.scala, free/src/main/scala/cats/free/Trampoline.scala, free/src/test/scala/cats/free/FreeTests.scala
This commit does a bunch of small things:
* Introduces `foldLeftM` and `runTailRec`
* Renames `mapSuspension` to `compile`
* Removes `Applicative[F]` requirement from `Free.suspend`
* Adds some new comments
* Moves the Free companion to the end of the file
* Minor formatting changes
I think all of these are good, but I'm happy to revert
any of them that seem like they are bad news. The main
reason I removed `mapSuspension` is that its description
was written using "compile" which seems like a more
evocative name (there are already several "map" variants).
=> Some clean up for Free (and friends).

docs/src/main/tut/optiont.md
This (strangely?) required adding an explicit type parameter.
Follow up to
https://github.com/typelevel/cats/pull/1104#issuecomment-224989444
=> Use uber import in OptionT doc

docs/src/main/tut/contravariant.md
I think I have spotted a typo in the docs. Find the actual function definition [here](https://github.com/typelevel/cats/blob/f592db84facd88d51d3f64e0e309f320878b8c52/core/src/main/scala/cats/functor/Contravariant.scala#L10).
=> Fix contramap signature in Contravariant doc page

core/src/main/scala/cats/Foldable.scala, core/src/main/scala/cats/data/OneAnd.scala, core/src/main/scala/cats/std/map.scala, core/src/main/scala/cats/std/set.scala, core/src/main/scala/cats/std/vector.scala, tests/src/test/scala/cats/tests/FoldableTests.scala, tests/src/test/scala/cats/tests/OneAndTests.scala
Partially addresses what discussed in #1091.
=> Add size to Foldable

core/src/main/scala/cats/data/Cokleisli.scala, core/src/main/scala/cats/data/Func.scala, core/src/main/scala/cats/data/Prod.scala, core/src/main/scala/cats/data/WriterT.scala, core/src/main/scala/cats/functor/Contravariant.scala, laws/src/main/scala/cats/laws/discipline/Arbitrary.scala, laws/src/main/scala/cats/laws/discipline/Eq.scala, tests/src/test/scala/cats/tests/CokleisliTests.scala, tests/src/test/scala/cats/tests/CoproductTests.scala, tests/src/test/scala/cats/tests/FuncTests.scala, tests/src/test/scala/cats/tests/KernelContravariantTests.scala, tests/src/test/scala/cats/tests/ProdTests.scala, tests/src/test/scala/cats/tests/WriterTTests.scala
=> Adding more contravariant instances

build.sbt
Currently the [ScalaDoc](http://typelevel.org/cats/api/#package)
doesn't include the kernel module, so types like Semigroup aren't
present.
=> Include kernel in ScalaDoc

core/src/main/scala/cats/Applicative.scala, core/src/main/scala/cats/Apply.scala, core/src/main/scala/cats/std/future.scala, core/src/main/scala/cats/std/try.scala
these are always lawful. The generalization to `Group` may not be (see Try, Failure has no inverse) or `Semilattice` (`Apply.map2(a, a)(_._1)` might not be idempotent, but if it is, we can add Band and Semilattice.
=> Add ApplySemigroup and ApplicativeMonoid

core/src/main/scala/cats/data/Xor.scala, tests/src/test/scala/cats/tests/XorTests.scala
Add a method to convert an `Xor` to a `Try`, since `Try` is very commonly used in existing libraries.
=> Add Xor.toTry

README.md
This add Kailuo to the maintainers list in the README. I've already invited him as a collaborator via Github.
=> Add Kailuo Wang as a Cats maintainer.

docs/src/main/tut/freemonad.md, docs/src/site/index.md
Is the project structure listing necessary at all given that nearly identical info is provided at the beginning?
=> Removed nesting in project structure listing

core/src/main/scala/cats/data/OptionT.scala, tests/src/test/scala/cats/tests/ListWrapper.scala, tests/src/test/scala/cats/tests/OptionTTests.scala
- Added `Eq`, `PartialOrder` and `Order`.
- Added `Semigroup` and `Monoid`.
- Added `SemigroupK` and `MonoidK`
- Added `MonadError`, `MonadCombine` and `MonadFilter` (the last two
instances are dissabled, because they violate the same laws as the
equivalent `Xor`T instances).
=> Add some more OptionT instances.

core/src/main/scala/cats/syntax/all.scala, core/src/main/scala/cats/syntax/monoid.scala, tests/src/test/scala/cats/tests/SyntaxTests.scala
This resolves #1124 
There are a couple of questions
- in `Group` and `SemiGroup` the comment `// TODO: use simulacrum instances eventually` has been made. I have copied this so all 3 can be changed at the same time. Is that the right thing to do here? I'm happy to use simulacrum if not
- in implementing `isEmpty` I originally attempted to use `Ops.binOp` but couldn't get it to work with my implicit `Eq`. Should I be using that here?
Sorry they are such basic questions, this is my first attempt at contributing to Cats and I'm trying to find my feet!
=> Add monoid syntax

core/src/main/scala/cats/syntax/package.scala
Currently `import cats.syntax._` brings in the list syntax but there is
no object to import only the list syntax.
=> Add list syntax object

core/src/main/scala/cats/data/Xor.scala, core/src/main/scala/cats/data/XorT.scala, tests/src/test/scala/cats/tests/ListWrapper.scala, tests/src/test/scala/cats/tests/XorTTests.scala
Add `Semigroup` and `Monoid` for `XorT`.
Also, cleanup the tests so the implicit resolution is clear.
=> XorTInstances + cleanup tests

README.md, docs/src/main/tut/contravariant.md, docs/src/main/tut/monoid.md, docs/src/main/tut/semigroup.md, docs/src/main/tut/semigroupk.md, docs/src/site/colophon.md
Remove / change some links to algebra in the documentation.
Removed the introduction about `Semigroup` in the `SemigroupK` documentation since it was a duplicate of the `Semigroup` documentation.
=> Adjust documentation to change from algebra to cats-kernel.

core/src/main/scala/cats/std/try.scala, tests/src/test/scala/cats/tests/TryTests.scala
I overlooked this when I added try support with #1059
=> Add instance of MonadRec[Try]

build.sbt
=> Exclude scoverage dependency from pom file

core/src/main/scala/cats/Cartesian.scala, core/src/main/scala/cats/FlatMap.scala, core/src/main/scala/cats/InvariantMonoidal.scala, core/src/main/scala/cats/TransLift.scala, core/src/main/scala/cats/Traverse.scala, core/src/main/scala/cats/data/Const.scala, core/src/main/scala/cats/data/Xor.scala, core/src/main/scala/cats/functor/Invariant.scala, core/src/main/scala/cats/syntax/bifunctor.scala, docs/src/main/tut/applicative.md, docs/src/main/tut/apply.md, docs/src/main/tut/invariant.md, docs/src/main/tut/invariantmonoidal.md, free/src/main/scala/cats/free/FreeInvariantMonoidal.scala, free/src/test/scala/cats/free/FreeApplicativeTests.scala, free/src/test/scala/cats/free/FreeInvariantMonoidalTests.scala, laws/src/main/scala/cats/laws/CartesianLaws.scala, laws/src/main/scala/cats/laws/InvariantMonoidalLaws.scala, laws/src/main/scala/cats/laws/discipline/AlternativeTests.scala, laws/src/main/scala/cats/laws/discipline/CartesianTests.scala, laws/src/main/scala/cats/laws/discipline/Eq.scala, laws/src/main/scala/cats/laws/discipline/InvariantMonoidalTests.scala, laws/src/main/scala/cats/laws/discipline/InvariantTests.scala, laws/src/main/scala/cats/laws/discipline/MonadCombineTests.scala, laws/src/main/scala/cats/laws/discipline/MonoidKTests.scala, laws/src/main/scala/cats/laws/discipline/SemigroupKTests.scala, tests/src/test/scala/cats/tests/AlgebraInvariantTests.scala, tests/src/test/scala/cats/tests/CsvCodecInvariantMonoidalTests.scala, tests/src/test/scala/cats/tests/TransLiftTests.scala
This PR adds `InvariantMonoidal` and `FreeInvariantMonoidal`, the invariant analogous to `Applicative` and `FreeApplicative`. Following this, we could consider adding a `Monoidal` type class and explore the `Contravariant` side of things.
--
Edit: I'm done with this one, it's good for review (ping @Fristi & @mpilquist)!
I realized that for every instance of `InvariantCartesian` I had in mind its also possible to define a `pure`, so I reworked everything to define an `InvariantMonoidal` and `FreeInvariantMonoidal` instead of their `Cartesian` counterpart.
--
This is work in progress on #802.
Before I finish it (doc is surprisingly long to write :smile:), I have concerns regarding the legitimacy of this new `InvariantCartesian` type class. I could not find new laws for it that cannot be …
=> Add InvariantMonoidal and FreeInvariantMonoidal

docs/src/main/tut/invariantmonoidal.md
To make it consistent with other docs.
=> Use tut:book in invariantmonoidal doc

build.sbt, project/plugins.sbt
This adds mima for kernel, but it does not pass, so it is not added to travis yet.
As discussed when moving kernel from algebra, the thinking was we could be more conservative there. I would like to turn this on after the next release (I guess 0.7.0) and I hope we can be conservative with kernel updates so that algebra is not too tightly coupled to cats.
=> Add mima for kernel

DESIGN.md
As suggested in
https://github.com/typelevel/cats/pull/1145#discussion_r67731278
=> Include kernel in modules doc

README.md
Inspired by a colleague who had a bit of trouble figuring out what problem Cats was solving
=> Add a Why section to README

core/src/main/scala/cats/data/Xor.scala, core/src/main/scala/cats/syntax/all.scala, core/src/main/scala/cats/syntax/package.scala, core/src/main/scala/cats/syntax/xort.scala, tests/src/test/scala/cats/tests/XorTests.scala
I have added syntax to create a `XorT` from a 
- `F[A]` :  `fa.leftXorT` and `fa.rightXorT` and which use `XorT.left` and `XorT.right`
- `Xor` : `xor.toXorT` (which was suggested by @ceedubs in #1078)
The last one is a little bit difficult:
- If I define it on `Xor` I need to work around the covariance of `A` and `B` in `Xor` versus the invariance in `XorT`, so you would need to write `xor.toXorT[F, A, B]`. 
- I have also defined `toXorT` (currently `toXorT2` in `syntax.xor`) as a syntax function on `Xor` so you can write `xor.toXorT[F]`. But it's probably not expected that there are syntax functions for a data type defined in cats itself (at least I couldn't think of / find an earlier precedent).
I prefer the syntax function because it is nicer/easier to use, but it would probably be …
=> Add syntax to create a XorT from an F[A] and from a Xor.

core/src/main/scala/cats/data/OneAnd.scala, core/src/main/scala/cats/syntax/apply.scala, core/src/main/scala/cats/syntax/cartesian.scala, core/src/main/scala/cats/syntax/coflatMap.scala, core/src/main/scala/cats/syntax/comonad.scala, core/src/main/scala/cats/syntax/contravariant.scala, core/src/main/scala/cats/syntax/flatMap.scala, core/src/main/scala/cats/syntax/foldable.scala, core/src/main/scala/cats/syntax/functor.scala, core/src/main/scala/cats/syntax/invariant.scala, core/src/main/scala/cats/syntax/monadError.scala, core/src/main/scala/cats/syntax/monadFilter.scala, core/src/main/scala/cats/syntax/reducible.scala, core/src/main/scala/cats/syntax/semigroupk.scala, core/src/main/scala/cats/syntax/traverse.scala
Hide the traits which are used for implicit resolution prioritization #1160.
=> Make the implicit priority traits private.

docs/src/main/tut/faq.md, docs/src/main/tut/imports.md, docs/src/site/_config.yml
This seemed like a bit too much information to shove into a FAQ answer. This also leaves room for a more detailed guide on piecemeal imports if someone gets around to writing it.
=> Break import guide out from FAQ

core/src/main/scala/cats/data/OptionT.scala, core/src/main/scala/cats/data/XorT.scala, tests/src/test/scala/cats/tests/OptionTTests.scala, tests/src/test/scala/cats/tests/XorTTests.scala
Adds `mapF` to OptionT and XorT making it easier in the case where you have `XorT[F, A, B]` and `B => F[C]` to get `XorT[F, A, C]`. 
I'm not sure if the name `mapF` is appropriate or even if this belongs in cats but I've found something like this very useful recently.
=> Add semiflatMap to OptionT and XorT

README.md
@johnynek's Cats contributions started fairly recently, but @johnynek was a big part of the algebra effort that led to cats-kernel and has contributed some nice changes and feedback since the creation of cats-kernel. Like @non, @johnynek is a person who is performance-conscious, and I think that Cats could benefit from this area of knowledge/awareness.
@johnynek thanks for the great work. Add a 👍 if you would like to be added as a maintainer.
_If anyone has reason to believe that this candidate's conduct does not align with typelevel's [code of conduct](http://typelevel.org/conduct.html) or goal of an inclusive, welcoming and safe environment; please contact a typelevel member (contact information is provided at the bottom of the code of conduct) via email or private Gitter message._
=> Add johnynek as a maintainer

README.md
@peterneyens has been quite active with Cats in the past 3 months. Peter has contributed a significant change set over a number of PRs, has always taken feedback well and addressed it quickly, and has provided helpful and friendly feedback on others' PRs.
Thanks a bunch, @peterneyens. Please give a 👍 if you'd like to be added as a maintainer.
_If anyone has reason to believe that this candidate's conduct does not align with typelevel's [code of conduct](http://typelevel.org/conduct.html) or goal of an inclusive, welcoming and safe environment; please contact a typelevel member (contact information is provided at the bottom of the code of conduct) via email or private Gitter message._
=> Add Peter Neyens as a maintainer

docs/src/main/tut/traverse.md
The following line says note the return type but it is not in the definition.
=> Add return type in Traverse example

core/src/main/scala/cats/data/StateT.scala, tests/src/test/scala/cats/tests/StateTTests.scala
Adding utility functions `lift` and `inspect` to the `StateT` object.
=> Adding lift and inspect to StateT

core/src/main/scala/cats/data/XorT.scala, tests/src/test/scala/cats/tests/XorTTests.scala
Currently there is only `.toValidated`, but I frequently need `toValidatedNel` as well, so here it is ;)
=> Add XorT.toValidatedNel

build.sbt, project/KernelBoiler.scala, project/plugins.sbt, tests/src/test/scala/cats/tests/TupleTests.scala
This PR (which is against the `series/0.6.x` branch that I just created) does a couple of things:
- Backport the tuple order fix from #1062 
- Add a binary compatibility check to all published modules (since we will want to maintain binary compatibility within the 0.6.x series)
I will largely unavailable for a little over a week, but I thought that if I got this branch set up someone else (@non?) might be able to get a 0.6.1 published with the fix for this pretty nasty bug.
cc @mpilquist and @travisbrown who have both expressed interest in getting this backported for a 0.6.1 release.
=> Backport tuple order fix for 0.6.x

docs/src/main/tut/monoidk.md
The scaladoc description of `MonoidK` is pretty good, and I think it's better to see a copy of it here than to find a blank page.
=> Copied scaladoc content as a better placeholder

index.md
This is a change directly to the `gh-pages` branch. Normally this would be taken care of by publishing the whole site for a new release, but we currently don't have a great setup for doing this outside of the `master` branch.
We should wait until 0.6.1 has synced to maven central before merging this.
=> Change dependency version to 0.6.1 on website

CHANGES.md, README.md, docs/src/site/index.md
This shouldn't be merged until version 0.6.1 is released.
Currently I don't have permission to publish to Sonatype for cats, so for now I'm hoping that @non (or someone else -- maybe @travisbrown or @kailuowang or @mpilquist ?) can publish the release (off of the `series/0.6.x` branch). Hopefully by the time we are ready for the next release I can get the necessary permissions. I've guessed Saturday as the release date in the changelog but we can definitely change that depending on when it actually gets released :)
Note: there's a little bit of strangeness in that we need to make these changes to the master branch since that's the README that people see, but it kind of seems like these changes should also live on the `series/0.6.x` branch. However, the `0.6.x` branch was made off of the …
=> Update docs for version 0.6.1

core/src/main/scala/cats/Reducible.scala, tests/src/test/scala/cats/tests/ReducibleTests.scala
`foldM` for nonempty collections. First mention: https://gitter.im/typelevel/cats?at=5781d3f33eaf66535e62da69
=> Implement Reducible.reduceM

core/src/main/scala/cats/data/OptionT.scala, core/src/main/scala/cats/data/XorT.scala
I have added `toNested` to `OptionT` and `XorT` like I mentioned in #1107.
This among other things makes it possible to use the "applicative `ap`" (called `app` in Scalaz) which is inconsistent the `ap` it gets from the monad instances of `OptionT` or `XorT` (see #1106).
```scala
import cats.data.OptionT
val ff: OptionT[List, Int => String] = 
OptionT(List(Option(_.toString), none[Int => String]))
val fa: OptionT[List, Int] = 
OptionT(List(1.some, 2.some))
ff.ap(fa)
// OptionT[List,String] = OptionT(List(Some(1), Some(2), None))
OptionT(ff.toNested.ap(fa.toNested).value)
// OptionT[List,String] = OptionT(List(Some(1), Some(2), None, None))
```
The `toNested` for `XorT` is currently not that useful because we are not able to get the implicits for `Nested[F, A Xor ?, …
=> Add toNested to OptionT and XorT.

core/src/main/scala/cats/MonadFilter.scala
Resolves #1054.
This simply removes `MonadFilter.filterM` to prevent confusion due to
this `filterM` being different than that from Haskell or Scalaz.
This version of `filterM` doesn't seem particularly useful to me. The
only type that comes to mind for which this might be useful is `Option`,
and it's pretty easy to come up with a more straightforward
implementation for the `Option` case. A more general solution for
`filterM` is provided by #1148, but so far there doesn't seem to be any
interest in that proposal, so I don't want it to hold up resolving #1054.
=> Remove MonadFilter.filterM

core/src/main/scala/cats/data/NonEmptyVector.scala, tests/src/test/scala/cats/tests/NonEmptyVectorTests.scala
This follows up on several small suggestions from comments in #1137. The
only meaningful modification is changing the format of `show` from
something like `NonEmptyVector(Vector(1, 2, 3))` to something like
`NonEmptyVector(1, 2, 3)`.
I've also added a `length` method to `NonEmptyVector`.
=> Change format of NonEmptyVector.show

core/src/main/scala/cats/data/WriterT.scala, core/src/main/scala/cats/data/package.scala, tests/src/test/scala/cats/tests/WriterTTests.scala
And also add `tell` and `value` methods to the `Writer` object to
conveniently create `Writer` instances.
=> Add tell method to WriterT

core/src/main/scala/cats/functor/Contravariant.scala, laws/src/main/scala/cats/laws/discipline/Arbitrary.scala, laws/src/main/scala/cats/laws/discipline/Eq.scala, tests/src/test/scala/cats/tests/KernelContravariantTests.scala, tests/src/test/scala/cats/tests/ShowTests.scala
As far I can tell this seemed to be the only missing `Contravariant` instance.
#579 also mentioned `StateT`, but I think only an `IndexedStateT` would have a `Contravariant` (that's also why there is no `Profunctor` instance, see #1067).
I don't think it is possible to test the instance for `Eq`, since `CovariantTests` would need an `Arbitrary[Eq[A]]` and an `Eq[Eq[A]]` ?
=> Add Contravariant instance for Eq and test Show instance.

core/src/main/scala/cats/instances/tuple.scala, tests/src/test/scala/cats/tests/TupleTests.scala
=> Add Traverse and Comonad instances for Tuple2.

core/src/main/scala/cats/FlatMap.scala, core/src/main/scala/cats/syntax/flatMap.scala
This partially addresses #1209, though it doesn't add much in the way of
the syntax tests suggested by that ticket.
=> Use Simulacrum Ops for FlatMap syntax

core/src/main/scala/cats/Foldable.scala, core/src/main/scala/cats/Reducible.scala, tests/src/test/scala/cats/tests/FoldableTests.scala
This adds:
- `reduceLeftOption` and `reduceRightOption` methods to `Foldable`
- `maximumOption` and `minimumOption` methods to `Foldable`
- `maximum` and `minimum` methods to `Reducible`
Resolves #1164.
=> Add max/min and reduceOption methods

core/src/main/scala/cats/data/Nested.scala
This came up [here](https://github.com/typelevel/cats/pull/1148#discussion_r71067154), but I didn't want to tie this change into #1148.
Among others, I think a review from @adelbertc would be helpful.
=> Use traits to avoid code duplication in Nested instances

core/src/main/scala/cats/Applicative.scala, core/src/main/scala/cats/Eval.scala, core/src/main/scala/cats/instances/future.scala, core/src/main/scala/cats/instances/try.scala, core/src/main/scala/cats/syntax/applicative.scala, tests/src/test/scala/cats/tests/SyntaxTests.scala
This probably resolves #1150, though it doesn't provide an alternative
type class as was brought up there.
@adelbertc has [gotten tripped up](https://github.com/typelevel/cats/issues/1150#issuecomment-235322721) by `pureEval` defaulting to a call to `pure` with `.value` called on the `Eval`.
@johnynek has also [questioned](https://github.com/typelevel/cats/issues/1150#issue-161092646) `pureEval` being directly on `Applicative`.
@tpolecat has [raised concerns](https://gitter.im/typelevel/cats?at=5794dc4c1b9de56c0edd887a) that `pureEval` looks like it might exist as a way to inject
side effects into a type, but that it doesn't actually make any claims
about execution semantics or value retention, so it can't be relied upon
to do this.
I think that there could be an argument for having an …
=> Remove Applicative#pureEval

build.sbt, core/src/main/scala/cats/data/NonEmptyVector.scala, tests/src/test/scala/cats/tests/NonEmptyVectorTests.scala
As suggested might be useful in #1204 -
Merging this would make `NonEmptyVector` a value class, which may be useful in some scenarios. It also:
- Renames variant of concat taking a `Vector` to `concatVector`. 
- Renames variant of `++` taking a `Vector` to `+++`
- Updates test in line with the change. 
- Adds additional consistency test.
Updates scaladoc in some minor places, including turning references to concat and concatVector from `++` and `+++` respectively into links to the relevant methods.
Not sure about naming, especially `+++`, but figured a PR would be a good place to discuss:
(a) The naming,
(b) If this is something we would want to do.
=> Make NonEmptyVector a value class. #1204

core/src/main/scala/cats/data/OptionT.scala
Updates a broken link on the `OptionT` scaladoc comments.
@ceedubs
=> Updated broken link on OptionT docs

scripts/travis-publish.sh
I believe the frequent scalajs build failure is caused by out of memory, So splitting the tasks helped. This is verified by #1254 which passes two builds consecutively.
Update: thanks to @mikejcurry in his comment [here](https://github.com/typelevel/cats/pull/1258#issuecomment-237067035)  I understand we are at the upper bound of memory available on travis, i.e. we can't increase jvm memory to solve this problem.
=> Split build tasks on travis fixes #1242

kernel/src/main/scala/cats/kernel/instances/option.scala
This is trivial but we might as well do it sooner rather than later.
=> Correct spelling in instance names

kernel-laws/src/test/scala/cats/kernel/laws/LawTests.scala
It appears that this test was overlooked.
=> Check Order laws for BigInt

build.sbt, core/src/main/scala/cats/instances/future.scala, jvm/src/test/scala/cats/tests/FutureTests.scala
This PR adds a new `MonadRec` instance for `Future` (as discussed on [Gitter](https://gitter.im/typelevel/cats?at=57a2073cc915a0e426b91de1)). The implementation of `tailRecM` is not literally tail recursive, but it is stack-safe.
I've also reinstated the `jvm` module that was removed in #1018, since it looks like the removal of the `MonadError` laws checking there wasn't intentional, and since I need a place to put the `MonadRec` laws checking for `Future`.
=> Add MonadRec for Future and reinstate Future tests for JVM

tests/src/test/scala/cats/tests/NonEmptyVectorTests.scala
@kailuowang @ceedubs - Apologies I didn't get back to the [comment](https://github.com/typelevel/cats/pull/1212#discussion_r72367628) by @kailuowang on the test name prior to the PR being merged.
Here is a follow up to address the text of the test. I have renamed it a different way than was suggested, and I have also added an additional test.
The original intent of the test was that it was a test to ensure that supplying a` Vector[Int]` to the `apply` method could not result in a `NonEmptyVector[Int] `(rather it should result in a `NonEmptyVector[Vector[Int]]`. 
As noted in #1214, supplying an empty `Vector[Int] `to apply was causing an empty `NonEmptyVector[Int]` to be created. The new test more explicitly verifies that this cannot happen.
These might be overkill as far as test goes, but …
=> Additional test to ensure that semantics of apply on NonEmptyVector remains as expected

core/src/main/scala/cats/data/NonEmptyList.scala, core/src/main/scala/cats/data/NonEmptyVector.scala, core/src/main/scala/cats/data/Validated.scala, core/src/main/scala/cats/data/XorT.scala, tests/src/test/scala/cats/tests/NonEmptyListTests.scala, tests/src/test/scala/cats/tests/NonEmptyVectorTests.scala, tests/src/test/scala/cats/tests/RegressionTests.scala, tests/src/test/scala/cats/tests/ValidatedTests.scala
See discussion [here](https://gitter.im/typelevel/cats?at=57a37a3e0bd017c16e3c0da2).
=> Replace overloaded variadic NonEmpty*.apply with of

core/src/main/scala/cats/Unapply.scala
... instead of calling `implicitly`. This removes an unnecessary
function call which also just returns the `ev` parameter.
=> Unapply.apply: return implicit parameter

core/src/main/scala/cats/Bitraverse.scala, core/src/main/scala/cats/functor/Bifunctor.scala
This was originally part of #1194, but since it's looking uncertain
whether or not that will go forward, I'm submitting it separately.
=> Add bisequence and bimap examples

core/src/main/scala/cats/syntax/package.scala, tests/src/test/scala/cats/tests/SyntaxTests.scala
This is something that I missed on #1225.
@travisbrown this might be something that we want to make it into 0.7.0.
=> Add syntax import objects for FunctorFilter and TraverseFilter

core/src/main/scala/cats/ApplicativeError.scala, tests/src/test/scala/cats/tests/TryTests.scala
This method seems really convenient for many common `MonadError` cases.
It is somewhat limited due to requiring `Throwable`, we could put it on the `MonadError` object rather than instance, and we could introduce a new typeclass `Catchable[M]`?
I think this covers 90% of the cases without adding too much complexity.
=> add catchNonFatal to MonadError

AUTHORS.md, CONTRIBUTING.md, core/src/main/scala/cats/FlatMapRec.scala, core/src/main/scala/cats/NotNull.scala, core/src/main/scala/cats/data/Validated.scala, core/src/main/scala/cats/data/Xor.scala
This is inspired by #1275. It doesn't include a CLA, and there is
most likely more work that should be done with respect to attribution,
but I'm hoping that this is a step in the right direction.
I've added a link to the scalaz contributors page within AUTHORS.md.
I'm not sure who all out of that should and would want to be directly listed
in the authors page for Cats. I've explicitly added Brian McKenna to the
authors page, as my understanding of [this
tweet](https://twitter.com/puffnfresh/status/762901748772057088) is that
he would like to be on there.
@puffnfresh, if you care to, please let me know if there is any way that I could improve this.
=> Some attribution work

core/src/main/scala/cats/syntax/all.scala, core/src/main/scala/cats/syntax/package.scala, core/src/main/scala/cats/syntax/tuple.scala, project/Boilerplate.scala, tests/src/test/scala/cats/tests/SyntaxTests.scala
Generates
```scala
trait TupleAritySyntax {
private[syntax] final class Tuple1Ops[F[_], A0](t1: Tuple1[F[A0]]) {
def map[Z](f: (A0) => Z)(implicit functor: Functor[F]): F[Z] = functor.map(t1._1)(f)
def contramap[Z](f: Z => (A0))(implicit contravariant: Contravariant[F]): F[Z] = contravariant.contramap(t1._1)(f)
def imap[Z](f: (A0) => Z)(g: Z => (A0))(implicit invariant: Invariant[F]): F[Z] = invariant.imap(t1._1)(f)(g)
}
implicit def tuple1Syntax[F[_], A0](t1: Tuple1[F[A0]]): Tuple1Ops[F, A0] = new Tuple1Ops(t1)
private[syntax] final class Tuple2Ops[F[_], A0, A1](t2: Tuple2[F[A0], F[A1]]) {
def map2[Z](f: (A0, A1) => Z)(implicit functor: Functor[F], cartesian: Cartesian[F]): F[Z] = Cartesian.map2(t2._1, t2._2)(f)
def contramap2[Z](f: Z => (A0, A1))(implicit contravariant: …
```
=> Syntax for Cartesian operations with tuples

core/src/main/scala/cats/data/XorT.scala, core/src/main/scala/cats/functor/Bifunctor.scala, core/src/main/scala/cats/syntax/bifunctor.scala, laws/src/main/scala/cats/laws/BifunctorLaws.scala, laws/src/main/scala/cats/laws/discipline/BifunctorTests.scala
Adding a `leftWiden` method to `XorT`, as `XorT` is invariant on errors, as referenced in #556
=> Adding leftWiden to XorT

build.sbt
SBT 0.13.12 added a warning about recompilation due to incremental build cache invalidation in the presence of macros. This is enabled by default.
Whilst in many ways laudable, this introduces a lot of unhelpful build noise in projects which define macros. Fortunately there is an SBT incremental build option to disable this warning. The PR adds that option to the Cats build.
More info on the warning can be found [here](https://github.com/sbt/sbt/issues/2654).
=> Eliminate macro build noise.

bench/src/main/scala/cats/bench/MapMonoidBench.scala, build.sbt, kernel/src/main/scala/cats/kernel/Monoid.scala, kernel/src/main/scala/cats/kernel/instances/StaticMethods.scala, kernel/src/main/scala/cats/kernel/instances/map.scala, kernel/src/main/scala/cats/kernel/instances/stream.scala, kernel/src/main/scala/cats/kernel/instances/vector.scala
This commit fixes a number of problems I introduced with cats-kernel.
1. Map's monoid was not overriding combineAll
2. It was also doing the wrong thing for combine
3. Monoid should have overridden combineAllOption
The performance for map's `combine` is 150x faster after this commit,
and `combineAll` is 780x faster. Rather than focusing on how good
these speed ups are, I want to apologize for how bad the
implementations were previously. The new `combine` is competitive with
other implementations, and `combineAll` is about x5 faster than the
equivalent code using combine.
(All figures using before/after numbers for the given benchmark.)
Thanks to Adelbert and Travis for noticing this problem. Also thanks
to Travis for producing this benchmark! Finally, thanks to Oscar for
helping me look …
=> Drastically speed up Monoid[Map[K, V]] instance.

core/src/main/scala/cats/data/XorT.scala
I found it useful to have liftT available to me for wrapping values in XorT.  I couldn't figure out what test should be added in this case, but if anyone has any examples or suggestions I'd love to add one.
=> Put liftT on the companion object of XorT

.travis.yml, build.sbt
As pointed out here https://github.com/typelevel/cats/pull/1025#issuecomment-218288666, the `botBuild` value on travis isn't set correctly, which might be causing the scalaJS build issues we saw on travis previously. This change should fix the setting. @ceedubs you have time to look at this one?
=> fix botBuild value on travis

free/src/main/scala/cats/free/Free.scala, free/src/main/scala/cats/free/FreeT.scala, free/src/test/scala/cats/free/FreeTTests.scala, free/src/test/scala/cats/free/FreeTests.scala
This will need to be fixed when #1306 is merged, but good to get before 0.7.0
=> Remove a recursive flatMap from Free

core/src/main/scala/cats/Cartesian.scala, core/src/main/scala/cats/Composed.scala, core/src/main/scala/cats/ContravariantCartesian.scala, core/src/main/scala/cats/InvariantMonoidal.scala, core/src/main/scala/cats/functor/Contravariant.scala, core/src/main/scala/cats/instances/tuple.scala, laws/src/main/scala/cats/laws/FlatMapLaws.scala, laws/src/main/scala/cats/laws/discipline/FlatMapTests.scala, tests/src/test/scala/cats/tests/TupleTests.scala
These new instances should be isomorphic to `WriterT[Id, A, B]` instances, but there may be cases where you already have a tuple2 and want to use a monad.
This approach can be generalized to `TupleN`, but I am not sure it yet justifies code-gen or macros for this purpose.
Interestingly, one could make a `Monad` for a general case-class that is generic in at least the last parameter, but that may be going too far.
I also added `Cartesian[Eq]` to make the tests easier (otherwise I needed to plumb some new implicits everywhere).
=> Add ContravariantCartesian typeclass and for Tuple2 add Monad and FlatMap

CHANGES.md
As @non pointed out on Gitter, I forgot to update the date here this morning.
=> Fix date in 0.7.0 release notes

core/src/main/scala/cats/data/OptionT.scala
This is a little thing but we might as well fix it now.
=> Rename instance for consistency and to avoid collisions

core/src/main/scala/cats/CoflatMap.scala
Apologies in advance for this, if I had the ability to label this PR, it would definitely be something along the lines of 'nitpick'.
The doc for `coflatMap` states that the value is in a Monadic context, which can be confusing, because:
- there is no Monad constraint on the context (the example being a Monad is incidental) 
- the context is *more likely* to be a Comonad
=> Remove references to Monad from CoflatMap doc

docs/src/site/resources_for_learners.md
@non @adelbertc This PR adds Scala Exercises Cats section to the list of resources for learners.
=> Adds Scala Exercises to list of resources for learners

core/src/main/scala/cats/data/WriterT.scala, tests/src/test/scala/cats/tests/WriterTTests.scala
I added the `liftT` method to the companion object of `WriterT` following the `StateT` style. I also added a test and it seems to pass locally. 
This is my first PR to cats so it probably needs some reviews. Anyway, the code added is minimal...
=> Added liftT to WriterT (issue #1315)

core/src/main/scala/cats/instances/bigDecimal.scala, core/src/main/scala/cats/instances/either.scala, core/src/main/scala/cats/instances/function.scala, core/src/main/scala/cats/instances/list.scala, core/src/main/scala/cats/instances/map.scala, core/src/main/scala/cats/instances/vector.scala, core/src/main/scala/cats/syntax/either.scala, kernel-laws/src/test/scala/cats/kernel/laws/LawTests.scala, kernel/src/main/scala/cats/kernel/instances/StaticMethods.scala, kernel/src/main/scala/cats/kernel/instances/all.scala, kernel/src/main/scala/cats/kernel/instances/bitSet.scala, kernel/src/main/scala/cats/kernel/instances/double.scala, kernel/src/main/scala/cats/kernel/instances/either.scala, kernel/src/main/scala/cats/kernel/instances/float.scala, kernel/src/main/scala/cats/kernel/instances/function.scala, kernel/src/main/scala/cats/kernel/instances/list.scala, kernel/src/main/scala/cats/kernel/instances/set.scala, kernel/src/main/scala/cats/kernel/instances/stream.scala, kernel/src/main/scala/cats/kernel/instances/vector.scala, tests/src/test/scala/cats/tests/FunctionTests.scala, tests/src/test/scala/cats/tests/Helpers.scala
This commit does a bunch of things:
1. Move relevant either/function instnaces into kernel
2. Add missing Eq/PartialOrder instances for Either
3. Add many missing instances for Function0/Function1
4. Add instances for BitSet
5. Remove code duplication between collection monoids
6. Improve test coverage of function instances
7. Add some missing package objects in kernel
8. A few stylistic changes
This is a relatively large commit but I think almost all of this is
stuff we'd like to get done before we freeze cats-kernel."
This fixes #1320.
=> Fix many cats-kernel instances.

core/src/main/scala/cats/data/EitherT.scala, tests/src/test/scala/cats/tests/EitherTTests.scala
Adds `EitherT.fromOption` which es the equivalent of `Either.fromOption` but directly lifts into an `Applicative`.
=> Add EitherT.fromOption

laws/src/main/scala/cats/laws/FlatMapLaws.scala
This is to address: #1329 where the test cost is too high for some libraries that depend on this.
This weakening should not really weaken the test too much if we know that `map` and `flatMap` are already lawful, which we are testing independently.
=> Reduce the cost of the tailRecM test

build.sbt, scripts/travis-publish.sh
1. disabled doctest plugin on all js projects which was enabled by this [commit])https://github.com/typelevel/cats/commit/67eacc7c3aa2f6ebebcb67eb6ee122103fdce4b1)
2. use the same commands for travis and release
3. added freeJS test to `validateJS`
4. try use aggregated project `test` as much as possible (will see if travis can handle)
=> fix doctest plugin / use same command for release and travis build

kernel-laws/src/main/scala/cats/kernel/laws/GroupLaws.scala, kernel/src/main/scala/cats/kernel/instances/map.scala
These tests will catch sitautions where the optimized methods are
broken (i.e. become inconsistent with the behavior of .combine).
These tests caught an issue with Monoid[Map[K, V]].combineAll, which
was broken.
Fixes #1346.
=> Add consistency laws for .combineAll and .combineAllOption.

AUTHORS.md, CHANGES.md, README.md
This adds four new authors, summarizes the PRs that were
pulled into the 0.7.x branch, and explains the release.
It also mentions that 0.7.1 was botched and should not
be used.
=> Update CHANGES.md, AUTHORS.md, and README.md for 0.7.2.

core/src/main/scala/cats/syntax/all.scala, core/src/main/scala/cats/syntax/package.scala, core/src/main/scala/cats/syntax/vector.scala, tests/src/test/scala/cats/tests/VectorTests.scala
For consistency with NonEmptyList and because its useful https://github.com/typelevel/cats/pull/520
=> vector.toNev syntax

core/src/main/scala/cats/data/NonEmptyVector.scala, tests/src/test/scala/cats/tests/NonEmptyVectorTests.scala
Append and prepend are everyday operations on Vectors and the need quickly arises when working with NonEmptyVectors. They maintain the NonEmpty invariant.
=> append and prepend on NonEmptyVectors

core/src/main/scala/cats/arrow/FunctionK.scala, macros/src/main/scala/cats/macros/compat.scala, tests/src/test/scala/cats/tests/FunctionKTests.scala
Quick attempt at providing a `lift` method for `FunctionK`, by means of a macro.
In my local testing, this works for `Free` and other more complicated types if you've enabled some form of the SI-2712 fix.
Thoughts?
=> Add lift to FunctionK

docs/src/site/index.md
The markdown on this page is rendering incorrectly. Sections have changed to generate headings consistent with the rest of the page.
=> Update documentation to use correct markdown

core/src/main/scala/cats/data/StateT.scala, tests/src/test/scala/cats/tests/StateTTests.scala
This adds `StateT.set` and `StateT.setF` methods on the `StateT` companion object. Their omission seemed to be a bit conspicuous so it may just be that I'm missing something!
=> Add StateT.set and StateT.setF.

.jvmopts, .travis.yml
as suggested by @BennyHill in #1387
=> try travis trusty beta with higher memory

core/src/main/scala/cats/MonadReader.scala, laws/src/main/scala/cats/laws/MonadReaderLaws.scala, laws/src/main/scala/cats/laws/discipline/MonadReaderTests.scala
Adding `reader` method to `MonadReader`, as present in [Haskell](https://hackage.haskell.org/package/mtl-2.2.1/docs/Control-Monad-Reader-Class.html)
=> Adding reader method to MonadReader

core/src/main/scala/cats/data/StateT.scala, tests/src/test/scala/cats/tests/StateTTests.scala
Adding `get` to `StateT` as mentioned in #1371
=> Adding get method to StateT

core/src/main/scala/cats/arrow/Compose.scala, tests/src/test/scala/cats/tests/SyntaxTests.scala
@non As we talked about at Lamba.world :-)
=> Add more syntax

core/src/main/scala/cats/arrow/FunctionK.scala
Coproduct.fold was added in #1032.
=> Simplify FunctionK.or by using Coproduct.fold.

docs/src/main/tut/monoidk.md
Just expands the `MonoidK` doc page slightly
=> Add a few examples for MonoidK

docs/src/site/index.md
Previously, _Getting Started_ and _Motivations_ headers didn't look
correctly because of the spacing.
=> fix homepage docs

core/src/main/scala/cats/Foldable.scala, core/src/main/scala/cats/instances/list.scala, core/src/main/scala/cats/instances/map.scala, core/src/main/scala/cats/instances/set.scala, core/src/main/scala/cats/instances/stream.scala, core/src/main/scala/cats/instances/vector.scala, tests/src/test/scala/cats/tests/FoldableTests.scala
If I am understanding correctly, now that `FlatMap` has `tailRecM` we can revisit #1030.
I adapted an [old commit](https://github.com/ceedubs/cats/commit/4d08b603f86db440a5d0db5291fac1294f8f3524) by @ceedubs for a PR to add `MonadRec` by @TomasMikula.
=> Lazy foldM for "Iterables"

docs/src/main/tut/typeclasses/monad.md
Fixed formatting error in 2nd paragraph of flatMap section, by reinstating missing backquote.
=> Fixed formatting overrun error in flatMap section

core/src/main/scala/cats/instances/all.scala, core/src/main/scala/cats/instances/package.scala, core/src/main/scala/cats/instances/uuid.scala, kernel-laws/src/test/scala/cats/kernel/laws/LawTests.scala, kernel/src/main/scala/cats/kernel/Order.scala, kernel/src/main/scala/cats/kernel/instances/all.scala, kernel/src/main/scala/cats/kernel/instances/uuid.scala
- `Order[UUID]`
- `Show[UUID]`
=> UUID instances

docs/src/main/tut/typeclasses/typeclasses.md
Obviously this is just a start, we can improve it once we have a starting point.
=> Add diagram of typeclass hierarchy continue #822

docs/src/main/tut/typeclasses.md
Not sure where the best place would be to put this. But I think it would be useful.
=> Add diagram of typeclass hierarchy

core/src/main/scala/cats/data/EitherT.scala, tests/src/test/scala/cats/tests/EitherTTests.scala
Issue: https://github.com/typelevel/cats/issues/1344
This is my first time contributing and am fairly new to these types so any feedback welcome. Would also like to add some examples if the code looks about right.
=> Add toNestedValidated and toNestedValidatedNel

core/src/main/scala/cats/data/StateT.scala, tests/src/test/scala/cats/tests/StateTTests.scala
@adelbertc is doing a lot of work on the MTL type classes, but before #1379 (or something similar) lands, we could add this instance for the time being.
Fixes #1397.
=> Add MonadError instance for StateT.

core/src/main/scala/cats/data/Prod.scala, laws/src/main/scala/cats/laws/discipline/Arbitrary.scala, tests/src/test/scala/cats/tests/ProdTests.scala
Creating more instances for `Prod`:
fixes https://github.com/typelevel/cats/issues/1375
=> More instances for prod

build.sbt
cc @SethTisue @BennyHill @travisbrown
=> Use friendly name in POM for published artifacts - fixes #1396

docs/src/main/tut/faq.md
These changes are minor, but to my ear "up to Cats 0.6.x" sounds like it excludes 0.6.x, and in any case `Xor` wasn't actually gone in 0.7. Since we're pointing to this FAQ entry in the 0.8.0 release / upgrade notes, I thought we should make the timing a little clearer. /cc @adelbertc
=> Clarify some details about the life and death of Xor

docs/src/main/tut/faq.md
This is a draft of a FAQ entry about the (newly mandatory) stack safety of `tailRecM`, as suggested by @kailuowang in #1412.
=> Add FAQ entry for tailRecM

docs/src/main/tut/faq.md
In response to @philwills's [comment](https://github.com/typelevel/cats/pull/1412#issuecomment-256167580) on #1412.
=> A few more Either FAQ details

free/src/main/scala/cats/free/FreeT.scala, free/src/test/scala/cats/free/FreeTTests.scala
Not that I'm impatient or anything, but here are the changes suggested by @non in @johnynek's #1411, which is currently the last thing we've said we want for the 0.8.0 release.
I went with `FunctionK` instead of `~>` because there are a lot of `FunctionK`s in cats-free and no `~>`s outside of FreeT.scala.
=> Rename interpret and replace ~>

free/src/main/scala/cats/free/Free.scala, free/src/main/scala/cats/free/FreeT.scala, free/src/test/scala/cats/free/FreeTTests.scala, free/src/test/scala/cats/free/FreeTests.scala
This came up for me in Free usage. We actually didn't want to call `foldMap` but to build another `FunctionK`.
Note, an interesting corollary to noting that Free converts a `FunctionK[S, M] => FunctionK[Free[S, ?], M]` and noting that we always have via `liftF` a `FunctionK[M, Free[M, ?]]` then if you have some code that requires complex recursive flatmaps, you can always first convert everything to `Free` via liftF, then in the end use the `Monad.tailRecM` along with `foldMap(FunctionK.id)`. So, in it seems that many classes of recursion, as long as you don't change the Monad, are covered by implementing tailRecM.
=> Add foldMap/compile FunctionK to Free companion

core/src/main/scala/cats/data/OptionT.scala, docs/src/main/tut/datatypes/either.md, docs/src/main/tut/datatypes/optiont.md, docs/src/main/tut/faq.md, docs/src/main/tut/typeclasses/imports.md, docs/src/main/tut/typeclasses/invariant.md
=> Fix broken documentation links

AUTHORS.md, CHANGES.md
I'd like to get an 0.8.0 release out sooner rather than later (see discussion on [Gitter](https://gitter.im/typelevel/cats?at=58068e502189c68f42fb6df9)), so I thought I'd get the ball rolling with a first draft of the release notes.
I'll also start a checklist for things that need to happen before the release. I'm only including PRs that other people have expressed an interest in seeing in this release (e.g. #1382) or that look ready-to-go and non-controversial, but we can add others if there's other stuff people want in 0.8.
I'll take care of finalizing the release notes, and could take a stab at the migration guide and `tailRecM` notes, but someone else might be able to get to those two tasks before me.
=> 0.8.0 time!

docs/src/main/tut/typeclasses/monad.md
Replaced `defaultTailRecM` with a handwritten example.
=> Remove `defaultTailRecM` from monad doc

docs/src/main/tut/typeclasses/monad.md
Not sure of the underlying machinary, but it turned out that the missing closing brace has been causing mysterious tut passing found on #1444.
=> Fix tut in monad doc

build.sbt, free/src/test/scala/cats/free/FreeTTests.scala, free/src/test/scala/cats/free/FreeTests.scala
A couple of weeks ago [I noticed](https://gitter.im/typelevel/cats?at=58080b6d48292577613d18e9) that updating to ScalaCheck 1.13.3 was causing weird ScalaTest errors. I "fixed" this by not updating to ScalaCheck 1.13.3.
Staying on 1.13.2 is no longer an option now that we're updating to 2.12.0, and I've confirmed that the same thing happens with 1.13.4 and 2.12.0. 
The problem isn't actually ScalaTest calling `getSimpleName`—that's just making the error message uselessly obscure. Instead the problem seems to be some new bounds checking for `Gen.Choose` that was introduced in ScalaCheck 1.13.3. This PR fixes the issue by ensuring we don't call `Gen.chooseNum` with `min = 1` and `max = 0`.
This seems sensible but someone whose familiar with the logic of these `Arbitrary` instances should …
=> Fix Arbitrary instances in Free tests for ScalaCheck 1.13.3

docs/src/main/tut/typeclasses.md, docs/src/main/tut/typeclasses/typeclasses.md
Also removed type class list at bottom of type classes page since it's now in the sidebar
I think the previous version didn't really motivate type classes or discuss how type classes compare to the "usual" subclassing. I think this new one does a better job, but of course am open to comments/criticisms :-)
=> Revamp type classes doc

core/src/main/scala/cats/instances/either.scala
I'm not sure I entirely understand the instance naming conventions but this one was clearly inconsistent.
=> Rename SemigroupK instance for Either for consistency

core/src/main/scala/cats/arrow/FunctionK.scala, free/src/main/scala/cats/free/Free.scala, free/src/main/scala/cats/free/FreeApplicative.scala, free/src/main/scala/cats/free/FreeInvariantMonoidal.scala, free/src/main/scala/cats/free/FreeT.scala
FunctionK is a prime candidate. See #1374.
=> Use poly lambda syntax for FunctionK SAM instances

laws/src/main/scala/cats/laws/MonadLaws.scala
=> make tailRecMStackSafety lazy val

core/src/main/scala/cats/data/Coproduct.scala, core/src/main/scala/cats/data/EitherT.scala, core/src/main/scala/cats/data/Func.scala, core/src/main/scala/cats/data/Ior.scala, core/src/main/scala/cats/data/Prod.scala, core/src/main/scala/cats/data/Validated.scala, core/src/main/scala/cats/data/WriterT.scala
Hide
- traits for type class instances: `Coproduct`, `Func` and `Prod`.
- traits for functions: `EitherT`, `Ior`, `Validated` and `WriterT`.
See #1160.
=> Hide traits in data package

core/src/main/scala/cats/instances/all.scala, core/src/main/scala/cats/instances/symbol.scala
This also makes sure, that cats.instances.AllInstances contains the Symbol instances.
BTW, there are other instances, which are not in AllInstances (and as a result, are not in scope after doing `import cats.implicits._`), e.g., Eq[BitSet]. Is this intentional?
=> Show instance for scala.Symbol

build.sbt, project/plugins.sbt, scripts/travis-publish.sh
This wasn't running. I added the command to `validateJVM`.
Once we publish a 2.12 version we'll want to remove my switch that excludes mima for the 2.12 build - anything that changes should get caught in the meantime.
I'll also make a strong push for enabling this plugin for more of our modules, and being okay with minor version bumps if we do want to move fast. Life's tough downstream when you can't trust the version number.
=> enable mima binary compatibility check for cats-kernel

core/src/main/scala/cats/data/EitherT.scala, tests/src/test/scala/cats/tests/EitherTTests.scala
Adds `EitherT.cond`, which behaves just like `Either.cond` but lifted into the applicative functor `F`.
I thought about calling this `fromBoolean`, but I wanted to be consistent with the existing cond method on Either.
=> Add EitherT.cond

docs/src/main/tut/datatypes.md
At present, the documentation page for data types has a list of all the available data types: in this bullet list, the "Data Types" page itself is listed (see attached image).
This PR fixes the generation of the data type bullet list, so that "Data Type" is no longer listed as a valid data type.
=> Docs Data Type list fix

free/src/main/scala/cats/free/Cofree.scala, free/src/test/scala/cats/free/CofreeTests.scala, tests/src/test/scala/cats/tests/EvalTests.scala, tests/src/test/scala/cats/tests/Spooky.scala
Basic Cofree Comonad functionality, including a couple of instances. I tried to implement a few other things (`mapBranching(F ~> G)(Cofree[F, A]): Cofree[G, A]`, `decompile(F ~> W)(W[A]): Cofree[F, A]`) but I couldn't make them stack-safe. This implementation is inspired by the one in Scalaz.
=> Cofree comonad

core/src/main/scala/cats/Show.scala, core/src/main/scala/cats/syntax/all.scala, core/src/main/scala/cats/syntax/show.scala, tests/src/test/scala/cats/tests/ShowTests.scala
Non-macro alternative to #1489.
Happy to iterate - feedback welcome.
=> String interpolator for Show, without macros

core/src/main/scala/cats/data/Cokleisli.scala, core/src/main/scala/cats/data/Kleisli.scala, core/src/main/scala/cats/instances/function.scala
We can use `Compose.algebraK` and `Category.algebraK` to create the endomorphic `SemigroupK` and `MonoidK` instances of `Function1[α, α]`, `Kleisli[F, α, α]` and `Cokleisli[F, α, α]`.
=> Use Compose/Category.algebraK for endomorphic SemigroupK/MonoidK

core/src/main/scala/cats/Functor.scala, tests/src/test/scala/cats/tests/FunctorTests.scala
`strengthL` and `strengthR` for `Functor`s. Tuple regular values with effectful ones.
=> Functor tupleLeft and tupleRight

core/src/main/scala/cats/data/StateT.scala, tests/src/test/scala/cats/tests/StateTTests.scala
I hit some stack overflows using traverse with StateT. I don't think this will always solve the issue, but I tried to minimize stack depth in a number of cases.
=> Reduce stack depth in StateT

core/src/main/scala/cats/data/Ior.scala, tests/src/test/scala/cats/tests/IorTests.scala
Ior is sometimes used in a very biased way. These tools make for convenient use in that case.
=> Add biased operators to Ior

core/src/main/scala/cats/Eval.scala, core/src/main/scala/cats/package.scala, laws/src/main/scala/cats/laws/ReducibleLaws.scala, laws/src/main/scala/cats/laws/discipline/ReducibleTests.scala, tests/src/test/scala/cats/tests/EvalTests.scala, tests/src/test/scala/cats/tests/IdTests.scala
Using these on their own may not be that useful, but Reducible composes, so this allows us to use a reducible on `F[Eval[T]], Eval[F[T]]` or `F[Id[T]], Id[F[T]]`.
One small nice win is that `size` on `Eval` can avoid evaluation entirely. Probably never a win in practice, but hey...
=> Add Reducible for Eval and Id

core/src/main/scala/cats/arrow/FunctionK.scala, docs/src/main/tut/datatypes/freeapplicative.md, tests/src/test/scala/cats/tests/FunctionKTests.scala
Combine a `FunctionK[F, G]` and a `FunctionK[F, H]` to a `FunctionK[F, Prod[G, H, ?]]`.
This won't see as much use as `FunctionK#or`, but see the `FreeApplicative` tut example I changed for an example where it is useful.
=> Add FunctionK and

core/src/main/scala/cats/Foldable.scala, core/src/main/scala/cats/Reducible.scala, tests/src/test/scala/cats/tests/FoldableTests.scala, tests/src/test/scala/cats/tests/NonEmptyListTests.scala, tests/src/test/scala/cats/tests/ReducibleTests.scala
This adds 
- `Foldable.foldMapM` which is similar to `foldM` but using a `Monoid` instance
- `Reducible.reduceMapM` which is similar to `reduceLeftM` but using a `Semigroup` instance.
=> Add `Foldable.foldMapM` and `Reducible.reduceMapM`

core/src/main/scala/cats/instances/future.scala
=> Make catchNonFatal on Future async

core/src/main/scala/cats/data/NonEmptyList.scala, tests/src/test/scala/cats/tests/NonEmptyListTests.scala
`NonEmptyList` is implementing the `filter` method, but not the `filterNot`, which is available at `scala.collection.immutable.List`. This method is useful in order to avoid negating a filter condition.
=> Implement NonEmptyList#FilterNot

core/src/main/scala/cats/data/NonEmptyVector.scala, tests/src/test/scala/cats/tests/NonEmptyVectorTests.scala
As a follow up for the PR #1512, `NonEmptyVector` is also implementing the filter method, but not the `filterNot`, which is available at `scala.collection.immutable.Vector`. This method is useful in order to avoid negating a filter condition.
=> Implement NonEmptyVector#filterNot

core/src/main/scala/cats/data/NonEmptyList.scala, core/src/main/scala/cats/data/NonEmptyVector.scala, core/src/main/scala/cats/data/package.scala
In which `NonEmptyList` and `ValidationNel` are made covariant.
=> Make NonEmptyList covariant

core/src/main/scala/cats/Foldable.scala, core/src/main/scala/cats/Reducible.scala, tests/src/test/scala/cats/tests/FoldableTests.scala, tests/src/test/scala/cats/tests/ReducibleTests.scala
Add an element between all the existing elements while folding.
=> Add Foldable.intercalate

AUTHORS.md
I added everybody who made a first contribution in 0.8.1 or 0.9.0 to the AUTHORS file. I hope I didn't forgot someone.
@marcin-rzeznicki, @fkz, @xavier-fernandez, @DanielaSfregola and @adamnfish, if you don't want to be included or if you want to be listed differently than the name I copied from your Github profile, please let me now.
=> Update AUTHORS file for 0.9.0

CHANGES.md
As discussed in #1508. I've included #1506 even though it's not merged yet, since it's the biggest change in this release, but not the other unmerged PRs that are likely to make it into 0.9.0.
=> Draft of 0.9.0 release notes

docs/src/main/resources/microsite/data/menu.yml
After PR #1513 there's no such page. 
http://typelevel.org/cats/typeclasses/apply.html returns 404.
=> Remove link to apply.html from menu

free/src/main/scala/cats/free/Free.scala
This adds an `inject` operation for `Free` that lifts programs rather than constructors. This allows you to use existing `Free` programs (like doobie `ConnectionIO`) in coproducts without having to write implicit modules of lifted constructors.
I'll add a test if people think this is useful.
=> inject for free programs

core/src/main/scala/cats/syntax/package.scala
@jackcviers and @Wogan pointed out on our gitter channel that there is no piecemeal syntax import for `MonadError`.
=> Add piecemeal import for MonadError

core/src/main/scala/cats/Foldable.scala, core/src/main/scala/cats/Reducible.scala, core/src/main/scala/cats/data/NonEmptyList.scala, core/src/main/scala/cats/data/NonEmptyVector.scala, core/src/main/scala/cats/data/Validated.scala, core/src/main/scala/cats/instances/either.scala, core/src/main/scala/cats/instances/list.scala, core/src/main/scala/cats/instances/option.scala, core/src/main/scala/cats/instances/set.scala, core/src/main/scala/cats/instances/stream.scala, core/src/main/scala/cats/instances/try.scala, core/src/main/scala/cats/instances/tuple.scala, core/src/main/scala/cats/instances/vector.scala, core/src/main/scala/cats/package.scala, laws/src/main/scala/cats/laws/FoldableLaws.scala, laws/src/main/scala/cats/laws/discipline/FoldableTests.scala, laws/src/main/scala/cats/laws/discipline/ReducibleTests.scala, laws/src/main/scala/cats/laws/discipline/TraverseFilterTests.scala, laws/src/main/scala/cats/laws/discipline/TraverseTests.scala, tests/src/test/scala/cats/tests/FoldableTests.scala, tests/src/test/scala/cats/tests/OneAndTests.scala, tests/src/test/scala/cats/tests/TupleTests.scala
- Override `Foldable` methods in a lot of instances (including `Reducible` and `NonEmptyReducible`)
- Override `MonoidK#algebra` for `List`, `Vector`, etc to get kernel `Monoid` instance
- Add `Reducible` for `Tuple2`
I might have gone a bit overboard with overriding in the "one element `Foldable`" instances (`Option`, `Either`, ...).
=> Override Foldable methods

CONTRIBUTING.md
it seems as if there are no static pages any more in the website.
I added a path to the menu file instead, as it might help to give people a lead on how the menus are
constructed.
=> fix ref to non-existent dir in contributing

docs/src/main/tut/typeclasses/monad.md
I found this section pretty confusing, but cleared up my misunderstanding quickly in the console.
This extra line in the example might help make it clear to people what is going on.
=> add to Monad ifM example

core/src/main/scala/cats/data/Kleisli.scala, tests/src/test/scala/cats/tests/KleisliTests.scala
=> MonadError instance for Kleisli

core/src/main/scala/cats/Eval.scala, tests/src/test/scala/cats/tests/EvalTests.scala
These methods provide the basis for a `MonadError[Eval, Throwable]`
instance, without adding any overhead for people who don't wish to use
these (admittedly limited) capabilities.
Since `Eval` defers evaluation, we can take advantage of this to defer
additional recovery logic to the eventual evaluation. Critically, it doesn't
add any kind of *error node* to the `Eval` AST, or any extra overhead to
the default evaluation paths.
This came up when I was trying to catch up on https://github.com/typelevel/cats/pull/1552.
I realized there was no real reason why we couldn't have a
`MonadError[Eval, Throwable]` instance.
Review by @johnynek, @alexandru, et al.
=> Add basic exception-handling to Eval.

core/src/main/scala/cats/eq/Is.scala, core/src/main/scala/cats/evidence/Is.scala, core/src/main/scala/cats/evidence/package.scala, tests/src/test/scala/cats/tests/EvidenceTests.scala
(See #1177 for initial discussion)
This PR adds Leibniz type equality under the name `A Is B`. Leibniz equality is an improvement over `Predef.=:=` as it can be substituted into type expressions and as it has more computational meaning. Both of these add power and convenience to `Is` which makes it appealing for certain kinds of pure functional work. I am, for instance, using a local version of this in a [Cats-based lens library I'm working on](https://github.com/tel/scala-telescope) to implement a generalized `Equality[S, T, A, B]` optic at the base of the optical hierarchy. It also shows up nicely for making GADTs with more computational integrity.
This is my first Cats contribution so there's probably a lot missing—please let me know how to continue to develop it.
- I've simplified the …
=> Add Is constructor for Leibniz equality

kernel/src/main/scala/cats/kernel/Group.scala
Documentation initially said `remove` was equivalent to `combine(a, inverse(a))`. Changed to be equivalent to `combine(a, inverse(b))` instead.
=> Fix mistake in documentation of Group.remove

core/src/main/scala/cats/data/NonEmptyList.scala, tests/src/test/scala/cats/tests/NonEmptyListTests.scala
- "collect" method is really useful when wanting to do a transformation in some of the elements from a collection, applying a partial function. This PR implements this method both for `NonEmptyVector` and `NonEmptyList`.
=> Implement NonEmptyList#Collect

README.md
I've already polled the current maintainers and they were unanimous in wanting to add Edmund to the list. I also spoke to Edmund and he agreed, so this PR is just a formality at this point.
=> Add Edmund Noble to maintainers.

core/src/main/scala/cats/Applicative.scala, core/src/main/scala/cats/Monad.scala, core/src/main/scala/cats/syntax/all.scala, core/src/main/scala/cats/syntax/applicative.scala, core/src/main/scala/cats/syntax/monad.scala, core/src/main/scala/cats/syntax/package.scala, tests/src/test/scala/cats/tests/ApplicativeTests.scala, tests/src/test/scala/cats/tests/MonadTest.scala
Continuation on #1216. I didn't add the other methods yet because I want to make sure I get the tests right first. There are no tests present in either original PR or Scalaz . 
cc @tpolecat @johnynek 
Fixes #1569.
=> added whileM, untilM, iterateWhile, etc to Monad

core/src/main/scala/cats/Applicative.scala, laws/src/main/scala/cats/laws/ApplicativeLaws.scala, laws/src/main/scala/cats/laws/discipline/ApplicativeTests.scala
Adding a short-hand to `Applicative` for `F.pure(())`.
```scala
@typeclass trait Applicative[F[_]] extends Apply[F] { self =>
/**
* Returns an `F[Unit]` value, equivalent with `pure(())`.
*
* A useful shorthand, also allowing implementations to optimize the
* returned reference (e.g. it can be a `val`).
*/
def unit: F[Unit] = pure(())
```
Reasons:
1. I find myself doing `F.pure(()).map(_ => a)` a lot (due to `pure` not taking a by-name param and having no way to do that otherwise, but that's another discussion)
2. `F[Unit]` is often used to indicate callbacks that are going to trigger side-effects, like for resource clean-ups - for example in `Task.doOnFinish` and we often need to create empty `F[Unit]` instances that don't do anything; `F.pure(())` is more noisy versus `F.unit`
3. …
=> Add Applicative.unit

docs/src/main/tut/datatypes/kleisli.md
First, I found the documentation to be a decent introduction to the concept -- so thanks!
I just found stating `Returning to our earlier example` and then using a different solution to the earlier example be misleading --  I ended up scrolling up the page thinking I had missed a step!
It would be clearer to use the same solution.
=> Docs/Tutorial -- Simplify Kleisli example

core/src/main/scala/cats/data/NonEmptyList.scala, tests/src/test/scala/cats/tests/NonEmptyListTests.scala
Adds a new method `NonEmptyList#fromFoldable`.  This generalizes `NonEmptyList.fromList` such that you can also create a `NonEmptyList` from anything that has a `Foldable` instance, e.g., `Vector`, `Set`, ...
=> Add NonEmptyList#fromFoldable

core/src/main/scala/cats/data/EitherT.scala, js/src/test/scala/cats/tests/FutureTests.scala, jvm/src/test/scala/cats/tests/FutureTests.scala, tests/src/test/scala/cats/tests/ConstTests.scala, tests/src/test/scala/cats/tests/EitherTTests.scala, tests/src/test/scala/cats/tests/NestedTests.scala, tests/src/test/scala/cats/tests/TryTests.scala, tests/src/test/scala/cats/tests/Tuple2KTests.scala
=> Improve test coverage

core/src/main/scala/cats/instances/all.scala, core/src/main/scala/cats/instances/bitSet.scala, core/src/main/scala/cats/instances/package.scala, tests/src/test/scala/cats/tests/BitSetTests.scala
Fixes #1485 , I double checked. I believe that `BitSet` is the only missing one.
=> added instances of BitSet to allInstances

core/src/main/scala/cats/FlatMap.scala, core/src/main/scala/cats/instances/tuple.scala, laws/src/main/scala/cats/laws/FlatMapLaws.scala, laws/src/main/scala/cats/laws/discipline/FlatMapTests.scala
=> Add FlatMap.forEffect

core/src/main/scala/cats/data/OneAnd.scala, docs/src/main/tut/datatypes/oneand.md
Additionally lessen the `MonadCombine` constraint to `Alternative` for some `OneAnd` methods.
=> Remove references of the NEL OneAnd alias

docs/src/main/resources/microsite/data/menu.yml, docs/src/main/tut/typeclasses/invariantmonoidal.md
InvariantMonoidal was not generated because of a typo and not present on the left-side menu, this PR solves both issues.
Related to #1609.
=> Fix doc for InvariantMonoidal

core/src/main/scala/cats/data/package.scala, free/src/test/scala/cats/free/FreeTTests.scala, laws/src/main/scala/cats/laws/discipline/Arbitrary.scala, tests/src/test/scala/cats/tests/KleisliTests.scala, tests/src/test/scala/cats/tests/StateTTests.scala
This should be the only data type missing `Arbitrary` instance in laws. 
fixes #1274
=> Move arbitrary instance of StateT to laws

docs/src/main/resources/microsite/data/menu.yml, docs/src/main/tut/datatypes/functionk.md
I'm sure that there is more that could be done with this, and I'm very
open to recommendations, but I wanted to get something out there.
=> Add tut doc for FunctionK

core/src/main/scala/cats/data/Kleisli.scala, tests/src/test/scala/cats/tests/KleisliTests.scala
- Switch the order of the traits so that some methods are overridden by the implementation in other type class instances in its hierarchy
For example:
- `extends Monad[Kleisli[F, A, ?]] with KleisliApplicative[F, A]`
- instead of `extends KleisliApplicative[F, A] with Monad[Kleisli[F, A, ?]]`)
We were already overriding `ap` in `Monad`, this also overrides `product` (which was the initial reason for this PR).
For the rest we can just loose a couple of explicit overrides (eg `super[KleisliSplit].split(f, g)`)
- Add a `MonadReader` test for `Reader`, which improves some code coverage.
=> Override some methods in Kleisli instances

core/src/main/scala/cats/data/EitherT.scala, tests/src/test/scala/cats/tests/EitherTTests.scala
using PartiallyApplied to improve the API
added a `leftT` and `rightT` alias
=> added leftT and improved existing lift API for EitherT

core/src/main/scala/cats/Show.scala
f could be misleading. usually f parameter is used for functions
=> show(f:T) to show(t:T)

build.sbt
@yilinwei mentioned on the gitter channel that we could change the simulacrum dependency to be compile time only.
=> Make simulacrum a compile time only dependency

core/src/main/scala/cats/InjectK.scala
Tiny tweak.
A similar update/cleanup can be done if an applicative for type constructors is introduced and a "`liftK`" helper is added to `FunctionK`
=> Make InjectK use FunctionK.id for reflexive injection

README.md
Feeestyle is a framework and collection of libraries for building purely functional applications and libraries. Freestyle integrates closely with cats and uses several of the cat's typeclasses and datatypes both internally and in the user facing APIs.
We'd love to be included in the list of Related Projects.
More info about Freestyle can be found at http://frees.io/
Thank you for you consideration :)
=> Adds Freestyle to `Related Projects` list

docs/src/main/tut/datatypes/freeapplicative.md
It seems like we use `validator` as a variable name for a similar value in the previous chapter.
And beside of that, this value is made from `ParValidator` type.
=> Fix typo in FreeApplicative doc.

core/src/main/scala/cats/InjectK.scala
It would be extremely useful to open up the injection helpers in Free to support any target coproduct type. This is the simplest solution to address this "issue".
Related gitter conversation: https://gitter.im/typelevel/cats?at=590627c9d32c6f2f0956189d
For discussion:
- Should this be converted to a trait?
- Should `apply`/`unapply` be removed?
- Should a test be added to ensure injection into type constructors other than `EitherK` can occur?
=> Unseal InjectK to allow for extension by other libraries

core/src/main/scala/cats/instances/either.scala, core/src/main/scala/cats/instances/try.scala, laws/src/main/scala/cats/laws/ApplicativeErrorLaws.scala, laws/src/main/scala/cats/laws/discipline/ApplicativeErrorTests.scala
- Overrides `ApplicativeError#fromTry` for `Try`
- Overrides `ApplicativeError#fromEither` for `Either`
- Add an additional law for `ApplicativeError` ensuring consistency between `attempt` + `fromEither` and `pure`.
The last two are sort of a follow up after #1651.
=> Override fromTry and fromEither for Try and Either

core/src/main/scala/cats/data/Const.scala, core/src/main/scala/cats/data/EitherT.scala, core/src/main/scala/cats/data/OptionT.scala, core/src/main/scala/cats/data/Validated.scala, core/src/main/scala/cats/syntax/either.scala, docs/src/main/tut/guidelines.md, free/src/main/scala/cats/free/Free.scala
A trick from scalaz thanks to @edmundnoble from this [comment](https://github.com/typelevel/cats/pull/1614#discussion_r112397323)
=> make all PartialApplied class AnyVal to achieve zero cost

core/src/main/scala/cats/data/Validated.scala
Present as a syntax enrichment already.
=> Add Validated.validNel

laws/src/main/scala/cats/laws/discipline/Arbitrary.scala
Resolves #1605.
This is a replacement for #1619. The approach taken in that PR led to
implicit resolution failures in scala.js.
=> Use Cogen for arbitrary instances

tests/src/test/scala/cats/tests/EitherTTests.scala
=> add unit test for variance on methods in EitherT

.travis.yml, core/src/main/scala/cats/data/Kleisli.scala, laws/src/main/scala/cats/laws/discipline/Eq.scala, laws/src/test/scala/cats/laws/discipline/EqTests.scala, scripts/travis-publish.sh
This PR breaks out the scalajs builds to separate travis matrix build to cut down build time which was exceeding the 50 minute hard limit set by traivs. 
see [#1666](https://github.com/typelevel/cats/pull/1666#issuecomment-301656528) for further discussion.
=> Fixing `Eq[Function1]` in testsJS; break JS build to separate matrix build. 

README.md
Per #1675, I created the cats-contrib channel and this is the PR to add it to README.
=> Update readme with the new dev channel.

core/src/main/scala/cats/Eval.scala, tests/src/test/scala/cats/tests/EvalTests.scala
This PR renames `Eval.raise` to `Eval.raiseError`.
This is a pet peeve of mine, but the naming of failing data constructors isn't consistent across the board, so we've got:
- `Eval.raise`
- `ApplicativeError.raiseError`
- `cats.effect.IO.fail`
- `Future.failure`
- `scalaz.concurrent.Task.fail`
- `scalaz.MonadError.raiseError`
- `fs2.Task.fail`
- `monix.eval.Task.raiseError`
If we have `raiseError` in `ApplicativeError`, then I see no reason to not use it across the board. 
And if that's not OK for some reason related to `Throwable`, then the next option should be `fail`, not `raise`.
Either way, we should standardise on something.
EDIT: trying to do the same in `cats-effect` - https://github.com/typelevel/cats-effect/pull/33
=> Rename Eval.raise to Eval.raiseError

tests/src/test/scala/cats/tests/CatsSuite.scala
As far as I can tell, our CI build has 2 cores available on Travis. So I
suspect that 2 workers might be a sweet spot for our JVM testing. As I
understand it, the JS runtime is single-threaded, so we probably won't
benefit from additional workers on it (as our tests should be
CPU-bound).
I could be totally wrong about these assumptions, but I'm interested in
how the build times for this PR compare.
=> Use 2 workers in JVM build

.travis.yml
If there are **no other builds** (for other PRs, branches, ...), switching the JVM/JS order to JS/JVM can be 10-15 minutes quicker.
There are now 6 Travis jobs for every build (3 Scala versions and JVM / JS) and only 5 are executing at the same time. By switching the order, the three longer JVM jobs are started first and when the 2.11 JS job finishes, the 2.12 JS job can start (which doesn't take as long as the 2.12 JVM job which is now started last).  
I ran Travis [twice](http://imgur.com/a/dPLRz) resulting in total build times of 31 and 39 minutes while the last master builds took around 50 minutes.
This is just a minor improvement of the Travis matrix build change by @kailuowang in #1671.
=> Build JVM before JS on travis

core/src/main/scala/cats/data/EitherT.scala
With the partial unification fix in place, we can clean up some `EitherT` doctests a bit.
=> Clean up EitherT doctests

core/src/main/scala/cats/Reducible.scala, tests/src/test/scala/cats/tests/ReducibleTests.scala
courtesy of @ceedubs finding the bug.
=> Fix issue in Reducible

core/src/main/scala/cats/data/Ior.scala, core/src/main/scala/cats/data/NonEmptyList.scala, core/src/main/scala/cats/data/NonEmptyVector.scala, free/src/test/scala/cats/free/CofreeTests.scala, tests/src/test/scala/cats/tests/IorTests.scala, tests/src/test/scala/cats/tests/NonEmptyVectorTests.scala
`NonEmptyList.one(x)` is analogous to `x.pure[NonEmptyList]`.
Alternative for `NonEmptyList.of(x)` where you don't pay the price of the varargs, which isn't used.
Benchmark for `.of(1)` and `.one(1)`:
```
[info] Benchmark           Mode  Cnt          Score          Error  Units
[info] NelOfBench.nelOf   thrpt   20   14153921.124 ±    71083.406  ops/s
[info] NelOfBench.nelOne  thrpt   20  122074571.622 ± 25745302.862  ops/s
[info] NelOfBench.nevOf   thrpt   20   19260517.026 ±  2714989.060  ops/s
[info] NelOfBench.nevOne  thrpt   20   28379095.763 ±  3294357.173  ops/s
```
=> Add NEL/NEV one

bench/src/main/scala/cats/bench/TrampolineBench.scala, free/src/main/scala/cats/free/Free.scala, free/src/main/scala/cats/free/FreeT.scala, free/src/main/scala/cats/free/Trampoline.scala, free/src/test/scala/cats/free/FreeTests.scala
I chose `defer` over `suspend` because both `Free` and `FreeT` have a `Suspend` which is used by `liftF` (not by `suspend`), so this may reduce that confusion as well.
This meant replacing three methods though, where `Eval.defer` -> `Eval.suspend` would be only one change. Cats-effect also seems to have chosen `suspend` (in `Sync`).
So this isn't set in stone, I'll happily switch it around if that is what we prefer. Just thought that a PR may help us to decide, since #1635 has been a bit quiet. So, what do we think?
=> Rename `suspend` to `defer` (or vice versa ??)

core/src/main/scala/cats/data/ReaderWriterStateT.scala, laws/src/main/scala/cats/laws/discipline/Arbitrary.scala, tests/src/test/scala/cats/tests/KleisliTests.scala, tests/src/test/scala/cats/tests/ListWrapper.scala, tests/src/test/scala/cats/tests/ReaderWriterStateTTests.scala, tests/src/test/scala/cats/tests/StateTTests.scala, tests/src/test/scala/cats/tests/WriterTTests.scala
- Check if type class instances are serializable
- Move Arbitrary instance to cats-laws
- Move unambiguous type class instances
---
I also find the ordering of the type parameters a bit confusing. Now it is `E` (`Reader`) -> `S` (`State`) -> `L` (`Writer`), while the name `ReaderWriterStateT` suggests that `Writer` comes before `State`. The reason is probably the `Bifunctor` instance for the `Writer` part.
I would drop the `Bifunctor` instance and switch the order of `S` and `L` so it aligns with the name. We could also leave as it is or change to `ReaderStateWriterT` :smiley:. If we want to change something, it should probably be done before 1.0.0-MF. Opinions?
=> Clean up ReaderWriterStateT

free/src/main/scala/cats/free/Coyoneda.scala, free/src/test/scala/cats/free/CoyonedaTests.scala
Makes Coyoneda's `map` stack-safe, by keeping a list of functions and reversing it before applying them.
Breaking change.
=> Stack-safe Coyoneda

laws/src/main/scala/cats/laws/InjectKLaws.scala, laws/src/main/scala/cats/laws/discipline/InjectKTests.scala, tests/src/test/scala/cats/tests/InjectKTests.scala
=> Add InjectK laws

core/src/main/scala/cats/Eval.scala, core/src/main/scala/cats/StackSafeMonad.scala, core/src/main/scala/cats/instances/future.scala, free/src/main/scala/cats/free/Free.scala, tests/src/test/scala/cats/tests/RegressionTests.scala
I'm tired of defining the same `tailRecM` over and over again when the underlying monad is already known to be stack-safe.  This mixin provides a more convenient way of achieving this goal.  Obviously, the implementation is only valid if the underlying monad has a stack-safe `flatMap`, but *if* it has a stack-safe `flatMap`, then this is almost certainly going to be the implementation.  May as well reduce some of the boilerplate in that case.
=> Added StackSafeMonad mixin

laws/src/main/scala/cats/laws/discipline/Arbitrary.scala
As pointed out [here](https://github.com/typelevel/cats/issues/1640#issuecomment-298125906)
This reveals law violations in `StateT`. It looks like `flatMap`/`ap`
consistency does not hold, as well as `MonadCombine`
right-distributivity. It's not immediately clear to me how to fix this,
so I'm opening this up in case somebody else gets to it first.
=> StateT violates laws

docs/src/main/tut/faq.md
Closes #1624 
Ping @ceedubs.  I'd also like to hear @alexandru's and @mpilquist's thoughts on the wording.  I wanted to make it clear that `cats.effect.IO` is an easy and minimal default, while the typeclasses should ensure that the space of alternatives remains coherent and should be viable (or even preferable) under most circumstances.
=> Rewrote documentation on the IO monad to reference cats-effect

core/src/main/scala/cats/Foldable.scala, free/src/main/scala/cats/free/Free.scala, free/src/test/scala/cats/free/FreeTests.scala, tests/src/test/scala/cats/tests/FoldableTests.scala
This is an implementation of `foldLeftM` without using `Free`. Instead, it introduces an auxiliary structure
``` scala
case class Source[A](uncons: () => Option[(A, Source[A])])
```
and a conversion from any foldable `F[A]` to `Source[A]`, which provides lazy access to elements of `F[A]`.
It still uses `foldRight`, but I think there is a better separation of concerns here, because `G` is not involved in the `foldRight` at all.
~~I didn't bother to move this out of `Free.scala`, but `Free` is not used here at all.~~ I moved the implementation to `Foldable`.
Funny enough, if I make `Source` extend `AnyVal`, it crashes the compiler with a `StackOverflowError` ([SI-9600](https://issues.scala-lang.org/browse/SI-9600)).
=> `foldLeftM` without `Free`.

core/src/main/scala/cats/Inject.scala, core/src/main/scala/cats/InjectK.scala, laws/src/main/scala/cats/laws/InjectLaws.scala, laws/src/main/scala/cats/laws/discipline/InjectTests.scala, tests/src/test/scala/cats/tests/InjectTests.scala
Re-introduces `Inject`, but for `Either`. I also went ahead and tried to document both `Inject` and `InjectK`.
Todo:
Associated issue: https://github.com/typelevel/cats/issues/1599
=> Inject for either

core/src/main/scala/cats/Foldable.scala, core/src/main/scala/cats/data/NonEmptyList.scala, core/src/main/scala/cats/data/NonEmptyVector.scala, core/src/main/scala/cats/instances/list.scala, core/src/main/scala/cats/instances/map.scala, core/src/main/scala/cats/instances/set.scala, core/src/main/scala/cats/instances/stream.scala, core/src/main/scala/cats/instances/vector.scala, tests/src/test/scala/cats/tests/FoldableTests.scala
also related https://github.com/typelevel/cats/pull/1117/files#r123765689
=> remove iteratorFoldM fixes #1716

core/src/main/scala/cats/data/package.scala
Often when doing validations using `ValidatedNel`, the result is converted to `Either` when returning to a higher level where steps are sequenced. It'd be convenient to represent this type as `EitherNel` instead of `Either[NonEmptyList[...`
=> Add EitherNel type alias for Either[NonEmptyList[E], A]

core/src/main/scala/cats/data/IdT.scala, free/src/test/scala/cats/free/FreeTTests.scala, tests/src/test/scala/cats/tests/EitherTTests.scala, tests/src/test/scala/cats/tests/IdTTests.scala, tests/src/test/scala/cats/tests/OptionTTests.scala, tests/src/test/scala/cats/tests/ReaderWriterStateTTests.scala, tests/src/test/scala/cats/tests/WriterTTests.scala
I am not sure how often `IdT` is actually used, but this PR should improve its test coverage.
I think it makes sense to merge #1621 first, I will replace `TransLift` with `MonadTrans` in this PR afterwards.
=> Improve test coverage `IdT`

.jvmopts, build.sbt, core/src/main/scala/cats/data/EitherT.scala, core/src/main/scala/cats/data/OneAnd.scala, core/src/main/scala/cats/data/Tuple2K.scala, core/src/main/scala/cats/syntax/all.scala, core/src/main/scala/cats/syntax/apply.scala, core/src/main/scala/cats/syntax/cartesian.scala, core/src/main/scala/cats/syntax/package.scala, core/src/main/scala/cats/syntax/tuple.scala, docs/src/main/tut/datatypes/freeapplicative.md, docs/src/main/tut/datatypes/validated.md, docs/src/main/tut/faq.md, docs/src/main/tut/typeclasses/applicative.md, docs/src/main/tut/typeclasses/invariantmonoidal.md, free/src/test/scala/cats/free/FreeApplicativeTests.scala, project/Boilerplate.scala, tests/src/test/scala/cats/tests/CsvCodecInvariantMonoidalTests.scala, tests/src/test/scala/cats/tests/ReaderWriterStateTTests.scala, tests/src/test/scala/cats/tests/SyntaxTests.scala
This PR is to finish up #1487. I deprecated the `CartesianBuilder`, merged the master and one small correction in the build file.
=> Deprecate CartesianBuilder, finish up #1487

core/src/main/scala/cats/instances/order.scala, kernel/src/main/scala/cats/kernel/Order.scala, tests/src/test/scala/cats/tests/OrderTests.scala
Does... anyone know where I would put a test? If it's worth testing? Also, kernel is open for changes for 1.0, right?
=> Add Order->Ordering implicit conversion to implicits, instances

core/src/main/scala/cats/syntax/package.scala, tests/src/test/scala/cats/tests/ShowTests.scala
Nobody can use the `show` interpolator otherwise with a-la-carte imports 😝
Edit: Thanks @alexknvl for pointing this out.
=> Make syntax.show extend ShowSyntax instead of Show.ToShowOps

tests/src/test/scala/cats/tests/CokleisliTests.scala, tests/src/test/scala/cats/tests/ReaderWriterStateTTests.scala, tests/src/test/scala/cats/tests/StateTTests.scala, tests/src/test/scala/cats/tests/WriterTTests.scala
(Partial) fix for #1757.
This doesn't help to speed up the associativity laws in `CokleisliTests` (or not very much).
=> Faster tests by reducing the size of lists

tests/src/test/scala/cats/tests/ReaderWriterStateTTests.scala, tests/src/test/scala/cats/tests/StateTTests.scala
Locally looping 60000-deep in a recursive function is enough to blow my stack; as it is, these tests still fail on my machine with `Eval` swapped for `Id`.
=> Decrease stack-safety test size

core/src/main/scala/cats/Show.scala, tests/src/test/scala/cats/tests/ShowTests.scala
Contravariance in type class parameters is well-documented to be an issue for the compiler. Specifically, the compiler has a useless version of "specificity" which forces the least specific instance to be used, if there are overlapping instances and the user does not use an explicit inheritance-based prioritization.
However, the benefit is still there: firstly there is no need for a `Show[BitSet]`, because the existing `Show[Set[Int]]` is narrowed implicitly. In the same vein, `Some(1).show` works even if your instance only exists for `Option[Int]` and not `Some[Int]`. These benefits become more apparent when you construct values from inside a `show` interpolator, and need to use type ascriptions with the existing version of `Show`.
For examples of how users can make overlapping `Show` …
=> Make Show inherit from a contravariant base trait

core/src/main/scala/cats/data/IdT.scala, core/src/main/scala/cats/data/NonEmptyList.scala, core/src/main/scala/cats/instances/stream.scala, free/src/test/scala/cats/free/FreeTests.scala, jvm/src/test/scala/cats/tests/FutureTests.scala, macros/src/main/scala/cats/macros/Ops.scala, tests/src/test/scala/cats/tests/ApplicativeTests.scala, tests/src/test/scala/cats/tests/ComposeTest.scala, tests/src/test/scala/cats/tests/EitherTests.scala, tests/src/test/scala/cats/tests/EvalTests.scala, tests/src/test/scala/cats/tests/GroupTests.scala, tests/src/test/scala/cats/tests/IdTTests.scala, tests/src/test/scala/cats/tests/IsTests.scala, tests/src/test/scala/cats/tests/KleisliTests.scala, tests/src/test/scala/cats/tests/MonoidTests.scala, tests/src/test/scala/cats/tests/NonEmptyListTests.scala, tests/src/test/scala/cats/tests/OrderTests.scala, tests/src/test/scala/cats/tests/PartialOrderTests.scala, tests/src/test/scala/cats/tests/SplitTest.scala, tests/src/test/scala/cats/tests/WriterTTests.scala
Calculated hail mary to increase coverage, to somewhat balance out the MTL removal coverage decrease.
=> More coverage

core/src/main/scala/cats/data/ReaderWriterStateT.scala, laws/src/main/scala/cats/laws/discipline/Arbitrary.scala, tests/src/test/scala/cats/tests/ReaderWriterStateTTests.scala
=> correct type parameter seq in RWST

core/src/main/scala/cats/Traverse.scala, core/src/main/scala/cats/instances/list.scala, core/src/main/scala/cats/instances/stream.scala, core/src/main/scala/cats/instances/vector.scala, tests/src/test/scala/cats/tests/TraverseTests.scala
This adds `traverseWithIndex`, `mapWithIndex` and `zipWithIndex` to `Traverse`.
- `traverseWithIndexM` is akin to `traverse`, but includes the index of the value in the structure `F`. This requires the effect to be monadic.
- `mapWithIndex` is akin to `map`, but includes the index of the value in the structure `F`.
- `zipWithIndex` returns F, with values tupled with their indices, just like Scala collection's zipWithIndex.
Instances for `List`, `Vector`, and `Stream` have overridden `mapWithIndex` and `zipWithIndex` that delegate to related underlying collections methods. `mapWithIndex` on `List` and `Vector` uses `.iterator` to avoid building an intermediate collection when first zipping with indices.
=> Add index related helpers to Traverse

core/src/main/scala/cats/data/Kleisli.scala, tests/src/test/scala/cats/tests/KleisliTests.scala
This adds a couple combinators that I was looking for today. `tap` exists in Scalaz, `tapWith` doesn't. I'm happy to take suggestions for better names.
=> Kleisli tap, tapWith

core/src/main/scala/cats/ApplicativeError.scala, core/src/main/scala/cats/MonadError.scala, core/src/main/scala/cats/syntax/applicativeError.scala, core/src/main/scala/cats/syntax/monadError.scala, laws/src/main/scala/cats/laws/ApplicativeErrorLaws.scala, laws/src/main/scala/cats/laws/MonadErrorLaws.scala, laws/src/main/scala/cats/laws/discipline/ApplicativeErrorTests.scala, laws/src/main/scala/cats/laws/discipline/MonadErrorTests.scala
PR:
As per [this](https://gitter.im/typelevel/cats?at=592d9206fcbbe1891c5cd4ac) Gitter conversation with @djspiewak, this PR adds two functions:
`ApplicativeError#onError`, to execute a callback on certain errors and rethrow:
```scala
onError[A](fa: F[A])(pf: PartialFunction[E, F[Unit]]): F[A]
```
with laws:
```scala
pure(a).onError(f) <-> pure(a)
raiseError(e).onError(err => fb) <-> fb *> raiseError(e)
```
Use case: error handling that respects module boundaries, e.g. rollback at the db layer, and then send a failed response at the http layer
`MonadError#adaptError`, to transform certain errors
```scala
def adaptError[A](fa: F[A])(pf: PartialFunction[E,E]): F[A] 
```
with laws:
```scala
pure(a).adaptError(f) <-> pure(a)
raiseError(e).adaptError(f) <-> raiseError(f(e))
```
Use case: …
=> Add `onError` and `adaptError` to Applicative/MonadError

docs/src/main/tut/typeclasses/monadcombine.md, docs/src/main/tut/typeclasses/monadfilter.md
This PR removes the `MonadCombine` and `MonadFilter` sections from the docs, as they have been moved to `cats-mtl` (they were empty before anyway).
=> Remove docs for old mtl type classes

AUTHORS.md, CHANGES.md, README.md, docs/src/main/tut/index.md
The process started July 27 and last for a couple of days, mainly due to the coordination needed between cats and cats-mtl). Here are the steps:
----------------------
As mentioned in the description, 1.0.0-MF is a draft for the final API of cats 1.0. Our user community will have the next couple of months to validate this draft and propose changes. 
The merged changes are included in the CHANGES.md. Let's talk about the outstanding items. 
Here are the outstanding PRs scheduled for 1.0.0-MF
Maintainers, if you have time, please help review, we can push them over the finish line. 
Here are the outstanding issues scheduled for 1.0.0-MF
The ones with "?" are the ones that I'm uncertain if they should or can go into 1.0.0-MF. Also obviously, these aren't the complete set of outstanding issues …
=> Prepare for the 1.0.0-MF release

README.md, docs/src/main/tut/index.md
=> promoting the ecosystem in readme a bit and fixed a typo

core/src/main/scala/cats/Foldable.scala, tests/src/test/scala/cats/tests/FoldableTests.scala
I was missing these utility functions.  I've been out of the loop for a while so let me know if I didn't contrib right, and I'll be happy to update.
=> Add `existsM` and `forallM` to Foldable

project/Boilerplate.scala
Fixes #1805 by moving the implicit parameter for tuple Cartesian methods from the ops class to the methods. As discussed in the issue this provides better error messages:
```
[error] C:\Users\gregoryd\Repos\cats\tests\src\test\scala\cats\tests\SyntaxTests.scala:204: could not find implicit value for parameter cartesian: cats.Cartesian[F]
[error]     tfabc mapN f
[error]           ^
```
instead of:
```
[error] C:\Users\gregoryd\Repos\cats\tests\src\test\scala\cats\tests\SyntaxTests.scala:204: value mapN is not a member of (F[A], F[B], F[C])
[error]     tfabc mapN f
[error]           ^
```
=> Move tuple Cartesian syntax implicit parameter

build.sbt, core/src/main/scala/cats/Show.scala, tests/src/test/scala-2.11+/cats/tests/RegressionTests.scala, tests/src/test/scala/cats/tests/RegressionTests.scala
=> workaround for a possible scala bug in show for value class. 

core/src/main/scala/cats/data/EitherT.scala
related type classes are removed.
=> remove outdated TODOs

docs/src/main/tut/typeclasses/foldable.md
Not sure if these examples are unnecessarily complicated?  I considered using `List[Option[Boolean]]` and `identity` instead, but I thought that might be confusing too.  Thanks for any feedback.
=> add Foldable.existsM/forallM to docs

scalafix/README.md, scalafix/build.sbt, scalafix/input/src/main/scala/fix/v1_0_0/RemoveCartesianBuilder2.scala, scalafix/input/src/main/scala/fix/v1_0_0/RemoveSplit.scala, scalafix/input/src/main/scala/fix/v1_0_0/RenameInjectProdAndCoproduct.scala, scalafix/input/src/main/scala/fix/v1_0_0/RenameTupleApplySyntax.scala, scalafix/output/src/main/scala/fix/v1_0_0/RemoveSplit.scala, scalafix/output/src/main/scala/fix/v1_0_0/RenameInjectProdAndCoproduct.scala, scalafix/output/src/main/scala/fix/v1_0_0/RenameTupleApplySyntax.scala, scalafix/project/plugins.sbt, scalafix/rewrites/src/main/scala/fix/Cats_v1_0_0.scala
This PR adds these rewrites:
- `RenameInjectProdAndCoproduct`
- `RenameTupleApplySyntax`
- `RemoveSplit`
Two of them are super easy thanks to a feature recently landed in Scalafix (`replaceSymbol`). For this reason I also upgraded Scalafix to the latest milestone release for 0.5.0.
=> Add RenameInjectProdAndCoproduct, RenameTupleApplySyntax and RemoveSplit Scalafix rewrites

core/src/main/scala/cats/data/EitherT.scala, core/src/main/scala/cats/data/IdT.scala, core/src/main/scala/cats/data/Ior.scala, core/src/main/scala/cats/data/OptionT.scala, core/src/main/scala/cats/data/Tuple2K.scala, core/src/main/scala/cats/data/WriterT.scala, core/src/main/scala/cats/instances/list.scala, core/src/main/scala/cats/instances/map.scala, core/src/main/scala/cats/instances/stream.scala, laws/src/main/scala/cats/laws/ApplyLaws.scala, laws/src/main/scala/cats/laws/discipline/ApplyTests.scala
I hit a case where I wanted laziness with map2Eval and realized in many
cases where we could have it, we do not. There were all the cases I saw
that we missed, which I hope our existing tests cover.
=> Added more implementations of map2Eval

README.md
This is a proposal to add `origami` to the list of Typelevel projects using cats. However if I remember correctly one of the criteria for being part of the system is to have a compiler-checked documentation which doesn't exist anymore (it was there on a previous version of the library). I will add it and maybe then we can merge in this PR? Is anything else needed?
=> Adding the origami project to the list of Typelevel projects using cats

README.md
This is for your consideration. Grafter uses `Reader` instances for component dependencies and `Eval` for actions starting-up the application graph.
=> Add `grafter` to the list of Typelevel projects using cats

docs/src/main/resources/microsite/data/menu.yml
Currently getting a 404 when selecting MonadCombine or MonadFilter.
=> Remove mtl classes from menu

free/src/main/scala/cats/free/Free.scala, free/src/test/scala/cats/free/FreeTests.scala
Addresses https://github.com/typelevel/cats/issues/1833 .
=> Add Foldable and Traversable instances for Free

build.sbt
This is required to compile cats for scala 2.13.0-M1.
=> Set scalaz version to 7.2.15

build.sbt
Both settings check if the `TRAVIS` environment variable is set.
=> Replace botBuild with sbt-travisci's isTravisBuild

build.sbt
This is a cosmetic change that has been possible since sbt 0.13.8:
https://github.com/sbt/sbt/releases/tag/v0.13.8
=> Pass sbt settings without varargs expansion

README.md
approval acquired at https://github.com/pureconfig/pureconfig/issues/298 and https://github.com/finagle/finch/issues/818
=> Add pureconfig and finch to ecosystem project list

build.sbt, core/src/main/scala/cats/syntax/apply.scala, core/src/main/scala/cats/syntax/cartesian.scala
This is required to compile cats for scala 2.13.0-M1.
see https://gitter.im/typelevel/cats-dev?at=59a03515a7b406262dc7722b
See also https://gitter.im/scala/community-builds?at=59a2c72eba0f0f6e38ea700c and links from there as well.
tldr is we wanted to check with scala team if these are known issues on 2.13.0-M1 as well.
This PR will override https://github.com/typelevel/cats/pull/1863, so sorry to @shokohara but thanks too!!
=> Set simulacrum version to 0.11.0

core/src/main/scala/cats/Monad.scala, core/src/main/scala/cats/syntax/monad.scala, tests/src/test/scala/cats/tests/MonadTest.scala
* Adds `iterateWhileM` and `iterateUntilM` to complement the existing `iterateWhile` and `iterateUntil` methods.
* Reimplements `iterateWhile` and `iterateUntil` in terms of the new `iterateWhileM` and `iterateUntilM`.
=> Add iterateWhileM and iterateUntilM

build.sbt
Scalatest 3.0.4 is not [published for 2.13.0-M1](http://central.maven.org/maven2/org/scalatest/scalatest_2.13.0-M1/) so we need to revert to 3.0.3 to compile cats for 2.13
3.0.4 is also [not mentioned in releases](https://github.com/scalatest/scalatest/releases) - we can track this and always re-bump later
=> Revert scalatest to 3.0.3

build.sbt
Using parentheses for disabling tasks with sbt 1.0 will issue the
following deprecation warning:
```
warning: Adaptation of argument list by inserting () is deprecated: this
is unlikely to be what you want.
signature: DefinableTask.:=(v: S): sbt.Def.Setting[sbt.Task[S]]
given arguments: <none>
after adaptation: DefinableTask.:=((): Unit)
publish := (),
^
```
This can be fixed with curly braces which is also perfectly fine with
sbt 0.13. So this can be merged right now and will make the actual
upgrade to sbt 1.0 easier.
=> build: use curly braces for disabling tasks

core/src/main/scala/cats/functor/Bifunctor.scala, tests/src/test/scala/cats/tests/BifunctorTests.scala
Quick and dirty, should resolve #1834.
=> Add right and left functor to BiFunctor

README.md, docs/src/main/tut/index.md
I think we have settled on "type class" being two words in all of our docs, so should be the same way here :)
=> Rename typeclass => type class in Readme.md

core/src/main/scala/cats/data/NonEmptyList.scala, core/src/main/scala/cats/data/NonEmptyVector.scala, tests/src/test/scala/cats/tests/NonEmptyListTests.scala, tests/src/test/scala/cats/tests/NonEmptyVectorTests.scala
=> Add zipWith to NonEmptyList and NonEmptyVector

build.sbt
Since Scala.js 0.6.20 our build displays this deprecation warning:
```
build.sbt:74: warning: value requiresDOM in object AutoImport is
deprecated: Requesting a DOM-enabled JS env with `jsDependencies +=
RuntimeDOM` or `requiresDOM := true` will not be supported in Scala.js
1.x. Instead, explicitly select a suitable JS with `jsEnv`, e.g., `jsEnv
:= new org.scalajs.jsenv.jsdomnodejs.JSDOMNodeJSEnv`.
requiresDOM := false,
^
```
Since we are already selecting a DOM-disabled JS environment with
```sbt
jsEnv := new org.scalajs.jsenv.nodejs.NodeJSEnv()
```
it seems to be enough to remove `requiresDOM` to get rid of this
deprecation warning.
=> Remove deprecated requiresDOM setting

core/src/main/scala/cats/Alternative.scala, core/src/main/scala/cats/Foldable.scala, core/src/main/scala/cats/Reducible.scala, core/src/main/scala/cats/data/NonEmptyList.scala, core/src/main/scala/cats/data/NonEmptyVector.scala, core/src/main/scala/cats/instances/list.scala, tests/src/test/scala/cats/tests/FoldableTests.scala, tests/src/test/scala/cats/tests/NonEmptyListTests.scala, tests/src/test/scala/cats/tests/NonEmptyVectorTests.scala, tests/src/test/scala/cats/tests/OneAndTests.scala, tests/src/test/scala/cats/tests/ReducibleTests.scala
As per #1743 (now closed). Also open for alternative names (`partitionIor` maybe?)
=> Add NonEmptyList#partitionE

docs/src/main/tut/faq.md
I think the right and left apply signatures should be switched, if I am reading https://github.com/typelevel/cats/blob/master/core/src/main/scala/cats/syntax/cartesian.scala#L20
and https://github.com/typelevel/cats/blob/master/core/src/main/scala/cats/syntax/cartesian.scala#L23
correctly.
=> Fix symbol signature for right and left apply in faq.md

build.sbt
This is another change that makes upgrading to sbt 1.0 easier
and which is compatible with sbt 0.13.
With sbt 1.0 the following line in `commonSettings`:
```
ivyConfigurations += config("compile-time").hide
```
leads to this exception:
```
[info] Loading settings from build.sbt,version.sbt ...
[info] Resolving key references (15580 settings) ...
[error] java.lang.IllegalArgumentException: requirement failed: id must be capitalized: commonSettings
[error]         at scala.Predef$.require(Predef.scala:277)
[error]         at sbt.librarymanagement.Configuration.<init>(Configuration.scala:19)
[error]         at sbt.librarymanagement.Configuration$.of(Configuration.scala:72)
[error]         at $61255add5b0123fd7403$.$anonfun$commonSettings$9(build.sbt:47)
```
The reason why `commonSettings` is …
=> Add val for "compile-time" sbt Configuration

core/src/main/scala/cats/Eval.scala, core/src/main/scala/cats/data/NonEmptyList.scala, core/src/main/scala/cats/data/NonEmptyVector.scala, core/src/main/scala/cats/data/OneAnd.scala, core/src/main/scala/cats/data/OptionT.scala, free/src/main/scala/cats/free/FreeT.scala
=> convert trait into abstract class for better bin compact

README.md
=> add bin compat goal

scalafix/project/plugins.sbt, scalafix/rewrites/src/main/scala/fix/Cats_v1_0_0.scala, scalafix/tests/src/test/scala/fix/Cats_Tests.scala
Since the last milestone there have been several breaking changes to the 0.5.0 API, which is now final!
Tests still pass ;)
/cc @olafurpg
=> Upgrade Scalafix to 0.5.0-RC2

build.sbt, docs/src/main/tut/typeclasses/lawtesting.md
Should resolve #1585. I'm thinking of creating another short section on why Laws are actually important, but for now this should be a good start I think.
Also I modified the build, so that `docs` depends on `testkit` and `laws`. Not sure, if this was the right way to do it, so feedback is very welcome :)
=> Add law testing guide

docs/src/main/resources/microsite/data/menu.yml, docs/src/main/tut/datatypes/eithert.md
I've been using `EitherT` recently, so I thought it would be a good idea to add some docs for it.
=> Add EitherT docs

tests/src/test/scala/cats/tests/IndexedStateTTests.scala
`MonoidK` laws were being checked instead of `Alternative`.
=> Fix Alternative law checking for IndexedStateT

docs/src/main/tut/typeclasses/imports.md
Still a WIP, but looking for some early feedback. Should resolve #1668
=> Add piecemeal import guide

core/src/main/scala/cats/data/NonEmptyList.scala, tests/src/test/scala/cats/tests/NonEmptyListTests.scala
I mentioned this on gitter (thanks @edmundnoble for the name suggestion). I needed to build a NEL from an init list and a last element, and didn't like using `unsafeFromList`. Not sure if it's generally useful but seems pretty natural given List's `init` and `last` operations.
No worries if you think it's out of scope and don't want to include it.
=> Add NonEmptyList.ofInitLast

core/src/main/scala/cats/data/Nested.scala, tests/src/test/scala/cats/tests/NestedTests.scala
Adds an instance for `ApplicativeError[Nested[F, G, ?], E]` given `ApplicativeError[F, E]` and `Applicative[G]` as discussed in #1818.
=> Add ApplicativeError for Nested

docs/src/main/resources/microsite/data/menu.yml, docs/src/main/tut/datatypes/eval.md
Adds some eval documentation with very basic examples, not sure if there are better examples around that can better showcase the usefulness of `Eval`. Either way, looking forward to feedback :)
=> Add Eval documentation

docs/src/main/resources/microsite/data/menu.yml, docs/src/main/tut/datatypes/ior.md
Some basic usage so far. Might make sense to also document more of the methods available on `Ior`:)
=> Add docs for Ior

docs/src/main/tut/typeclasses/show.md
This is still WIP as, `kittens` doesn't currently support `Show` (I hope to create PR soonish, https://github.com/milessabin/kittens/issues/40) @kailuowang also expressed interest :)
=> Add documentation for `Show`

docs/src/main/resources/microsite/data/menu.yml, docs/src/main/tut/typeclasses/eq.md
Adds some basic documentation for `Eq`. I'm not sure if this is enough, or if more would complicate things and turn off users, would love to hear some feedback :)
=> Add Eq docs

free/src/main/scala/cats/free/FreeApplicative.scala
Follow up after #1748 
`Ap` now contains two `FreeApplicative`s (instead of just one before), so we can do some more optimisation as we are currently doing. (The new implementation should also result in the same `FreeApplicative` as the original implementation).
Currently the result of `FreeApplicative`'s `map2` is one of the following two :
```scala
Pure(f(a, b))
Ap({ case (a, b) => f(a, b) }, Ap(Ap(Pure(a => b => (a, b)), fa), fb))
```
With this change it can be one of :
```scala
Pure(f(a, b))
Ap(Pure(f(a, _)), fb)
Ap(Pure(f(_, b)), fa)
Ap(Ap(Pure(a => b => f(a, b))), fa), fb)
```
=> Optimize FreeApplicative.product

docs/src/main/tut/guidelines.md
=> Document naming implicits according to @non s comment in #1061

project/plugins.sbt
I can't build cats because of https://github.com/coursier/coursier/issues/655.
=> Update coursier to version 1.0.0-RC12

README.md
Approvals from current maintainers were already given offline.  This is to make it official.
Welcome @LukaJCB!
=> Add Luka Jacobowitz as a maintainer

docs/src/main/tut/datatypes/validated.md
This is an approach to address #1678.
Being my first PR, I pushed to my fork the first draft of this a week ago and @zainab-ali gladly helped me with a revision.
This PR contains fixes to the suggestions made in the revision, grammar fixes and the addition of `toValidated`/`toValidatedNel` combinators in the example.
I'm aware of the discussion made in the issue about the detail level of this doc. I tried to document this as clearly as possible without delving into too much detail.
=> Validated beginners doc

core/src/main/scala/cats/syntax/either.scala, tests/src/test/scala/cats/tests/EitherTests.scala
This adds syntax for `ApplicativeError.fromEither` as [discussed on gitter](https://gitter.im/typelevel/cats?at=59caa574614889d47540eba7).
=> Add syntax for ApplicativeError.fromEither

build.sbt, kernel-laws/src/test/scala/cats/kernel/laws/LawTests.scala, kernel/src/main/scala/cats/kernel/instances/all.scala
temporarily disable to allow a couple of approved PRs (#1712 #1527) to pass build, should reenable after 1.0.0-RC1.
Also added `QueueInstances` and `DurationInstances` to `all` imports
=> temporarily disable MiMa check on kernel

core/src/main/scala/cats/data/EitherT.scala, tests/src/test/scala/cats/tests/EitherTTests.scala
Modeled after the right versions.
=> Implement EitherT#leftFlatMap and EitherT#leftSemiflatMap

core/src/main/scala/cats/Alternative.scala, core/src/main/scala/cats/syntax/alternative.scala
This PR adds `guard`, a small function on Alternative which I personally find pretty useful.
`guard: Boolean => F[Unit]`
Which returns `Alternative[F].empty` if the the boolean is  false, and `().pure[F]` if true
=> Add `guard` to Alternative

README.md
After answering questions about relating to partial-unification, I think we should reprioritize its standing in the Readme.md. This PR mentions the fix up front instead of a side-note further down below. WDYT? :)
=> Give higher priority to partial-unification fix

laws/src/main/scala/cats/laws/FlatMapLaws.scala, laws/src/main/scala/cats/laws/discipline/FlatMapTests.scala
I noticed you can implement flatMap from tailRecM and map. This gives a more direct law for flatMap rather than the limited `A, A => F[A]` iterated law that we have currently (since we can take `F[A]` and `A => F[B]` we have less structure on the input, so it is a stronger law.
I'd like to add this even though it shouldn't increase test coverage or currently find any bugs, it is a nice documentation of thinking about tailRecM which I continue to think of as a very important method for FlatMap/Monad when thinking about implementations which use bounded stack such as the scala on the jvm.
=> Add a more direct tailRecM law

README.md
I'm as much a fan of Rush as the next person, but 2712 should be a famous number in its own right.
Also, scala uses GitHub now.
I was intending on making a cooler first PR, but I skimmed the README while IntelliJ did what it does and now I can't un-notice this.
=> Mention the right issue number of doom.

.travis.yml, scalafix/build.sbt, scalafix/input/src/main/scala/fix/v1_0_0/ContraMapToLMap.scala, scalafix/output/src/main/scala/fix/v1_0_0/ContraMapToLMap.scala, scalafix/rules/src/main/scala/fix/Cats_v1_0_0.scala, scripts/travis-publish.sh
This PR provides an automatic fix for #1850, which should provide a seamless upgrading experience :)
=> Add scalafix for contramap

core/src/main/scala/cats/Apply.scala, core/src/main/scala/cats/Cartesian.scala, core/src/main/scala/cats/FlatMap.scala, core/src/main/scala/cats/syntax/cartesian.scala, core/src/main/scala/cats/syntax/flatMap.scala, docs/src/main/tut/faq.md, free/src/test/scala/cats/free/FreeTests.scala, laws/src/main/scala/cats/laws/ApplyLaws.scala, laws/src/main/scala/cats/laws/FlatMapLaws.scala, tests/src/test/scala/cats/tests/MonadTest.scala, tests/src/test/scala/cats/tests/SyntaxTests.scala
To do so, I moved `*>` and `<*` from `Cartesian` syntax to `Cartesian` type class. I also moved `followedBy` and `forEffect` to `Apply`. :)
Should fix #1954
=> Deprecate FlatMap's >> and << 

core/src/main/scala/cats/ApplicativeError.scala, core/src/main/scala/cats/data/EitherT.scala, docs/src/main/tut/datatypes/eithert.md, scalafix/README.md, scalafix/input/src/main/scala/fix/v1_0_0/RenameEitherTLiftT.scala, scalafix/output/src/main/scala/fix/v1_0_0/RenameEitherTLiftT.scala, scalafix/rules/src/main/scala/fix/Cats_v1_0_0.scala
To be consistent with `OptionT.liftF`.
Fixes #1945
=> Rename EitherT.liftT to EitherT.liftF

core/src/main/scala/cats/FlatMap.scala
It's a useful way of adding side-effects (as in, effects on the side) of a monadic computation.
I almost called it `flatTap`; I welcome opinions for or against either name.
=> Add FlatMap#flatTap, a more principled version of the kestrel combinator.

laws/src/main/scala/cats/laws/discipline/ApplyTests.scala, laws/src/main/scala/cats/laws/discipline/FlatMapTests.scala
Move the `followedBy` and `forEffect` consistency tests from `FlatMapTests` to `ApplyTests`.
Small follow up on #1955.
=> Move followedBy/forEffect tests to ApplyTests

core/src/main/scala/cats/NonEmptyTraverse.scala, core/src/main/scala/cats/data/NonEmptyList.scala, core/src/main/scala/cats/syntax/list.scala
This addresses: #1959 
I didn't see a way to require just an `Eq` instance for `B` while preserving the performance characteristics. A `mutable.Map` uses more than just universal equality, it also uses the built-in JVM hashing. So, what I did was to switch to a `mutable.TreeMap` which requires a `scala.math.Ordering` instance, and we get that by constraining `B` to have a `cats.Order` instance.
=> Require an Order instance for NonEmptyList's groupBy function

docs/src/main/tut/datatypes/state.md
=> Add docs for StateT and IndexedStateT

core/src/main/scala/cats/data/Validated.scala
=> reduced usage of `fold` in `Validated`

core/src/main/scala/cats/data/NonEmptyList.scala, core/src/main/scala/cats/data/NonEmptyVector.scala, tests/src/test/scala/cats/tests/NonEmptyListTests.scala, tests/src/test/scala/cats/tests/NonEmptyVectorTests.scala, tests/src/test/scala/cats/tests/nonEmptyListTests.scala
There is one notable change: NEL previously had a `concat` which accepted another NEL. To be similar to NEV, I changed this (and added `concatNel`).
The following differences are (intentionally) not addressed:
- `groupBy`: NEL has one, but I didn't add it to NEV, because I think that it should have an `Eq` constraint, however implementing that would need a `Map` which works with `Eq`...
- `length`/`size`: NEV has a `length: Int` and a `size: Long` (as an extension method). NEL had a `size: Int` and I've added `length: Int`. (Possibly `size` should be changed to `Long`, or simply removed, to be an extension method.)
- a few `Vector`-specific methods, e.g., `updated`.
This fixes #1832 (cc @johnynek).
=> Sync NEL and NEV methods (fixes #1832)

core/src/main/scala/cats/data/Kleisli.scala, tests/src/test/scala/cats/tests/KleisliTests.scala
I'm not sure how common a use case this is but I find myself needing to do it occasionally.
The test I added feels a bit pointless. Can delete if people agree.
Say I'm using `Kleisli[Either[String, ?], Context, ?]` in the core of my program:
```scala
case class Context()
case class User()
case class Thing()
def getUser(userId: String): Kleisli[Either[String, ?], Context, User] = ???
def getThing(user: User): Kleisli[Either[String, ?], Context, Thing] = ???
def getThingByUserId(userId: String): Kleisli[Either[String, ?], Context, Thing] =
for {
user  <- getUser(userId)
thing <- getThing(user)
} yield thing
```
Then on the edge of the program, say in an HTTP controller, I want to match on the `Either` in order to build an HTTP response:
```scala
def buildHttpResult(errorOrThing: …
```
=> Helper method to convert Kleisli[F, A, B] to Kleisli[Id, A, F[B]]

AUTHORS.md, README.md, build.sbt
In light of the recent admission of attempted career sabotage by @larsrh on Twitter, I'm resigning as maintainer on all typelevel and typelevel incubator projects. It was nice working with all of you, and I hope to work with you again in the future.
=> Remove Edmund Noble as maintainer and author

docs/src/main/tut/faq.md, docs/src/main/tut/typeclasses/lawtesting.md, docs/src/main/tut/typeclasses/typeclasses.md
=> Links "LawTesting.md" in FAQ and TypeClasses pages

tests/src/test/scala/cats/tests/EitherTSuite.scala
This is very minor, but the order of the comparison for the `EitherT.cond` test is swapped: if the test ever winds up catching a breaking change, it will output the incorrect "expected" value.
This fixes the order and also adjusts the test name to describe what's being checked.
=> Fix order of comparison for EitherT.cond

core/src/main/scala/cats/data/Validated.scala, tests/src/test/scala/cats/tests/ValidatedSuite.scala
Since `cond` is already available on `Either` and `EitherT` it seems reasonable to have it on `Validated` as well.
=> Add Validated.cond and Validated.condNel

scalafix/README.md
- link to Scalafix website for installation instructions
- replace MF with RC1
=> Upgrade Scalafix instructions

docs/src/main/tut/datatypes/const.md, docs/src/main/tut/datatypes/kleisli.md, docs/src/main/tut/typeclasses/imports.md, docs/src/main/tut/typeclasses/invariantmonoidal.md
Corrects a few instances where `it's` was used instead of the correct possessive `its`.
=> Correct it's -> its documentation errors

kernel-laws/src/main/scala/cats/kernel/laws/SemigroupLaws.scala, kernel-laws/src/main/scala/cats/kernel/laws/discipline/package.scala
Note: I just noticed the redundancy in this implicit conversion. As I'm working on something else, I did *not* check that all tests pass locally, I'll check the C.I. output later.
=> Removed redundant Eq instance

build.sbt, core/src/main/scala/cats/Foldable.scala, core/src/main/scala/cats/syntax/foldable.scala, tests/src/test/scala/cats/tests/SyntaxSuite.scala
This PR adds aliases for Foldable's `foldRight` and `foldLeft` ops so that the callee can be sure that the correct method is being invoked.
Because of syntax extensions the end signature looks like:
```scala
def foldRight[B](b: Eval[B])(f: (Eval[B], A) => Eval[B]): Eval[B]
```
This can then lead to some confusion when folding over things which already have the `foldRight` operation, namely pretty much all collections.
Even though we do:
```scala
List
.range(0, 10000000)
.foldRight(Eval.now(0))((n, e) => e.map(_ + n))
```
the fold won't be evaluated lazily, using `Foldable`'s definition of `foldRight` instead the stdlib's version will be chosen.
To avoid this pitfall, this PR introduces these aliases:
- `foldr <=> foldRight`
- `foldl <=> foldLeft`
these methods can …
=> Add `foldl` and `foldr` aliases to `Foldable`

docs/src/main/tut/faq.md
Here's how it looks like for me currently:
=> Correctly close a tut:silent block in faq

docs/src/main/tut/datatypes/validated.md
I'm learning Validated from the docs and think this may be a typo. 
Please let me know otherwise :)
=> Rename Validation to Validated in Validated docs

docs/src/main/tut/typeclasses/lawtesting.md
See alexarchambault/scalacheck-shapeless#76
=> Update scalacheck-shapeless to 1.1.6

CONTRIBUTING.md, core/src/main/scala/cats/data/IorT.scala, docs/src/main/resources/microsite/data/menu.yml, docs/src/main/tut/datatypes/iort.md, laws/src/main/scala/cats/laws/discipline/Arbitrary.scala, tests/src/test/scala/cats/tests/IorTSuite.scala, tests/src/test/scala/cats/tests/IorTTests.scala
Initial work for #1943. Happy to add docs and more methods (that EitherT has), if this seems ok
=> Add Ior Monad Transformer

docs/src/main/tut/typeclasses/applicative.md
The code was updated to use the new syntax, but the text no longer matched up with the code. This brings them in sync once again.
=> Clean up applicative syntax doc

CHANGES.md
...Because it's not there. @LukaJCB++ on gitter pointed out that the use cases for MonadCombine are handled using `Alternative` or `Monad` + `MonoidK` now.
Note: it appears there's a [MonadCombineSuite](https://github.com/typelevel/cats/blob/master/tests/src/test/scala/cats/tests/MonadCombineSuite.scala), which provides a test for a single method of `Alternative`. If I can get some time I'll rename it & add the missing tests.
=> Do redirect to look into cats-mtl for MonadCombine

build.sbt, core/src/main/scala/cats/Parallel.scala, core/src/main/scala/cats/syntax/parallel.scala, tests/src/test/scala/cats/tests/SyntaxSuite.scala
Should fix #2015. I chose `&>` and `<&` seemingly at random. I wanted to use `!>` before, but it appears that's illegal, as it's XML or something. If someone has better names for these operations, I'd be glad to hear! :)
=> Add &> and <& as syntax for Parallel

build.sbt, core/src/main/scala/cats/FlatMap.scala, core/src/main/scala/cats/syntax/flatMap.scala
In FS2, we rely heavily on recursive functions that return values of type `Pull[F,O,R]`. These functions typically take a form similar to:
```scala
def foo: Pull[F,O,R] =
if (guard) Pull.done else doSomeWork *> foo
```
Recently, @pchlupacek noticed that FS2 defines `*>` with a by-name param whereas cats defines `*>` with a strict param. Such recursive programs are broken if we use a strict param. Hence, we are going to change the FS2 definition of `*>` to be strict and reintroduce `>>` with a by-name param and then use `>>` in all recursive pulls.
Ideally, cats would have the same definition for `>>`, so in this PR I removed the deprecation of `>>` and defined it with a by-name param, making it a true alias for `flatMap(_ => fb)`. Note that we already have `followedByEval` and …
=> Removed deprecation of >> and changed its param to be a by-name

build.sbt, core/src/main/scala/cats/instances/sortedMap.scala, tests/src/test/scala/cats/tests/SortedMapSuite.scala
This PR adds a `CommutativeMonoid` instance for `SortedMap` when there is a `CommutativeSemigroup` instance for the value type.
Besides adding a test for `CommutativeMonoid[SortedMap[String, Int]]`, I also modified the test for `Monoid[SortedMap[String, Int]]` to be a `Monoid[SortedMap[String, String]]`, such that I can ensure that the `Monoid` instance can still be resolved when there is not a `CommutativeSemigroup` for the value type.
=> CommutativeMonoid instance for SortedMap

README.md
This PR fixes #2003 by adding a direct link to the [scaladoc](https://typelevel.github.io/cats/api/cats/index.html) in README.md.
=>  Add direct link to the scaladoc in README.md

build.sbt, core/src/main/scala/cats/data/EitherT.scala, core/src/main/scala/cats/data/IndexedReaderWriterStateT.scala, core/src/main/scala/cats/data/IndexedStateT.scala, core/src/main/scala/cats/data/Kleisli.scala, core/src/main/scala/cats/data/OptionT.scala, core/src/main/scala/cats/data/WriterT.scala, scalafix/README.md, scalafix/input/src/main/scala/fix/v1_0_0/RenameTransformersLift.scala, scalafix/output/src/main/scala/fix/v1_0_0/RenameTransformersLift.scala, scalafix/rules/src/main/scala/fix/Cats_v1_0_0.scala, tests/src/test/scala/cats/tests/IndexedReaderWriterStateTSuite.scala, tests/src/test/scala/cats/tests/IndexedStateTSuite.scala, tests/src/test/scala/cats/tests/ParallelSuite.scala, tests/src/test/scala/cats/tests/WriterTSuite.scala
This PR deprecates `lift` on all transformers in favour of `liftF`, and adds a FunctionK version named `liftK` (for use with `mapK`).
I'm leaving a possible scalafix to a separate PR.
=> standardise on `liftF` and add `liftK` to transformers

build.sbt, docs/src/main/tut/typeclasses/contravariant.md, docs/src/main/tut/typeclasses/invariant.md
This resolves https://github.com/typelevel/cats/issues/2005 providing link directly to the `cats` package in the ScalaDoc.
Rider: Fix some Scala source links in microSite sources that were killed when `Contravariant` and `Invariant` were moved out of `functor` package.
=> Link Directly to Cats Package in ScalaDoc

docs/src/main/resources/microsite/data/menu.yml, docs/src/main/tut/typeclasses/parallel.md
Adds some documentation for the new `Parallel` class. Right now it depends on #1938. We should be able to give more examples once we have a `Parallel` instance for `cats.effect.IO` :)
=> Add parallel docs

kernel-laws/src/main/scala/cats/kernel/laws/discipline/package.scala, laws/src/main/scala/cats/laws/discipline/package.scala
For failed `IsEq` produce labels with both values to simplify debugging.
The implementation was borrowed from `org.scalacheck.Prop.?=` with minimal changes. No changes to `*Test` traits were made, so the default pretty-printer will be used in most cases, which shouldn't cause any problems. Changes to pass a pretty-printer through would be trivial, but would require a lot of small changes (and would be fragile unless we convert `IsEq` to `Prop` explicitly everywhere, since we always have implicit pretty-printer for `Any`).
=> Add labels to prop produced from IsEq

kernel-laws/src/main/scala/cats/kernel/laws/discipline/EqTests.scala
First contribution to cats :tada: , let me know if something is missing.
=> Fix #2051, Remove superfluous implicit

build.sbt, core/src/main/scala/cats/data/Ior.scala, core/src/main/scala/cats/syntax/either.scala
Adds the `Ior.fromEither` method.  I am aware that there is a `toIor` provided via `EitherOps`, but this one is harder to find for newcomers (IMHO :D) and needs the import of the `EitherSyntax`.
So I added the `Ior.fromEither` which does not require any import and is easily discoverable on the `Ior` companion.
)
=> Add `Ior.fromEither`

core/src/main/scala/cats/data/Ior.scala, tests/src/test/scala/cats/tests/ParallelSuite.scala
Adds a `Parallel` instance for `Ior`.
The parallel instance is defined as `Parallel[Ior[E, ?], Ior[E, ?]]` without any wrapper type for a "parallel Ior". We could add one, if it's useful.
=> Add Parallel instance for Ior

docs/src/main/tut/faq.md
Resolves https://github.com/typelevel/cats/issues/2066
The unmerged symbols `&&&` and `-<` are in a different commit, just in case that need to be punted for a later date.
I made the choice to bring the un-deprecated symbol up in the table to the other `FlatMap` symbols and to add the new `Arrow` symbols near the `Combine` symbols, which makes the diff look larger than it really is.
=> Update symbols table

core/src/main/scala/cats/Alternative.scala
I took the examples from the `alternative` syntax file and slightly
modified them to use the type class instance directly instead of the
syntax helper methods.
=> Add some doctest examples for Alternative methods

build.sbt, scripts/travis-publish.sh
Our test log is always too long to display inside travis, the raw log downloaded is a really a pain to read. 
This change will make it only display success TestSuite names in JVM tests. So with this change it should be a lot easier to see where build fails.
=> improve build by not displaying each success test

build.sbt, core/src/main/scala/cats/arrow/Arrow.scala, core/src/main/scala/cats/data/Cokleisli.scala, core/src/main/scala/cats/data/Kleisli.scala, core/src/main/scala/cats/instances/function.scala
we already have a law 
```
F.lift(identity[A]) <-> F.id[A]
```
so it's hard to see why this shouldn't be given as a default.
=> added a default id for Arrow

kernel-laws/src/main/scala/cats/kernel/laws/discipline/EqTests.scala, kernel-laws/src/main/scala/cats/kernel/laws/discipline/SemigroupTests.scala
Previously if you ran the `CommutativeSemigroup` tests on a type (`Mean`
in this example) you would see something like:
```
MeanTests:
- Mean.commutativeSemigroup.commutative
- Mean.commutativeSemigroup.semigroup associative
- Mean.commutativeSemigroup.semigroup combineAllOption
- Mean.commutativeSemigroup.semigroup repeat1
- Mean.commutativeSemigroup.semigroup repeat2
```
The extra `semigroup` in the name seems redundant to me, and as far as I
can tell, it's inconsistent with tests for other type classes. `Eq` had
a similar issue.
=> Reduce redundancy in Semigroup and Eq test names

core/src/main/scala/cats/data/Ior.scala
Fixing my own mistake of incorrectly naming the TC instance provider.
=> Fix name of parallel TC instance materializer

core/src/main/scala/cats/Applicative.scala, core/src/main/scala/cats/arrow/Arrow.scala, tests/src/test/scala/cats/tests/FunctionSuite.scala
Adds an `Apply` instance as discussed in https://github.com/typelevel/cats/issues/2069
It can be weakened to `Semigroupal` if we don't buy the `Apply`.
Currently, it is implicit. There was discussion in the issue on whether it should be explicit or implicit. Either answer seems reasonable so I wrote the doctest to be compatible with either way people end up preferring.
Do we need additional tests over the doctest?
=> Add Applicative for Arrow

tests/src/test/scala/cats/tests/RegressionSuite.scala
This adds a test case that the `traverse` implementation for `Vector`
short-circuits the traversal when possible. This would have failed the build
in #2091.
See #1015 for when similar tests were added for similar structures.
=> Test that Vector's traverse short-circuits

core/src/main/scala/cats/data/IorT.scala, tests/src/test/scala/cats/tests/ParallelSuite.scala
The same functionality as https://github.com/typelevel/cats/pull/2059, but for IorT instead of Ior.
=> Add parallel instance for IorT

build.sbt, kernel-laws/src/test/scala/cats/kernel/laws/LawTests.scala, kernel/src/main/scala/cats/kernel/instances/map.scala
Since we already have a `Monoid` instance for `Map`, it seems natural to
have a `CommutativeMonoid` when the value type has a commutative
semigroup.
Note: Unfortunately, I believe that this is a binary-incompatible change in cats kernel. cc @johnynek
=> Add a CommutativeMonoid for Map

core/src/main/scala/cats/Eval.scala, tests/src/test/scala/cats/tests/EvalSuite.scala
I believe (and the law tests seem to agree) that the existing monad
instance for `Eval` is a valid `CommutativeMonad`, so we might as well
expose it as one.
=> CommutativeMonad for Eval

build.sbt, core/src/main/scala/cats/data/Kleisli.scala, tests/src/test/scala/cats/tests/KleisliSuite.scala
- Remove an irrelevant and unused `B` type parameter on
`catsDataCommutativeMonadForKleisli`.
- Upgrade `catsDataMonadForKleisliId` from `Monad` to `CommutativeMonad`
- Note that while I had to add a mima exception for this, I think that
it should be 100% binary compatible since its a member of a `sealed`
and `private` abstract class and returns a subtype of what it was
before.
- Add a `CommutativeFlatMap` instance for `Kleisli`
- Add a couple of implicit resolution tests for Kleisli that were
missing
=> Some Kleisli instance cleanup

core/src/main/scala/cats/data/IndexedReaderWriterStateT.scala, core/src/main/scala/cats/data/IndexedStateT.scala, core/src/main/scala/cats/data/Kleisli.scala, core/src/main/scala/cats/data/WriterT.scala, free/src/main/scala/cats/free/Coyoneda.scala
This updates the deprecations we previously expected to debut in 1.0.0.
=> Update version of deprecation to 1.0.0-RC2

core/src/main/scala/cats/package.scala
=> add `Comparison` to `cats` package

core/src/main/scala/cats/Applicative.scala, tests/src/test/scala/cats/tests/ApplicativeSuite.scala
Adds `CoflatMap` instance for `Applicative`. Discovered this today looking at extension for libraries using tests and believe this to be lawful as far as I can tell from an initial inspection.
=> CoflatMap Instance for Applicative

kernel/src/main/scala/cats/kernel/Order.scala, tests/src/test/scala/cats/tests/OrderSuite.scala, tests/src/test/scala/cats/tests/PartialOrderSuite.scala
The main goal of this PR was to add syntax tests for the `Order` and
`PartialOrder` syntax (provided via machinist ops) to address [this comment](https://github.com/typelevel/cats/pull/1867#discussion_r138765045).
In the process I noticed that the Order companion object didn't have a
`comparison` function to forward through to the type class instance like
it did for other methods, so I added that.
I did notice that the `Order`/`PartialOrder` syntax does work whether or
not you take the `Order`/`PartialOrder` instances as implicit parameters
to the ops classes. I think that only @non understands quite what's
going on with the machinist syntax macros, so I didn't make the changes
to take away those implicit parameters without knowing the implications.
The tests pass either way, so I think …
=> Add comparison method in Order companion object

build.sbt, core/src/main/scala/cats/instances/eq.scala, core/src/main/scala/cats/instances/hash.scala, core/src/main/scala/cats/instances/order.scala, core/src/main/scala/cats/instances/partialOrder.scala, core/src/main/scala/cats/instances/partialOrdering.scala, kernel-laws/src/test/scala/cats/kernel/laws/LawTests.scala, kernel/src/main/scala/cats/kernel/Eq.scala, kernel/src/main/scala/cats/kernel/Hash.scala, kernel/src/main/scala/cats/kernel/Order.scala, kernel/src/main/scala/cats/kernel/PartialOrder.scala, kernel/src/main/scala/cats/kernel/instances/all.scala, kernel/src/main/scala/cats/kernel/instances/eq.scala, kernel/src/main/scala/cats/kernel/instances/hash.scala, kernel/src/main/scala/cats/kernel/instances/order.scala, kernel/src/main/scala/cats/kernel/instances/partialOrder.scala
To address some items in #2093
Note that this code change is binary compatible in kernel  (I tested Mima without any of the exceptions I added) but not binary compatible in core.
=> conversion `PartialOrder` to `PartialOrdering` and `Hash` to `Hashing`
